### ISSUE TITLE
Reduce function

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1047]
implement Reduce(fn, ne) where `fn` is the reducer, and `ne` represents the initial value for the reducer.

**Comment by jsternberg** [comment]
I think @aanthony1243 is working on this so I'm assigning him so nobody tries to pick this up.

We also discussed in slack a different name for the initial value. Possibilities were `init`, `initial`, and `zero` from what I remember. We rejected `start` because we wanted the possibility of parallelizing reduce and didn't want to call it a start variable.
