### ISSUE TITLE
Design Planner options

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#106]
Possible options:

* Disable push downs
* Turn of optimization X
* etc

**Comment by wolffcm** [comment]
Some discussion on Slack with @aanthony1243 about how to get better tracing of Flux execution: we could add a planner option that would inject `yield` nodes in between plan nodes so that the user can get an idea of the output of their query at each stage.

Taking the idea further, one could imagine extending `yield` to take an additional `fn` argument that is an additional aggregation to perform on the yielded data, e.g., `yield(name: "range_sum", fn: sum)`.  (This would likely require additional support from the execution engine)

**Comment by wolffcm** [comment]
I filed #1439 that describes a possible way to do this.
