### ISSUE TITLE
Design tests that exercise sources

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#107]
Three layers to test

* Test source implementation produce the correct RPC calls
* Test sources return correct results (this only applies when we control the source)
* End to End tests

**Comment by aanthony1243** [comment]
### proposal for a new testing approach

our current 'integration' tests are convenient to define and run.  they consist of the following steps: 

1. parse a `flux` query
2. replace the `from` spec with a `fromCSV` spec
3. run the query with provided input CSV data file
4. compare the result with provided CSV output data file

This approach has two major flaws.  First, the planner is not being adequately tested.  Since the `fromCSV` function does not implement any push-down rules, the planner is effectively disabled in terms of pushing down operations that are, in some cases, required for issuing a request to InfluxDB.  So we are unable to test whether the required push-downs are taking place.  Second, we have observed several mismatches over time in the values returned by a pushed-down operation (e.g. from `filter`) and the values returned by the `flux` implementation.  Both results should be determined by the `flux` spec, and should therefore be identical.  A third issue that's not a significant is that `flux` is meant to be a full-featured data manipulation lanaguage, and it makes sense that tests would be written purely in the language.  

A possible solution to these problems is to add functions/primitives to the language that will allow for testing queries via the query engine.  For example, a simple test would look like: 

```
input = loadTable(file: "test.in.csv")
got = input |> test()
want = loadTable(file: "test.out.csv")
assertEQ(want,got)
```
Where: 

- `test()` is a placeholder and represents whatever code must be run to produce the expected result. 

- `assertEQ` could be defined in one of several ways.  it could panic or error on a difference, or it could produce a diff of the tables if one is detected.  Another key feature will be to allow for enabling/disabling tests in a script, so that a function's definition and its test can be written in the same file.  

- `loadTable` may differ in its definition, depending on what platform is running the tests.  For example, on a platform that includes an `influxdb` storage layer, `loadTable` can be defined as: 

  ```
  loadTable = (file) => {
    fromCSV(file:file) |> to(bucket: "testUID")
    return from(bucket:"testUID")
  }
  ```
  while in the `flux` repo, with no backend available, the table may be loaded into memory: 

  ```
  loadTable = (file) => fromCSV(file: file)
  ```

Much of the logic we need to implement the above is already available, though some refactoring may be required.  There are some other requirements we should consider implementing to make this approach effective: 
1. if loading data to a bucket, should `to` be able to create buckets?  or should we presume that some default testing or scratch/sandbox bucket will always exist?  
2. If loading data into memory, we should have a source type that adequately tests the planner wrt pushdown logic. 
3.  Support in `cmd/influx` to run the tests.  ideally, in a regular execution mode, tests should be skipped, but in testing mode, they are executed and report failures.  This mode should also produce output that is CI friendly, e.g. in `junit` format.

**Comment by nathanielc** [comment]
+1 A couple of thoughts to take this one step further....

We can define a `test` function that can encapsulate this entire process. For example:

```
package testing


 // Test will load data from a file and run a test function against that data expecting the result to be the same as the data loaded from the want file.
// The default is to load the csv file directly, but other load functions may be defined to load data from other sources.
test = (name, file, load=fromCSV, test, want) => {
     input = load(file:file)
     got = input |> test()
     want = load(file:want)
     return assertEQ(name: name, want: want, got: got)
}
```

Then the influxdb package could do this
```
package influxdb

import "testing"

// Test calls the testing.test method with the influxdb.load method
test =  (name, file, test, want) =>
     testing.test(name:name, file:file, test:test, want:want, load:load)

```

Then a user can write tests against the influxdb source like so:

```
import "influxdb"

mean = (table=<-) =>
    table |> aggregateWindow(every:10s,fn:mean)

influxdb.test(
    name: "mean aggregation",
    file: "aggdata.csv",
    test: mean,
    want: "mean_aggdata.csv",
)
```


This allows for tests to target specific sources and therefore exercise the planner, or to simply use the default behavior of loading the data off the csv directly if the source is not important to the test.

This is a rough draft of what the `test` function should look like. I am sure it will need to be though out better than this.

**Comment by jsternberg** [comment]
Where would `loadTable` be getting defined? I personally like using `from` for tests and I think it works well. It would be nice if we could still use `from` and the test harness would translate the bucket name to the appropriate table load implementation.

**Comment by wolffcm** [comment]
It would be great to be able to use the new framework to run the transpiler end-to-end tests that @jlapacik and I have been working on.  (Those use `fromInfluxJSON` to read their input, but are otherwise the same.)  I wonder if that could be achieved using only Flux?

**Comment by mark-rushakoff** [comment]
I agree with the premise of `loadTable`. In tests, you want to specify exactly the data you're reading from the storage backend. If the data read back isn't equivalent to the source CSV, that's probably a critical bug in the storage backend.

I agree that push-downs need to be tested, but they should be tested explicitly, per storage backend. If you were writing a traditional compiler, you would have an input source code and you would have an external assertion of what instructions you generate for a particular target. `from() |> count()` might be optimized with a push-down on one storage backend but not another.

I don't think it's worth it in the short or medium term, to inspect flux plans, from flux. Assuming we use `loadTable` or something like it, the pure-flux tests should only be concerned with correctness of output. Tests of correct planning should live near the tests for a particular storage backend. I'm not generally familiar with the planner implementation - maybe there would be similar tests in the planner for given sets of backend capabilities.

I agree with introducing a testing namespace. However, I think it's extremely unlikely that we'll be happy with the first attempt or two of finding the right API for testing and assertions, so I would prefer that we introduce the namespace as `experimental.testing.v1` or something that makes it clear that we're going to break the API or supersede it until we're comfortable promoting it to simply the `testing` namespace.

There's bikeshedding aplenty when it comes to assertion APIs, so maybe the bare minimum start for that would be `log`, `error`, and `fail` like Go's testing API. I'd prefer to see a thorough evaluation of popular assertion libraries, as part of a proposal, before work on an assertion API.

**Comment by aanthony1243** [comment]
Perhaps the best thing about this approach is that it's more-or-less platform agnostic.  

@jsternberg   `loadTables`  would be implemented uniquely for each platform but the rest of the testing functions would be implemented in the `flux` repo.   So to run the tests in `flux` we implement `loadTables` to use fromCSV.   to run them in `platform`  we use something more sophisticated.  With proper support in the CLI tools, we may have a consistent  `--test`   

The issue with using `from` everywhere is that `from` is different depending on the platform that you are using. If designed correctly, we should get a corpus of 'portable' tests that are designed to work on any platform that includes base `flux` plus a custom implementation of `loadTables`  

Also, i forgot to put in the design that it only makes sense to also provide a `saveTables` function. This gives us an opportunity to eliminate the dependency on the CSV encoder entirely. We could even use a binary format if we chose.

**Comment by pauldix** [comment]
It would be nice to have the test data show up in the actual test script. We had talked about being able to create sample data in Flux so we'd need that. Based on our discussion the other day, I'm really leaning towards some sort of fixed width format.

There should be some way to test the pushdown logic per source, but those tests should live where he source is defined (the from, not the other functions). But that's just unit testing. I think there's a ton of value in having higher level integration tests that exercise multiple functions all the way down to an actual source.

**Comment by aanthony1243** [comment]
@pauldix thanks for commenting.  RE:  testing sources.  I think there's a few ways we need to test push-downs: 
1.  A source that can verify that everything that SHOULD be pushed down, IS pushed down.  Unit tests are probably sufficient for this.  
2.  A source that can mock out, at least, influxdb storage but read data from a file (CSV , LP, whatever).  it would implement all elements of the spec perfectly and would stand as the gold-standard baseline for real-life sources. 
3.  A real-life source that accepts pushed-down logic should be producing equivalent results as the `flux` implementations of the same operations.  Easiest way to do this is to run twice, once with planning enabled, and once disabled and verify that the results are identical. 


RE: test data in the files.  Currently, we could have the test data embedded as a blob of text but it's not readable.  We could come up with a friendlier format and write a new decoder for it.  JSON wouldn't be a bad idea if it's formatted nicely, but something that's tabbed-out or fixed-width could be viable too.  

Another idea that I proposed a while back was to have a stream builder API, like : 

```
TK = {_field: "cpu-total", _measurement: "cpu", host: "host1"}
VC = {_time:time, _value: float]
testData = NewStream()
  //   copy the incoming stream, and add this table if it doesn't already exist 
  |> addTable(tableKey: TK, variableColumns: VC ) 
  // add a row to the table 
  |> addRow(tableKey: TK, row: {_time: 1/1/2017T12:00:00Z, _value: 0.8})
  |> addRow(tableKey: TK, row: {_time: 1/1/2017T12:00:01Z, _value: 0.75})
  ...
```
There's actually no limitation in our current query engine for doing this. It's a bit verbose, so some syntax to make it more convenient could be good, but there's also an advantage to users learning about table keys and how they are part of the stream.

**Comment by pauldix** [comment]
@aanthony1243 agree on 1-3. 3 in particular sounds like it's pretty high value and ideally could be run against every `from` source.

On the test data, I think adding multi-line strings and a parser for a fixed width format would be best. The only thing I'm wondering is if the format should be able to specify the type of the columns. It would also need a way to specify multiple tables (could just be separated by a blank line).

**Comment by aanthony1243** [comment]
@pauldix the current CSV format in 2.0 answers all of those issues except for readability.  If we can re-tool it to have a fixed-width option, then I think we're all done.

**Comment by nathanielc** [comment]
We have implemented many of these ideas and we have something working. Further changes can be individual issues from here.
