### ISSUE TITLE
GroupKeyBuilder type

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#109]
it's often cumbersome to construct a group key, having to keep track of separate keys and values.  

Added to this is that group keys are sensitive to having overlapping memory if slices are accidentally shared.  

An API as below could be a useful abstraction for a common task: 

```
type GroupKeyBuilder struct {
       cols   []flux.ColMeta
	values []values.Value
}
func (*GroupKeyBuilder) AddGroupKey(key GroupKey) (error) 
func (*GroupKeyBuilder) AddKeyValues(keys []string, values []values.Value) (error)
func (*GroupKeyBuilder) GroupKey() (GroupKey, error)
```

**Comment by jsternberg** [comment]
Here's a possible alternative interface:

```
// NewGroupKeyBuilder creates a new GroupKeyBuilder. If a GroupKey is passed as the argument,
// it is copied and used as the base of the new GroupKey. If nil is passed, a blank GroupKeyBuilder
// is constructed.
func NewGroupKeyBuilder(key GroupKey) *GroupKeyBuilder
// AddKeyValue will add a new group key to the existing builder.
func (*GroupKeyBuilder) AddKeyValue(key string, value values.Value) *GroupKeyBuilder
// Build will construct the GroupKey. If there is any problem with the GroupKey (such as
// one of the columns is not a valid type, the error will be returned here.
func (*GroupKeyBuilder) Build() (GroupKey, error)
```

I like this better because one issue I've had with the `GroupKey` interface is there aren't a lot of strong guarantees that the slices are of the same size and it can make it easier to mess up the code. In this way, we can chain the `AddKeyValue` call and it works for the most common scenario of adding a single column or dropping a single column.

Maybe we should also add utilities to those? I think it would personally be nice to have the schema mutator functions as utilities that can be used. We commonly have a need to modify tables to my understanding outside of the direct schema mutators so this might be a good location to start with that.

Before we discuss that though, thoughts on my proposed interface?

**Comment by aanthony1243** [comment]
I like it. adding a single key value at a time makes sense.  any case I can
think of that would use slices for key values, I would have to build those
externally with append anyway.
