### ISSUE TITLE
Does table order matter?

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1120]
When iterating over a stream of tables does the order matter?

In the case of narrow transformations table order doesn't matter as tables are processed in isolation.

For other transformations the table order can have an effect on the results. For example the `|> group()` operation will concatenate all tables from the stream into a single table, the order the tables are received is the order in which they are concatenated. 

In the case of wide transformations does table order matter?
This question only has two possible answers:

1. Order does matter, in which case the order should be deterministic such that code can rely on the order.
2. Order does not matter, in which case the order should be artificially randomized so that code cannot rely on any order provided by the implementation. 

Agreeing to a deterministic order means that we always have to pay the cost of sorting the tables when the implementation itself cannot preserve the order. As such ordering the tables will come at a cost. My preference is to not have any order such that only when a user needs a consistent order will a sort be needed, (i.e. `|> group() |> sort()`).

On the other hand having inconsistent order can make learning and working with Flux harder.

See #1067 for a bug created from table ordering.

**Comment by pauldix** [comment]
I think that table order should be deterministic. There are a few things that make me think this. First, we need to give users the ability to limit the number of tables in the response and optionally offset to the last sets of results they had gone through. Second, when combining results from multiple servers, the engine will only be able to stream if it can match tables as they come through, rather than marshaling the entire set at once (in memory or even spill to disk).

Finally, there are use cases where the user may want to alter the order of tables.
