### ISSUE TITLE
Re-implement BucketsAccessed for `from`

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#114]
was removed when refactoring `from` execution code to platform, while keeping the OpSpec on flux.  It's a genuine cyclic dependency that we need to work around.

**Comment by affo** [comment]
Removing `from` from flux only breaks tests. Below, some `make test` output.  
These tests were broken because of a dependency with `FromProcedureSpec` and `FromKind`:

```
# github.com/influxdata/flux/querytest
querytest/execute.go:46:24: undefined: inputs.FromKind
querytest/execute.go:56:24: undefined: inputs.FromKind
# github.com/influxdata/flux_test [github.com/influxdata/flux.test]
./spec_test.go:70:12: undefined: inputs.FromOpSpec
# github.com/influxdata/flux/plan_test [github.com/influxdata/flux/plan.test]
plan/logical_test.go:67:15: undefined: inputs.FromProcedureSpec
plan/logical_test.go:448:38: undefined: inputs.FromProcedureSpec
plan/logical_test.go:479:39: undefined: inputs.FromProcedureSpec
plan/logical_test.go:518:39: undefined: inputs.FromProcedureSpec
plan/pattern_test.go:15:10: undefined: inputs.FromProcedureSpec
plan/pattern_test.go:36:65: undefined: inputs.FromKind
plan/pattern_test.go:39:10: undefined: inputs.FromProcedureSpec
```

Other tests fail in `control/controller_test.go`, but only because `from` is not registered:

```
failed to compile query: type error 1:1-1:5: undefined identifier "from"
```

A simple solution, could be to create type `BucketAccess` in flux (basically the same as `platform.BucketFilter`):

```golang
type BucketFilter struct {
    ID    *string
    Name    *string
    OrganizationID    *string
    Organization    *string
}
```

And make `BucketAwareOperationSpec` return `flux.BucketAccess` (https://github.com/influxdata/platform/blob/master/query/spec.go):

```golang
type BucketAwareOperationSpec interface {
	BucketsAccessed() (readBuckets, writeBuckets []flux.BucketAccess)
}
```

And let the function `BucketsAccessed` in `query/spec.go` perform the conversion to `BucketFilter` (`string` -> `platform.ID`).

In this way, flux won't need `platform` because it doesn't need either `ID` nor `BucketFilter`.

Is this an acceptable solution?

**Comment by aanthony1243** [comment]
@nathanielc 1/2 of `from`  is stuck in `flux` because of @affo 's points above.   He has a nice proposal to get `BucketAware` working again, but I feel like that leaves technical debt unpaid.  Should we address how to generalize `from`  to liberate the tests from influx-dependent code + specs?

**Comment by nathanielc** [comment]
@aanthony1243 @affo I'd rather not work around the platform.ID dependency. We should look into how we can fix this more generally.

**Comment by affo** [comment]
The problem lies in `platform` defining an interface that is supposed to be implemented by transformations that stay in `flux`, but requires to return a type that is defined in `platform`, hence the cycle.

Moving `to` to `platform` was possible because `to` is not necessary for tests to work, instead, `from` is necessary to produce correct plans, hence the dependency between Flux tests and `FromOpSpec` and `FromProcedureSpec`.

Maybe the problem is more in `to` being in `platform` than in `from` being in `flux`.

If `flux` defines a `BucketAccess` used by `BucketAwareOperationSpec`:

```golang
type BucketAccess struct {
    ID             int64
    Name           *string
    OrganizationID int64
    Organization   *string
}
```

then `platform.BucketFilter` can become a wrapper around it, and `platform` can apply its bucket-filtering logic that is meaningless to `flux`.

In this case, we could also move `to` in flux in order to make it available for testing in queries and to keep every transformation in one repo.

If we move `from` to `platform` we should
 - move every test that involves it, or remove their dependency from it. This seems a little weird, cause the queries in tests would miss `from`;
 - register a mock `from` in order to make `Test_QueryEndToEnd` run.

Another solution is to change the way `platform` checks for external bucket dependencies. We could define an interface in flux that expresses the fact that an operation is affected by something external in flux itself:

```golang
type ExternalResourceRequiredOperationSpec interface {
     Get() []ExternalResource
}

type ExternalResource interface {
    Kind() string // could be "bucket", "file", "socket"
    IsRead() bool
    IsWrite() bool
}

// Bucket is an ExternalResource
type Bucket struct {
    //...
}
```

in `platform`:

```golang
query.Walk(func(o *flux.Operation) error {
    io, ok := o.Spec.(ExternalResourceRequiredOperationSpec)
    if ok {
        for _, res := range io.Get() {
              if res.Kind() == "bucket" {
                  bucket := io.Resource.(Bucket)
                  // use bucket.ID ...
              }
        }
    }
    return nil
})
```

Still `Bucket` would be defined in `flux` and not in `platform`.

**Comment by aanthony1243** [comment]
at this point, if we can't move `fromOpSpec` to`platform` without breaking the planner then the planner needs some refactoring.    

breaking tests is another story.  we should be OK to write a `mockFromOpSpec`  and `mockFromProcedureSpec` in `flux`  to fix any tests that only need an fromOpSpec/fromProcedureSpec to run.  This should be true for all the tests in `flux`  since the transformation code was moved long ago.   

also:  when this code is moved it will break `influxdb`  since it relies on the `fromOpSpec` definition on flux.  probably we'll just have to copy some code.
