### ISSUE TITLE
Upgrade arrow dependency and unskip arrow tests

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/flux#1209]
There are 3 tests in arrow/arrow_test.go  that are skipped with a link to https://issues.apache.org/jira/browse/ARROW-4081.

https://github.com/influxdata/flux/blob/4c6a7d4595e9e3b9a518184d7fcdf1cb28669f9c/arrow/arrow_test.go#L13-L65

 Following that jira link, the issue is listed as having been resolved by https://github.com/apache/arrow/pull/3906, which was merged a little over a month ago.

**Comment by jsternberg** [comment]
There is also this issue so that we can optimize constructing the group key columns: https://issues.apache.org/jira/browse/ARROW-5212

The pull request to fix that is apache/arrow#4204.

**Comment by jsternberg** [comment]
I looked at the places where we added a workaround and I think the current code is correct. We can call sum when the array is empty, but I'm not sure why we would. It doesn't save us any time since we need to do the same code anyway so I'm just going to remove the comment since the current code is correct.

In each of the places where we do this check, we have to check to see if the array is empty anyway because there's something special. In sum, we set `ok` to true only if the length is greater than zero. In mean, we add the number of points for the total count of points.
