### ISSUE TITLE
Proposal: group key join

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1219]
This proposal is for a new approach to joins that is more memory friendly and understandable than the current version.  

The current join implementation has the following issues: 
1.  Because any row can be joined with any other row, the entire stream must be effectively cached.  
2. The join conditions are often not flexible enough. 
3.  No outer joins
4.  Schema inflexibility
5.  Sometimes hard to predict what the output group key will be.  

This issue proposes the `GroupKeyJoin` which first restricts joins only to tables from streams with the same group key.  Doing so reduces the cardinality of the operation and also allows us to avoid having to cache all rows for the entirety of the join process.  

Consider the following data with group key in parentheses: 

S1(K1,K2): 

_time|K1|K2|V1|V2
-|-|-|-|-
1|A|B|1|2
2|A|B|3|4
3|A|B|3|8
1|C|D|1|4

S2(K1, K2):

_time|K1|K2|V1
-|-|-|-
1|A|B|X
2|A|B|Y 
3|A|B|Z
4|A|B|R
1|C|D|Q

First, let's approach joins as a cross product on tables with the same group key: 
`GroupKeyJoin(left:S1, right:S2)`
we get the output: 

Result(K1,K2):

left_time|K1|K2|left_V1|left_V2|right_time|right_V2
-|-|-|-|-|-|-
1|A|B|1|2|1|X
2|A|B|3|4|1|X
3|A|B|3|8|1|X
1|A|B|1|2|2|Y
2|A|B|3|4|2|Y
3|A|B|3|8|2|Y
 1|A|B|1|2|3|Z
2|A|B|3|4|3|Z
3|A|B|3|8|3|Z
 1|A|B|1|2|4|R
2|A|B|3|4|4|R
3|A|B|3|8|4|R
1|C|D|1|4|1|Q

This is close to what we want, but we often want to attach additional conditions to the join, e.g. where time values match, or where one table or the other has a certain value on the row.  We can introduce a `join row function` to cover these cases: 

`GroupKeyJoin(left:S1, right:S2, joinRowFn: (left,right) => left._time == right._time )`
This creates the result: 

Result(K1,K2):

left_time|K1|K2|left_V1|left_V2|right_time|right_V2
-|-|-|-|-|-|-
1|A|B|1|2|1|X
2|A|B|3|4|2|Y
3|A|B|3|8|3|Z
1|C|D|1|4|1|Q

Finally, we can introduce an `outer` parameter that lets us implement a full/left/right outer-join by introducing an `outer` parameter with possible values `["left", "right", "full", "none"]`
`GroupKeyJoin(left:S1, right: S2, joinRowFn: (left,right) => left._time == right._time, outer: "right" )`
This would produce the following: 
Result(K1,K2):

left_time|K1|K2|left_V1|left_V2|right_time|right_V2
-|-|-|-|-|-|-
1|A|B|1|2|1|X
2|A|B|3|4|2|Y
3|A|B|3|8|3|Z
nil|A|B|nil|nil|4|R
1|C|D|1|4|1|Q

Why the new formulation?  Here are my reasons: 
1.  This method is consistent with all of our other transformations that occur on a per-group-key basis.  
2.  The majority of the time,  a user will want the group key in the join criteria.  This prevents stutter.  If they want the group key excluded, this can be achieved by re-grouping the data prior to a join.  
3.  In the implementation, we will not need to cache all rows for the entire stream.  The tables in the table builder cache are dynamically extensible so that we can write the left/right half of the table at the moment we encounter it, and complete the join when the second table is encountered.  

One unanswered question is how to deal with tables that don't have a matching group-key table in the other stream.  It may not be known that there is no paired table until the operation is complete.  One approach to this would be to define the above as always being FULL OUTER and then using a post-filter to enforce an inner/left/right join.  This may require introducing extra columns in the output to make filtering easy and predictable (e.g. HAS_LEFT and HAS_RIGHT columns would let us quickly scan/filter a table to compute an inner join--`filter(fn: (r)=>r.HAS_LEFT && r.HAS_RIGHT)`.

**Comment by nathanielc** [comment]
Thanks for the detailed write up.

> The majority of the time, a user will want the group key in the join criteria. This prevents stutter. If they want the group key excluded, this can be achieved by re-grouping the data prior to a join.

I think this is my biggest concern with this proposal. I disagree that the user will want the _entire_ group key in the join criteria most of the time. Instead I expect that the common case is that the user will want _most_ of the group key in the join criteria. My reasoning for thinking this is that the `_measurement` and `_field` columns are by default part of the group key and will almost never be part of the join criteria.  This one exception I think changes the most common case for users. With this proposal users will now need to use `group` before most joins to remove the `_measurement` and `_field` columns from the group key.


I agree that we need support for outer joins. Does this proposal simplify adding outer joins compared to the existing design? 

FWIW Kapacitor does joins only within groups, and it has been challenging for users. The biggest challenges users face is that they don't realize they have to line up the groups correctly.  Another challenge is that expressing joins across groups became really awkward in Kapacitor such that most users simply can't figure it out (See http://docs.influxdata.com/kapacitor/v1.5/nodes/join_node/#on) . We can probably solve both of these issues with a better design in the Flux, but in general Kapacitor users are tripped up by the per group join behavior of Kapactior.

**Comment by jsternberg** [comment]
I've got some concerned that this won't be more memory friendly. In order to do a join on a non-group column, it's going to need to involve using `group()` on a non-group column and this would generate a bunch of tables.

Additionally, the current join is completely unoptimized so it may be incorrect to judge the current join against a hypothetical other join. I also haven't seen the current join show up on a performance graph yet. It might be best to try and get some benchmarks of the existing join for situations that we expect such as joining on time and the group key.

I do think the usability of join is very difficult and I do think it would be useful to have a way to say "join on time + keys" that I don't think is currently present, but those might be different issues.

**Comment by jsternberg** [comment]
I may have been misunderstanding this. It seems as if this will be a "join on group key plus potentially other row-specific criteria" which would likely resolve the issue I mentioned above since it would be unnecessary to group by the time.

**Comment by aanthony1243** [comment]
I think that flux will help us to hide some of the usability problems.   This approach is more atomic/composable than what's currently there. It fits with the spirit of our design, that we want smaller functions that can be combined/reordered/pushed down by the planner.  

also, `join` ought to be consistent with our group key semantics.  it's kind of hard right now to pre-analyze 2 streams and have a good idea what the resulting group key would/should be after a join.  And in fact, we miss many edge cases that currently result in a panic.  For example, since we can join on rows that aren't in the same group, this means that the column schemas can be wildly different.  The default behavior would seem to be the union of the schemas (btw `group` does this already) with missing values set to nil. but when that's done, what's the group key?  is it a union?   finally, and there may be no way of avoiding this even in this proposal, but the schemas resulting from a join can vary between two runs of the same query.  (fun fact: `pivot` has this problem too, though the answer there ought to be "if this doesn't work you'll have to use a join" but in fact, we have told users in the past "if join isn't working for you try pivot"...

**Comment by aanthony1243** [comment]
copied transcript from slack: 

```
Joshua Lapacik [3:16 PM]
I really like your join proposal @adam. It would greatly simplify the implementation.
We could still define a standard join that joins arbitrary columns together, and just have the planner rewrite it as `join(group(A), group(B))` using this much simpler implementation.

nathaniel [3:18 PM]
@adam I commented on the proposal. I have some usability concerns, but as @Joshua Lapacik just pointed out we might be able to solve them via other means.
@Joshua Lapacik Can you add that comment to the issue?

Joshua Lapacik [3:18 PM]
Yes I can.

nathaniel [3:18 PM]
thx

Joshua Lapacik [3:19 PM]
I think right now, join just does too much. If we can offload some of the work to the planner, that might make it easier/possible to optimize it further.

adam [3:20 PM]
@Joshua Lapacik that was some of my thinking too...those groups could be pushed down to storage, making the join much faster
and in general we should try to discourage joining streams without a proper group key

adam [3:21 PM]
and restricting `join` from changing the group key makes planning around it easer

Joshua Lapacik [3:21 PM]
Much much easier.

nathaniel [3:22 PM]
> I think right now, join just does too much. If we can offload some of the work to the planner, that might make it easier/possible to optimize it further.

I think the proposal does the opposite of this. Instead of offloading the optimization work to the planner it off loads it to the user. Meaning the user now has to manage the groupings. But maybe a mix of the two would allow for this. We change the implementation of the join *transformation* to operate on a per group basis, then we let the planner inject the `groups` based on how the user defined the `join` on columns. So the `join` Flux function remains the same, but we don't actually have an implementation of that function rather its a combination of pre-grouping and joining. Not sure if this is feasable
@jsternberg OK, can you create an issue to track getting that fixed? I don't want to loose track of it with all the activity going on.

Joshua Lapacik [3:26 PM]
@nathaniel yes I think that’s what @adam is saying. Instead of placing the burden on the user, give it to the planner. So to the user, nothing really changes. But the implementation changes substantially. Instead of having all of the logic in just a single function, we have a much simpler join transformation that just joins on the group key. But the planner makes sure it adds the correct calls to `group` beforehand.

jsternberg [3:28 PM]
> Instead of having all of the logic in just a single function, we have a much simpler join transformation that just joins on the group key. But the planner makes sure it adds the correct calls to `group` beforehand.
I like this. this is cool. but is the purpose behind this to make it easier for users to use and then have the planner optimize things or is this making the code more simple?
to me, having the planner optimize things involves a planner rule that constructs our current join implementation and modifying it a bit to produce the correct output

adam [3:32 PM]
@nathaniel @Joshua Lapacik I was thinking slightly differently.    calls to `group` would be added by helper functions.
where the planner wins is that it can take those calls to `group` and optimize them separately from the call to `join`
in fact, the planner may have access to a join implementation that puts them all back together
if that was more efficient

jsternberg [3:32 PM]
ok, I just read it again and I think I’m understanding it better. so there would be two parts of the join operation. one would be the group keys and one would be the individual rows? then you wouldn’t have to `group(columns: ["_time"])` or anything

adam [3:33 PM]
^^ I think this is a good example

jsternberg [3:33 PM]
so it would default to `join(left: left, right: right, on: ["_time"])` instead of having to list every key in the group key? if this is the case, I’m getting to “strongly in favor”, but not quite there.

adam [3:34 PM]
^^  in the current impl.  you have to compare every row from every table on both streams
if we restrict to the group-key matches, the problem is smaller
but I think that gets to nathaniel's point.  what will a user expect?
IMO, we never want the user to forget about group keys.

nathaniel [3:39 PM]
Can we move this discussion the  issue? I like where it is going and I'll follow it closely but I think we need to capture this on the issue itself.

jsternberg [3:39 PM]
I just put my additional message saying my previous thought is probably wrong

nathaniel [3:39 PM]
cool (edited) 

```

**Comment by jlapacik** [comment]
I really really like this proposal. This join implementation would be much much simpler than the current one. However I don't think we should scrap the current join. Instead we should just replace its implementation with the new join.

I see it working like this. We have two join methods - the current one, `join`, and the new one `groupJoin`. `groupJoin` would be more intuitive and user friendly in certain situations. However we should still allow users the ability to do standard and arbitrary joins without having to worry about how to group their data beforehand. Instead we should have the query planner do that.

So for a regular `join`, the planner would rewrite it as something like this:

    groupJoin(group(streamA), group(streamB))

This then makes it possible for the query planner to push down the two group operations to storage, reducing memory consumption drastically on the Flux side. This is something that just isn't possible with the current implementation.

So not only would the implementation of `join` be much simpler (fewer lines of code) and much easier to reason about, but it would also be much more memory efficient in the majority of cases. A win win.

**Comment by jsternberg** [comment]
I think the above may not be perfectly accurate since there's no `group()` with no arguments. If I understand correctly, the `group()` for each of them will need to have the same arguments so you would have this:

```
left = streamA |> group(columns: ["host"])
right = streamB |> group(columns: ["host"])
join(left: left, right: right, on: ["_time"])
```

It might be nice to build these joins into the syntax itself and have it separate out into the group and join as part of converting from a logical to a physical operation. So instead of the above, maybe change `on` to be how the tables are grouped and add an additional function for matching rows?

```
join(left: left, right: right, on: ["host"], fn: (l, r) => l._time == r._time)
```

**Comment by pauldix** [comment]
@aanthony1243 to your point #8, I think this isn't strictly necessary and more an artifact of the current implementation. Take the following three tables:

*Table 1*

A (in group) | B (in group) | C (not in)
------------ | ------------ | ---------
asdf | bar | car

*Table 2*

A (in group) | B (in group) | C (not in)
------------ | ------------ | ---------
asdf | baz | whatevs

*Table 3*

A (not in) | B (in group) | C (not in)
------------ | ------------ | ---------
aargg | baz | chow

I only put a single row in the examples, but for this imagine that they have thousands of records each. For each table, each column in the group key will have the same value across all records in the table.

So any join on A across the tables would require only a single comparison against each table, regardless of the number of records. A join on `(A,  B)` would require a single comparison for tables 1 & 2. When comparing against table 3, table 1 can immediately be ruled out with a single comparison because of the group keys of B not matching, while tables 2 and 3 would require row by row comparisons.

We should make join require joining on group keys, but rather optimize when one or more of the join columns are in the group keys of two or more of the tables.

**Comment by jsternberg** [comment]
At the moment, to limit the scope of this, we're thinking about implementing this first following the given criteria.

1. It joins only two tables.
2. It will assume the input is already sorted correctly.
3. It will have the following function signature:

```
join = (left, right, on=["_time"])
```

4. Any group key values in `on` will be ignored (they are already matched).

The only unresolved question is what to do when there are either multiple values that match or missing values because of the different types of join. I also think that this proposal matches the needs of promql and we should ensure there is an issue for the promql join and implement this as that type of join. That way we can work on this within an internal package and get immediately feedback for how well this works and performs.
