### ISSUE TITLE
proposal: transformation function scope

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1221]
It's already been discussed that transformation functions (predicatefn, rowMapFn, rowReduceFn) are limited by only being aware of the global scope.   Users need to be able to: 

* import packages from the calling scope
* use functions defined in the calling scope
* use static values defined or evaluated in the calling scope

Additionally, it will be useful to have *table level* scope by definition, so that ANY transformation function has access, replicated for each unique group key: 
 * table schema information, including column labels and group keys
 * table row index?
 * table row record
 * local storage for defining variables specific to this table

**Comment by affo** [comment]
This looks great! One thing we should be really careful with is:

> use static values defined or evaluated in the calling scope

If you mean this:

```
obj = {foo: 1, bar: 2}
from(...) |> map(fn: (r) => {
   inc = if r._value > 0 then 1 else 0
   obj.foo = obj.foo + inc
   return {buz: obj.foo} 
})
```

Then we'll have race conditions on the globally-available `obj` and the results produced by `map` could be messy and not understandable. Maybe I misunderstood what you mean with "calling scope" 🤔. Do you mean only what is defined inside `fn`?  
(I brought up the example above also to talk about the functionalities that a shared state could provide, even if I don't think that, now, what I wrote would produce what one could think, because `obj` should be immutable).

This:
> Additionally, it will be useful to have table level scope by definition, so that ANY transformation function has access, replicated for each unique group key ...

Is something really useful and would make users able to define stateful user-defined functions.

**Comment by aanthony1243** [comment]
yeah, that only works for read-only variables.  the most important use case is locally defined functions.  But we should disallow assignment into the calling scope, or else you are correct that we would need to have concurrency primitives, which I think we should try to avoid.

**Comment by nathanielc** [comment]
@affo @aanthony1243 We get to ignore the race condition because values in Flux are immutable :), This means you can create a local copy of a static value and modify it, but that modification cannot be observed by any outside scope. 

I like this proposal, I think it will be a natural consequence of using a VM and exposing iteration over streams and tables directly.

For example take the `map` function.  Instead of defining `map` as a blackbox function over a `stream` value, it could be defined in terms of iterating over the stream's tables and rows etc.

Psuedo Flux:

```
map = (tables=<-, fn) =>
    forEachTable(tables: tables, fn: (tbl) => 
        forEachRow(table: tbl, fn: (r) => {
             // Here the table is in scope, so tbl.schema is a valid expression
             return fn(r:r) // just call into the passed in map `fn`
        }
    )
```

Ignore the bad `forEach*` function names and the fact that we can standardize how iteration works such that we do not need a function per type...

The above naturally creates a transformation scope where the current table etc are all in scope.

We need to build out the iteration primitives and change the query engine to understand them before we can do this though.

**Comment by affo** [comment]
@nathanielc I do like it! I am gathering some thoughts about stream processing in Flux. This also contains a proposal for stateful UDFs. I'll link it to this issue as soon as it is ready.
