### ISSUE TITLE
proposal: stream(groupkey) scope

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1222]
We have recently proposed the concept of extracting a table from a stream, and a row from a table, and finally, a scalar from a row.  The current design puts the results of these values into the script-local scope.  

I believe that the next logical step users will ask is "can I compute a scalar value for each table in a stream?"  There may be many ways to do this.  One possibility is that `map` adds the scalars to a globally-visible array or object for use later in the script.  

An alternative proposal is the idea of stream(groupkey) scope. In this concept, a call to a function like `map` will create a local scope that is defined exclusively for each output table on the stream.  Variables can be defined within this scope and they are retained by the runtime after the stream of transformations is complete.   The scope may be extracted with a `LocalScope(->tables)` function.  This function takes a stream of tables and extracts a data structure defining the computed local scope.  The type of this data is somewhat complex; each collection of table-scoped variables is indexed by a table schema object, specifically the group key component of the schema.  

By default, the LocalScope will always contain: table ID and schema information. 

A transformation may add values to the local scope for each table.  For example, to find the mean value for each table, and then store that value as `max` on the local scope, we could do: 
```
ls = from(...) |> range(...) 
|>  filter(...)
|>  mean()
|>  map(fn: (r) => scope.mean = r._value)
|>  LocalScope()
```
Why compute and extract a local scope?  So we can use it later: 
```
ScopedStream(scope: ls, stream: 
from(...)
|> range(...)
|> filter(fn: (r) => r._value > 2*scope.mean
```

This works well with the proposal in #1221

**Comment by affo** [comment]
I think there is a lot to say about this.

This is definitely related with stateful functions, which, in turn, is definitely related with stream processing.

In next days I'll put up a proposal for stream processing and reference this issue.

**Comment by nathanielc** [comment]
I really like where this is going. Like #1221 I think it will fall out naturally if we expose iteration over streams and tables directly See comment https://github.com/influxdata/flux/issues/1221#issuecomment-489747197

If I were to try and restate this proposal it is basically to have polymorphic containers in Flux where one of those container types is a stream, where a stream can contain tables or just a single record or value. 

Again using psuedo Flux and the `map` function. Lets first assume that we have figured out how to abstract iteration and that we have updated the `map` function to use that abstraction. The `map` function then becomes a transformation from `iterable of type A` to `iterable of type B`

So `map`'s signature is something like:

```
builtin map : (iterable: [...]'a, fn: (r:'a) -> 'b) -> [...]'b
```

Using `[...]` as the type syntax for an iterable.

So in practice a user can do this:

```
from()
   |> ...
   // Here we have a stream, which is an iterable of tables, the return value of `fn` is a scalar value.
   //  Therefore the result is an iterable of scalars.
   |> map(fn: (r) => r._value)
```

There are a few challenges to this. We have overloaded `map` already so its not clear that there are two layers of iteration happening above, i.e. one over tables and one over rows. So its not clear what the final result iterable is. We need to figure out how to make this consistent. Maybe we need a function `iter` that is the pure map function from standard functional languages and the `map` function is the the one that understands the double iteration of streams? Or possibly we use namespaces? Or maybe the solution is to always be explicit about the two layers of iteration and so to map over rows one must do:

```
|> map(fn: (tbl) => tbl |> map(fn: (r) => ({_value: r._value +2 })))
```

At which point changing the type of the iterable is more clear:

```
|> map(fn: (tbl) => tbl |> getRecord(i:0)._value)
```

Since the second map is not present it is clear that we collapsed the table into a single scalar value.

**Comment by affo** [comment]
@nathanielc looks great!

>We have overloaded map already so its not clear that there are two layers of iteration happening above, i.e. one over tables and one over rows. So its not clear what the final result iterable is.

IMHO, Flux should always compute per-group, and the user should give it for granted.  
No computation can return a simple scalar or row. It would always return scalar**s** and row**s** grouped by key. Every function, let it be a `map`, a `filter`, a `flatMap` (we should have that in the future) performs group-local computation with a group-local state.  
The user should conform with our model and know that there cannot be a group-wide computation. If a user wants to do so, then he/she will need to create a single group. This is great, because the user would be aware that he/she is (maybe) adding a performance bottleneck. Group-wide computation, in general, is indeed constrained to a single thread of execution.

This shared-nothing model would allow us to reduce conflicts in state access and easily parallelize flux pipelines.

**Comment by aanthony1243** [comment]
group key is the secret sauce of flux.  it lets you define a _class_ of jobs that will be repeated once per group.  This concept is important in alerting, monitoring, analysis, machine learning, etc.  All of these have data management problems where we are doing the same thing many times over but on different data subsets.  Most other languages reserve grouping for the purpose of computing an aggregate.  Here, we are proposing something very different.  it's an inside-out way of defining job replication, e.g., "do this one finite task for all the groups I've identified".

**Comment by affo** [comment]
@aanthony1243 I think I agree with you, but I would spend more words on:

> Here, we are proposing something very different. it's an inside-out way of defining job replication, e.g., "do this one finite task for all the groups I've identified".

I think that this is definitely related to #1256 .
That proposal calls the `scope` -> `state` (that is group-local and transformation-local too), and it explicits it in the function definition.  

I really like the idea of extracting the local scope to re-use it. This is usually done in stream processors by sending updates on the local state, so that you can cache them downstream and reuse them. In other words, `LocalScope` would return a stream of per-state (i.e. per-group) changes on the local state of a user-defined function.
