### ISSUE TITLE
Create a way to skip tests with Flux syntax

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1236]
Maybe something like this:
```
test aggregate_window_empty = () => ({
    skip: true,  // <---
    input: testing.loadStorage(csv: inData),
    want: testing.loadMem(csv: outData),
    fn: (table=<-) =>
        table
            |> range(start: 2018-05-22T19:53:26Z, stop: 2018-05-22T19:55:00Z)
            |> aggregateWindow(every: 30s, fn: sum),
})
```
We maintain skip lists in flux, influxdb and idpe, and they can get out of sync:
https://github.com/influxdata/idpe/issues/3300
Since we don't export test code, there is not a way to cascade skipped tests across repos.

But since the AST for the stdlib is exported from Flux, adding a way to skip in Flux code would solve this problem.

Caveat: if we want to run tests in the flux repo, but not in influxdb or idpe, then doing the skipping in the flux test itself would be too heavy-handed.

**Comment by affo** [comment]
I am moving this back to "Planned". I think this requires further discussion.

One key issue of the proposed approach is that `input` and `want` must be evaluated in order to see if `skip == true`.

Another one is that we don't have in flux a way to test if an object has a property, so we should add `skip == false/true` to every test. However, we could add it in the AST when running the test.

`skip` would better be a function that returns the reason why the test is skipped. The function could also use options to decide wether to skip the test or not:

```
test aggregate_window_empty = () => ({
    skip: () => {
        return if env_influxdb then "" else "give me a million reasons"
    }
    input: testing.loadStorage(csv: inData),
    want: testing.loadMem(csv: outData),
    fn: (table=<-) => ...
})
```

Given this, when running a query, we get `flux.Result`s back and not `values.Value`. So, the test execution should be changed to use `flux.EvalAST` instead of the `Querier` to inspect the scope and see what was the result of `testCase.skip()`.

If we decide to keep the boolean, then it is only necessary to `visit` the AST.

**Comment by jsternberg** [comment]
I'm wondering if it might be better for skip to be an option instead. The way we plan to use it is by defining the condition inside of Go itself and testing against a set of test names that we want to skip. I wonder if we should do this with an option instead of as part of the test object?

**Comment by affo** [comment]
After Slack call:

the test case should be an object and `input` and `want` should be functions.  
From this:

```
test aggregate_window_empty = () => ({
    skip: () => ....
    input: testing.loadStorage(csv: inData),
    want: testing.loadMem(csv: outData),
    fn: (table=<-) => ...
})
```

to this:

```
test aggregate_window_empty = {
    skip: () => ....
    input: () => (testing.loadStorage(csv: inData)),
    want: () => (testing.loadMem(csv: outData)),
    fn: (table=<-) => ...
}
```

This way we can skip tests without making `input` and `want` be evaluated.

Then `skip` can be a function that returns the reason and `testing.run` should use an `if` expression to decide what to do basing on its result.

If `skip` returns a reason, it should return a table containing the reason.
