### ISSUE TITLE
proposal:  timeSeriesAlign

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1297]
Many databases have the concept of a time series as follows:  series-key[t1, t2, t3], f1, f2, _time  where a series can be printed as a table where the series-key columns are the same on every row, and f1 and f2 and _time have changing values to represent a sequence of measurements from a specific source idetified by the series key.  The series key is typically  a set of strings.  

propose function `timeSeriesAlign(series:[{stream: S1, fields: [f1,f2]},{stream: S2, fields: [f3]},{stream:S3}], on:["t1","t2"])`  
(note:  may also have an `except: ["t3"]` that is the inverse of `on` but is not discussed here, for simplification of the writing.  

preconditions:  
1.  All streams are ordered by time
2.  All streams have the columns in `on`, which must be string-valued.  

Postconditions: 
a single stream, with a _time column, one column for each `on` column, and one column for each indicated field (or defaults if none given).  

Defaults: 
if `on` not given, we default to using all string-typed columns.   If the tables differ in this regard, then the result would be empty. 
if `fields` not given for a stream, we default to using all non-string columns. 

Two rows from a stream will match if: 
-- they have identical `on` column values. 
-- They have identical _time

Any unmatched row from any stream will be dropped  (DISCUSSION:  should we allow an OUTER join of some sort?)

**Comment by juliusv** [comment]
@aanthony1243 Coming here from your comment on https://github.com/influxdata/flux/issues/1045...

Questions/remarks on this proposal:

- For PromQL binops, this would need to support non-existent `on` columns (if one side has a column and the other doesn't => no match, if neither have it, they will still match on that column).
- In PromQL, an empty label value (column value) is treated 100% equivalently to a non-existent one, so it might also be useful to support that here. However, since that might be esoteric in the Flux context, I could also remove columns with empty values in a pre-processing step to normalize the data.
- The spec above doesn't mention how the `_value` columns of the two streams will be represented in the output. They will still need to be suffixed like in the current `join()`, I guess?
- For PromQL's `or` and `unless`, this would have to support outer joins as well.

So currently (given the above), the new join proposal in https://github.com/influxdata/flux/issues/1219 would already be closer to what I need.
