### ISSUE TITLE
Implement exists

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1327]
The SPEC states:

https://github.com/influxdata/flux/blob/15e15bd756e290d797de67afd90e44769db52404/docs/SPEC.md#L1366-L1370

This issue is to track the implementation of `exists`.

Note that the SPEC defines `exists` to be a function, however it could be implemented as a unary operator that returns `false` if its operand evaluates to _null_ and `true` otherwise.

I prefer the latter implementation as Flux does not support operator overloading and so incorporating null checks into query planning rules would not require variable context information as it would in the case of an `exists` function.

**Comment by aanthony1243** [comment]
exists as a function implemented here:  https://github.com/influxdata/flux/pull/1278

**Comment by nathanielc** [comment]
A thought: should we rename `exists` to `isNull`? When the keyword `null` was being hidden from the user and the being only modeled via this function it made sense to call it `exists`. Now that we expose `null` as a first class  concept to the user as a value that represent missing or unknown values, then perhaps calling the function `isNull` is more intuitive since that is the operation it is performing.

**Comment by jlapacik** [comment]
@nathanielc I don't have a strong opinion on the name. Both make more sense in different contexts. I would say `isNull` makes more sense if you are testing an arbitrary expression or variable, and I would say `exists` makes more sense when testing for the existence of a property on an object.

`isNull` is closer to the sql standard and implemented by a lot, if not all, sql databases.

**Comment by aanthony1243** [comment]
@nathanielc @jlapacik  the difference is in the context of the call.  
`exists(r: r,  key: "host")`
vs
`isNull(v: r.host)`

if there is no such field `host` then under the current row function implementation, it will  fail.  We'd have to update it to allow references to columns that don't exist, and deal with the resulting cascade into the evaluation.

**Comment by aanthony1243** [comment]
@affo i have an existing PR for this, i'll take it

**Comment by affo** [comment]
@aanthony1243 I was taking the approach suggested by @jlapacik (unary operator) and I was quite done with that 😅 

> if there is no such field host then under the current row function implementation, it will fail. We'd have to update it to allow references to columns that don't exist, and deal with the resulting cascade into the evaluation.

From our specification of `null`:

```
If `obj` does **not** contain an entry with property `k`, both `obj.k` and `obj["k"]` return _null_
```

So that wouldn't fail.

**Comment by nathanielc** [comment]
@aanthony1243 I like the breakdown of the two different ways to do it.  In the previous design we intentionally wanted to constrain the concept of missing values to object access hence the `exists(r: key:)` signature of the function.   Since now any expression could be evaluated to a null value, I think it makes more sense to implement the `isNull` variant as its not necessarily tied to the concept of object properties.

**Comment by aanthony1243** [comment]
this is fine.  i will still review my code as it may help with other parts of the umbrella issue around nulls.

**Comment by nathanielc** [comment]
@aanthony1243 and I had a quick chat about this, here is a quick summary:

There are two open questions on this function:

1. Should it be an operator of the language or a function with a single argument?
2. Should it be called `isNull` or `exists`.


Thoughts on operator vs function:

What is the motivation for using an operator over just a function? Do existence/null checks have something special about them that requires special syntax?

An operator requires adding a new keyword to the grammar and updating the parser etc.
An operator makes type inference a bit easier to implement because there is syntax around which type inference can apply special constraints. If its a function then those constraints need to be part of the function's type signature.

Thoughts on isNull vs exists

Do we want the function to convey its semantics or its behavior?
If its semantics, then use `exists` because the name implies the semantics.
If you want to name the behavior use `isNull`.


My opinion was that I like how these two read:

```
if exists r.host then ...
if isNull(v: r.host) then ...
```

but these other two seem inconsistent and potentially confusing

```
if exists(r: r, key: "host") then ...
if isNull r.host then ...
```

**Comment by jlapacik** [comment]
So the reason I would like it to be an operator is because the query planner will be using it to determine what can be pushed down to storage. I don't think we ever plan on a user being able to define custom operator overloading and so filter's rewrite rule can safely determine if it can push a predicate down to storage based off of the predicate's syntax.

If exists is a function then you could potentially shadow the builtin exists function and the query planner would perform it's optimizations thinking that the exists call it sees in filter is the builtin flux version. To be honest I'm not sure if this would be possible at the moment just because of the differences between row functions and pure flux functions, but I could definitely see it becoming an issue at a later date.

As far as naming is concerned, is sort of prefer `if exists r.host then ...` because I see exists mostly being used in this context. That is, I see it mostly being used to test for the existence of a property on an object. However in pretty much any other circumstance, `isNull` probably makes more sense. Coming from SQL you'd probably expect `isNull` but I'll defer to others on this one.

**Comment by nathanielc** [comment]
The concern on shadowing the function makes sense in the context of the planner. Do we have this problem with other functions? Should we just solve the resolution problem now instead of working around it? Meaning build tooling for the planner to easily determine if a function is a specific implementation of a function or if it was shadowed. 

FWIW  I am fine if we use `exists` as an operator, it's me preference from an aesthetic point of view.

**Comment by jlapacik** [comment]
We don't have this problem with any functions currently. Meaning that none of our planner rewrite rules perform actions based on whether a certain function call is present in the expression. However the planner could optimize more queries if it had more context. I prefer the aesthetics of an operator as well, so while we should give the planner more context eventually, I don't think we should block this work on it.

**Comment by nathanielc** [comment]
@jlapacik Sounds good, lets do `exists` as a unary operator.
