### ISSUE TITLE
Add Rust build process to CI

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1351]
Before merging `feat/rust-parser` we must setup running the Rust CI system.

**Comment by jsternberg** [comment]
@nathanielc and I had a conversation about this that piked my interest and I want to see how feasible that process is.

The basics is that adding Rust to the build process is probably a non-starter because the Go toolchain will not run the Rust compiler at all. The Go compiler only has the capability to compile C/C++ code and some form of assembly.

If we want to use Rust in the actual build process, it would mostly make using Flux as a library hard to impossible for most users because they would have to integrate additional build steps that wouldn't easily be possible within a Go library. This also effects InfluxDB and would make the build process much more complicated.

One idea I had though was that if it's possible for Rust to emit C or some format that the Go compiler can use, then we could write the code in Rust, generate the outputs to something the Go toolchain can process that isn't object files and commit that. Then the general method for compiling dependencies will work out of the box and InfluxDB can use the WASM generator on the Rust code directly so we would have a common input between the two systems and would use generators for the other components.

I'm going to just give this a quick try since it's in planned and report back. I see that apache arrow uses a tool called [c2goasm](https://github.com/minio/c2goasm) which seems to take ASM as input and the Rust compiler can emit ASM so I might be able to build a little toolchain from that. Then we can generate the parser for the platforms we care about and use conditional compilation to disable the Flux parser for non-cgo/not platforms we want to generate code for.

**Comment by nathanielc** [comment]
@jsternberg Thanks for the summary on this.

This issue is about simply getting the Rust WASM module built as part of CI. It is not about integrating the Rust parser as part of the Go build process.

**Comment by jsternberg** [comment]
Adding a final note to this.

Using ASM may be difficult because Rust will seemingly link libraries as part of its runtime. These get embedded in the static library that is created, but do not get emitted when you emit ASM. Since these don't get emitted, the ASM file is mostly unusable due to Rust's complicated linking mechanisms.
