### ISSUE TITLE
Create kind constraint for Nullable types

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1353]
We want to model the basic types that can be nullable using the kind constraints.

The reason is that it allows us to treat types and nullability as orthogonal concepts in the type system. Thus allowing for a type that can expression non-nullable basic types and nullable basic types.

For example 

```
a = true
```

Type inference can correctly infer that `a` is a non-nullable boolean value. This allows for better type checking and error messages to the user. 

This design is not final, we can explore related designs.

**Comment by jsternberg** [comment]
I did some investigation today and I am not sure this is needed at the moment. I am not even sure it is required for us to have nil as a possible type in the type system.

I was working through the code and I found that the type system works pretty well without adding anything for null, but just relaxing some of the constraints on the object kind. The most important for us, filter, can be gotten without any changes to the type system algorithm itself and no new constraints.

The objects keep bounds of what elements are required for the lower bound and for the upper bound. The member expression node adds each element it encounters to the lower bound and these are unioned together to form the required values. If this constraint is removed, then with a few small changes, the type system just works. It allows `{a: int}` to be used in a function that's looking for `{a: int, b: int}` without any issue and the only part that has to happen is modifying `values/binary.go` and the compiler to handle null values. Since the attribute doesn't exist, the nil type doesn't cause any conflicts. When a typed null happens, then it retains the correct type and there is no issue.

So this function:

```
f = (r) => r.a + r.b
```

This will work properly with `{a: int}` as the parameter and give a null value with the changes outlined above.

I haven't found a situation where this doesn't apply. The reason is because the only way to get null is to access an object that doesn't have a property and then the above type system works correctly with the above changes.

It may be worth trying that out before we try to add an additional constraint. I like the idea, but I'm not sure it applies in this circumstance.

**Comment by jsternberg** [comment]
Note: The above doesn't seem to work for the comparison operators because they don't add any type constraints, but that also applies to if we use a null kind constraint since it still wouldn't resolve to a monomorphic type.

This would also probably be true if two nonexistant values were retrieved too.
