### ISSUE TITLE
Flux should provide a way to distinguish between user and internal error

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1364]
Some errors happen because a user did something wrong:
- Invalid syntax
- Function call with wrong number/type/name of parameters
- Divide by zero (maybe)
- etc

When Flux is run through an http connection, for these errors it should return 4xx to indicate that the user should change their request before trying again.

Other errors happen because there was an internal error:
- A bug in our code (e.g, a recovered panic)
- Some service that flux depends on is down
- etc

In these cases, the http status should be 5xx.

The flux repo can't depend on `influxdb` and has no http interface of its own, but it should provide someway for clients to make the distinction between a bad request and an internal error.

Consider also that the type of error returned is _not_ necessarily dependent on when the error occurs; it's possible that we hit a user error when evaluating a lambda in a filter for example.

Related to influxdata/idpe#3519.

**Comment by jsternberg** [comment]
It might be worth either copying the same pattern that influxdb is now using for errors and including it in flux, as the pattern is generic, or possibly separating out the error code from influxdb so that flux can use it as a library.

@goller do you have any thoughts on this?

**Comment by nathanielc** [comment]
@jsternberg are you referring to https://github.com/influxdata/influxdb/blob/master/kit/errors/errors.go ?

The code is small enough that I am fine with copying the code directly into Flux. A little copypasta is better than a little dependency.

**Comment by jsternberg** [comment]
Yes, that's what I was referring to.

The potential reason for a dependency is then influxdb and flux could share the code and also the types would evaluate to the same for type switches. I don't think they would currently so parts of influxdb that do this:

```go
if err, ok := err.(*influxdb.Error); ok {
}
```

Those wouldn't function.

Since the code is fairly small, it could likely be a fairly reliable library so that's why I think that might be an option. I'll start playing around with the idea of copying that code.

**Comment by nathanielc** [comment]
@jsternberg Sounds good, an alternative is to have both copies of the code implement a common interface, so the type switch is on an interface instead of a concrete type, thus avoiding the need to share the type themselves.

**Comment by jsternberg** [comment]
I'm finding that it would probably be easier if we separated out the errors into a simple dependency at `influxdata/errors`. The main reason is mostly because of marshaling and unmarshaling. When it comes to marshaling and unmarshaling, the flux and influxdb errors have to be the exact same anyway in order to allow an error marshaled to JSON to work properly anyway. This probably wouldn't be an issue since the two are going to be code copies so they would have the same interface, but it seems less brittle if we create a single one file dependency with a proper version and use that to share a common interface among the products.

The other reason is because of how things like `influxdb.ErrorMessage` work. They right now perform a typecast on the specific error implementation. The reason for this is frankly that it's easier and marshaling requires using that specific type anyway. I'm in the process of changing the code so there's a method on the type like `ErrorMessage()` so it is possible to do a typeswitch on an anonymous interface with that method, but that change will also have to be propagated to influxdb too.

It seems like it would just be easier to have a separate library rather than introduce the possibility of divergence.

**Comment by jsternberg** [comment]
I created a PR for copying the errors into influxdb. I looked through the influxdb code base and I think we will have to make a more conscious effort to be more compatible with it.

It seems like in the influxdb http handler for queries it wraps the returned error and gives it a code of invalid. It seems like we'll have to go back through some of those and have them not set a code since `ErrorCode` seems to recursively check the errors within the other errors.

But that will be easier to do once we start returning error codes and have the capability to return things other then `EInternal`.
