### ISSUE TITLE
Type inference should not allow composite types to be null

### ISSUE THREAD

**Issue by jpacik** [influxdata/flux#1372]
Type checking will fail if it is determined that an object type is null. However currently it cannot tell if other composite types like functions or arrays are null. It also cannot tell whether or not a regexp type is null. This issue is to add that ability to type inference.

One way to possibly do this is to create a new kind, say a `NonNullableKind`, and any time a type is inferred or constrained to be a composite or regexp type, constrain it to also be a `NonNullableKind`. Unifying a nullable kind with a non-nullable kind will fail.

This is one way I see to implement this feature, but perhaps it is not the best way. Other implementations are possible.

The following (currently failing) test case should be un-skipped and should pass when implemented correctly:
https://github.com/influxdata/flux/blob/86860cae27c46290e20649fa65a6aabe5a6824c5/semantic/inference_test.go#L2013-L2020

**Comment by jsternberg** [comment]
This ended up getting resolved during the initial null type inference by adding all of the used keys to lower and returning an error if a key was missing and was not a nullable kind. That made it so something like this:

```
foo = {a: 1}
foo.b.c + foo.a
```

This would cause a type error because the type constraint determined that `b` was an object, but wasn't present on the `foo` object literal.

**Comment by jlapacik** [comment]
I'm reopening this as it hasn't been completely fixed.
