### ISSUE TITLE
SQL function support for Oracle

### ISSUE THREAD

**Issue by gogangipark** [influxdata/flux#1433]
I know Flux implemented postgreSQL, MySQL.
In Enterprise, We need Oracle, MSSQL support

**Comment by gogangipark** [comment]
Do you have any plan to implement oracle/mssql?

**Comment by timhallinflux** [comment]
MS SQL is done and available. https://docs.influxdata.com/influxdb/v2.0/query-data/flux/sql/

I'm going to modify this to focus on Oracle.  We need to have some discussion about how to handle the Oracle driver through the build system.

**Comment by nathanielc** [comment]
@timhallinflux Can you link us some details about the planned Oracle driver that Flux would need to use?

**Comment by ivankudibal** [comment]
* https://github.com/golang/go/wiki/SQLDrivers lists these two candidates:
  * Oracle (uses cgo): https://github.com/godror/godror this C-Go is what we used first, the most active project... support of multiple oracle versions in the cloud can be disadvantage (client time zone file should match the server, otherwise errors with TIMESTAMP WITH TIME ZONE type may occur
(such as "ORA-01805"); or yet not analyzed method of Patching of Timestamp with Time Zone Data Type can be used...?
  * Oracle (pure go): https://github.com/sijms/go-ora has not been released yet, this is what we need to try, too, because the usage in cloud might be way easier

**Comment by timhallinflux** [comment]
Cannot currently be done based on the exposed API/drivers.
