### ISSUE TITLE
Rust scanner: Ragel doesn't match µs

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1448]
The scanner in Rust doesn't  match the token "µs". There are failing tests for that both in `parser` and `scanner`. Start from them.

**Comment by yzhang1991** [comment]
After reading about Raegel, reading the scanner code, I tried:

```
duration_unit = "y" | "mo" | "w" | "d" | "h" | "m" | "s" | "ms" | "us" | 0xCE 0xBC "s" | "ns";
duration_unit = "y" | "mo" | "w" | "d" | "h" | "m" | "s" | "ms" | "us" | 0xCE 0xBC 0x73 | "ns";
```
Somehow it does not work at all.

I tried
```
duration_unit = "y" | "mo" | "w" | "d" | "h" | "m" | "s" | "ms" | "us" | ulower "s" | "ns";
```
This makes `µs` pass in Go not using the Unicode literal (along with other invalid cases, it's OK, just for testing). But that cannot make Rust work too. So I now think it may be a Rust issue rather than changing the way we define it in Raegel.

I have been debugging the test case, not getting helpful insight yet.

**Comment by affo** [comment]
I tried to encode the "mu" character in hexadecimal as well, but it didn't work. I suppose that's a C problem. I'll have a try on this once I finish with my current task.
