### ISSUE TITLE
Pass over SPEC.md

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1454]
By looking at SPEC.md, I saw 2 issues:

 - some tables are poorly formatted;
 - aggregates are defined to work on many columns, while function signatures specify a single column.

**Comment by stormasm** [comment]
I have generated out a table of contents (TOC) of spec.md that allows one to better understand the organization of the spec.  

https://github.com/stormasm/fluxspec/blob/master/specindex.md

One can see from this TOC that the spec and the 
[doc for the spec](https://v2.docs.influxdata.com/v2.0/reference/flux/)

is organized differently
with (2) sections and **Flux Packages and Functions**  broken out from the spec organizationally in the doc.

Having a TOC would enable everyone to better understand how the SPEC is organized.
I would highly suggest we do that soon, because the SPEC is a very important document
that needs to be a bit more refined from an organization point of view and right now it is
very challenging to decipher the organization level of the SPEC.md file.

**Comment by affo** [comment]
@stormasm I see, good point.

This issue was more about fixing the current spec, but I think you are raising a crucial point.  
Just to brainstorm ideas, we could organize our SPEC.md into a Github wiki (https://help.github.com/en/articles/about-wikis). We should discuss this as a team, because that would introduce overhead when producing changes in the Flux engine (managing wikis in the flux repo: https://stackoverflow.com/questions/11735012/github-wiki-managed-by-the-main-repository), but it would improve considerably user experience. 

FYI @nathanielc ^^

**Comment by stormasm** [comment]
@affo @nathanielc  I really like the current solution of spec.md and think the whole wiki solution is probably overkill.  My suggestion would be to leave spec.md alone as it is, just simply re-organize the spec file a bit to align with the documentation.
