### ISSUE TITLE
Investigate improvements to arrow array builder interface

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1523]
Some open questions:

Q: Is the arrow array builder slow?

Create benchmarks for builder vs slice append.

Q: How can we mutate arrow arrays as part of building? 
  Read C++ API for builders on how to mutate arrow buffers. Do we really need to mutate them or can we construct the Holt-Winters algorithm as append only?

**Comment by jsternberg** [comment]
The C++ array builder API does not appear to have any API for swapping or setting values. There does appear to be an API for building an array from an external buffer so it may be worth figuring out if we can do that ourselves with direct access to the memory buffers. It is possible using `NewData` to construct an array without using the array builders.

**Comment by jsternberg** [comment]
It is possible to use and manipulate slices and integrate them with arrow. Here is an example: https://play.golang.org/p/qZzsIv81w8t

Some caveats.

1. The array needs to be created using `memory.NewResizableBuffer`. If you create the byte slice outside of that and use `memory.NewBufferBytes`, the buffer will not free the memory because it doesn't "own" the memory so you would have to do that yourself.
2. It does not appear to be necessary to use `CastToBytes` after manipulating the array. I tried this with floats and ints.
3. Nulls are not supported in this circumstance. If we want to make it possible to use nulls, then arrow will need to expose some of their internal packages. The bit manipulation stuff seems to be in internal packages and therefore not accessible to us.
4. The arrow builder API does not expose this, but honestly, it probably could?
5. You need to use `Resize`. `Reserve` does not work.
6. It is not very user friendly with the locations where you have to call `Release` although they are consistent.

I cannot speak about the Holt Winters algorithm itself, but it would be very possible and not too difficult to make our own separate mutable builder that would allow us to work with a slice as a slice and then have it built. Since the methods don't exist in the C++ API, it would probably be harder to get this implemented within arrow itself and it would likely involve a lot of back and forth.

I would recommend that we just build our own utilities to encapsulate some of the calls above. I don't think it would be very difficult and it would likely be easiest.

**Comment by nathanielc** [comment]
In conclusion using mutable arrow arrays is not really doable. Which makes since because arrow arrays are designed to be immutable from the start.

In the case of Holt-Winters we need a mutable array of floats but it is of fixed size so we only need to change the values within the array but not grow/shrink the array. In this part of the Holt-Winters code nulls are also not needed.

I think in this case it makes sense to build our own lib for allocation tracked slices, and use a slice in the Holt-Winters code. See my comment here https://github.com/influxdata/flux/pull/1498#discussion_r303612996 Its a rough sketch but the idea is that the allocation tracking is internal to the implementation as much as possible.

**Comment by nathanielc** [comment]
Adding a bit more clarification after an internal conversation.

There are two relevant parts to Arrow: the allocation API, and the array API. My conclusion is that since Arrow arrays are not meant to be mutable we should not try and make them mutable. Since we need an implementation of a mutable allocation tracked array of floats we should build it ourselves since changing the arrow array API is not an option.

The mutable allocation tracked array type we build can be backed by the arrow allocation API as that is solid good code. But the type should not try to expose or modify the arrow array API to be mutable rather it should expose slices.

T:DR arrow arrays are not meant to be mutable, as such we should not try to use them as such. But we can build our own mutable array type that uses many of the arrow array concepts and even libs.

**Comment by jsternberg** [comment]
I'm going to create an issue for creating a small library for dealing with mutable arrays and then close this one because this was a research issue and that is done.

**Comment by jsternberg** [comment]
Something further, it does seem like you can modify the array _after_ it is constructed when you are using one of the arrays with direct access to the values. This seems a bit dirty, but it does seem to work.

This code works although the playground doesn't work with `memory.Set` so you have to copy/paste it locally.

https://play.golang.org/p/P8jN4qwHbWm
