### ISSUE TITLE
Implement integration points

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1546]

**Comment by aanthony1243** [comment]
### Integration points
These should be implemented as output nodes 

- [ ] Alert See 
- [ ] HTTPOut
- [ ] HTTPPost
- [ ] InfluxDBOut
- [ ] K8sAutoscale
- [ ] KapacitorLoopback
- [ ] Log
- [ ] Stats
- [ ] UDF

**Comment by nathanielc** [comment]
The Alert and HTTPPost nodes above are really part of the alert and notification work and do not need to be tracked here.

Some of the other nodes in this list require some specific discussion:

* HTTPOut, this is likely not possible in Flux. It allows for a cache of the data to be stored and then exposed via Kapacitor's HTTP API. The Flux way to do this would be to integrate with third party HTTP caches and move that workload outside of Flux. 
* InfluxDBOut is just the `to` function so it can be marked done
* K8sAutoscale could be implemented in Flux without issue.
* KapacitorLoopback is also just the `to` function in Flux context and can be marked done.
* Log node was used in Kapacitor much like the yield function is used in Flux. While they are functionally very different, they serve the same use case, (i.e. debugging scripts). We can probably mark this one as done too since exposing logs is not how we will debug Flux scripts.
* Stats this node will be served by the meta channel concept we have planned in Flux. As such we can disregard it here as its scope is tracked elsewhere.
* UDF - I have no plan for how these will work inside Flux. This is a significant design question and will needs its own issue/epic to track progress.

**Comment by nathanielc** [comment]
This issue has served its purpose. Closing, if we need to track details on anything left we can do so in a specific issue.
