### ISSUE TITLE
Sleep 

### ISSUE THREAD

**Issue by docmerlin** [influxdata/flux#1581]
the sleep function should happen on execution, instead of where it is happening now.  Right now a sleep function has deleterious affects on tasks.

**Comment by nathanielc** [comment]
@docmerlin can you explain how the sleep function is effecting tasks?

**Comment by docmerlin** [comment]
If someone creates or updates the flux code in a task with a sleep in it.  It will lock the connection for the duration of the sleep.  Example: if you create a task, with a 35 second sleep, the createtask api call won't return for over 35 seconds.

**Comment by nathanielc** [comment]
@docmerlin Why does creating a task evaluate the Flux code?

**Comment by docmerlin** [comment]
@nathanielc it calls flux.EvalAST to look for errors in the flux code, that would signify an incorrectly written task.

**Comment by docmerlin** [comment]
We also need the scope, to pull out the task options.

**Comment by nathanielc** [comment]
@docmerlin The task options as well as basic error should be available statically. Looking at some code I can see how flux.EvalAST works for now to accomplish that but it is not a safe operation. In the Flux engine we are no longer exposing a different between evaluating the interpreter vs the query execution steps. They will be one in the same since they can call back into each other.

This means we need to provide you with the correct static analysis functions that you need. Can you create an issue that details what exactly you need from the initial analysis of the Flux code on task create?
