### ISSUE TITLE
Move changelog generator its own repo

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1589]
The changelog generator command has been working well and we are moving the practice of semantic commits to  more repos. As such we need to move the changelog generator out of this repo and into its own.

**Comment by jsternberg** [comment]
The `influxdata/changelog` repo would be a good place for this, but I ended up using that repository for the changelog generate for v1.

I'm going to experiment with this though to see if it's possible to keep them both in the same repository. If it doesn't yield anything in maybe an hour, I'll figure something else out.

**Comment by jsternberg** [comment]
I found out that the changelog as used by influxdb has been using a pre-built docker container for awhile as the changelog does not build at the moment because it doesn't use any dependency manager and one of the dependencies it used changed.

I'm just going to move the master branch to an `old` branch and hijack the repository for the changelog.
