### ISSUE TITLE
SlidingReduce Function

### ISSUE THREAD

**Issue by roshie548** [influxdata/flux#1611]
### Function
`slidingReduce` will window data and apply a function to each of those windows. It has 3 parameters:
- `every`, duration
- `period`, duration
- `fn`, signature `(rows) => ...`

`fn` can index into rows

### Example Use
`slidingReduce` can be used to write `tripleExponentialDerivative` in pure Flux:
```
tripleExponentialDerivative = (n, tables=<-) (
    tables
        |> exponentialMovingAverage(n: n)
        |> exponentialMovingAverage(n: n)
        |> exponentialMovingAverage(n: n)
        |> duplicate(column:"_value", as:"diff")
        |> difference(columns: ["diff"], keepFirst: true)
        |> slidingReduce(every: 1, period: 2, fn: (rows) => rows[1].diff/rows[0]._value)

**Comment by aanthony1243** [comment]
I think `every` and `period` should be integers so that the sliding group is row-based, and not time-based.   

to clarify the expectation:  the `(rows)` function will take an array of row records, and return a single row record.  So this is, in a way, a combination of map and reduce.  the record will be stored at the same position as the first element in the set.

**Comment by jlapacik** [comment]
Is this more general than `aggregateWindow`? Can `aggregateWindow` be defined in terms of `slidingReduce`? I'm also not sure I quite understand this function definition:
```
fn: (rows) => rows[1].diff/rows[0]._value
```
Why does rows need to be a list?

**Comment by jlapacik** [comment]
How do we reduce an array of records down to a single record in pure Flux?
