### ISSUE TITLE
`diff` does not check for rows.

### ISSUE THREAD

**Issue by ewendai** [influxdata/flux#1616]
Specifically, diff does not see the difference between:

```
#group,false,false
#default,_result,0
,result,table
``` 

and

```
#group,false,false
#default,_result,
,result,table
,,0
```

**Comment by wolffcm** [comment]
This issue is specific to the edge case where there are zero columns in both tables.  When there are no columns, there is nothing for `diff` to actually do.

Maybe this is a distinction without a difference.  Just noting it here for posterity.  Note however that it is possible to express a non-zero number of rows even when there are no columns in CSV.
