### ISSUE TITLE
Develop set of possible integration plans with PromQL transpiler

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1619]
The PromQL transpiler work brought in many dependencies into Flux which in turn effects projects which consume Flux. We need several plans for how to incorporate PromQL into Flux such that it doesn't bring tons of unneeded dependencies.

One concrete example is `k8s.io/client-go` the Prometheus module depends on that module and idpe depends on a different version of the same module. This causes issues and it should be a non-issue because Flux's dependency on PromQL doesn't actually use k8s. 

Possible solutions:

1. Prometheus upstream creates separate modules.
2. Flux downstream (i.e. idpe) uses replace directive to force the correct k8s.io/client-go module version.
3. Use separate modules within the Flux repo so that dependency creep is isolate to just those module.

**Comment by juliusv** [comment]
Here's a general (relatively InfluxData-independent) discussion I started on the Prometheus developers mailing list about how we should deal with Go modules and versioning: https://groups.google.com/forum/#!topic/prometheus-developers/F1Vp0rLk3TQ

**Comment by jsternberg** [comment]
My current thought on this is that while number 1 would be useful for Prometheus to do, it might be bad for us to rely on them making a decision so I am going to spend some time seeing how the second option would look in combination with the third option.

So the idea is that the promql transpiler would be its own module so as not to effect flux. And then we would use replace directives in our closed source code that uses k8s where we need to be able to set the dependency. I'm curious if this would work.

If it does work, then we can just do that and continue the conversation with the Prometheus development team while we have the transpiler work integrated rather than being blocked on external decisions.

**Comment by jsternberg** [comment]
It's not going to work. The influxdb project cannot depend on prometheus in any way because prometheus depends on influxdb (specifically v1 of the project) and that causes a _huge_ dependency mess.

This may be resolvable by us though. But, we would need to change v2 to actually follow the v2 syntax for modules so that v1 and v2 can live side-by-side with each other.

@goller I don't know if you have wanted to make that change. It may be time for us to fix our own impending `+incompatible` problem with modules.

**Comment by jsternberg** [comment]
Another option that came to my mind but may not find favor is that we "vendor" the promql parser and AST inside of an internal package within the transpiler. This allows us to control the work ourselves. While we wouldn't get updates automatically, I'm not sure we need updates automatically. It would only be relevant if the promql package itself changes and needs to be updated and we could keep a record for how to maintain it.

If we did the work for this, then we would also be able to present the Prometheus developers with exactly what we need. But we wouldn't actually be at a loss if they chose not to use it.

**Comment by juliusv** [comment]
> Another option that came to my mind but may not find favor is that we "vendor" the promql parser

That is similar to what Calle proposed here, where the Prometheus project itself would mirror out those packages into smaller, consumable modules somewhere: https://groups.google.com/d/msg/prometheus-developers/F1Vp0rLk3TQ/os0ufXY9CAAJ

Not sure how likely that is to happen yet of course.

**Comment by jsternberg** [comment]
Here's the set of possible plans: https://gist.github.com/jsternberg/474f6b2377702fe97e15589bd6e82cf4

@nathanielc can you look at that and comment in this issue if there's something else you want me to explore? The vendoring in internal of promql is probably our easiest, safest, and most future-proof of the options that we have at the moment.

**Comment by nathanielc** [comment]
@jsternberg Thanks for the various options. I think we should wait to see what the Prometheus teams decides. If they decide to export a module for the PromQL bits then we can go forward with that. There is no specific reason to rush getting this integrated other than the code becoming stale. So I am fine waiting a bit to see what upstream decides.

I'd like to hear the specific reasons why you think creating a separate module in Flux for the transpiler will not work. It that because in the end InfluxDB/IDPE will need to import the module anyway so it doesn't really help the current issue? Or something else?

**Comment by jsternberg** [comment]
That's fine if we wait for Prometheus.

And yes, that is the reason I think creating a separate module won't work. `k8s.io` is really only the beginning. Prometheus, the main project, imports influxdb v1 and our own project isn't `go.mod` compatible for having those two major versions sitting side-by-side. We can fix this, but I feel as though I'll find another dependency that causes an issue and we'll be playing whack-a-mole with dependencies we didn't want to begin with.

If you don't have any other questions, we can likely close this issue.

**Comment by juliusv** [comment]
I think the thread I linked above piqued the interest about modularization in a bunch of Prometheus people, but there won't be consensus on anything without a more concrete worked-out PR / proposal. I'll try to actually play around with module-splitting in the Prometheus repo now to see what it would actually look like and how much of a burden it introduces in Prometheus-land, and then go from there.

**Comment by nathanielc** [comment]
Great, thanks for the update and let us know if we can help in any way.

**Comment by nathanielc** [comment]
We have decided to go down this path 


## Vendor PromQL and remove extraneous dependencies

I do not believe it would be difficult to vendor PromQL and remove the engine components. The PromQL AST is really all we need from prometheus for anything other than the end to end tests and we could feasiably place the end to end tests somewhere separate so dependencies aren't an issue.

This would be the simplest and most in our own control. I don't think that the PromQL parser and AST will change frequently and, if it were to do that, the Transpiler would probably have to be updated too. This also means we get the cleanest dependency tree and we do not rely on Prometheus to make any specific decisions.

If in the future they were to split of PromQL into a separate module in the same way, we would just replace our version that would be vendored in `internal` with the officially released module with very little problem.

**Comment by juliusv** [comment]
Note we'll still need the PromQL engine for the e2e tests, but that code could be put into a separate package if we don't want to depend on it in the transpiler itself. It just needs to be also vendored+modified, in order to be able to depend on the vendored AST types and not the "official" ones from `github.com/prometheus/prometheus/promql`.
