### ISSUE TITLE
options without flux.EvalAST

### ISSUE THREAD

**Issue by docmerlin** [influxdata/flux#1621]
Tasks needs to be able to inspect task options safely, and validate flux code, without having to evaluate flux.problems due to the sleep function in flux as described in #1581 .

 Currently we call flux.EvalAST to get a scope, that we then use, but this runs into problems.  Nathaniel suggested that the problem wasn't with the sleep function but with us needing to eval the code.  This ticket is the result.

https://github.com/influxdata/influxdb/blob/master/task/options/options.go#L206

**Comment by nathanielc** [comment]
@docmerlin can you add details here about how the options are used? There are parts to how this works that I don't understand/have enough context. Here are a bunch of questions to help communicate where my gaps in understanding are. 

* What kinds of validation are being performed? Are you just checking that the script 
can parse? Something more specific?
* When the option scope is retrieved how is it used? It is modified, or is it read only? I know we created some `edit` APIs for tasks but those all operate at the AST layer not on actual values. Do you need the actual values? My guess is you do in order to know the option values. Maybe we need to provide more explicit way of getting just the options out of a script instead of having you evaluate it and then extract the option scope?
* Do you extract anything else from the evaluation? Or just the options and the fact that it can evaluate (i.e. it is valid)?

**Comment by docmerlin** [comment]
We extract only the options and validate them and the rest of the script.  
  1) we make sure it is a flux object and that it is valid flux.
  2) we make sure the required fields (for tasks) are defined and are the right flux type and the correct value.
  3) because durations are funny, we would prefer the duration string (for now) not the value, unti longer durations (month, week, etc) are fixed in flux.
  4) we validate the task option values with relation to each other.
