### ISSUE TITLE
Implement check function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1639]
The check function has been defined in #1601. It might be able to implement in pure Flux in terms of a map function with conditionals. Prefer the pure Flux implementation.

**Comment by wolffcm** [comment]
I am implementing this with a slight difference from the doc that was checked into Flux:
https://github.com/influxdata/flux/blob/11215b685510974f3742a649449ec5a1bf9d03e9/docs/Alerts.md#check

Instead of adding `_name` to the group key, the `_name` column will just be added to the table without being in the group key.  This will allow the implementation of `check` to be in pure Flux.

The `_name` field should be part of the group key when the output of `check` is stored via the `write` option.  In order to achieve this in `influxdb`, changes to `to()` need to be prioritized instead.  That's this issue: #213

**Comment by wolffcm** [comment]
New proposed implementation of `check` looks like this:
```
check = (tables=<-, name, crit, warn, info, ok, messageFn, extraTags) =>
    tables
    |> experimental.set(o: extraTags)
    |> map(fn: (r) => ({r with
        _name:  name,
        _level: if crit(r: r) then levelCrit else ...,
    }))
    |> map(fn: (r) => ({r with _message: messageFn(r)})
    |> experimental.group(mode: "extend", columns: ["_level", "_name"])
    |> experimental.group(mode: "extend", columns: objectKeys(o: extraTags))
    |> experimental.to()
```
I made issues for `experimental.group`, `experimental.to`, `objectKeys` and `experimental.set`, and this issue depends on all of them.
