### ISSUE TITLE
HTTP Post function with Authorization lookup capability

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1683]
The actual HTTP post will be implemented on this issue: https://github.com/influxdata/flux/issues/1686

we will extend this function to perform secret lookups where relevant as described in : https://github.com/influxdata/flux/pull/1648/

**Comment by jsternberg** [comment]
I think this needs #1682 to be done before this can be done meaningfully. I think that the format has been defined, but there will likely be some utility methods that will get defined as part of implementing #1682 that this one would use so I'm going to put this back in the backlog.

I'm keeping it assigned to myself because I plan to do it, but if someone wants to pair or start working on it, please contact me and we can work together on this.

**Comment by jsternberg** [comment]
I think this does not need to be done. We clarified the requirements and there was no requirement to only do secret lookups in Go code so the HTTP post can just load the secret and the secret can be used as if it were a normal string value.

I don't think there's any change to HTTP post required so I'm going to close this.
