### ISSUE TITLE
Cannot see overridden options from inside stdlib functions

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1720]
Consider a package in the standard library:
```
package foo

option bar = 37

do = (tables=<-) => tables |> map(fn: (r) => ({r with bar_opt: bar}))
```
If I use `bar` from my Flux script:
```
package main
import "foo"
option foo.bar = 72
from(bucket: "my-bucket") |> foo.do()
```
I would expect that I would get rows with `bar_opt` set to 72, however, because of scoping issues, I instead see the original value for the option, 37.

**Comment by nathanielc** [comment]
Accidentally created duplicate issue in #1721 

Adding details from that issue here:

In short the builtins have a differing startup scope to the runtime scope and so assignment expressions do not effect the startup scope and therefore options cannot be mutated for builtins.

Possible solution is to create named scopes and explicit options scopes, and merge the scope stack for startup scopes to runtime scopes into a new scope that observes the option mutations.

The merged/swapping behavior can be implemented in the doCall method of the interpreter.
