### ISSUE TITLE
Add ability to test side effects in FluxEndToEnd tests

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1728]
Specifically we need the ability to test that HTTP post creates side effects (POST requests to an httptest server) during the TestFluxEndToEnd test cases.

**Comment by jsternberg** [comment]
We might need to discuss the plan for how to do this before we begin implementation. I think the first thing might be to discuss how execution of the scripts are supposed to happen. I have been under the impression we're moving towards more of a deterministic execution model which would potential help with making sure that we can test this. Otherwise, at the moment, I'm not sure this would be possible just because there would be no way to guarantee the order of execution.

Alternatively, we could have the testing of side effects be within the Go code itself, but I'm not sure how we feel about that since I think the goal is to not require Go for running Flux tests.

**Comment by affo** [comment]
#1799 should be a blocker. It should make the execution more deterministic.

Once we have included that, we can avoid the double round of execution when running e2e tests. And we can safely say that side effects are produced once.

In order to make this work we should:
 - run the dependencies of every test (http server, slack mock endpoint, and so on so forth).
 - check that those endpoints "contain" the expected results.

How can we test that those endpoints have the correct results?

I would say that the user should specify the side effects in the flux code.
For now, the only viable option seems to specify the expected results as tables in our CSV format.

This implies that we should have `from` functions for every endpoint we have, so that we can compare what we get from those endpoints to the user's expected results directly in Flux.

Thoughts?
