### ISSUE TITLE
numericarray's reset() causes buffer.go to panic when provided with a null argument 

### ISSUE THREAD

**Issue by sauren-khosla** [influxdata/flux#1743]
The line: 
`return mutable.NewFloat64Array(r.alloc).NewFloat64Array()`
from a previous version of `Holt-Winters` caused a panic (nil pointer dereference).
The issue is the communication between our `numericarray.go` and `buffer.go`. `Release()` In `buffer.go` (which is called by `reset()` in `numericarray.go`) assumes the `b` passed in is not nil, as it tries to access one of its fields before actually releasing:
`if b.mem != nil {`,
which is where we're getting the panic. We should verify on line 341 of `numericarray.go` that `b.data` is not `nil`, as that is what we're passing in as the `b` in `buffer.go`.

**Comment by jsternberg** [comment]
Ah, this may not be a bug in the mutable package then. Unlike the `arrow` package, the `mutable` package requires that the allocator actually be real. Also, the code above might cause a memory leak anyway.

**Comment by sauren-khosla** [comment]
> Ah, this may not be a bug in the mutable package then. Unlike the `arrow` package, the `mutable` package requires that the allocator actually be real. Also, the code above might cause a memory leak anyway.

It just takes in a pointer to a Float64Array. How does it verify the address is not invalid or null?

**Comment by jsternberg** [comment]
I'm not sure what you mean. Is `r.alloc` nil in the example above or is it something else?

The weird part is it should be valid for `b.data` to be nil.

**Comment by sauren-khosla** [comment]
> The weird part is it should be valid for `b.data` to be nil.

This^ answers my question. 

I actually just checked and `r.alloc` is a seemingly valid `memory.Allocator`. Its values `bytesAllocated` and `maxAllocated` are both initialized. So you're right, it must be another issue.

**Comment by sauren-khosla** [comment]
Line 53 of `buffer.go` seems to be the culprit. In `Release()`, we don't check if the `b` passed in is nil or not, so when we try to check if `b.mem` != `nil`, we're trying to dereference a nil value.

**Comment by sauren-khosla** [comment]
I think the issue is the communication between our `numericarray.go` and `buffer.go` (which was not written by us). `Release()` in `buffer.go` assumes the `b` passed in is not `nil`, as it tries to access one of its fields before actually releasing:
`if b.mem != nil {`,
which is where we're getting the panic. We should verify on line 341 of `numericarray.go` that `b.data` is not `nil`, as that is what we're passing in as the `b` in `buffer.go`.

**Comment by jsternberg** [comment]
Ah, I see it now. It's `NewInt64Array` (or the equivalent methods) that cause the issue.

So just a note, it's ok to have a null buffer for the arrow data type. There's code in there that prevents attempting to release a null buffer. It seems that a mistake was made in `numericarray.go` though. The `reset()` method is only supposed to be called if `b.data` is non-nil, but the `NewXXXArray()` methods all call `b.reset()` without checking if that is true or not.

So there's two possible fixes and both are valid.

1. Make it so the check for `b.data != nil` is inside of `b.reset()`. If this is done, then `Release()` should be changed to rely on this behavior instead of checking for `b.data != nil` itself.
2. Have `NewXXXArray()` check if `b.data != nil` before calling `b.reset()`.
