### ISSUE TITLE
Interpolate arbitrary expressions in string literals

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1775]
Currently you can only interpolate string valued expressions inside of string literals. This issue is to add support for interpolating arbitrary expressions inside of string literals. All interpolated types should be formatted as strings according to their literal representations.

**Comment by rbetts** [comment]
Since, currently, only string literals can be interpolated, interpolation provides client writers a reasonable bind-parameter equivalent to prevent flux injection.  If this is relaxed to allow arbitrary expressions, we should still let script authors force the type of the interpreted variable so they can continue to rely on the language not evaluating user provided input as executable expressions.

**Comment by jsternberg** [comment]
@rbetts I think extern variables are what does that. String expressions right now still allow arbitrary expressions to be evaluated. The only requirement is that the return type is a string. So I can still do:

```
"${string(v: a + b)}"
```

This doesn't create an injection opportunity though because the user isn't modifying the flux program at all. They are only modifying the data. The string expression doesn't change how the expression is parsed.

I'm happy to go into this more. Injection is pretty serious so we want to make sure we avoid it and hopefully I've understood what you mean.

**Comment by philomory** [comment]
Has there been any more discussion on this?

I'd especially like to see support for this feature because as it stands, `string(v: r.foo)` is null if `r.foo` is null, which means the only way to interpolate the value of a column that may be null (e.g. for a check message) is to do something gross like `"foo is ${if exists r.foo then string(v: r.foo) else "null"}"`.
