### ISSUE TITLE
Refactor dependency injection in Flux

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1795]
This should solve different issues:
 1. make it so that injecting dependency is clean an clear;
 2. make it so that injecting dependency is extendable once one uses Flux as a library;
 3. enable dynamic queries.

For `3`, dependencies should include the `memory.Allocator` used for the current query.

Dependencies are a mixture of static ones (bucket lookup service, storage reader, points writer, the secret service etc.) and dynamic (the allocator, the logger?, etc.). We need to find the best pattern to incorporate them.

Given that there is at least one dynamic dependency, there should be a new dependency object that gets created per request.

Possible ways of implementing this:
 1. use Go's `context.Context` and use private keys to inject the deps into it (very flexible);
 2. some framework for Dependency Injection (DI) in Go (idea to explore);
 3. Object embedding. Flux define its deps, InfluxDB embeds those and adds its ones and casts the dep object to extract them when it needs to. Other Flux users can do the same.

I have already implemented a refactor for InfluxDB and Flux to remove `execute.Dependencies` and only use `dependencies.Interface` (implementing strategy `3`). That is a good starting point to move to another implementation if needed.

The changes are WIP, this is the link to them:
 - Flux: https://github.com/influxdata/flux/compare/exp/dynamic-queries
 - InfluxDB: https://github.com/influxdata/influxdb/compare/exp/dynamic-queries

This issue also makes the implementation  for the new design of compilation and execution unnecessary (#1499  and its children).

**Comment by jsternberg** [comment]
I had worked on a prototype to how dependency injection might work using context. I like context because it is very flexible and I think it is more user friendly from a programming point of view. Since it is a common Go library and idiom, it would work well. Further, I believe that moving to using the `context.Context` would be a good middle ground as it would be easily possible to inject all of the dependencies in `execute.Dependencies` into the context and have them live in the dependencies so that the code transition is lighter.

I kind of fear that another major refactor of the code without a clear transition plan will be too difficult.

https://github.com/influxdata/flux/compare/refactor/dependency-injection?expand=1

Now the exact method of how the dependencies are structured inside of the context is very flexible. For example, we could just inject the `execute.Dependencies` themselves into the context. I am not a big fan of the string keys and how the dependencies are usually organized on a per procedure basis, but it would be something that was possible. But the above pattern is very flexible on the internal details of how the stuff is stored in the context and I think it would provide a good base to start with.

**Comment by affo** [comment]
@jsternberg Thinking about it more, I like your proposal @jsternberg because of its flexibility.

If we implement that, we could actually remove `execute.Dependencies` from Flux, because, at that point, Flux shouldn't need to be aware of them, only InfluxDB. InfluxDB should trust Flux to keep everything in the context until when its control comes back in transformations or sources (in order to extract deps from it).

I think that the impact of this implementation, in terms of refactor, would be equal to mine implementation, because, in the end, you will need to remove `dependencies.Interface` from signatures and make the testing code work and blablabla. That's almost what I did in the code above.

I think the only thing here is to decide whether  to chose DI, context, or embedding. Any solution will bring a big refactor if we want to cleanup the code and simplify things.

**Comment by jsternberg** [comment]
Yea. The end result would likely be the same because removing `dependencies.Interface` would have a similar impact. I think we should avoid removing that in the first part of the refactor and just provide the dependencies through both methods.

I guess it depends on which is easier. I'm hesitant to perform a large refactor and also change method signatures at the same time because I think it will end up in conflict hell.

**Comment by jsternberg** [comment]
Here's my proposed interface. I would eliminate the `dependencies` package personally.

```go
type Dependency interface {
    Inject(ctx context.Context) context.Context
}
```

Each dependency type would have something like this in a package dedicated to secrets. Names can be different. If this is in something like a `secrets` package, the names may not need to be so verbose.

```go
type key int

const (
       secretServiceKey key = iota
)

// WithSecretService will inject a SecretService into a context.
func WithSecretService(ctx context.Context, ss SecretService) context.Context {
       return context.WithValue(ctx, secretServiceKey, ss)
}

// SecretServiceFromContext will retrieve a SecretService from the
// context. It will return nil if none has been set.
func SecretServiceFromContext(ctx context.Context) SecretService {
       ss, _ := ctx.Value(secretServiceKey).(SecretService)
       return ss
}
```
