### ISSUE TITLE
strings.repeat can easily crash Flux

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#1812]
It's possible to create huge strings using the Flux function `strings.repeat()`, thus exhausting memory and potentially bringing down a production environment:
```
// allocate a bunch of 1GB strings:
from(...) |> ... |> map(fn: (r) => ({r with _value: strings.repeat(v: "?", i: 1000000000)}))
```
We should guard against this somehow... maybe `repeat` needs a limit to its `i` argument?

Do other functions have the potential for abuse like this?

**Comment by nathanielc** [comment]
What about making `strings.repeat` use the Allocator explicitly? Then if it would allocate too much it would be killed. 

That fixes this specific function, but does not address the more general issue. Should we do this for all strings.* functions?

**Comment by jsternberg** [comment]
The easiest way of dealing with this is probably just to limit the size of strings that can be produced by this method. At the moment, we don't have any tracking of allocations for any types outside of rows so using the allocator is mostly not possible because we can't track when the string is dead.

I think we can choose a reasonable limit, such as 10 kb, and say that no string produced by this method can go past that.
