### ISSUE TITLE
from.sql() appears not to close the db connection

### ISSUE THREAD

**Issue by davidgs** [influxdata/flux#1854]
After a very short mount of time, the UI returns: `Error 1040: Too many connections` 

In looking through from.go it appears that while: 

func (c *SQLIterator) Close() error {
	return c.db.Close()
}
Exists, it is never called from anywhere in the code, thus leaving the connection open.

**Comment by davidgs** [comment]
Can confirm it is still present in latest `master`

**Comment by jsternberg** [comment]
@davidgs any chance you can give an anonymized version of the query you are using? I'm just curious if it has a `GROUP BY` as I suspect I may know what is happening. It does not seem as if we ever call `Close()` on the `sql.Rows` that are returned and I'm curious if that's keeping the connection open. But the documentation also says that `Next()` should close the `sql.Rows` if there are no further result sets.

**Comment by davidgs** [comment]
`import "sql"

humidity = from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "environment" and (r._field == "humidity"))
  |> last()
  |> map(fn: (r) => {
        return { query: "SELECT * FROM Sensor_Data WHERE Sensor_ID is ${r.Sensor_id}" }
        })
// |> yield()
  
sql.from(
  driverName: "mysql",
  dataSourceName: "foo:barr@tcp(localhost:3306)/IoTMeta",
  query: humidity.query // "SELECT * FROM Sensor_Data WHERE Sensor_ID = \"THPL001\""
)`

This is from the UI, not CLI. If you just paste the SQL query in to a dashboard query, and set the update frequency to `5s` you will see the # of connections increment every 5s. 

I've attached a SQL file here with the right database stuff so you can import it into a local MySQL instance to test. 
[IoTMeta.sql.zip](https://github.com/influxdata/flux/files/3621484/IoTMeta.sql.zip)

**Comment by jsternberg** [comment]
I took a short look at it and I think I understand the issue. The source decoder will call `Fetch` repeatedly until it gets `false` from it. For some reason, it will always `Fetch` and `Decode` the first response even when it returns false. On the second though, it will not call `Decode` if false is returned. The sql iterator executes a new query each time that `Fetch` is called and unless that row is read, it will not close it which leaves the connection open. Since the `Fetch` method for sql always returns false, we get a situation where every call to `Fetch` leaves a connection open even if you close the overall connection because that sql reader is left open and will likely never be closed until the sql server forces it.

**Comment by davidgs** [comment]
Your fix has been running all weekend and my sql connector count has remained steady at 3, so I think you nailed. it.
