### ISSUE TITLE
The timestamp of an alert check should be the timestamp that the check was generated, not the timestamp of the point

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#1899]
The timestamp of an alert check status is currently the timestamp of the point that generated the status (max and min for example is the timestamp of the max or min point). The timestamp of the check status should be the time that the check was run. There should also be a field for the timestamp of the point stored in the status.

@desa could you fill in the technical details about the flux function that should be updated?

**Comment by desa** [comment]
The specific issue is that

https://github.com/influxdata/flux/blob/b27c09481c15f361ab522684ee3f089323a1996e/stdlib/influxdata/influxdb/monitor/monitor.flux#L119

the `now` call here happens at different times, which result in the statuses in a check happening at different times.

**Comment by ebb-tide** [comment]
See https://github.com/influxdata/influxdb/issues/15224 for statuses written from the same check run.

**Comment by nathanielc** [comment]
The call to `now()` should be the time the check is run. From https://github.com/influxdata/influxdb/issues/15224 it looks like multiple calls to `now()` within the same task run are reporting different values which is incorrect. 

In other words I think the bug is not in the implementation of the `check` function rather in the implementation of `now()`. It should always return the same time for each call in a single run of the task.
