### ISSUE TITLE
Optimize grouping between transformations

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1913]
How the Flux engine works now: most transformations build groups and the triggering mechanism passes them to the next transformations.

However, most of these transformations do not deal with time and shouldn't wait for any trigger to send their result to the next transformation.

Suppose you have

```flux
from()
 |> range()
 |> filter()
 |> map()
 |> group()
 |> count()
```

This pipeline does not require any transformation to stop and wait for a specific group to be created and further processed. What really matters is that records for a group end up being process in the same go routine by `count`. Furthermore, note  that it is not necessary to preserve any order among records, because `count` is commutative.

Furthermore, note that this behavior impacts every transformation that imply grouping. Not only `group`, but, for example, `map` and schema mutators.

I propose to design a way to bypass the triggering mechanism and send records to the next transformation as @jsternberg did with `filter` (https://github.com/influxdata/flux/pull/1909) and to redirect records to the right transport/go routine for stateful operations (e.g. `count`).

_Draft proposal_: we could annotate records with their group key (its hash maybe?) so that, once they  need to be sent, they can be redirected to the right transport and, once they hit a stateful transformation, it can reconstruct the state properly and send it out as a final result.

This change will impact the memory consumption and the speed of many pipelines, including the one above.

**Comment by jsternberg** [comment]
It was the intention of that `filter` issue to set how this would be done for other transformations so I think the overall direction is good, although I will point out a few minor details that I think differ.

The intention of that filter issue was that we don't have to bypass the trigger mechanism and we do not want to because at some point we want to design out and use the triggers. But, we also would recognize that we don't have to have the trigger mechanism at every single dataset within the system. If you look at Kapacitor which already implements this kind of system, many of the nodes will just forward the message to the downstream edges and that works great. There was no particular reason that `filter` had to know how to retract a table other than to tell its downstream transformations that a table was retracted. While we haven't designed out how streaming will work, I feel reasonably certain that the above logic will still work when we do flesh out that design.

But, there are some transformations that would need to cache the data until it receives a specific trigger and I think of `group()` as one of those. That's relevant because it is included in the above example query. I think all of the other transformations are 1-to-1, but group isn't and it would need to cache data until it receives a trigger that sends the data downstream.

Fortunately, we can still create a pretty reasonable pipeline in most circumstances with this. Most group/aggregate operations can be optimized to perform the aggregation multiple times and this could be one of our planner rules. If you see `group() |> count()`, it can be rewritten to `count() |> group() |> sum()` with no issues. Similarly, you can do this with others like `max()` and `min()`.

**Comment by affo** [comment]
@jsternberg I see your point, but I don't think that `group` or grouping in general requires caching. Caching is required in stateful operations that require the whole group to be present.

`group` can be seen as assigning a record to a group, for example, tagging it with its group key hash. The transport (maybe that's not the correct word) has to make sure that every record is sent to the correct transformation downstream.

Once records are submitted correctly, the stateful operation can ensure that it `count`s (for  example) every record in some group key.

The case of triggering is of special interest once we run time-related transformations, otherwise it is less relevant. Yeah, that's true that  we could solve everything with triggers, but if you introduce a trigger that says "push downstream every 100 records" then you could split groups and we are basically dealing with the same problem I am discussing here.

It could be subjective, but I see triggers related to the time semantics, but we could use them for everything. It's up to us to decide if to mix system-specific aspects to "semantic" ones. Triggers indeed, should be specified by the user to obtain different results.

For the planner rules, I would personal avoid to write planner rules for something that can be optimized in general, we would end up writing a lot of planner rules for every possible case and  having queries that perform bad for no particular reason until a planner rule has been added to the system.

Just to wrap up, I think that we should not handle the entire flow of execution with triggers. Some transformation can work better without accounting for that mechanism (as you demonstrated in `filter`), instead, some others _need_ a trigger  o know when to materialize the result (e.g. `window`).
