### ISSUE TITLE
Improve contains

### ISSUE THREAD

**Issue by affo** [influxdata/flux#1914]
`contains` is slow because it performs a linear search.

In the case of dynamic queries, it is used with columns. It could be cool to offer users a functionality that turns an array into a set for speeding up `contains` invocations in lambdas.

The workaround is to use `distinct` before extracting the column for now.

**Comment by MzazM** [comment]
I noticed and reported on a community quesion that contains is extremely slow (30x slower). We use it for dynamic queries, in particular to search an element into an array. I dont get what you mean by "the workaround is to use distinct before extracting the column for now"

**Comment by LieLieLiekey** [comment]
+1, `contains` too slow.

**Comment by MzazM** [comment]
concern about performance also here #20931

**Comment by LieLieLiekey** [comment]
any progress?

**Comment by MarcoPignati** [comment]
rather than using contains() I am now using the approach suggested here: https://community.grafana.com/t/grafana-influxdb-flux-query-for-displaying-multi-select-variable-inputs/35536 
the filtering works perfectly and performance is not impacted. In my case the variable $device of the example is obtained via a another query.
