### ISSUE TITLE
saving tasks with dynamic query errors

### ISSUE THREAD

**Issue by aanthony1243** [influxdata/flux#1915]
it seems dependencies are not properly set up for running dynamic queries: 

![Screen Shot 2019-09-24 at 12.40.33 PM.png](https://images.zenhubusercontent.com/5d1398574586cb3fe198494a/54b167ae-2a83-485a-8046-53a903ca074b)

**Comment by affo** [comment]
https://github.com/influxdata/influxdb/blob/master/query/spec.go#L33

This should be

```go
ctx := influxdb.Dependencies{
		StorageDeps: influxdb.StorageDependencies{},
		FluxDeps:    newDeps(),
	}.Inject(context.Background())
```

We should understand what king of `influxdb.StorageDependencies{}`  we need  in that case.

If we decide for a "dry run" that shouldn't matter.

**Comment by nathanielc** [comment]
@aanthony1243 This is likely a difficult issue to resolve. Currently task uses the interpreter to execute a Flux script and get the value of the _task_ option. This has worked so far since that execution pass ignored the side effects produced and did not call down into the execute package to perform any real queries. With dynamic queries this is no longer a safe assumption. Flux likely needs to provide a more specific way of evaluating options independent of the rest of the script. 

To make progress on this issue we will need to understand the exact ways tasks relies on partially executing Flux scripts so we can determine the correct API to expose.

**Comment by affo** [comment]
@nathanielc I think we agreed with the task team that pre-authorization for tasks is not necessary anymore.

This function: https://github.com/influxdata/influxdb/blob/2a6cfe3c78f49100d3c17d266107b7efa99f1067/query/spec.go#L32

Seem to have no invocation in the codebase anymore.

I guess that, at the moment those tasks should run. Is it correct @aanthony1243 

If so, we should close the issue and open another if we want to re-enable preauth.

**Comment by nathanielc** [comment]
@affo Makes sense, can you create an issue to remove that dead code?

**Comment by affo** [comment]
Yep: https://github.com/influxdata/influxdb/issues/15389
