### ISSUE TITLE
Spike: Rust to Go memory management

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1941]
We need to understand the mechanics of passing memory from Rust to Go. 

How does garbage collection work with memory received from Rust?
How does the Rust borrow checker work with memory passed to Go?

How do parsing times compare between a pure Go and a Rust backed Go version?

What methods are there for passing rich data structures between Rust and Go?
* Pass serialized bytes to Go and have Go de-serialize (using JSON or some kind of zero-copy serialization)
* Pass pointers to C represented structures that both Rust and Go can interact with directly

**Comment by jsternberg** [comment]
> How does garbage collection work with memory received from Rust?
> How does the Rust borrow checker work with memory passed to Go?

This will work the same as C/C++ would as evidenced here: https://stackoverflow.com/a/42525561

Basically, we use an unsafe block to release the allocated pointer and pass it back as a reference to Go. The Go version would keep the reference. We will need to expose a proper C API where we have an allocation and a free and we will likely need to use [runtime.SetFinalizer](https://godoc.org/runtime#SetFinalizer) in order to free the memory when the garbage collector would reap the object.

> What methods are there for passing rich data structures between Rust and Go?

Flatbuffers implementations exist in both Rust and Go so that would likely be our best option if we could. There is also protobuf. We should document where we believe we will need the two to interact. A difficult part of this is that if we decided we need the type checker to be in Rust, then we will need to perform the parsing, pass it back to Go, then reserialize when we need to perform the semantic checks. So flatbuffers is probably our best bet in terms of binary interop. Arrow uses flatbuffers internally (I think) so it matches with our general usage of flatbuffers.

**Comment by jlapacik** [comment]
Correct me if I'm wrong but both parsing and semantic analysis should happen within Rust. Serialization should only need to happen once after the semantic phase, at which point Go will deserialize the types and evaluate the program.

**Comment by nathanielc** [comment]
@jlapacik That is my expectation as well.

**Comment by jsternberg** [comment]
We modify the AST within Go code so we would need to have a way to manipulate AST in Go.

**Comment by jsternberg** [comment]
Also we construct AST in Go code to pass it to semantic analysis directly so we would need it for that reason too.

**Comment by nathanielc** [comment]
>Also we construct AST in Go code to pass it to semantic analysis directly so we would need it for that reason too.

The semantic analysis code is the type inference code. Once that is all in Rust the API there will be pure Rust. 

> We modify the AST within Go code so we would need to have a way to manipulate AST in Go.

You are correct that the AST is used in various places and I expect the Rust parser to expose the AST to Go directly in addition to the semantic graph. 

Eventually we may discover that we do not use the AST anywhere in Go but that is not an immediate goal.

**Comment by jsternberg** [comment]
> The semantic analysis code is the type inference code. Once that is all in Rust the API there will be pure Rust.

I don't mean the parser. The transpilers also construct AST. We need to be able to build the AST from Go unless we also plan to have the transpilers in Rust.

**Comment by nathanielc** [comment]
The AST is part of the public API for Flux, as such its fine if both Rust and Go have representations of the AST. In fact we expect javascript and other languages to also interact minimally with the Flux AST.

**Comment by jsternberg** [comment]
Yes, that was my expectation. I was responding to above where we said that the AST would not need to be serialized into other languages because the parser and the type inference would both be in Rust so there would be no requirement to serialize the AST but only the semantic nodes.

**Comment by wolffcm** [comment]
Here's what I've found. I wrote a small benchmark program that parses in Go and in Rust called from Go: https://github.com/influxdata/flux/pull/1967

Here's some timings for the time it takes to parse one of the Flux scripts from our repo, invoked like this:
```
rm -f gorust && cd internal/rust/parser && cargo build --release && cd - && go build ./internal/cmd/gorust && ./gorust parse ./stdlib/testing/testdata/drop_newname_before_test.flux
```

Task | Duration
------------------ | -------------
rust-do-nothing | 0.004216ms
rust-parse-return-handle | 0.59489ms
rust-parse-return-json | 0.685535ms
rust-parse-and-deserialize | 3.189690ms
go-parse | 0.121347ms

This performed 1000 parses using each method described above, and took the average.

`rust-do-nothing` did not do any parsing, it just measures the overhead to call a Rust function with the cgo mechanism.

`rust-parse-return-handle` parses a script and returns to Go a pointer to the `File` object .  The handle is freed by calling back into Rust and re-boxing it.

`rust-parse-return-json` parses a script and then serializes it to JSON, returning a `char*`, which is later freed by calling back into Rust.

`rust-parse-and-deserialized` is like the above, but also deserializes the JSON in Go to produce an `ast.Package`.

`go-parse` is the standard way of parsing in Go by calling `parser.ParseSource()`.

Some takeaways from this:
- Overhead of calling cgo is only a few microseconds
- Parsing in Rust seems pretty slow, about 5x slower than Go.  Maybe something about our Rust parser is hard for rustc to optimize?
- Deserializing to Go's `ast` structs is expensive.

I see two courses of action here:
- Profile our Rust parser and see why it's taking so long
- Explore the possibility of using flatbuffers to avoid needing to deserialize JSON in Go.

**Comment by wolffcm** [comment]
To address some of the questions from the issue description:
> How does garbage collection work with memory received from Rust?

Go will not garbage collect pointers received from a cgo function call.  For strings, one can use `C.GoString` to convert (copy) to a managed Go string.

> How does the Rust borrow checker work with memory passed to Go?

For strings, Rust provides a `std::ffi:CStr` type that represents a C-style string that is borrowed, and will not be freed by Rust.  It can be converted to the `&str` type needed by the Rust parser:
https://github.com/influxdata/flux/blob/a0cf91caf16d7fe37a089492e3098784d0c76533/internal/rust/parser/src/lib.rs#L25

For more general data types, one can box/unbox to control how Rust will release memory.  There is an example of this here:
https://github.com/influxdata/flux/blob/a0cf91caf16d7fe37a089492e3098784d0c76533/internal/rust/parser/src/lib.rs#L44-L61

> How do parsing times compare between a pure Go and a Rust backed Go version?

As noted above, Rust parsing is a lot slower, but this does not seem to be due to the overhead of cgo.

> What methods are there for passing rich data structures between Rust and Go?

I just used a naive method of passing JSON strings between Go.  Flatbuffers may be worth exploring.

**Comment by nathanielc** [comment]
>As noted above, Rust parsing is a lot slower, but this does not seem to be due to the overhead of cgo.

On the topic of the Rust parser being slow, if I remember right we do a lot of copy/cloning in Rust to avoid issues the borrow checker. In other words in our literal port of the Go code we didn't revisit Rust memory borrowing paradigms, rather we just made Rust copy the value anytime it was ambiguous. This is my initial guess as to why the Rust one is slower. 


It looks like JSON deserialization is the dominate factor. I suggest we try to optimize this portion before trying to optimize the Rust parser bits.

**Comment by wolffcm** [comment]
@nathanielc Okay, this makes sense.  If we need to serialize AST to Go, then FlatBuffers seems to be the best:
- JSON is slow to deserialize in Go
- protocol buffers don't seem to be able to handle polymorphic and hierarchical data structures... proto3 has a `OneOf` type that is still experimental.
- FlatBuffers has a `union` type that will allow us to represent different kinds of statements and expression trees, and boasts of its good performance.

Using FlatBuffers we could return a pointer to memory allocated in Rust, and convert to a Go `[]byte` using `unsafe.Pointer` and `reflect.SliceHeader`.  Thus we could truly have zero-copy communication between the two environments.

But it seems like our plans are to convert to the AST to a semantic graph before returning to Go, which is this issue: https://github.com/influxdata/flux/issues/1961

Details of how we end up actually passing memory will be dependent on our design moving forward, but I don't see any unsurmountable problems here.

**Comment by wolffcm** [comment]
Here is a POC that passes flatbuffers between Go and Rust:
https://github.com/wolffcm/flatbuffers-example

It uses a simple flatbuffers schema that represent an expression tree.  I chose that format to ensure that we could represent arbitrarily nested data structures, and polymorphism, which flatbuffers implements with unions.

If we move forward with this strategy for serialization between Rust and Go, perhaps this can serve as a guide.
