### ISSUE TITLE
Spike: Rust + Go build chain questions

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1942]
Will Flux remain `go gettable` if we use Rust? 

What changes will need to be made to influxdb and idpe in-order to use Flux once it depends on Rust?

Can we still build static binaries?

**Comment by jsternberg** [comment]
This is possible, but only with some incredibly specific caveats.

The first problem is that the cgo toolchain does not support compiling Rust programs and the only way to produce a suitable static library is if you invoke the Rust compiler. I don't know if the Go team would accept it and I think they wouldn't, but it may be possible to change Go to invoke the Rust compiler. But, to do this, you would be unlikely to use Cargo. So we are likely limited to compiling it ourselves.

It is not possible to use the LLVM IR output. It does not contain the necessary libraries for it to link properly after it is fed into the clang compiler. This would also require that clang is the only compiler that we could use for building Flux which may not work for Linux OS's.

It is possible to compile a static library for each platform we plan to support and commit those to source control. If we do, then Go will download them as it would any other repository and it would follow the link instructions. I didn't try this out with a committed module, but I faked a module and used `replace` and it worked just fine. The only caveat is that `lto` _must_ be disabled. If it is enabled, then the Rust compiler removes symbols that are necessary for later linking. Rust works fine without them because it gets those symbols when producing the final binary, but Go can't emit the correct link command because of the hash that is contained in the Rust libraries.

I can create a sample module and show its usage. I can possibly do this with the Rust parser we have already built.

**Comment by jsternberg** [comment]
Proof of concept:

* https://github.com/influxdata/flux/blob/chore/rust-parser-poc/internal/cmd/compile/main.go
* https://github.com/jsternberg/flux-lang

If you compile that, on the latest Mac OS X, it will compile and output the AST. I did not implement returning back an AST as a string mostly because that's part of the other issue related to memory management. At least it worked on my machine and it may be all that I can guarantee.

Here are a few caveats though.

1. The binaries must be uploaded for this to work and the advice on how to lower the size that is specified in the `Cargo.toml` will not work. `lto=true` must not be set or it strips out important symbols that are needed for it to function.
2. It will likely be needed to separate this out into a separate module so that the work is kept separate. Especially since, because we will need to commit a suite of binaries, the repository's tags will more likely function as a set of orphan commits for the already built binaries. This is the equivalent of using a binary only package with all the caveats that brings.
3. It is possible to use module replace directives to build the parser locally to test it within the main flux repository.

The good news with this method though is that the size will be smaller and won't effect development as much as committing the binaries to the primary repository would be. This is because it will only download the specific revision and you can reclaim disk space after upgrades by just cleaning the module cache. While this will incur a heavier load than source code and we'll have to look at the binaries, it should probably be fine. But, I have also only built the binary for one platform. I do not know the effect it would have beyond that.

The bad news is that we do use vendoring in some parts and vendoring would mean that we're committing binaries into the project that is doing the vendoring. This is unlikely to be ok in my opinion for the general maintenance of the version control system.

I'll be doing some research to see what steps would be needed to make this work without committing a suite of binaries.

**Comment by jsternberg** [comment]
Oh and here's an `otool -L` of the resulting binary:

```
./compile:
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

I think this means that it only relies on the standard system library which indicates to me that it is fully statically linked. I am under the impression that this will be included in every binary produced on Mac OS X if `cgo` is used or enabled in anyway. I believe it is expected that the binary will not be portable to other systems since we cannot build with `CGO_ENABLED=0`. This will be true regardless of which language we interoperated with.

**Comment by nathanielc** [comment]
@jsternberg Thanks! What does it look like if we do not commit the binaries? Meaning can we use `go generate` or something similar to build the static lib resource?

**Comment by jsternberg** [comment]
It's unlikely to work, but I haven't tried it. The main reason is that modules are in read only directories and we would be unable to write the output to them so we would need somewhere else to put it. This method of embedding the library with the source that uses it only works if they are in the same location because otherwise we would have to figure out the proper directory for the `-L` argument (which would need to be an absolute instead of relative path) and somehow pass it as part of the build with a `#cgo` directive.

**Comment by nathanielc** [comment]
OK, I'd like to explore if that is possible. At the very least it would be possible using a Makefile out of band of the Go build steps.

**Comment by jsternberg** [comment]
The cgo documentation indicates it is possible to set ldflags from an environment variable so it would be possible to generate the binary to a temporary location and then pass that as part of an environment variable to the go binary.

The documentation also says not to use this.

> When building, the CGO_CFLAGS, CGO_CPPFLAGS, CGO_CXXFLAGS, CGO_FFLAGS and CGO_LDFLAGS environment variables are added to the flags derived from these directives. Package-specific flags should be set using the directives, not the environment variables, so that builds work in unmodified environments. Flags obtained from environment variables are not subject to the security limitations described above.

https://golang.org/cmd/cgo/

We would have to build additional tooling around building the project if we want to maintain any kind of cache for builds since the module directory cannot be written to.

**Comment by nathanielc** [comment]
Looking at the docs I see this:

```
// #cgo LDFLAGS: -L${SRCDIR}/libs -lfoo
```

That looks like what we want. My thinking is that as far as Go is concerned the static lib exists in the source path already and it just links against it. Go does not manage building that static lib itself we would leverage Cargo for that. We can link up the two build steps using either `go generate` phase or a simple Makefile.

**Comment by jsternberg** [comment]
Is the source directory the directory of the module being compiled, the directory that go build was run from, or, preferably, the module root? If it's the first one, then it probably won't work because of what I mentioned above.

**Comment by nathanielc** [comment]
From the docs:

> When the cgo directives are parsed, any occurrence of the string ${SRCDIR} will be replaced by the absolute path to the directory containing the source file. This allows pre-compiled static libraries to be included in the package directory and linked properly.

**Comment by jsternberg** [comment]
That indicates to me that it's the first of the options I listed which means the pre-compiled static library would need to be included as part of the module itself rather than compiled as a separate build step. If the binary was placed somewhere else, we would need to inject that path as part of the build process.

I think the effect would end up being the same. We learned recently how to trigger release builds. If we had the parser/type inference as a separate module and we had a model where we tagged it `src/vX.Y.Z` we could trigger a build process across multiple architectures and then finish it by creating an orphaned commit, tagging it with `vX.Y.Z`, and we integrate fully with the Go build toolchain.

**Comment by nathanielc** [comment]
@jsternberg I am thinking something along this lines of this https://github.com/influxdata/flux/pull/1944

It shows how you can build the Rust static lib from a `go generate` command and then link against it statically using LDFLAGS in combination with SRCDIR. This avoids using multiple repos and modules and committing binary files.

**Comment by jsternberg** [comment]
That's what I was saying is very unlikely to work. It won't be able to be depended on by other repositories so nobody will be able to include Flux as a module. So I think you would end up making the build process more complicated without any of the benefit.

The reason why I would favor the separate repository as a module approach is also because then the repository can become a place where we include the base client library for parsing the language and allow it to be usable to others as a C API. We define a header file and then implement it using Rust. I'm thinking a structure similar to the Apache Arrow project, but we would make special accommodations to make the Go version usable by modules similar to how you would make special accommodations for any other language.

* A base directory with the Rust source code. Likely a single crate to simplify dependency resolution. It's unlikely we would need separate crates specific to scanning and parsing.
* A `go` directory with the source files for interfacing with the FFI.
* Any other directory we want such as an `include` directory for the external C interface (which the Go version would use) and probably a `js` directory for maintaining the Javascript module that we can upload to NPM.

With this directory structure, you could then tag it with a standard `vX.Y.Z` and initiate a build process that would create an orphaned commit and tag it with `go/vX.Y.Z` which would allow Go to find the module in a subdirectory. Further, we would be able to use the repository for anything we want to be cross-language.

Also leaving a note to myself for something to investigate. Arrow works when cgo is disabled and I just realized how weird that was because I know it uses assembly and I figured that the compiler was still invoked to put those together. The main reason we need cgo is to tell Go about the C interface, but we don't need C for that. This is likely further down the road, but it may be possible to use goasm as the go-between on the two languages: https://golang.org/doc/asm

I think this is likely further down the line as cgo is convenient for parsing a C header into the equivalent GoAsm that would be needed above and it could easily be an incremental upgrade. Also note that GoAsm is _not_ ASM and it is not architecture dependent. It may be worth visiting this sooner though as the main reason why I think different binaries would be needed between Mac OS X and Linux is the system library that's linked. But, I think I was wrong earlier as static libraries have no information about dependent shared libraries so I'm curious if Rust requires the system library. If it doesn't, then we could likely compile it once on any AMD64 machine and be fine on all operating systems. I need to test if I can take a static library from Mac OS X and then compile it on Linux within a Docker Container. If I can, then we would likely only have to compile two binaries for the two architectures we care about at the moment: amd64 and whichever of the arm architectures is most compatible. Alternatively, we can deploy arm in a separate way that doesn't require us to commit the binaries. If a person is building on arm, we can ask them to ensure that the flux shared library is installed on the system and only commit the amd64 binary.

Just leaving myself some notes. I think that our total number of committed binaries should be one and it would be fairly easy to ensure that it was isolated into a repository that had a purpose beyond "need it for go modules".

**Comment by jsternberg** [comment]
If I attempt to use the same static library on Linux through Docker I get this linker error.

```
# github.com/jsternberg/flux-lang/parser
/go/pkg/mod/github.com/jsternberg/flux-lang@v0.1.0/parser/target/release/libflux_parser.a: error adding symbols: Archive has no index; run ranlib to add one
collect2: error: ld returned 1 exit status
```

Going to try to figure out what that means. I'm guessing the object files aren't of the correct format. I think Mac OS X doesn't use the ELF format which may stop us from sharing the two with each other.

**Comment by jsternberg** [comment]
Confirming that we can't share these. The object files that are compiled are apparently a format called Mach-O and Linux uses ELF. https://stackoverflow.com/a/51624888

There's documentation for the target triples here: https://clang.llvm.org/docs/CrossCompilation.html#target-triple

It looks like it would be pretty simple for us to build for `x86_64` for all of the target triples pretty easily and then link to the appropriate one with conditional compilation. I'll give that a try.

I think the remaining questions that I have currently are:

1. If a single crate is used instead of multiple crates, can LTO be re-enabled to make the static library smaller? The only symbol I remember seeing missing was `scan` which I found really weird why it was the only one being excluded. If LTO can be enabled again, then the resulting binaries will also be smaller. There's a certain limit to how many compiled binaries we can include in a module, but I don't think this number is particularly high at the current moment. I would probably recommend that we only do this for `x86_64` and only for the three systems (`darwin`, `linux`, and `win32`).
2. I want to know if I can avoid using cgo by using the GoASM language.

**Comment by jsternberg** [comment]
I think we would be able to turn LTO on, but only if we're constructing a single static library. If I compile the scanner with lto enabled as-is, the symbol is present. If I compile the parser with lto enabled, it gets removed possibly because it is flagged as not used in some way?

Either way, it's likely not the most significant section. And while I am kind of curious why it's not present, it would be feasible to include it separately as part of cgo. I tested out that second one and if I just copy over the generated `scanner.c` to the Go folder and link the LTO library from Rust, I get a working executable and the static library is only 1.5 MB instead of 6.4 MB.

**Comment by jsternberg** [comment]
It also needs to be noted that the files are compressed with zip. I just tried downloading the `v0.1.0.zip` example (without lto) and the zip file was 2.0 MB for the total content while the actual library was 6.4 MB. I pushed up a new version with LTO enabled for Mac OS X specifically and the zip file was 633 KB. This is still more than text files would be, but the size isn't too bad for what would be considered a binary distribution for a limited number of platforms.

**Comment by jsternberg** [comment]
I wrote up the current conclusions here: https://gist.github.com/jsternberg/3adac9a7b3386d7eb53846e47955604b

**Comment by jsternberg** [comment]
I'm going to close this. I think the research has been done and summarized. If there are any lingering questions @nathanielc, please reopen this so I can go into it or I can provide an answer and ensure that it is in the summary above.

**Comment by jsternberg** [comment]
I just kind of, erroneously, assumed that go generate would work. It does not.

```
jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) go generate github.com/jsternberg/flux-lang/parser
go: not generating in packages in dependency modules
```

So we can't use go generate for this. I am going to attempt to see if I can do this with an executable, but this gets harder. The build information doesn't tell us where the files are in the cache. I might be able to get the information though and make something work.

**Comment by jsternberg** [comment]
You can run binaries that are located in `internal`. I like this mostly because it signals that this is a dev tool and not part of the main distribution. But, the command for generating should possibly be somewhere else. Maybe a `buildcmd` package.

We'll pontificate on that later.

**Comment by jsternberg** [comment]
Version 0.3.2 of the sample library I have removes the precompiled static library and attempts to use a build command to build it within the module when it's a dependency. Fails for the reason I thought it would above:

```
jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) go build
# github.com/jsternberg/flux-lang/parser
ld: warning: directory not found for option '-L/Users/jsternberg/go/pkg/mod/github.com/jsternberg/flux-lang@v0.3.2/parser/target/release'
ld: library not found for -lflux_parser
clang: error: linker command failed with exit code 1 (use -v to see invocation)
jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) go run github.com/jsternberg/flux-lang/internal/cmd/build
error: failed to open: /Users/jsternberg/go/pkg/mod/github.com/jsternberg/flux-lang@v0.3.2/parser/target/release/.cargo-lock

Caused by:
  Permission denied (os error 13)
panic: exit status 101

goroutine 1 [running]:
main.main()
        /Users/jsternberg/go/pkg/mod/github.com/jsternberg/flux-lang@v0.3.2/internal/cmd/build/main.go:96 +0x186
exit status 2
```

(The panics are because my build script just panics when it encounters an error and has nothing to do with the error)

**Comment by jsternberg** [comment]
Version 0.3.4 contains a prototype for making building work when included as a module. The script will find the location where the source code is contained, make the necessary parts of the directory writeable, build using cargo, then reset everything back to how it was.

For a final version, we should ensure that it does this additional behavior:

1. Checks to see if the static library already exists and skip any compilation. The module is finalized at that point and has no chance of being different so there is no need to have incremental builds since the sources cannot change.
2. Clean up everything about building after the build is performed.

```
jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) go get github.com/jsternberg/flux-lang@v0.3.4
go: finding github.com/jsternberg/flux-lang v0.3.4
go: downloading github.com/jsternberg/flux-lang v0.3.4
go: extracting github.com/jsternberg/flux-lang v0.3.4                                                                                                          jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) go run github.com/jsternberg/flux-lang/internal/cmd/build
(bunch of build output)
    Finished release [optimized] target(s) in 1m 10s
jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) go build
jsternberg:[~/g/s/g/i/f/i/c/compile] $ (chore/rust-parser-poc *$=) ./compile ../../../stdlib/testing/testdata/map_test.flux
(ast output)
```

I have not seen an error message yet about `go.sum` getting messed up. I am not sure if it will happen and it is quite possible that the `go.sum` is based on the zip file that was downloaded and not the sources that are present on disk. I attempted by updating to the dependency, saving `go.sum`, running the cargo build, then running `go build` and `go mod tidy`, and checking to see if `go.sum` changed. The hash for v0.3.4 did not change so apparently you can add files to the module cache? I'm wondering if the `go.sum` would change if I added a `*.go` file, but I'm not so that's not really a problem. I am wondering about this from a security perspective. It seems like a **major** attack vector to inject code into the product without having any awareness. I am frankly surprised that this is even possible.

**Comment by nathanielc** [comment]
I think I am missing an important piece, how does the `internal/cmd/build` command get run? Is that a feature of Go modules or something? 

On version 0.3.4 I agree its a major attack vector as well as a hack that will likely be fragile to future changes to the Go build chain.

On version 0.3.2 this was also expected. My assumption was that downstream projects would have to build `libflux` from source and place it in `LD_LIBRARY_PATH` before running the `go build` process.

**Comment by jsternberg** [comment]
So about the attack vector, it appears that this attack vector exists in general and it also applies to Go code. I think that by itself mitigates the attack vector although we may want to open up an issue with the Go toolchain for why it doesn't validate the files after they have been unpacked. Basically, if you modify a Go file that has been extracted in the module cache, you can modify whatever code you want and `go build` won't tell you.

If Go code and the static library have the same behavior, then I'm not sure this is the problem I had stated it to be. You would still need to compromise the build machine and, if that happened, the attacker would still be able to inject whatever code they wanted without the build toolchain informing us.

A project that depends on another project can use `go run` to run any main module in another package. That just allows us to pass on a more complicated build script since it isn't as simple as running `cargo build --release`. Basically, we need to find the source directory for the package, we need to make the directories writeable, and we need to then run the build command.

`LD_LIBRARY_PATH` is only for loading dynamic libraries so I'm assuming you mean the `-L` option or `CGO_LDFLAGS` environment variable? If we were to do that, it is easier for us to have a common location where we build it and just use multiple `-L` invocations to search for the library and, if it isn't in one of these spots, then the builder can provide the `CGO_LDFLAGS`. But I would like it if our build toolchain didn't require work on the developer for how to build. It should be seamless to them or at the least easily possible to say "just run this one command exactly once when you use a new version and you are fine".

**Comment by jsternberg** [comment]
Additional complication is that, if you recompile the static library, since Go is not aware of the file, it will not recompile the Go version and it will not relink the Go static library. This adds additional complications to the Go build that may be a bit too much, but this is just an initial impression.

This can be reproduced by using `go mod edit -replace github.com/jsternberg/flux-lang=../flux-lang` (or to whichever directory you have that checked out). Afterwards, compile the library using `cargo build --release`. Go to `flux` on the branch from above and go to `internal/cmd/compile`. Run:

```bash
$ go clean -cache
$ go build
```

If you run the binary, it works fine. But, if you make a modification to the Rust library and run `cargo build --release` and then run:

```bash
$ go build
```

You will notice that any `println` that was added to the library does not get printed because no recompilation happened.

But, weirdly enough, if I delete the `compile` binary by itself, a recompilation somehow happens. My guess is that Go saves the link information needed from each static library because static libraries do not contain that information and then it reproduces the proper link command.

But, it does mean that the normal workflow of expecting the go toolchain to pick up that the binary needs to be recompiled will not work and any build will _need_ to remove the old binary to ensure a correct build or call `go clean`.

**Comment by jsternberg** [comment]
`go mod verify` complains if you modify the source in the module cache in anyway which includes additional files. That means we're going to have to find somewhere else to store the binary. This likely means we'll have to store it in `/usr/local` or a user build directory somewhere for source builds.

The main reason we need to know the location of the build directory is because we want to make it reproducible without relying on environment variables and unless we choose an absolute directory or a directory relative to the module, we will have to inject the directory for the library into the build toolchain by using an environment variable.

**Comment by jsternberg** [comment]
Final note: Even after consolidating all of the libraries into a single library, the scan method still gets taken out of the final static library when lto is used. I thought it wouldn't because of an initial test regarding it, but it does get removed. We can work around this by either only enabling lto for wasm builds in some way. I'm not really sure how to do this because it seems like custom profiles aren't current supported, but it's possible to work around on it.

It is also possible to just generate the C file in the Go package and then copy it as part of the build process or vice-versa. It is generated code so it largely doesn't matter.

**Comment by jsternberg** [comment]
Closing this as there are no pending questions.
