### ISSUE TITLE
Instantiate Flux types from AST for type expressions

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#1973]
#1952 will define an AST for type expressions. There should be a 1-1 mapping from the nodes of this AST to the type structures defined in #1951. We will need a function to perform this translation so that we can generate a type structure from a textual type expression.

Note this function will only be used in test cases. As such it should be defined inside of the main test module.

**Comment by nathanielc** [comment]
Note concretely we mean converting the AST for this expression:

```
forall [t0] where to is Addable (a:t0) -> t0
```

to the Flux types defined in `libflux/src/semantic/type.rs`.

**Comment by fchikwekwe** [comment]
What additional work is this issue asking for beyond outputting an AST representation of PolyTypes as defined in `libflux/src/semantic/type.rs`? I believe that I may have already resolved much of this issue with #1952.

**Comment by fchikwekwe** [comment]
PR #2066 will resolve this issue for now once closed. Instead of creating a separate AST and then parsing type expressions into semantic types, I parsed them directly into semantic types. Due to this, there will have to be more work in the future to create a separate AST and then add type expressions into the Flux grammar.

**Comment by fchikwekwe** [comment]
PR #2066 is now merged.
