### ISSUE TITLE
Should we use single quotes in the type expression grammar?

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#1993]
See #1952 for details on the grammar. 

The grammar specifies that type variables are written as a single quote followed by an identifier. For example `'a` and `'foo` etc.

The types in #1986 use the form `t0` and `t1` etc. Using both forms is likely confusing as end users will think they are different since one is missing the single quote. Should we just drop the single quote and use normal identifiers? Do type variables and _normal_ variables ever appear in the same context? If not then there is no real need to mark them as different using a single quote. If they do then maybe there is a better syntax.

**Comment by jlapacik** [comment]
Note I adopted the single quote syntax for type variables from OCaml. End users will only be exposed to type variables through error messages. Subsequently they should only see type variables of the form `t0, t1, ...`. In my opinion we should not modify these type variables in any way before they are displayed. Therefore I think it makes sense that we use this latter syntax in the type expression grammar instead of the OCaml syntax.

**Comment by nathanielc** [comment]
Works for me, I think the non-single quote version will be less confusing to new users anyways and since it will be consistent in using `t#` it will be clear they are type variables and not normal variables.

Decision:

Use `t#` format for type variables in type expressions. I'll update the issue in #1952
