### ISSUE TITLE
AppendMappedRecordWithNulls: colMap must have an entry for each table builder column

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#2002]
This seems to be related to trying to drop the "result" column. It also seems to be related to the specific data being queried because it works for some timeranges and not for others.

I have attached the query and the data to investigate.

`AppendMappedRecordWithNulls: colMap must have an entry for each table builder column`

```
import "influxdata/influxdb/v1"
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "website_check")
  |> v1.fieldsAsCols()
  |> drop(columns: ["_start", "_stop","result","_measurement","host","result_type","result_code"])
```

and this is a csv of the response just before the `drop` function:
[2019-10-15-13-52_chronograf_data.csv.zip](https://github.com/influxdata/flux/files/3731401/2019-10-15-13-52_chronograf_data.csv.zip)

**Comment by wolffcm** [comment]
This does not seem to be a regression, it easily reproduces as far back as v0.40.0.

**Comment by wolffcm** [comment]
@russorat Thanks for the excellent reproducible for this!  Having the data that is being fed to the problematic function made this super easy.

The issue here is that there are two tables that end up having the same group key when the columns are dropped.  The first and sixth tables ends up having a group key of `(method=GET,server=https://cloud2.influxdata.com/signup)`.  However they have different sets of columns, so `drop` cannot combine them into one table.

I'll update `drop` to return an error for this situation.

It seems like the best solution for this particular issue would be to not drop the `result` column.

**Comment by wolffcm** [comment]
Note that this bug is specific to `drop` and `keep`, when they merge tables as a result of removing a column in the group key. This could produce a wrong answer if the number of columns and data types of merged tables happened to be compatible, but had different column names.
