### ISSUE TITLE
Translate AST FlatBuffers representation to natural AST nodes in Go

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2005]
DOD:
Tests exist that show each kind of AST node in the FlatBuffers representation maps to a proper "natural" ast node in Go.

**Comment by nathanielc** [comment]
@wolffcm Should this one wait till we have flatbuffers for the new semantic types? 

My thinking is that we won't have the natural Go semantic node types, rather we will just use the flatbuffer versions. 

The process would be

JSON -> Rust AST -> Rust Semantic -> Flatbuffer Semantic 

Then the Go side just uses Flatbuffer Semantic types. In other words I expect that we won't have a use for the current Go semantic types once we have flatbuffer semantic types.

Does this sound right?

**Comment by wolffcm** [comment]
Certainly the flow you describe sounds good as the final outcome.

I guess it comes down to sequencing.  Right now we still need to do type inference in Go, and I don't think we want to rewrite Go type inference to use the flatbuffers---it seems like a fair amount of work that would only need to be discarded.

If Rust type inference lands soon, then I agree, then the flow you describe makes sense.  But if we want an intermediate stage (where we use flatbuffers to communicate between Rust and Go before type inference lands) then maybe this makes sense:

JSON -> Rust AST -> FlatBuffers AST -> Go "natural" semantic nodes -> Go type inference

Or is there another flow that would be better?  I think @affo translation from Rust AST to Rust semantic might be done soon?

**Comment by nathanielc** [comment]
Interesting here are my thoughts, I don't have an opinion yet.

What about this flow?

JSON -> Rust AST -> FlatBuffers AST -> Go "natural" AST -> Go "natural" semantic nodes -> Go Type inference

The `FlatBuffers AST -> Go "natural" AST ` translation will be useful long term as its likely the Go  "natural" AST types will remain useful for marshaling JSON etc.

Obviously this will be slow and negates the value of using FlatBuffers for the AST as we would have to copy them into "natural" Go types. The advantage of this method is it is less wasted effort and  more straightforward translation because the _analysis_ step remains independent of the translation.

On the other hand using ` FlatBuffers AST -> Go "natural" semantic nodes` we get the value of using the flatbuffer AST types and we get early feedback on how well they work. Its more performant and doesn't block on the Rust type implementation. The disadvantage is that we have to duplicate the _analysis_ code and we could introduce some odd bugs. We could leverage the existing test cases thought to ensure that we have correctly implemented the analysis bits. Using the existing test cases means we need to build a `Go AST -> FlatBuffer AST` translation.

I am not sure which works best, its probably fine to do either but both seems wasteful. So lets just pick one and do it. Thoughts?

**Comment by affo** [comment]
@wolffcm yeah, I should complete it soon.

Would `FlatBuffers AST -> Go "natural" semantic nodes` mean that we should write the Rust bits depending on the FlatBuffer serialization of the AST, or we make semantic analysis in Go work with fbs? I think I am not following.

To me, the more natural seems `JSON -> Rust AST -> FlatBuffers AST -> Go "natural" AST -> Go "natural" semantic nodes -> Go Type inference`.
It seems better to spend effort in a simple translation instead of rewriting semantic analysis. Given that, in both cases, we will probably throw it away after the transition phase.

Moreover, our "final" implementation will require `fbs semantic -> go semantic` to run the interpreter. That could be achieved via copy/paste + edits of the `fbs ast -> go ast`. So that shouldn't be completely thrown away.

A side note: @nathanielc I don't see the value in the future for `FlatBuffers AST -> Go "natural" AST`:

> as its likely the Go "natural" AST types will remain useful for marshaling JSON etc.

That part should be already covered by Rust.

**Comment by wolffcm** [comment]
@affo @nathanielc 

Lorenzo Asked:
> Would FlatBuffers AST -> Go "natural" semantic nodes mean that we should write the Rust bits depending on the FlatBuffer serialization of the AST, or we make semantic analysis in Go work with fbs? I think I am not following.

I was thinking that Rust would parse and return flatbuffers AST to Go, and then Go would translate from the flatbuffers representation directly to `semantic.Node`.  

However, I had forgotten that we currently do the translation from Go natural AST to Go natural semantic graph together with a bunch of static analysis. (That happens here: https://github.com/influxdata/flux/blob/master/semantic/analyze.go#L14)

Given this, I like the alternative Flow that Nathaniel described:
`JSON -> Rust AST -> FlatBuffers AST -> Go "natural" AST -> Go "natural" semantic nodes -> Go Type inference`

My only concern is that it will be too slow, but I don't have a sense of how slow it will be.

**Comment by wolffcm** [comment]
I've updated the issue description to use the alternative flow going from FlatBuffers AST to Go "natural" AST.
