### ISSUE TITLE
Internal Error: Caused by bad TLS handshake

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#2075]
The TLS error should be surfaced to the user.

```
2019/10/28 13:43:20 http: TLS handshake error from [::1]:60342: remote error: tls: bad certificate
```

```
import "experimental/prometheus"

prometheus.scrape(url: "https://localhost:9999/metrics")
	|> map(fn: (r) =>
		({r with scrape_interval: string(v: 5)}))
```

**Comment by docmerlin** [comment]
This because we aren't properly bubbling up errors that occur during result iterator exhaustion.

https://github.com/influxdata/influxdb/blob/fc7bb9fcaf48f5e481a18752a36b0b1b1b0669b4/task/backend/executor/executor.go#L179

https://github.com/influxdata/influxdb/blob/552168d3aefd142d64299e45642210bebac9c146/task/backend/executor/task_executor.go#L391

**Comment by docmerlin** [comment]
I think this may be a bug in Tasks.

**Comment by jsternberg** [comment]
We also likely need to recognize the error and categorize it. It will be marked as an internal error since it is "unknown".
