### ISSUE TITLE
Missing build info on FLux 0.50.2 inside of InfluxDB 1.7.9

### ISSUE THREAD

**Issue by youcann** [influxdata/flux#2103]
I'm running influxdb 1.7.9:
```
> import "runtime"
> runtime.version()
Error: error calling function "version": build info is not present
> 2018-07-01T00:00:00Z + 1mo
Error: type error 1:1-1:27: time != duration
>
```
What is wrong here?

**Comment by nathanielc** [comment]
@youcann Thanks for the report. The missing build info looks like a bug we will investigate. 

The addition of a time and duration is a known limitation. We are working to fix it. 

This issue is required to get it working https://github.com/influxdata/flux/issues/220. 

We also have a proposal for a different syntax here https://github.com/influxdata/flux/issues/2026 we appreciate any feedback you have on that. We are not sure its a good idea yet.

**Comment by jsternberg** [comment]
This is caused by this not being done: https://github.com/influxdata/influxdb/issues/15567

**Comment by jsternberg** [comment]
Also for the duration addition, it's just not implemented yet. I am sorry for that. We're undergoing some existing work on our type system that should make it possible to enable `time + duration` in the future.
