### ISSUE TITLE
Allow procedure specs to expose table schemas in the planner

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2131]
There are some transformations that could be more efficiently implemented if we knew the incoming table schema. An example is the sort function where, if we knew that the table was already sorted, we wouldn't need to perform a sort at all. Another example is the pivot function which will attempt to join rows from different tables based on a set of columns. If we know those columns are already sorted, we don't have to do any sort to join these.

This shows up in a lot of optimization areas. We should find a way to expose table schemas to the planner so that the planner can inform the execution.

**Comment by jsternberg** [comment]
I thought of a good potential implementation of this. The interfaces are below with godoc comments.

```go
// SchemaAwareProcedureSpec is a ProcedureSpec that
// is able to answer questions about the schema for
// the tables it produces.
type SchemaAwareProcedureSpec interface {
	ProcedureSpec

	// GetTableSchema will return the known TableSchema of the procedure.
	// It will be passed in the plan.Node of the procedure
	// spec which can be used to determine the parents.
	GetTableSchema(n Node) TableSchema
}
```

This is an optional interface that a procedure spec could implement. This allows a planner rule to retrieve the table schema for a particular node in the graph. The reason why the `plan.Node` needs to be passed in is because a procedure spec may need to refer to its predecessors when determining its own table schema. This is seen in the circumstances like narrow transformations which do not modify the schema, but just pass on the schema to the next transformation.

```go
// TableSchema is the known information about the table schemas
// that are produced by a procedure.
//
// The schema can be queried to get information about these
// tables. But, the schema may have incomplete knowledge.
//
// When filling out a schema for a procedure, include as many
// methods as you can for the information that can be known
// before the procedure is executed. This information may be
// known statically or dynamically, but it must be capable
// of being known before the procedure is executed and be
// consistent with any changes that may happen between retrieving
// the schema and executing the procedure.
//
// When both filling out the schema and reading it, keep in mind
// that a source may produce tables with different schemas.
// These methods should only return Yes or No if it applies to
// all tables that the source would produce.
//
// If an attribute is not filled out, then it is assumed that
// the procedure is not aware of that part of the schema.
// This causes the function to always return maybe.
type TableSchema struct {
	// IsKeyColumnFunc defines how this schema responds to an IsKeyColumn query.
	IsKeyColumnFunc func(label string) Answer

	// IsValueColumnFunc defines how this schema responds to an IsValueColumn query.
	IsValueColumnFunc func(label string) Answer

	// HasColumnFunc defines how this schema responds to a HasColumn query.
	HasColumnFunc func(label string) Answer

	// IsSortedByFunc defines how this schema responds to an IsSortedBy query.
	IsSortedByFunc func(cols []string, desc bool) Answer
}

// Answer is a response to a query against the schema.
// The answer can either be yes, no, or maybe.
// The default is maybe.
type Answer int

const (
	// Maybe indicates that we do not know the answer
	// to the query about the schema.
	Maybe Answer = iota

	// Yes indicates that we can affirmatively answer
	// yes to a query about the schema.
	Yes

	// No indicates that we can affirmatively answer
	// no to a query about the schema.
	No
)
```

This is the `TableSchema`. Notice how the schema is not an interface, which would break when we added new methods, but it also isn't really a struct. It is a set of functions that can be executed to query information about the table schema. And then there is the `plan.Answer` enum. It allows for the schema queries to answer the affirmative, negative, or say it doesn't know the answer.

These two together make this interface extensible and safe for future implementations. If we decide we want to implement a new schema query to help the optimizer in the future, we can freely add a new function without breaking existing implementations. This is because we would just make the default response to return `plan.Maybe` if a function hasn't been specified.

This allows us to add schema information to procedures in an extensible way that is future proof.

**Comment by jsternberg** [comment]
Here's an example of one of the implementations of the functions on the schema for context.

```go
// HasColumn will return if a column with the label name exists
// in all of the tables returned by this procedure.
func (s TableSchema) HasColumn(label string) Answer {
	if s.HasColumnFunc == nil {
		return Maybe
	}
	return s.HasColumnFunc(label)
}
```

If the schema has not specified a method, it responds with `plan.Maybe`. Otherwise it responds with one of the three potential answers. We can then act on these in the planner to reorganize the query or substitute faster versions when we know we can.

**Comment by nathanielc** [comment]
The general idea of exposing schema information to the planner is good. I expect that the source of this information will be the output of type inference. Because of that I would like to make a few suggestions. 

First do not pass the plan.Node into the `GetTableSchema` method. Doing so is sort of expecting the procedures to perform some kind of type inference to figure out what their schema is. As such I would rather we leave that kind of logic inside the type inference algorithm. 

Second, what if we just used single method interfaces? Something like this instead of a struct with function fields?

```
type KeyColumnSpec interface {
	IsKeyColumn(label string) Answer
}

type IsValueColumnSpec interface {
	IsValueColumn(label string) Answer
}

type HasColumnSpec interface {
	HasColumn(label string) Answer
}

type IsSortedBySpec interface {
	IsSortedBy(cols []string, desc bool) Answer
}
```

This is still future proof has less indirection. Thoughts?


Also the planner design has the concept of an `Enforcer`, which is a property of a procedure spec when can _enforce_ certain expectations, like that the data is sorted by a specific column. The planner will make sure the `enforcer`'s requirements are met by either injecting a sort or removing a sort when it knows its already sorted. I would like to explore how this proposal interacts with that original design.

**Comment by wolffcm** [comment]
@nathanielc I think this question is mostly orthogonal to how we will use enforcers in the planner. What Jonathan is proposing here is on the analysis side, as in, how do we learn what we need to know to produce a correct and optimal plan.  The enforcer concept is on the plan transformation side, as in, how do we change the plan based on what we've learned from analysis.

As long as we keep the two concepts separate (plan analysis vs plan transformation), I think any method of answering important questions like these is fine from the perspective of future work on enforcers.

I'm a little unclear on how this will work though.  The inputs to procedure specs are streams of tables.  So if we ask `HasColumn` and the answer is yes for some tables and not for others, do we return `Maybe`?  Seems like we would return `Maybe` a lot---but this might be fine.

Jonathan's original design (with `Node` as a parameter) appealed to me because it was immediately intuitive and there was less hand-waving about what type inference gives us.  Consider an simple example that I think would be pretty common:
```javascript
... |> filter(fn: (r) => r.host == "foo") |> ...
``` 
The Answers produced by this filter should reflect that `host` must exist (although we may not know if its a key or value column), and for other questions, just return the Answer that would be produced by its predecessor.

I have some concerns about type inference being involved in answering these questions.  As the plan is transformed during planning (suppose we swap the position of the filter with an adjacent node), we want to ensure that analysis still gives us right answers.  Do we need to re-run type inference after each transformation?

I go back and forth on it, but maybe type inference and planning need to be distinct, with clear boundaries.  If type inference can give us info on sources (the leaves of the plan tree), then maybe planning can infer answers to schema questions from that.

**Comment by jlapacik** [comment]
@wolffcm you are correct. What type inference will initially give us is an inexpensive way to obtain the schema for the tuples produced by storage - that is, `influxdb.from()`. However this schema information will have to be propagated through the rest of the operations, at least initially.

While any planner transformation must preserve the final output schema of a query, there's nothing that says that rewrite rules must preserve the types of intermediate expressions. Hence if we annotate `filter` with its input record type, and we transpose that same filter operation with a `map` or `drop`, `filter`'s input record type is no longer valid.

Preserving valid type signatures during planning will require some careful consideration. Running type inference fully after each planner transformation will produce correct intermediate types but it might be a bit expensive. However we have already inferred each function signature before planning begins, so in theory it should be possible to isolate the type inference that must be performed to only the rewritten operators.

**Comment by nathanielc** [comment]
> I think this question is mostly orthogonal to how we will use enforcers in the planner.

Makes sense, thanks.

> As the plan is transformed during planning (suppose we swap the position of the filter with an adjacent node), we want to ensure that analysis still gives us right answers. Do we need to re-run type inference after each transformation?

This is a good question, my initial thought is that it shouldn't need to be re-run because the planner will only make changes that produce the same final result. I am not sure if the planner would introduce changes that could change the intermediate results of type inference. We should investigate this.

> I go back and forth on it, but maybe type inference and planning need to be distinct, with clear boundaries. 

I think they should absolutely be distinct with clear boundaries. I think this proposal is partly about how we can expose that information to the planner. 


The way I see how planning and type inference interact is that first, type inference is difficult to get correct. Meaning we are using very special rules to ensure that type inference is sound (infers the correct type for all possible Flux code). That logic needs to remain encapsulated. Second the planner needs the information that type inference can provide. From my perspective the table schema information is the same thing as types. Given that perspective the planner should consume the type/schema information but should not try to further infer anything about it. If we discover that rewrite rules change type information, then we should find a design for how the planner can invoke type inference again as needed. 

Thoughts?

**Comment by wolffcm** [comment]
> I am not sure if the planner would introduce changes that could change the intermediate results of type inference. We should investigate this.

I think it can, for sure.  Consider an example like this:
```javascript
... |> duplicate(column: "host", as: "host_2") |> filter(fn: (r) => r._value > 100) |> ...
```
We should be able to push down this filter closer to the source.  But if we do this, the schema for the `filter` will certainly change.  Josh's example with `drop` or `map` applies as well.

This is a pretty common problem in compilers; an analysis is expensive, but we want to use it to alter the program in a way that invalidates the analysis.  I guess there's a few strategies to cope with it:
- Just redo the analysis whenever needed.  Maybe easy to implement, but bad for performance.
- Cache the results of an analysis, and implement a mechanism to invalidate the cache if the program changes such that the analysis has become invalid.  E.g., swap a filter with a filter, you don't need to invalidate anything, hopefully?
- Implement the analysis in such a way that you can update it incrementally when the program changes, and not have to redo the whole thing.
- Some combination of those last two.

We also have the added complexity of two distinct representations between type inference and planning, and the Go/Rust boundary to deal with.  It seems like making it easy to translate between the two representations (part of a semantic graph and its corresponding plan nodes) would make this a bit more tractable.

**Comment by jsternberg** [comment]
> First do not pass the plan.Node into the GetTableSchema method. Doing so is sort of expecting the procedures to perform some kind of type inference to figure out what their schema is. As such I would rather we leave that kind of logic inside the type inference algorithm.

Type inference information may change this, but in the current world, the node is required to allow the schema to be based off of its position in the graph. At the minimum, the procedure spec isn't enough to do something like, say, decide what the output schema of filter is because filter's schema is a straight copy of its parent. Procedure specs are separated from where they are in the graph so they need the planner node. When type inference is the primary method to learn this information, I don't know if it would still be the planner node or if it would be something else. At the minimum, something will have to get passed in. Maybe type inference will make it so the procedure spec itself knows the input. Since this is unknown, maybe we could put this interface as an internal interface just so we can change it later on. An internal interface could still be implemented by influxdb and, because of the design, there's no penalty for just not implementing the interface. It just means the planner rules that use it won't work.

> Second, what if we just used single method interfaces? Something like this instead of a struct with function fields?

I had rejected this originally because of an issue with how interfaces in Go work, but I may have been wrong. It may work in the same way as long as the parent node was still passed so it was functionally equivalent.

> I'm a little unclear on how this will work though. The inputs to procedure specs are streams of tables. So if we ask HasColumn and the answer is yes for some tables and not for others, do we return Maybe? Seems like we would return Maybe a lot---but this might be fine.

This is correct. If a single table would have a column and not all, it would answer maybe. But, it turns out that this is more a question of what kind of questions you allow the schema to ask. I had written this proposal as part of a change that I was going to make so I need to update the proposal with the full godocs.

```go
// IsKeyColumn will return if label is a key column in all of the
// tables returned by this procedure.
//
// This can return yes even if the schema cannot confirm that the
// column exists as long as, if the column does exist, it would
// be part of the group key.
```

If you phrase these schema queries in a certain way, they become easier to answer. If I ask if the column `host` exists to the `influxdb.from()` procedure, it will say maybe because it doesn't know until it queries. But if I ask it, "if host did exist, would it be a key?" I can answer an affirmative yes. I can then optimize a future query by saying "it looks like this procedure is referencing a column that is a key. I can't confirm it exists until we run this, but if it does, I can confirm it will be a key and we can use the more efficient algorithm that requires all of the tables to have that column as a key." At the current moment, we can act on a table in a specific way if we see the column is part of the key, but we can't do anything that would require us to know the schema of the rest of the tables. An example might be map where, if we can identify that the only thing that changes are value columns, we can decide that map is a narrow transformation and we don't have to buffer results trying to figure out if we need to regroup the data.

I think getting the right questions to ask will be something of trial and error.

I think that this question may be orthogonal and work in tandem with type inference. Type inference would make it easier to ask certain questions. Right now, it may be a bit difficult for me to figure out what attributes change in the map function. I think the new type inference algorithm will make it easier for me to easily say, "value is the only thing that changes."

The key behind the proposal is that we can infer certain properties without knowing all of the information and we can make optimizations based on some more broad questions. Many of the properties of a schema are based on how the procedure functions and are not based on the underlying data. You may not know every tag that `influxdb.from()` could possibly return, but you do know that they're tags and you do know they are referenced.

**Comment by nathanielc** [comment]
@wolffcm Thanks that does make it clear.

My thoughts are that since Algo W is inherently recursive it could be possible to implement and iterative approach to type inference with appropriate caching so we only have to redo the minimal amount of work. 

I agree that because the semantic graph and the plan nodes are so disconnected it hard to communicate about how they would interact. Perhaps that is where we should start with this proposal? How do we want the planner to consume the semantic graph if at all? Our previous discussions on this point talked about the planner just being another step in the whole compilation process. 

Also, if we can design type inference to be iterative that might also help when we start asking sources for their meta data to more concretely understand the flow of the schema through the code. Sort of like the schema pre-flight idea we had a while back. 


I don't have answers to these questions, but now that we are nearly at the point that type inference contains all the schema information it seems like the right time to start exploring these questions again.

**Comment by jsternberg** [comment]
I've thought about this more and I think that this is completely orthogonal to type inference. I think the confusion may come from the word schema and so maybe we want to change this proposal to use a different word.

In particular, the part that I find helpful for future optimization isn't the schema, but the properties of the table. `HasColumn` isn't as interesting to me as `IsSortedBy` and `IsKeyValue`. These last two aren't things that I think we plan to solve with the type system. There are certain optimizations I can make if I know that a certain column that was referenced is going to be a key or a value column. To my knowledge, the type system is just going to tell me if it is a string or an integer. And I don't think we're going to use the type system to determine if the data is sorted by a certain column.

An example might be the new #2161 I wrote. I plan to expand this to work with more input types, but the initial implementation will only work if the row column is sorted and the column to pivot around is a key value. I don't think the type system tells me either of those.

Would it help to change the name of the function to `GetTableProperties` so that this focused more on the properties of the table, which aren't covered by the type system, rather than use the word schema since that implies that it is a record of the types?

**Comment by wolffcm** [comment]
@jsternberg I'm understanding your use case better now.  You're right, there's lots of information that the typing framework cannot allow for, including sortedness and whether a column is a key column, and these are super important for the planner.

I'd like to see any solution in this space use the output of type inference in addition to any other metadata that we can collect, including the invariants that are guaranteed by influxdb sources.  It doesn't need to be able to use type inference at first, but the design shouldn't rule it out in the future.

Will the table properties be expensive to compute?  If it involves visiting all the predecessors of a plan node, then they might be.  The planner might be consulting them a lot, although maybe not at first.  I think it would be good to design this in a way that makes caching table properties easier.

**Comment by jsternberg** [comment]
I am not sure if it would be expensive to compute. My understanding is each of the methods should be constant time, but there could be recursion involved. My idea was that the planner would only use it when it was considering a rewrite which I think happens less than the pattern matching.

I think if there were caching involved, then the get schema would act on the plan node itself. I'll play around with this. I think the interface would still be the same, but we would make it so the code was roughly like this:

```
func GetTableProperties(n plan.Node) plan.TableProperties {
    // See if the procedure spec implements the interface for this
    // and invoke it if it does. The plan.Node can cache the table properties
    // and skip past this if it doesn't.
}
```
