### ISSUE TITLE
flux: window(every:inf) broken

### ISSUE THREAD

**Issue by rbetts** [influxdata/flux#217]
Rumor has it - from @russorat, @timhallinflux, @pauldix  - that `window(every:inf)` isn't working.

**Comment by timhallinflux** [comment]
Result is: `Error: missing time column "_time"`

**Comment by nathanielc** [comment]
The window function requires a time column on which to window the data. By default that is the `_time` column. If you have just performed an aggregate transformation then the `_time` column will not exist since in most cases its not the column being aggregated nor is it part of the group key.

In such cases you can recreate the `_time` column by duplicating the `_stop` column as the `_time` column. 

The `aggregateWindow` function is a wrapper function that manages all of this for you.

For example:

```
from(bucket: "telegraf/autogen")
  |> range(start: -1h)
  |> filter(fn: (r) => r._measurement == "cpu" and (r._field == "usage_system"))
  |> aggregateWindow(every: 1m, fn:mean)
```
