### ISSUE TITLE
Address OSS build issue with goreleaser when build with Rust parser

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/flux#2245]
With #15768, we now can build OSS using the flux with the Rust parser via Makefile. However, goreleaser does not use the Makefile for building. This may need special consideration if we want goreleaser to be able to build with libflux

**Comment by nathanielc** [comment]
DOD:

* Time box exploring what our options are for cross-compiling InfluxDB with libflux


Open questions:

* How do we cross compile InfluxDB with its libflux dependency?
    Specifically what are the steps to produce an ARM or Darwin build from within a Linux OS?
* Can we use Goreleaser to drive the cross-compilation steps?


Notes:

Both the Rust and Go build tool chains have support for cross compilation. In theory we can build both libflux and the Go dependencies for each target platform. We are unsure how to perform the linking step for a cross-compiled  build.

Maybe we can use `clang` for this?

**Comment by jsternberg** [comment]
My thought is that clang probably _can_ do this. But, I don't think it's incredibly simple. For those unfamiliar, cross compilers are usually named in some hyper-specific way for the exact architecture. I think this was traditionally done so that the compilers could be smaller and most of the infrastructure for cross compiling is based on that. But, clang contains all of the cross compilers in a single binary like Go does. These can be accessed by setting the target triple.

Because of this, I think the easiest way might be for us to create a simple script that chooses the correct target triple when cross compiling and redirects itself to clang. For reference, here's what I'm referring to in the [cgo documentation](https://golang.org/cmd/cgo/#hdr-Using_cgo_with_the_go_command).

> When cross-compiling, you must specify a C cross-compiler for cgo to use. You can do this by setting the generic CC_FOR_TARGET or the more specific CC_FOR_${GOOS}_${GOARCH} (for example, CC_FOR_linux_arm) environment variable when building the toolchain using make.bash, or you can set the CC environment variable any time you run the go tool.

I think if we create a script for something like `clang-x86_64-darwin` and have it invoke `clang` with the appropriate target set, we will be able to use goreleaser with cgo.

This should hopefully be really easy. The easiest way to test this is to try writing a script for Linux on a Mac computer and seeing if you can build a binary by setting `GOOS=linux` when compiling and then try copying it to a Docker image to ensure it works.

**Comment by rockstar** [comment]
Rather than using the `flux-config` tool and some symlinks, we're adding a shim to `pkg-config` that will build `libflux` when `pkg-config --cflags flux` is called, and return the path to the built library, whether that be a native build or a cross compiled build; the path is the only thing that matters at that point.

In the end, the expectation is that we are still able to call `release.sh` and get binaries for all targeted triples. The Windows and macOS builds still have some planning and research related to them, and I'll add that information as it becomes available.

**Comment by rockstar** [comment]
As an update for where we are: pkg-config now has support for fleshing out cargo targets from the go environment, and does it successfully. flux now has a dockerfile describing an image that can be used to cross compile all the linux images. We've tested the building of those binaries from the docker container.

Here's what's left:
  - Integrate this image's use into our use of goreleaser
  - Figure out how to build `darwin_amd64` images from this image, and possibly windows images as well, though goreleaser doesn't currently require it.

**Comment by jsternberg** [comment]
Opened #2654 for Mac OS X.
