### ISSUE TITLE
Functions that drop value columns cannot be typed well

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#2256]
Several functions (notably the aggregate functions) will drop some value columns from their input table when producing their output tables.

This makes it hard to relate the input type of a function to its output type.

We should fix this somehow, perhaps by modeling the group key column specifically for table stream functions, e.g., suppose we modeled the type of `sum` like this:
```
forall [t0, t1, t2] where t0: Row, t1: Numeric, t2: Row, (
    <-tables: [{keyColumns: t0 | _value: t1 | t2}]
) -> [{keyColumns: t0 | _value: t1}]
```

**Comment by nathanielc** [comment]
Another possible solution to this problem is to not drop the columns at all rather let them take on a specific value. This was discussed a bit here https://github.com/influxdata/flux/pull/3530#issuecomment-790936788

I see a few options:

1. Leave the columns but set their value to `null`.
2. Leave the columns and let the implementation chose one of the values from the aggregated rows.

I think I prefer option 1 as it has less chance of being confusing to users since the data will always be null, i.e. representing an unknown value. If you pick a value as in option 2 it might mislead users as being a reasonable value to pick.
