### ISSUE TITLE
Mapping a duration type conversion caused panic: unknown type invalid

### ISSUE THREAD

**Issue by nisley** [influxdata/flux#2262]
I'm storing an int to a bucket to represent a duration. 

The raw _value data when I query the data out lists a long:
![image](https://user-images.githubusercontent.com/1389799/70477715-4eec2b00-1a8e-11ea-8873-f045e13e730e.png)

Trying to convert _value to a duration:
```
from(bucket: "Pingpire")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "PingService")
  |> filter(fn: (r) => r._field == "responseTime")
  |> drop(columns: ["_start", "_stop", "_time"])
  |> map(fn: (r) => ({ r with theDuration: duration(v: r._value)  }))
```

Results in 
>panic: unknown type invalid

**Comment by NULLx76** [comment]
I'm encountering the same problem even doing something like
```flux
|> map(fn:(r) => ({_value: duration(v: 10)}))
```
or
```
|> map(fn:(r) => ({_value: duration(v: "1s")}))
```
seems to result in the same error.

Does `duration` even work at all, or just not inside of maps or something?

**Comment by sanderson** [comment]
@NULLx76 Flux doesn't support a duration column type (you're trying to store duration values in the `_value` column). Durations are valid data types, you just can't have a duration-typed column. This is partially because InfluxDB doesn't support durations in storage.

To get this to work, you have to cast the duration values to string, integer, or uinteger values.

**Comment by russorat** [comment]
this no longer panics, but gives a runtime error as expected: `runtime error @7:6-7:60: map: map object property "new_value" is duration type which is not supported in a flux table`
