### ISSUE TITLE
Fix DurationLiterals in Rust Semantic Graph

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2290]
Right now the Rust semantic graph's value is a single Duration. 

```pub struct DurationLit {
    pub loc: ast::SourceLocation,
    pub typ: MonoType, 
    pub value: Duration,
}
```

While the Rust AST and the Go Semantic graph and AST contain a vector of durations to accommodate the possibility of multiple Duration values in Flux. 

```pub struct DurationLit {
    pub base: BaseNode,
    pub values: Vec<Duration>,
}
```

The Duration and DurationLiteral representations do not have to reflect the ones on the Go side, but they do need to include months in addition to the nanoseconds currently stored. They also need to indicate whether the value is positive or negative. 

@jsternberg suggested following the example from `values/time.go`: 
```// Duration is a vector representing the duration unit components.
type Duration struct {
	// months is the number of months for the duration.
	// This must be a positive value.
	months int64
	// nsecs is the number of nanoseconds for the duration.
	// This must be a positive value.
	nsecs int64
	// negative indicates this duration is a negative value.
	negative bool
}
```

This issue is to: 
- Add a Duration struct to the Rust semantic graph
- Update the semantic graph Flatbuffers to this change (schema, serialization and deserialization) 
- Fix any bugs that this change causes
- Update tests accordingly

**Comment by fchikwekwe** [comment]
Basically, we wanna bring the Rust semantic graph `DurationLiteral` nodes in line with the Rust AST, Go semantic and Go AST representations of DurationLiterals. Flatbuffers handles the differences right now, but it does that by storing a Duration value in nanoseconds only. We want to be able to store the multi-value durations that exist in Flux. `1mo2d3h4s` etc.

**Comment by jlapacik** [comment]
What's the value in storing `1mo2d3h4s` in the semantic graph? Or I guess a better question would be, is there a duration value that can be represented in the AST but not the semantic graph? I'm just trying to get a better understanding on what is being fixed.

**Comment by jsternberg** [comment]
To clarify, the only reason the Go semantic graph stores the individual units is because it was the easiest way to migrate the duration value. Once we get to the semantic graph, we don't really care about any units except for months and nanoseconds.

So if it's easier to keep doing that, then do that. But it might be easier in this circumstance to define the duration literal as months, nanoseconds, and whether the value is negative. These are the only things tracked by the `values.Duration` so you would likely be fine. If you turned `1y` into `12mo` there's no loss once you're in that part of the code.

**Comment by jsternberg** [comment]
An example of this can be seen here: https://github.com/influxdata/flux/blob/a84b0cb78a70df4afad187cf66d9b12e49558124/interpreter/interpreter.go#L1153

It reconstructs the ast duration components from the value and it doesn't bother to preserve the original units because it physically isn't capable of doing that. And the only reason why `AsValues()` doesn't use only months and nanoseconds is because it is also used for the `.String()` method and I believe I wanted it to look nicer.

**Comment by fchikwekwe** [comment]
@jlapacik, @jsternberg  just clarified for me that we don't actually need all the units to be stored on the semantic graph side. I think I need a little bit more understanding on this, but I'm happy to simplify and just represent Durations using months and nanoseconds or another combination.

**Comment by fchikwekwe** [comment]
I'll update the issue to reflect that understanding.

**Comment by fchikwekwe** [comment]
@jsternberg Does that mean that we can just keep things the way that they are? Right now, I convert the Rust semantic Duration value to nanoseconds and store it like that in Flatbuffers. I do store it in a vector so that it matches the Go side, but its just a single value.

**Comment by jsternberg** [comment]
@fchikwekwe you need to also store months. If you changed this to store months, nanoseconds, and whether it is positive or negative, then you're good.

See here for details: https://github.com/influxdata/flux/blob/966b4a7139f27c4d1cc975123df65ed538fe8f2c/values/time.go#L17

If you match that struct, then you're good.

**Comment by fchikwekwe** [comment]
Cool. I'll update the issue to reflect this.
