### ISSUE TITLE
Experimental Set has incorrect builtin type

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2303]
Current type is:

```
forall [t0, t1, t2] where t0: Row, t1: Row, t2: Row (<-tables: t0, o: t1) -> [t2]
```

The type should be:

```
forall [t0, t1, t2] where t0: Row, t1: Row, t2: Row (<-tables: [t0], o: t1) -> [t2]
```

DOD:

* Fix type
* Add test case to validate the type is correct

**Comment by wolffcm** [comment]
D'oh!

Regarding adding a test case, when we can run type inference on all of our `_test.flux` files, we will certainly catch errors like this.  

In the meantime, I don't see how adding a unit test for this adds much value since all we can do at this point is assert that it has the type that we said it has.

**Comment by nathanielc** [comment]
Makes sense, agreed. We found this by running the type inference against a set of queries. The existing test cases should catch this once Algo W is part of that code path.
