### ISSUE TITLE
Reimplement mutable object value with flatbuffers

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2318]
We use a mutable object value on the Go side in a few places. We need to reimplement that behavior using flatbuffers. See https://github.com/influxdata/flux/blob/feat/use-algo-w/values/object.go#L22

Since using mutable flatbuffers is complicated maybe we can implement only a subset of the previous behavior where the type is known and not mutable but the values are mutable? Not sure if this is possible in all current uses.

**Comment by jsternberg** [comment]
The mutable objects were a pretty bad performance area in filter and map mostly because of recomputing the types. It might be possible to have it so you create the object's type ahead of time and `Set` only works when you don't change the type. That would fit everything that we need for map/filter and would also remove the possibility of making a mistake. I think that should be compatible with the flatbuffers implementation.

**Comment by jsternberg** [comment]
As an example, I think this kind of thing would work fine.

```
func NewObject(properties map[string]semantic.MonoType) values.Object { ... }

// Set will set the value for the property at key. If Set is used on an unknown key
// or the value does not match the specified type, this method will panic.
func (o *object) Set(key string, value values.Value)
```

**Comment by jsternberg** [comment]
I'm trying to do this by testing it by modifying filter so I can understand the requirements for what we need.

Some things I have found.

1. Checking types on Set is likely prohibitive so I am not sure that Set should panic when given the wrong type.
2. I likely need to support dealing with tvars that come up from the type system and perform a substitute/replace operation on them. At the same time, I don't know any of the constraints because they are gone. This seems to be a problem. As an example, I won't be able to identify this:

```
filter(fn: (r) => r.a + r.b)
```

I'll be able to know that `r.a` and `r.b` are supposed to be the same type, but I won't know they can't be strings. cc @jlapacik.

The type returned by type inference for a function seems more like a suggestion to me. To ensure that this would work (`map(fn: (r) => ({r with _value: 2}))`) I would need to still fill out the `r` object with all of the columns in the table which means I have to construct the object type from Go anyway since I can't use the Rust one. Not a big deal, but informative. I was hoping I would be able to just use the one I got from Rust.

**Comment by nathanielc** [comment]
Adding a note since we discussed on a call. 

The plan for now is to ignore constraints as any mismatched type will get caught at runtime later with an appropriate error message. That is the way it is currently since the old Go type inference didn't understand constraints. A follow on issue will be to teach row functions about constraints where its useful.
