### ISSUE TITLE
Add a function or option for writing query output to a CSV file

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/flux#2322]
From a new user's perspective, it would be great to be able to send the output of a query to a CSV file that can be inspected using a text editor and/or loaded back using `csv.from()`. While learning flux I am often inspecting the result of a query to see if it does what I want.

This could be a `csv.to()` function, or some kind of redirect of the output to a file.

@rawkode 
Slack discussion: https://influxcommunity.slack.com/archives/CH8RGRW4T/p1578304122062500

**Comment by adriandt** [comment]
I took a stab at implementing csv.to in the above commit. Wondering if someone could give me some feedback? I'm new to both flux and go. I used experimental/mtqq.to as a reference. Some questions I have:

1. Do I need all that ProcedureSpec Kind and Copy boilerplate? Not sure what it is doing.

2. I am collecting tables to an array, then in the Finish I make a flux.Result and pass that to the CSV Encode function. It strikes me that it could me made more efficient by working incrementally. Is there some kind of goroutine magic I can take advantage of to write tables as they arrive in Process?

3. My transformation returns something I think is wonky: `Result: toCSV1`. What do I have to do to return a proper empty table? Or is this normal? 


Thanks!

**Comment by nathanielc** [comment]
@adriandt Great questions

>  Do I need all that ProcedureSpec Kind and Copy boilerplate? Not sure what it is doing.

Yes you will need that boiler plate. In short what is doing it creating a mapping of functions in the Flux language to an implementation of a transformation for the execution DAG.  Here is a longer document on how that all works https://github.com/influxdata/flux/blob/master/stdlib/doc.go

>  I am collecting tables to an array, then in the Finish I make a flux.Result and pass that to the CSV Encode function. It strikes me that it could me made more efficient by working incrementally. Is there some kind of goroutine magic I can take advantage of to write tables as they arrive in Process?

Yeah there is some goroutine channel logic you can use for this, in fact we already have it written but its not exposed as a public API that you could consume. Have a looks at this https://github.com/influxdata/flux/blob/master/execute/result.go Its a type that implements the execute.Transformation interface and the flux.Result interface. This way you can essentially convert a transformation into a result. Then pass that result into the csv.Encoder. Doing it this way will allow for the results to be streamed into the encoder. Feel free to make that `result.go` code public so you can import it from your  csv.to code. That should get you started in the right direction. This is the first time we are writing a `to` output function that wants to encode an entire result instead of individual tables so this is a bit of uncharted territory.

> My transformation returns something I think is wonky: Result: toCSV1. What do I have to do to return a proper empty table? Or is this normal?


That is expected. The Flux functions for transformations actually produce futures/promises to the real results. Those results get computed via the execution layer, so the return of the `csv.to` function will look a little odd. That said the standard is for `to` output transformations to behave like an identity function, they should output the same data they receive as input. @jsternberg  has recently created a PassthroughDataset https://github.com/influxdata/flux/blob/master/execute/dataset.go#L177 that may be of some use there. But you can probably worry about this part last. If your Process method never adds a new table to the data set then no data will be output which is fine for a first attempt at a solution.


Hope this helps. Feel free to ask anymore questions you run into.

**Comment by adrian-thurston** [comment]
Unassigning myself as this needs to get scheduled into a sprint now.
