### ISSUE TITLE
Failed to create logical plan: cannot pass zero time to 'range'

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#238]
This error is occurring in the query log.

The error means that one of the time parameters to range is the zero time. 

Maybe update the error message to be more clear. It was misunderstood as the range being a zero width range.

**Comment by jsternberg** [comment]
This is a circumstance where the code assumed that `createRangeOpSpec` would get called and the system that is producing the error directly submits specs rather than goes through the compiler.

**Comment by jsternberg** [comment]
There's also two different ways to resolve this that I think are important to discuss. I've submitted a PR for one of them, but the other is also valid.

Should the stop value be required when submitting a query spec? We forced `Now` to be required, but I'm curious if we think the defaults should only be defaults when using the compiler or if defaults should be defaults for the spec too so that the language is just a very thin wrapper around the spec.

**Comment by jsternberg** [comment]
I'm considering this closed and that this was an error with the transpiler. We likely will have to spend some time on a few decisions:

1. Are there default arguments in the spec and what should be a default argument? I think there's a pretty strong argument that could be made for `Stop` being required in the spec and that the transpiler should have filled it out (argument not made here), but there's also a good argument of the opposite.
2. What programmatic interface are we going to provide for building specs? It seems like the transpiler should have access to whatever is used by the flux compiler.

But the error message and the associated change to the transpiler in influxdata/platform#1314.
