### ISSUE TITLE
Failed to transition query into requeueing state

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#239]
This error is occurring in the query log.

**Comment by jsternberg** [comment]
I think this can happen when a query enters the requeueing state because there aren't enough resources. If it then attempts to get the same resources again while in the requeueing state and fails, it will try to enter the requeueing state (which it's already in). The `tryRequeue` function expects it to be in the planning state and the transition fails and it would abort the query.

I'm going to just patch this one up, submit the fix, and then dig up an old controller refactor I had. The controller refactor will of course not apply to 0.7.0, but I'll get it started.
