### ISSUE TITLE
Iteration over values of time series with flux

### ISSUE THREAD

**Issue by sgerhardt1** [influxdata/flux#2452]
It would be very helpful for outlier detection to iterate over all values of a time series with access to previous values. So that you can do something like this:

`for(i=0; i<values.size; i++) {
    if (i > 1 && value[i-2] > value[i-1]*10 && abs(value[i]-value[i-2]) < 5) {
        listOfOutliers.add(value[i-1]);
    } 
}`

There should be an element like a for-loop that you can use to iterate over values.

**Comment by nathanielc** [comment]
@sgerhardt1 Yes we agree, we have some longer term plans to add loops to the language. In the meantime we have a `reduce` function that will let you do something similar. See https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/reduce/

**Comment by sanderson** [comment]
The issue with `reduce` is that it doesn't preserve the previous rows. It outputs only one row per table. `map` iterates over each row and preserves all rows.

## Proposal
What if we extended `map` so you could pass additional row objects into each row loop? For example, a `includePreviousRows` parameter that would accept an integer representing the number of previous rows to include in the mapping operation. You could then reference previous row objects using something like `p1.columnName` where `p1` is essentially `r-1`.

The example above in Flux would look something like this:

```js
import "math"
// ...
  |> map(
    includePreviousRows: 2,
    fn: (r, p1, p2) => ({ r with 
      outlier: if r._value > 1.0 and p2._value > (p1._value * 10.0) and math.abs(x: p2._value) < 5.0 then true else false
    }))
  |> filter(fn: (r) => r.outlier == true)
```

Some other notes:

- If `includePreviousRows=2`, each output table will have 2 less rows than their corresponding input table because you can't complete the loop with null values. The first `x` rows would be dropped after the transformation.
- I know this would increase the resource demands of `map`, but I don't know by how much. It would mainly depend on how many rows the user includes and the size of those rows.

**Comment by sgerhardt1** [comment]
Great, that sounds very promising. I think this feature would be very helpful for many situations.

Perhaps it would be a good idea to also be able to access the loop iteration variable (like the `i` in a for-loop). In the example above, the first two values must always end up in the result, because no outlier detection can be carried out for the first two values. And the aggregation of all filtered values after that have to result in a correct value.

Thank you for your thoughts on this.

**Comment by geropl** [comment]
To frame this a bit differently, and raise attention again: We're missing a "map-reduce" function that allows to store "side-effects" next to aggregation

Usage of an alternative implementation might look like this:
```
// ...
|> mapReduce(
  fn: (r, accumulator) => {
    state = accumulator.state + r.value
    return ({
      row: { r with currentState: state },
      accumulator: {
        state: state
      }
    })
  },
  identity: { sum: 0.0, before: 0.0 }
)
```

(This is basically similar to this suggestion @sanderson linked above: https://github.com/influxdata/flux/issues/1256

**Comment by sanderson** [comment]
@geropl There is work happening right now to update reduce so that it can produce all the side effects of the table transformation, so you can preserve each row in the table. Here's the PR: https://github.com/influxdata/flux/pull/4387

It adds an `emitAll` parameter to reduce that tells the function to output all rows through the reduce operation. It fulfills at least part of my proposal above (carrying values forward into the next row iteration), but it can't look ahead to rows and pull values back into the current operation.

**Comment by geropl** [comment]
@sanderson Interesting, thx for sharing!

> but it can't look ahead to rows and pull values back into the current operation.

Understood; but at least works for my case: emulating the map-reduce case is currently O(log n * n) compared to O(n) as it should.

BTW, I tried to validate by ideas on this PR: https://github.com/influxdata/flux/pull/4395 But the "map with sideeffects" looks indeed like a little less bulky.
