### ISSUE TITLE
Error when attempting to unmarshal semantic.Node in Filter test

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2492]
When running `TestFilterOperation_Marshaling`, trying to unmarshal json representation of a flux.Operation causes the following error message: 

`failed to unmarshal operation "filter": json: cannot unmarshal object into Go struct field FunctionBlock.fn.fn.Block.Body of type semantic.Node`

**Comment by fchikwekwe** [comment]
DOD: 
-  Tests are unskipped and now pass

**Comment by fchikwekwe** [comment]
UPDATE: This also affects `TestMapOperation_Marshaling`

**Comment by wolffcm** [comment]
Ah, hmm, we decided to discontinue support for being able to marshal the semantic graph as JSON, since we have flatbuffers now.  But we still serialize the Spec for the REPL I believe, and the Spec for map and filter contain semantic graphs for their lambdas.

This is something else that would need to change to get the  REPL working again I think.  Probably okay to treat this as lower priority.
