### ISSUE TITLE
Go build should rebuild when the libflux archives change

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2511]
Currently the Go build system only rebuilds the `libflux/go/libflux` package if a Go source or C related source file changes. This causes confusion as changes to the Rust code are not immediately available when called from Go as the Go code is still linked against the older Rust code. Its also not clear how to force the Go build to perform a complete rebuild when this happens.

We need a way to automatically inform the Go build process when the Rust code has changed. This PR has a good first idea https://github.com/influxdata/flux/pull/2423 It uses `make` to generate a unique C source file from the output of the Rust build. This has the effect (even though C files are never used) to trigger the Go build to rebuild that package and link against the new libflux.a and liblibstd.a archives.

As proposed in https://github.com/influxdata/flux/pull/2423#issuecomment-578288822 it would be nice if the build tooling worked without requiring a `Makefile` wrapper. A quick search suggests that Rust does not have any post-build hooks https://github.com/rust-lang/cargo/issues/545 and as such it would be difficult to generate the unique C files as part of the `cargo build` process.

In light of the above my recommendation is to use the simple `make` based solution as a starting point.

DOD

* There exist a command that can build the project where changes to the Rust code result in the Go build correctly linking against the new archives

**Comment by adriandt** [comment]
I quickly experimented with using `pkg-config` to generate a unique `-DVAR="value"` define on each run, but:

1. That would be an awful hack.
2. `cgo` does not call `pkg-config` on every invocation of `go build` so it's a no-go. (pun intended).

**Comment by jsternberg** [comment]
@adriandt it should be possible to do this using a generated variable inside of the `libflux/go/libflux` package and it might be possible to leverage the work that @rockstar and I have been working on.

https://github.com/influxdata/pkg-config

We've been working on a utility that you can install and is a drop-in replacement for `pkg-config` that Go can execute. If you put it on your path, Go will use it as if it were the system `pkg-config` or you can use it by setting `PKG_CONFIG=/path/to/the/above/binary` and then execute Go.

I was thinking that `pkg-config` could be extended to support the `--variable` option. We can then generate the `flux.pc` file to include either the source or binary hashes. The `go generate` command can then call `pkg-config --variable sha1sum` or something and insert that into the Go code somewhere so it is unique.

The above `pkg-config` will rebuild the Rust library so `go generate ./libflux` would be the equivalent of calling `cargo build` as if you had called the makefile.

```
const char *flux_sources_hash = "hash value";
```

Or preferably we generate a variable like:

```
const int FLUX_VERSION_HASH_hashvalue;
```

@rockstar and I are making a change soon that will make it so manually running `cargo build` won't be necessary since Go will execute it automatically so the only part of this is generating a change to the go package so it forces a recompilation because Go won't consult `pkg-config` to see if anything has changed.

I like the second one because we can generate that same constant in the Rust library and it would cause a linker error if it failed to link with the correct sources, but any change would be good and integrating it with `go generate` means that CI will catch it. I think the hash should be generated by walking the `src` directory and

**Comment by nathanielc** [comment]
@adriandt I was missing some context and so I chatted with @jsternberg to get caught up.

Here is what I learned

The proposed workflow for a developer of Flux when they make changes to the Rust is the following:

1. Make changes to some Rust code
2. Run `go generate ./libflux/go/libflux` 
3. Run any `go {build,test,run}` command and it just works

Note that `cargo build` is not explicitly necessary with this workflow.

The mechanics for how this works are two fold:

1. There is a wrapped  `pkg-config` script that knows how to build libflux on the fly. (i.e. builds it whenever Go tries to find it). 
2. The `go generate` command produces unique C code in order to inform Go it needs to look for something new.

This issue is about the second mechanic.
 
The crux of the issue is still the same, we need to generate unique C code inside the `libflux/go/libflux`  package in order for Go to trigger a rebuild. But instead of doing that action via `Makefile` we encapsulate it as part of the `go generate ` step. 

Then the `makefile` can be updated to always call `go generate ./libflux/go/libflux` after building the Rust archives this way we get the best of both worlds. 

When using `make` a single command builds everything.
When using the normal `go` tooling it just works, with the knowledge that a `go generate` step is needed. Using `go generate` is normal and expected, for example in the `stdlib` when you change a `.flux` source file you must use `go generate` for those changes to take effect.

**Comment by jsternberg** [comment]
The above is a good summary. How `go generate` is implemented can vary. For example, we can make it so that `go generate` calls `pkg-config --variable sha1sum` and we can ensure that `pkg-config` adds the sha1sum as a variable in the `.pc` file. I think this is probably the easiest method of implementing this.

But the generate process can do almost anything as long as it changes the file in some way in a consistent manner.

**Comment by adriandt** [comment]
I would prefer to leave `pkg-config` out of the `go generate` call because `pkg-config` is normally part of the package configuration step, eg using `./configure` to examine the environment and set any build parameters that you want to persist across multiple invocations of `make`. Calling it to build seems strange to me and might lead to confusion.

**Comment by adriandt** [comment]
I've exhausted all options I can think of when trying to get a solution to this that is based on just `go build`

My conclusion is that we either need to rely on a call to `go generate` getting called first, or wrapping `go build` with make.

**Comment by adriandt** [comment]
There is one option actually: to have it always rebuild by using pkg-config to to generate the unique C/Go file to always cause rebuild on the next invocation.

**Comment by adriandt** [comment]
Some more info on the above mentioned technique ...

It is to alter the source code to the golang wrapper package in the pkg-config call. This forces a rebuild the next time you invoke go build because of the order of operations performed by the go build:
* compute the cache key for the source files (hash them all + some other things)
* if different from the cache, trigger a build of the package
* (building) call pkg-config, we edit the source code in our wrapper of this prog
* do rest of build (compiling, linking, etc)
* store the results in the cache, using the hash key computed **before** the edit.

The result is that the source files on disk don’t match the cache key and we get a rebuild the next time. This gives us rebuild of the golang package every single time we type `go build`.  That itself is a nuisance, as every test case run and probably also even formatting run will result in a rebuild. But I’m not sure what is worse, that or not getting rebuilt software when you think you’re running the code you just wrote.

**Comment by jsternberg** [comment]
I am wondering if we're overthinking things. The rebuild is only needed when we are developing locally. What if we just had an easy script we could run to generate a C file with the current timestamp and inserted that into the package? We could invoke that script with `go generate`. We only need this functionality for local builds and we would have to run something anyway to generate the file. Instead of generating some kind of hash, we can even do something like:

```
printf "const int FLUX_BUILD_TIMESTAMP = \"%s\"" "$(date +%s)" > build.c
```

I forget the syntax for the bash printf but I think the above is all we would need. Then add the `.c` file to the `.gitignore` so we never check it in and we can configure our editors to run that script any time we modify a rust file.

**Comment by adriandt** [comment]
Yeah that can work. Just wondering if all the other stuff `go generate` does is okay to do every time we need the Go package to build. A SHA sum is definitely overkill. It can just be an awk script that increments an integer, or use `date`, so long as the time granularity is there.

Though I think my preference is still to use a `Makefile` for gluing the two build systems together. All roads I explore take me back to wanting that. It has the added benefit that developers instantly recognize the need to run `make` when a `Makefile` is there. After the first `make`, if you only touch Go you can stick with `go build`. If you touch rust code, you need to use `make`.

We would have to supply makefiles for the other repositories and they would need to shift to using that. It's not ideal, but without any compromise we might not get to a solution, short of hacking go itself to give us the hook we need to invalidate the build cache key and trigger a cargo build.

Also we might want to consider adding a requirement that we separately checkout and build `libflux`, then in the Go program we are building, require a configure step that persistently links the two, via the Cgo build flag `-L`, possibly using `pkg-config`. Essentially take the autoconf approach and instill that `libflux` is a dependency, external to the Go dependency mechanisms. It must be present on the system like `libc` or `libpthread`. We would write `./configure --with-libflux=/path/to/libflux` before building `idpe` and `influxdb` programs. This might eliminate some confusion for people. It's not very Go-like and probably breaks some go things like `go get`, but then again, our project is no longer pure Go.
