### ISSUE TITLE
Restructure libflux crates to avoid dynamic linking issues

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2655]
With https://github.com/influxdata/flux/issues/2636 we discovered that because of some Rust tricks when you allocate a Btree in one crate and pass it to another to free that was dynamically linked it creates an invalid free. This means that we should keep allocate and free the Rust structure from the same crate. This seems like a good sane practice anyways.

The current structure of the crates means that Rust objects are allocated in one crate, passed through C ABI and then free via another crate. As a result it becomes difficult to easily audit and track the alloc/free pairs.

The proposal is to restructure the crates so that this passing of pointers between crates is no longer necessary. 

Currently the implementation of the C API is spread across both the `flux` and `libstd` crates. The suggestion is to add a new create that consumes both existing crates and move all the unsafe logic that implements the C API into that single crate. This way the C API is implemented in a singe crate. The alloc/free pairs can easily be audited as they will exist in the same file. 

Here is the new proposed crate structure:

```
libflux/src/
    flux  # this is the "public" crate that directly implements the C API
    core # this is what we currently call the flux crate, it contains the implementation of Algo W
    libstd # this contains the data files of the encoded standard lib
```

With this structure the `core` crate will not contain any unsafe logic or implementation logic of the C API. The `libstd` crate will not contain any logic beyond just returning the std lib data structures. The `flux` crate is the new crate that will tie the other two together and directly implement the C API. 

The `flux` crate should export the types and function from the other two crates thus defining the public Rust API for interacting with Flux.

**Comment by jsternberg** [comment]
I think this will work fine, but it does add another link target. In the future, I would like us to try refactoring this back down to one crate, but I'll write an issue at some point detailing how I think that should be done.

**Comment by wolffcm** [comment]
I like it. Will we need to link against all three crates as static libraries?  If so, the name `libstd` irks me, because the file is named `liblibstd.a`, which seems strange.  Maybe rename it to `stdflux`, so the file ends up as `libstdflux.a`.  Just my $0.02.

**Comment by jsternberg** [comment]
So I understand this better, is it because we're compiling the crates to static libraries which duplicates the btree code into two different implementations?

**Comment by wolffcm** [comment]
@jsternberg We found the invalid free in the valgrind test, which uses dynamic linking.  In that case, yes, the btree static data is duplicated.

Not sure if this would show up in a static build. But in any case our Rust code should work linked either statically or dynamically.

**Comment by jsternberg** [comment]
Ok I think I understand this better. I have a plan for merging the two crates that I prototyped and was going to propose after we got algorithm w to production. It would remove the multiple crates. If this issue is only affecting dynamic libraries and won't affect the static builds produced by Go, it might be best to look at that strategy and see if it is a better long term plan.

I think this technique will work as a stop gap though if we need to get it working now.

**Comment by nathanielc** [comment]
@wolffcm 

> Maybe rename it to stdflux, so the file ends up as libstdflux.a

I agree. The name `libstd` is confusing and redundant. I am open to renaming it as part of this change.

@jsternberg  Yeah, I'd like to leave the exploring of a single crate till later.  This proposal should be a simple change without too many open questions.

@bthesorceror How does a change like this effect you? I'd expect you might have to update a few import/use paths but otherwise shouldn't have to change too much. Thoughts?

**Comment by adrian-thurston** [comment]
We can restructure so there is a single crate/library exported to the world by doing the following. This is a proposal based off a proof of concept.

1. Converting the `crate-type` of `libflux` to be just `lib`. This allows the compiler to decide which type of library to build. Since we will not expose this crate beyond the flux repository, we don't need to specify the type.

2. Importing `libflux` in `libstd` using `pub use flux::*;` This takes in all the public stuff from `libflux` and *re-exports* it in `libstd`. After doing this, rust code using our library only needs to `use` one thing.

3. Changing C/CGo builds to link against `libstd.{so,a}` only. The crate type `staticlib`, which produces the `.a` file, incorporates all the dependencies into the `.a` file (except `libpthread` and `libdl`). This is explicitly mentioned in the documentation. The crate type `cdylib`, which produces the `.so` file, also incorporates the dependencies, but it is not explicitly mentioned in the docs.

https://doc.rust-lang.org/reference/linkage.html

After all this (or maybe before) we can rename `libflux` to `libcore` and `libstd` to `libflux` and then hide the new `libcore` inside the new `libflux`.

To address @rockstar's question "why do we need multiple crates" ... I investigated this and the reason is that in order to use the first stage `libcore` in the build script of `libflux` we need to import the code as a crate. I didn't see this in the docs, but tried to use a module and got various errors. It makes sense though, as the build system needs a self-contained fully built crate to link to and run before it attempts to build the second stage.

The POC: https://github.com/adrian-thurston/sandbox/tree/master/bootstrap

**Comment by adrian-thurston** [comment]
Testing this in https://github.com/influxdata/flux/tree/refactor/one-public-crate

Although at the moment it requires hacking pkg-config to make it work because the specification of the C libs has been moved there.
