### ISSUE TITLE
Audit all  tests cases that hand write semantic graph and update them to use parsing of source

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2664]
The semantic analyzer is responsible for producing semantic graph. This happens to be implemented in Rust. There are unit tests for producing the correct semantic graph. As such all other tests not related directly to the semantic analyzer should make use of the analyzer to construct their semantic graph. This way we ensure that tests are using _real world_ semantic graphs.

This so happens to align with the Go/Rust boundary currently. Therefore we should audit all Go tests cases that have hand written semantic graph and update them to parser Flux source and analyze it to produce the semantic graph.

**Comment by jsternberg** [comment]
I've audited the test cases and I believe that the cases left for catching this are in the remove trivial filter and some big table tests. I have modified the test cases. Since this overlaps with the remove trivial filter rule fix, I am holding off on actually fixing the bigtable stuff until that goes in so I can reuse that code.

I did find some tests in the semantic package that I don't seem to be able to convert to using analyze. It's because it uses a semantic graph that won't type check. I'll be leaving those tests alone since they don't directly impact how the planner functions.

**Comment by nathanielc** [comment]
> 

I did find some tests in the semantic package that I don't seem to be able to convert to using analyze. It's because it uses a semantic graph that won't type check. I'll be leaving those tests alone since they don't directly impact how the planner functions.

Can you expand on this? What kinds of tests are operating against non type checked semantic graph? Are these tests from before Algo W that can just be removed since they are testing the validatity of the semantic graph of something?

**Comment by jsternberg** [comment]
It's graphs that have imports. Some of them test options from other packages like this:

```
import "bar"
option bar.foo = 2
```

But this won't type check because the Rust code can't analyze arbitrary file trees. It is limited to only the packages that are builtin at the moment. We should be able to do this in the future, but it will require a bit of refactoring that we are putting off until after we merge algorithm w to master.

**Comment by jsternberg** [comment]
I am not sure if the tests can be removed. The ones that I am seeing that cause a problem are primarily in `semantic/check_test.go` and I'm not sure what they are checking for. It does seem like something that should probably be in the Rust code if it isn't already there.

**Comment by nathanielc** [comment]
Based on the name I'd bet they are test cases for the semantic.Checks we have, where are akin to the ast.Checks for checking for invalid graphs. Those were ported to Rust for both AST and semantic packages. Can you confirm this? And if so then remove the checks and their Go implementations?

**Comment by jsternberg** [comment]
Yes it looks like there are tests for this in the Rust implementation. I'll remove these.
