### ISSUE TITLE
Unexpected behavior in Testing.diff 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2700]
We are seeing inconsistent behavior in testing.diff. It seems to be releated to reading data directly a source instead of a transformation. 

For example 

```
csv.from() |> testing.diff()
```

behaves oddly

while 
```
csv.from() |> duplicate() |> testing.diff()
```

seems to behave correctly.

Maybe this is related to caching and outputting tables in group key order?

**Comment by jsternberg** [comment]
We've traced this down to a problem in the group lookup's delete method. It seems that `Delete` is causing the group lookup to "lose" values. A delete happens and some unrelated values that are presently in the structure cannot be found anymore.

We're not sure of the exact cause, but we may end up reevaluating how the `Delete` method works. I also reapplied a change in influxdata/flux#2720 that included an alternative implementation for the same structure. It was originally committed as one of the tools used by an optimization for window but ended up being reverted because it was part of the same commit even though the code wasn't specific to window.
