### ISSUE TITLE
Produce a broken semantic graph (graph with errors) from a broken parse tree

### ISSUE THREAD

**Issue by adrian-thurston** [influxdata/flux#2708]
Given a parse tree with errors in it, attempt, within reason, to produce a semantic graph also with errors. This should involve classifying errors into some number of groups and developing corresponding error nodes for the semantic graph. These should correspond to the kinds of errors we wish to push past in the tools, such as when the user is typing and the program is therefore incomplete, or when the user has an unknown (to them) error.

**Comment by nathanielc** [comment]
NOTE:

 * Create BadExpression and BadStatement semantic node like their AST counterparts.
 * What do we do about errors on the BaseNode of the AST? Transfer BaseNode to semantic graph with its errors. As part of #2709 the semantic::check function will report any errors found in the BaseNode.
 * This issue does not need to concern itself with the Go semantic graph nor the flatbuffer representation of the graph. We will address those in a separate issue.

**Comment by jsternberg** [comment]
I started working on this and I'm not sure if using `BadExpression` and `BadStatement` are the ideal choices for this. The way the code is, it seems easier if the errors are just collected at the top level and default values are chosen for the values in the semantic graph. It seems to me like it would be an easier API and would invalidate the need for `BadExpression` and `BadStatement`. Something like:

```
pub struct Result {
    pub env: Environment,
    pub cons: Constraints,
    pub errors: Vec<Error>,
}
```

I think this would match with the flow of the code more easily and the errors themselves already have location information included within them. We could then add an error to the list of the errors whenever we encounter a bad statement and exclude it from the final semantic graph.

I think this would involve changing less code and I think the API would likely be easier. We could add a function to the result like this:

```
impl Result {
    pub fn get(self) -> std::result::Result<(Environment, Constraints), Vec<Error>>;
}
```

We would then be able to keep a lot of the existing patterns and be able to use `match` calls to unwrap. We might even want to turn the vector of errors into something that implements the rust error type.

**Comment by nathanielc** [comment]
The reason we plan to use BadExpression and BadStatement is they are needed to make the graph complete. Without some kind of place holder the graph would have dangling edges that our design in Rust won't allow.

For example given the `UnaryExpr` semantic node, how do you add that to the graph if it is _broken_, i.e. an error occurred?

```rust
pub struct UnaryExpr {
    pub loc: ast::SourceLocation,
    #[derivative(PartialEq = "ignore")]
    pub typ: MonoType,

    pub operator: ast::Operator,
    pub argument: Expression,
}
```

Concretely what do you put in the graph for the `argument` field? If the AST node has a `BadExpression` for the argument field?

Also it makes sense to me to have the AST and semantic graphs mirror each other where appropriate. Choosing a different mechanism for the semantic graph compared to the AST sounds like it will create complications in translating between them.

**Comment by jsternberg** [comment]
I understand that intention and `BadExpression` makes more sense to me than `BadStatement`. What I don't find compelling is adding errors to each node since the expected usage is then to call `check` and iterate to gather the exact same errors. I think it makes more sense if we collect the errors during our initial traversal of the tree and, if we need placeholders such as `BadExpression`, we use those, but those nodes can be much more simple.

For specifics, I think it makes sense to iterate through each of the nodes and do one of three things.

1. If you see a `BadStatement`, add the error to the list of errors and skip over it. There doesn't seem to be a need to keep this and it isn't needed as a placeholder.
2. If you see a `BadExpression`, add an `Invalid` or `Bad` node as the translation. The type would include no additional information and would act as a no-op during type inference. Then add the actual error message with the node information to the list of nodes.
3. For any other node that gets converted, add the errors to the list of semantic errors that are returned and then translate the semantic graph as normal while filling in auto-filled values if necessary and when appropriate.

I think this handles all of the situations where you would see errors.

My fear is the AST solution is more complicated and I am not sure what benefit we get from it. The location information is already attached to the error itself and we can perform highlighting of the error locations based on that information. It's a lot of code to write and refactor for what, in my opinion, might be an anti-pattern.

> Choosing a different mechanism for the semantic graph compared to the AST sounds like it will create complications in translating between them.

This is something I would like to explore. I don't believe this is the case, but I will find out if I am wrong very quickly while working on this issue since this issue is about converting the AST to the semantic graph so I'll find out if this is true if I try this alternate solution today. If I am able to convert the AST to the semantic graph in a way that makes sense, I don't believe that it will extend to another portion of the system.

**Comment by adrian-thurston** [comment]
I think adding `BadExpression` and `BadStatement` to the semantic graph is a good start. One of the issues with this project is that we don't know exactly what we need in order to give the tools team as much information as possible. Mirroring the AST errors in the semantic graph is conceptually quite simple and is a good starting point for pushing forward through the next stages. Creating the bad nodes and then ignoring them or incorporating them in type checking becomes an option.

**Comment by jsternberg** [comment]
I talked to @bthesorceror about the proposal [here](https://github.com/influxdata/flux/issues/2708#issuecomment-611003790) and he said that this proposal would work so, if we like it, it would fit their needs. So if that proposal sounds good, I can go about implementing that more easily.

I think mirroring the AST ends up not being very simple which is why I want to avoid it. It means there's more information to copy over and it means that, because of list item 3 above, we end up with a more complicated type system. Instead of carrying the ast errors into the semantic graph, I think it would be easier if we extracted the errors while constructing the best semantic graph we can. I also think that this matches more with our current code and so the change in code will be less.

While we talk this through, I'm going to work on `BadExpression` and, after that, `BadStatement`. If it turns out the work involved isn't what I think it is, then we can just go with the current proposal.

**Comment by nathanielc** [comment]
@jsternberg I am not sure I understand your proposal. To me it sounds like you are saying that we would both add the BadExpression nodes and that we would not add them. Can you clarify? 

> If you see a BadStatement, add the error to the list of errors and skip over it. There doesn't seem to be a need to keep this and it isn't needed as a placeholder.

We need to at least track that it was there, either by inserting a BadStatement or recording the error in some other way. We do not want a broken AST to result in a valid semantic graph.

> If you see a BadExpression, add an Invalid or Bad node as the translation. The type would include no additional information and would act as a no-op during type inference. Then add the actual error message with the node information to the list of nodes.

Here it sounds like you are suggesting that we add a BadExpression node to the semantic graph. Maybe the point of clarification is what is the difference between what you call an `Invalid` or `Bad` node vs what I am calling a `BadExpression`? Are they the same? Can you maybe be specific in what you mean so we can compare? My concept of a BadExpression in the semantic graph is a direct copy of the AST BadExpression node.

As for making it a no-op during type inference that makes sense to me.

>For any other node that gets converted, add the errors to the list of semantic errors that are returned and then translate the semantic graph as normal while filling in auto-filled values if necessary and when appropriate.

This parts makes sense. Basically all normal nodes behave the same except we collect and errors in their BaseNode into a separate global list of errors for the entire graph.

Further thoughts...

As I understand it there are several steps to fully analyze an AST into a typed semantic graph:

1. Convert the AST -this is the raw translation of AST nodes to semantic nodes
2. Run semantic checks 
3. Run type inference
4. Apply the type solution to the graph

We call this entire process `analyze`. Since errors can occur in all of these steps. How do they accrue between the steps? 

NOTE: This issues is purely about the first step but I think I am missing the big picture.

Finally we never cleared up this point of confusion, maybe we need to revisit this issue https://github.com/influxdata/flux/issues/2031 ?

**Comment by jsternberg** [comment]
I've been working on this for a half a day so I'm getting a better idea of the work involved to finish what I am doing. I have `BadStatement` and `BadExpression` and those weren't too much work, but attempting to propagate error nodes to every semantic node has been a lot of work and I have a lot more to do. It has been a lot of work to do even one.

The work that I roughly have to do:

1. Implement something like ast::check for the semantic nodes to extract the errors because they are nested and not easily accessible.
2. Modify the location attribute for each node to be the base node instead.
3. Modify every single reference to the location attribute to now reference the base node because now that contains location information.
4. Also add a way to access the errors in the exact same way. I'm leaning towards modifying the `loc()` function for walking to just access the base node instead, but this isn't my first preference.

I think I'll take this time to try and answer the above questions and see if there's an easier way. I still believe there to be a lot of work left to convert a lot of code and it isn't as mechanical a change as I thought it would be.

> I am not sure I understand your proposal. To me it sounds like you are saying that we would both add the BadExpression nodes and that we would not add them. Can you clarify?

`BadExpression` is the only node I think we should add. At the same time, `BadExpression` would be stripped of the error text and the error text would instead be added to the list of errors just for consistency.

> We need to at least track that it was there, either by inserting a BadStatement or recording the error in some other way. We do not want a broken AST to result in a valid semantic graph.

There may be a disconnect, but I am not sure I understand this. My thought is that we would get something like:

```
pub struct Result {
    pkg: Package,
    errors: Vec<Error>,
}

pub fn convert_with(pkg: ast::Package, fresher: &mut Fresher) -> Result {
    let mut errors = Vec::new();
    let pkg convert_package(pkg, &errors, fresher);
    return Result { pkg, errors };
}
```

The errors would still be available, but the user could just discard them and use the graph as normal. Can you expand on what you mean by a broken AST to a valid semantic graph? To me, if errors are returned and ignored, then that was the decision of the developer and it seems to me like that's what we want because we want the next section of type inference to work.

> Here it sounds like you are suggesting that we add a BadExpression node to the semantic graph. Maybe the point of clarification is what is the difference between what you call an Invalid or Bad node vs what I am calling a BadExpression? Are they the same? Can you maybe be specific in what you mean so we can compare? My concept of a BadExpression in the semantic graph is a direct copy of the AST BadExpression node.

They are the same, but I do not want to perform a direct copy. I want to append an error to the list of errors so it is accessed in the same way as all other errors and then I want to put the equivalent of a `None` node in the place of an expression.

> We call this entire process analyze. Since errors can occur in all of these steps. How do they accrue between the steps?

My thought was just to append errors to the same list so each stage could return errors and we would just concatenate them all together. But, the goal of each stage should be that while they record an error, they try to make as valid a semantic graph as possible so the next stage has the highest percentage chance of not producing a cascading error.

I can probably demonstrate what I mean in a short code snippet if that would help.

**Comment by nathanielc** [comment]
> The errors would still be available, but the user could just discard them and use the graph as normal. Can you expand on what you mean by a broken AST to a valid semantic graph? To me, if errors are returned and ignored, then that was the decision of the developer and it seems to me like that's what we want because we want the next section of type inference to work.

Yes we are on the same page. If we return the errors and they are discarded that is fine. It sounded like not even an error would be reported so I wanted to clarify. Those error do not have to be part of the graph but can be part of the Result. That makes sense to me.

>My thought was just to append errors to the same list so each stage could return errors and we would just concatenate them all together. But, the goal of each stage should be that while they record an error, they try to make as valid a semantic graph as possible so the next stage has the highest percentage chance of not producing a cascading error.

This is what I expected, thanks for confirming.

**Comment by adrian-thurston** [comment]
Might help out a bit if we spend some time on the later stages of the pipeline in the hopes of shedding some light on what form we need to keep things in. In regards to the current work I just have a couple general observations:

1. If something is causing a lot of work we should probably look for a quick approximation or hacky alternative, and failing that, back burner the idea. Some of this stuff could be throw-away work for now and we don't have a clear idea of what we need, so big time investments should probably be avoided.

2. Keeping the errors as close as possible to their original location seems like the right strategy to me, because in the big picture, errors are now something we are trying to provide an implementation for. It's almost as if errors are now part of our actual language, and we are treating them as valid program text through the compilation pipeline. The only difference now is we discard programs with errors just before execution, instead of as they are found.

**Comment by nathanielc** [comment]
The change was reverted because it was not complete. Reopening till we really solve the issue.
