### ISSUE TITLE
10MB mem allocation error on Flux Task

### ISSUE THREAD

**Issue by samhld** [influxdata/flux#2747]
The customer reporting this is Screenscape.  The user is linux.smartplayer@screenscape.com.

The error they're getting is in the UI but seems to be related to Flux, itself.  It is below:

```Error exhausting result iterator; Err: memory allocation limit reached: limit 10000000 bytes, allocated: 10000000, wanted: 32: memory allocation limit reached: limit 10000000 bytes, allocated: 10000000, wanted: 32```

In the last 6 runs of this Task (as of creating this issue), it has error'ed this way 5 times and succeeded once. 

The one successful run took 17 seconds.  This is also far too long given the query and the shape/size of the underlying dataset, especially when we're charing for those seconds.

This customer has given us permission to masquerade into the instance to repro the issues they're facing.   

That said, here is the query being run:
```
option v = {timeRangeStart: -1h, timeRangeStop: now()}
option task = {name: "prod_downsample_wireless", every: 1h}
from(bucket: "prod_device_metrics")
	|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) =>
		(r._measurement == "wireless"))
	|> filter(fn: (r) =>
		(r._field == "level"))
	|> aggregateWindow(every: 5m, fn: mean)
	|> yield(name: "mean")
	|> to(bucket: "prod_device_metrics_downsampled", org: "linux.smartplayer@screenscape.com")
```

Is this an error due to a limit on total volume of the query response or is this error coming from a per-table type of limit?  I ask because this customer really isn't dealing with much data in the grand scheme of things.

**Comment by nathanielc** [comment]
The task is running out of memory, long term we should be able to avoid errors like this and use appropriate techniques to make the query work with limited ram.

In the short term the query is running once an hour and computing the mean per 5m period. You can rewrite the query to run every 5m and that will require less memory to compute as each run will be smaller.
```
option v = {timeRangeStart: -5m, timeRangeStop: now()}
option task = {name: "prod_downsample_wireless", every: 5m}
from(bucket: "prod_device_metrics")
	|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) =>
		(r._measurement == "wireless"))
	|> filter(fn: (r) =>
		(r._field == "level"))
        |> mean()
	|> yield(name: "mean")
	|> to(bucket: "prod_device_metrics_downsampled", org: "linux.smartplayer@screenscape.com")

```

**Comment by samhld** [comment]
@nathanielc thank you -- I will relay the short-term proposal to customer.

**Comment by samhld** [comment]
@nathanielc customer made the change to 5m (from 1h).  The Task took 2s to complete.  The second run of the Task errored with the same panic referred to in this EAR: https://github.com/influxdata/EAR/issues/1449

```
Error exhausting result iterator; Err: panic: runtime error: invalid memory address or nil pointer dereference: panic: runtime error: invalid memory address or nil pointer dereference
```

I noticed the new query still used `|> aggregateWindow()` when it was no longer necessary (or so I think) so I had them run it again without that.  

Results of the _newest_ query are to follow...

**Comment by samhld** [comment]
The newest query:
```
option v = {timeRangeStart: -5m, timeRangeStop: now()}
option task = {name: "prod_downsample_wireless", every: 5m}
from(bucket: "prod_device_metrics")
	|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) =>
		(r._measurement == "wireless"))
	|> filter(fn: (r) =>
		(r._field == "level"))
	|> yield(name: "mean")
	|> to(bucket: "prod_device_metrics_downsampled", org: "linux.smartplayer@screenscape.com")
```

This is still yielding the same nil pointer panic as above.

**Comment by samhld** [comment]
With the mean (should've been there in the first place):
```
still having trouble.  This seems to work in the data explorer, but am getting an error as a task:
```
option v = {timeRangeStart: -5m, timeRangeStop: now()}
option task = {name: "prod_downsample_wireless", every: 5m}
from(bucket: "prod_device_metrics")
	|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
	|> filter(fn: (r) => (r._measurement == "wireless"))
	|> filter(fn: (r) => (r._field == "level"))
	|> mean()
	|> yield(name: "mean")
	|> to(bucket: "prod_device_metrics_downsampled", org: "linux.smartplayer@screenscape.com")
```
error:
Error exhausting result iterator; Err: no time column detected: no time column detected

**Comment by wolffcm** [comment]
@samhld The `no time column detected` is because the `to` function expects data sent to influxdb to have a `_time` column, and the call to `mean` removes all the columns not in the group key, which includes `_time`.

One way to solve this is to take the value of the `_stop` columns and duplicate it as the `_time` column:
```
   ...
   |> mean()
   |> duplicate(column: "_stop", as: "_time")
   ...
```

**Comment by samhld** [comment]
@wolffcm does aggregateWindow() solve for that automatically?  I had them remove that and just use `mean()` as they didn't need any windowing in this specific case.  Adding another line to retain a `_time` column seems like needless effort.  Is there not another way to do this more cleanly?

**Comment by wolffcm** [comment]
@samhld Yes, `aggregateWindow()` literally does the `duplicate` for you, it's defined here:
https://github.com/influxdata/flux/blob/master/stdlib/universe/universe.flux#L111-L116

If you step back and think about what `mean()` does, it's taking several rows, potentially from different points in time, and computing a mean of their `_value` column.  So it makes sense that the output of `mean()` would not have a `_time` column defined.  What time should it put there?  In this case it's up to author of the Flux script to decide, since writing to influxdb requires that each point have a timestamp.

If you want to be more concise (I have not tried this), you could try:
```
... |> aggregateWindow(fn: mean, every: inf)
```
The `inf` means that the "window" would just be the entire range.  This might be a bit less performant than using `mean |> duplicate` though, since `aggregateWindow` will contain calls to `window` that you don't need.

I agree with you though, at first it seems weird to have to put the `_time` column back. Maybe there's a way we can get that behavior as a default somehow in the future.

**Comment by samhld** [comment]
Fair point @wolffcm!
