### ISSUE TITLE
As a user I expect to be able to lookup dynamic keys in a map

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2765]
See https://github.com/influxdata/flux/issues/2757 as a good example of use case for this.

We should provide a way for this to work the _Flux_ way of doing things.

Records in Flux are like structs in other languages and it surprises people that they can't access their fields with a dynamic value.

Some possible solutions that have been proposed:

* Introduce a new `map` type that is an associated map data structure
* Add a function to get a value from a record with a default `getWithDefault : forall [t0, t1] where t0 is Record (r:t0, key: string, default: t1) -> t1` 

There are other solutions I am sure. We should explore various ways of achieving this use case.

**Comment by jsternberg** [comment]
I think a likely good solution to this is to add a function and to point towards the function when someone tries to use a dynamic index. A slight change to the function signature:

```
get : forall [t0, t1] where t0: Row (v: t0, key: string, default: () -> t1) -> t1
```

Type inference should tell us what `t1` is and we can ensure that the value returned matches that type value or it will error. The reason for a function is it will prevent the object from being instantiated when the record is not chosen.

**Comment by nathanielc** [comment]
Thoughts? Should we introduce a new `map` type on which the `get` function can operate? Or should we make `get` work on records directly?

Adding a new type allows for creating future API around the type. Making the function work with records blurs the line even more between the struct map separation. 

What syntax would we use for a `map` type if we created one? Should it even have its own syntax?

Also the Elm language struggled with the same problem. See https://stackoverflow.com/questions/53356457/dict-vs-record-in-elm and https://elm-lang.org/docs/records#comparison-of-records-and-objects for how the clearly document the differences between a typical Javascript object and a record in Elm.

**Comment by nathanielc** [comment]
Elm Dict type docs https://package.elm-lang.org/packages/elm/core/latest/Dict

**Comment by jsternberg** [comment]
I am a bit hesitant on adding a `map` type as I don't really see what it adds. Since values are immutable, at least at the moment, mutating a map to assign a value isn't possible. Additionally, maps aren't typed to a specific value type. That makes me not find a lot of value out of a different map type. I would have to hear how maps are different than records.

I do wonder if there are two separate problems though here. I think I myself am conflating them:

1. It seems like it should be possible to use the `[]` syntax for arbitrary expressions.
2. What should happen when the string used to index doesn't exist in the record/map?

My understanding is the reason why we have the `[]` syntax at all is that it allows us to use the dot syntax with columns that wouldn't be representable in flux syntax. This makes sense. The reason why we are strict about using strings is so that `r.badtag` can be caught at type checking time rather than be a runtime error.

I do wonder if we can potentially relax that condition and allow index expressions to work on record types rather than only array types. If you attempt to access a key that doesn't exist, it returns an error. We would then have the `get` function be the "safe access" for dynamic lookup as it would allow you to specify a default. I think this is a small change to the type system and the runtime and you get "dynamic lookup".

**Comment by markddavidoff** [comment]
My main use case would be to have a map with some external info or readable name, where i can automatically convert certain values based on their field keys. I can write a function to do this but within the function i end up with a long if else block. It is not convenient for me to store the data as a record as it is unique to the way the data will be transformed for output and only used to say send an alert or http request. It allows a separation of data and buisness logic. 

If there could be some additional convenince methods to allow using records in this way easily i think it could also fulfill the requirement but using a map like the above is definitely what i expect just by looking at it, having used it in other languages.

**Comment by jlapacik** [comment]
I definitely think the confusion comes from the `[]` syntax. Records are equivalent to anonymous struct types in other languages. `r.label` should be the default standard for accessing record labels. Unfortunately due to the fact that in influxdb an arbitrary string can be a tag key, the `r["label"]` syntax is probably here to stay.

I don't agree with a `get` function that operates on records types. Records are a static datatype and they should remain that way. If a dynamic datatype is needed (and I do agree it would be useful) then it should be in addition to record types. My proposal would be for a new builtin map type along with a map package
```
package map

builtin from: (values: [(T, S)]) => map { T, S } where T: Comparable

builtin get : (key: T, from: map { T, S }, default: S) => S where T: Comparable

builtin insert: (key: T, value: S, into: map { T, S }) => map { T, S } where T: Comparable
```

Unification of map types is as follows:

    map { T, S } = map { A, B } => T = A, S = B

One down side to this approach is that `map.get(key: "a", from: m, default: -1)` is not as concise as `m["a"]`. I'd much prefer the latter. That however would require adding a sum type to the Flux language so that `m["a"]` returned something along the lines of Ocaml's option type
```Ocaml
type `a option = Some of `a | None
```

**Comment by jsternberg** [comment]
@jlapacik I guess one thing I don't understand is how adding the capability for dynamic access to the existing records would functionally be different than the work required to create a new type and new access. To clarify, I haven't seen any requirement to create a dynamic datatype or to convert record into a dynamic datatype. What I have seen is a request to allow dynamic access to a value in a record. I also haven't seen a requirement to provide a fallback default value although I do think we want to enable that as a workflow.

I agree that `r.label` is the default standard for accessing record labels and that `r["label"]` should also return an error when the value is not available. This isn't universally true but we should try to fix that. What I don't understand is why `r[varname]` shouldn't be allowed with the same behavior. It seems the equivalent of making reflection on the type easy and it seems functionally easier than creating a new type in the type system that would function mostly identically.

Right now we have `MemberExpression` and `IndexExpression`. When an access is done with anything that's not a string, it's considered an `IndexExpression` and this is to allow dynamic values to be used for accessing an array index. What stops us from making it so index expressions can be used on both records and arrays? This isn't a proposal to change the record to a dynamic datatype. We're referring to dynamic access and not a dynamic type. I haven't seen any request that the record be capable of supporting insert and I haven't seen a requirement to type the object with a type for the key and a type for the value.

There's another issue that I'm afraid we might be conflating with this one that's very type-system specific. The `rename()` function takes `columns` as a parameter and it's mostly a `map[string]string`. We can't represent that type in the type system so we have to use `t0` and check the types at runtime which is non-desirable. It would be nice, as part of the type system, to say "This takes a map type and the key is a string and the value is a string." I think that's a separate issue though and it isn't related to whether or not dynamic lookups should be possible.

**Comment by jlapacik** [comment]
@jsternberg my argument is that dynamic lookup doesn't make sense for a record type because records are static. Given a record type and a source location, you know exactly the labels of that particular record at that location. There are certain flux functions that invalidate this assertion, but I don't think that's an argument for supporting dynamic record access.

Because Flux is completely type inferred, the syntax must be completely unambiguous. Right now there's no ambiguity, `a[idx]` means that `a` is an array and `idx` is an integer. If `a` could also be a record there would be ambiguity. Now type constraints can remove this ambiguity, but there's still the issue of what type `a[idx]` is. If `idx` is a dynamic value, it's impossible to be able to determine the type of `a[idx]` statically. If we want to continue to support this type of inference, then we must have a separate map type for dynamic key lookup.
