### ISSUE TITLE
Delete Go Parser

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#2794]
Now that we have the Rust parser and Formatter we want to delete the Go versions so as to not expose older broken functionality. 

The uses of the Go Parser are already all using the Rust version of the parser. ~The Formatter may have a few uses elsewhere.~

Note we are going to remove the Formatter as part of a different issue.

**Comment by wolffcm** [comment]
There are some functions for parsing durations that need to still exist after deleting the Go parser.

**Comment by wolffcm** [comment]
If there are uses of the Go formatter, look into using the Rust parser instead. If it's difficult file an other issue to do it.

**Comment by jsternberg** [comment]
It's fine for us to modify the formatter to use the Rust formatter, but we need to move the function invocation from the AST package. The `ast` package cannot import the libflux package as it cannot have a C dependency.

So we're going to have to create a new package probably like this:

1. Create a new `github.com/influxdata/flux/ast/format` and `github.com/influxdata/flux/ast/internal/format` package.
2. Copy the current format implementation to the internal package.
3. Make it so that both of the above packages reference the same internal implementation. Mark the current function as deprecated.
4. Perform a release.
5. Modify downstream dependencies to use the new package.
6. Remove the `ast.Format()` method from the `ast` package and the internal package. Move the implementation to the new location and change it to use Rust if it isn't already.

This may seem complex and it may seem easier to just break it and fix the downstream dependencies during the release, but I'd like us to get into the habit of doing this kind of thing when making breaking API changes. Releases shouldn't require refactors to make them work.

**Comment by fchikwekwe** [comment]
Places where the Go parser is still referenced: 

- `ast/flatbuffers_test.go TestRoundTrip`
- `libflux/go/libflux/bench_test.go GoParse`
- `libflux/go/libflux/parser_test.go TestASTPkg_MarshalJSON`

And then of course the parser references itself in some places.

**Comment by wolffcm** [comment]
As far as `ast/flatbuffers_test.go TestRoundTrip` goes, the Go parser is used to create the expected value for an AST that is created like this 
```
parse in Rust -> seralized in Rust to FB -> deserialize from FB in Go
```
This test was intended to show that the AST we get from Rust including flatbuffers serde is nearly same as what we would get from the old Go parser, with only some trivial differences. However we've been using this codepath in production for several months now, so I think we're safe on this front.

We could delete this test and not lose any coverage. This is because we have tests in Rust the demonstrate that the AST was serialized as expected.

**Comment by nathanielc** [comment]
Note this benchmark can also be deleted `libflux/go/libflux/bench_test.go GoParse` as it was to benchmark the Go parser against the Rust parser. We no longer need that comparison.

**Comment by nathanielc** [comment]
DOD:

- The Go parser is deleted
- Test coverage is updated to reflect that we only have a single parser
- InfluxDB and IDPE are updated accordingly

**Comment by scbrickley** [comment]
# Update

After making [this PR](https://github.com/influxdata/flux/pull/3142), and and trying to test it out in `influxdb`, I had a few failing tests that all output something like the following: 

```
query/mock/service.go:65:5: cannot use (*Query)(nil) (type *Query) as type flux.Query in assignment:
        *Query does not implement flux.Query (missing ProfilerResults method)
```

It looks like @rockstar had the same issues and addressed them [here](https://github.com/influxdata/influxdb/pull/19427). However, when I pointed that branch to my local `flux` branch, I had completely different tests fail. The same tests fail even if I point that branch back at `flux/master`. To further complicate the issue, it looks like those tests all pass in CI for Paul's PR.

# To replicate failing tests

- checkout `scb/delete-go-parser` in the `flux` repo.
- checkout `flux-staging/v0.82.2` in influxdb, and add `replace github.com/influxdata/flux => /path/to/local/flux/repo` to `go.mod`
- run `go test -v ./...` from the root of `influxdb`

There should be a a few failing tests that output something similar to this:

```
...
--- FAIL: TestStorageReader_ReadWindowFirstCreateEmpty (0.09s)
    table_test.go:59: error opening TSI1 index: open /var/folders/96/t9kd2yfd70b9r4vcmwcgt1j00000gn/T/storage-flux-test104210576/engine/index/0/MANIFEST: too many open files
=== RUN   TestStorageReader_WindowFirstOffsetCreateEmpty
--- FAIL: TestStorageReader_WindowFirstOffsetCreateEmpty (0.15s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
=== RUN   TestStorageReader_WindowSumOffsetCreateEmpty
--- FAIL: TestStorageReader_WindowSumOffsetCreateEmpty (0.22s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
=== RUN   TestStorageReader_ReadWindowFirstTimeColumn
--- FAIL: TestStorageReader_ReadWindowFirstTimeColumn (0.12s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
=== RUN   TestStorageReader_WindowFirstOffsetTimeColumn
--- FAIL: TestStorageReader_WindowFirstOffsetTimeColumn (0.12s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
=== RUN   TestStorageReader_WindowSumOffsetTimeColumn
--- FAIL: TestStorageReader_WindowSumOffsetTimeColumn (0.18s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
=== RUN   TestStorageReader_EmptyTableNoEmptyWindows
--- FAIL: TestStorageReader_EmptyTableNoEmptyWindows (0.12s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
=== RUN   TestStorageReader_ReadGroup
--- FAIL: TestStorageReader_ReadGroup (0.11s)
    table_test.go:59: error opening TSI1 index: fcntl: too many open files
FAIL
FAIL	github.com/influxdata/influxdb/v2/storage/flux	5.681s
...
--- PASS: TestVerifies_Valid (0.09s)
=== RUN   TestVerifies_Invalid
--- PASS: TestVerifies_Invalid (0.12s)
PASS
ok  	github.com/influxdata/influxdb/v2/tsdb/seriesfile	2.172s
Run go generate to download testdata directory.
FAIL	github.com/influxdata/influxdb/v2/tsdb/tsi1	0.193s
=== RUN   TestDescendingCursor_SinglePointStartTime
=== RUN   TestDescendingCursor_SinglePointStartTime/cache
...
FAIL
```
