### ISSUE TITLE
Investigate adding a ProcessTableBuffer method to the execution engine

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2827]
Investigate adding `ProcessTableBuffer` and `FinishSeries` messages to the execution engine.

At the moment, the engine contains these messages and what they act on:

* Process (Table)
* Finish (Stream)
* UpdateWatermark (Stream)
* UpdateProcessingTime (Stream)

Missing is a way to process an individual buffer from a table and a way to signify that only one series has ended. This makes implementing narrow transformations and streaming them very difficult and it requires working around the engine. The only node that is correctly able to implement these without launching additional goroutines are sources which natively support this behavior.

The canonical example for this would be `filter()`. The filter function does not need anything other than the current buffer to process the current buffer and to output a transformed buffer.

At the moment, we work around this by using [passthrough dataset](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/execute?tab=doc#PassthroughDataset) and [table.Stream](https://pkg.go.dev/github.com/influxdata/flux@v0.67.0/internal/execute/table?tab=doc#StreamWithContext) as an experimental way of getting the same effect. The problem is these two really work around the existing system and stream spawns its own goroutines rather than work within the system's constraints.

This issue is about experimenting with adding an API for single-buffer transformations and how to add that API to the current engine. The engine would need to be able to convert between these different APIs since there will be some transformations that will only support reading from one table at a time and some that would be able to process a single buffer for a series at a time.

**Comment by nathanielc** [comment]
I have been thinking about this idea of passing individual Table Buffers through the transformation edges.

I think this is equivalent to passing Table using Accumulating mode. Here is why I think that:

The current semantics are that passing a Table means that the entire table has been provided. The able may be split into multiple buffers but it represents the entire table. The downside to this is if you have one buffer ready to be passed on you have to wait until you know all buffers are ready otherwise you break the semantics. 

The semantics that passing a Table means its the entire table are specific to the Discarding Mode. If we implement accumulating mode then the semantics are different. Passing the same Table multiple times is effectively the same as passing the same table in multiple buffers. Using accumulating mode we can do the same thing as passing multiple buffers.

But what does this mean for transformations, do the need to implement a Process method for each mode? Is the mode passed to the Process method? Do we treat different modes a different physical transformations that only know how to operate in one mode and then the planner pick which one to use?

I don't have the answers to those questions, I just thought it was interesting to observe that passing partial tables is equivalent (at least logically) to passing Tables in accumulating mode.

**Comment by jsternberg** [comment]
This is now called `table.Chunk` and is also done.
