### ISSUE TITLE
Conditionals in filters stop push downs

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#2874]
Changing the order of the filters in this query causes drastically different query performance. As a user, I would expect Flux to be smart enough to order these filters correctly.

Runtime: ~20s
```
from(bucket: "telegraf_1m")
	|> range(start: -6h, stop: now())
	|> filter(fn: (r) =>
		(if 1 == 2 then true
     else r["host"] == "bigsur.prod"))
  |> filter(fn: (r) =>
		(r["_measurement"] == "cpu"))
  |> filter(fn: (r) =>
		(r["_field"] == "usage_user" and r["cpu"] == "cpu-total"))
	|> filter(fn: (r) =>
		(if exists r["aggregate"] then r["aggregate"] =~ /^mean$/ else true))
```

Moving the first conditional filter lower, i see:

Runtime: ~1.2s
```
from(bucket: "telegraf_1m")
	|> range(start: -6h, stop: now())
	|> filter(fn: (r) =>
		(r["_measurement"] == "cpu"))
  |> filter(fn: (r) =>
		(if 1 == 2 then true
     else r["host"] == "bigsur.prod"))
  |> filter(fn: (r) =>
		(r["_field"] == "usage_user" and r["cpu"] == "cpu-total"))
	|> filter(fn: (r) =>
		(if exists r["aggregate"] then r["aggregate"] =~ /^mean$/ else true))
```

And lower still, i get

Runtime: 0.35s
```
from(bucket: "telegraf_1m")
	|> range(start: -6h, stop: now())
	|> filter(fn: (r) =>
		(r["_measurement"] == "cpu"))
  |> filter(fn: (r) =>
		(r["_field"] == "usage_user" and r["cpu"] == "cpu-total"))
	|> filter(fn: (r) =>
		(if 1 == 2 then true
     else r["host"] == "bigsur.prod"))
  |> filter(fn: (r) =>
		(if exists r["aggregate"] then r["aggregate"] =~ /^mean$/ else true))
```

**Comment by russorat** [comment]
Combining all the individual filters into a single call has the performance of the ordering:

Runtime: ~0.30s
```
from(bucket: "telegraf_1m")
	|> range(start: -6h, stop: now())
	|> filter(fn: (r) => (if 1 == 2 then true else r["host"] == "bigsur.prod") and (r["_measurement"] == "cpu") and (r["_field"] == "usage_user" and r["cpu"] == "cpu-total") and (if exists r["aggregate"] then r["aggregate"] =~ /^mean$/ else true))
```

**Comment by wolffcm** [comment]
Currently we have some work in progress that @yuktarakesh is working on so that when we have filters that we can't push down (like `if/then/else`) that it doesn't block the other filters from being evaluated in the storage tier:
https://github.com/influxdata/flux/issues/2947

To further improve performance of the above query, I see few ways to do it:
- It should be possible to simplify the conditional to just one of its branches if its condition doesn't actually access streaming data. I.e., just transform `(if 1 == 2 then true else r["host"] == "bigsur.prod"))` to `r["host"] == "bigsur.prod"` before we plan the query, so that the filter can be pushed down.
- For the general case for filters like `(r) => if r.region != "east" then true else r.city == "nyc"` we'd need to think about when pushing down conditionals makes sense to do. I think that storage still uses InfluxQL AST for its predicates, so I'm not sure how much work that would be.
