### ISSUE TITLE
Categorize errors in the date package and update to deal with null values

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#2877]
The date package returns an error using `fmt.Errorf` and it should output it with `errors.Newf(codes.FailedPrecondition, ...)`. It also doesn't handle null values. Both of these should be fixed.

**Comment by rockstar** [comment]
The allowance of `nil` values _feels_ problematic to me, because the user can't specify those null values, but may get an error that doesn't make sense to them. Either they get "this value was null when it shouldn't have been" or they get "unknown + 1 = unknown," neither of which is going make sense to them.

I sat down to write a test for this, to reproduce a panic in dates due to a nil value. Even our testing harness doesn't really provide a concession for this (and I assert that maybe it shouldn't) but a little bit of exploring provides *a* way to do this. Then the fix is to check if the value is `nil` before operating on it. But then how many places are you going to have to go back and check if something is `nil`, particularly in a case where the user didn't specify that `nil` value, because the date package is definitely not the only place this could happen.

This is all to say, this bug is easily addressable, but is only a band-aid solution, and we need something that will work better long-term. My suggestion is to not allow `nil` values at all.
