### ISSUE TITLE
Guiding the user to build a valid query

### ISSUE THREAD

**Issue by desa** [influxdata/flux#2954]
In the UI, we're trying to do more to guide the user towards building a valid query. Specifically, we'd like to allow the user to select aggregates that make sense for the field types. If the user selects a field in the query builder that is a string we'd like to show aggregates that make sense like `first`,`last`, and `count`.

Link https://github.com/influxdata/flux/issues/2938

**Comment by nathanielc** [comment]
@desa Are you thinking this experience is part of the query builder workflow or more generally as part of the Flux script editor workflow?

If its part of the query builder then I think it makes sense to add a new meta query (or improve and existing one) to report the type of fields. This is because the query builder is very specific to the influxdb source and it will be a good path to a quick win. 

If this is part of the Flux script editor I think we should think of it in terms of a dynamic completion that the LSP provides. The way this works currrently is you can provide the LSP with connection details to influxdb and it can run some meta queries to determine buckets and these kinds of things. Then it makes auto-completion suggestions from within the LSP mechanisms. This method would also need a meta query to get the field types.

In either case it seems like we need to expose the field types via a query.

@bthesorceror Thoughts on using dynamic completions from the LSP to provide type aware completions based on the schema of the data?

**Comment by desa** [comment]
> Are you thinking this experience is part of the query builder workflow or more generally as part of the Flux script editor workflow?

The current plan is to get it set up for query builder, but it would also be cool to have it in the lsp.
