### ISSUE TITLE
Investigate flux end-to-end tests' flakiness

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2958]
We would like to understand what's going on with flaky flux end to end tests. 

One way to do this is to create a circleCI job that runs our CI tests on a schedule, or use `cpulimit` on your local machine.

**Comment by jsternberg** [comment]
I believe I can explain why this happens now. There seem to be multiple subsystems causing some weird and possibly undefined or unexpected behavior.

I tested this by modifying the test harness to run the first of the three queries and then have it just immediately try to read the data and do nothing else. If it was able to read data, then the data had been written and the test should succeed. I then modified various parts of the system to print statements. What I found was decently surprising.

It appears that the first query does successfully write the points and it does not cancel the write. An error from the first script does not prevent it from writing data as I had guessed. But, the write seems to sometimes happen _after_ the query returns. So you can end up with the following flow.

1. Run query.
2. Failure happens and query is "ended" on the client.
3. Write of data happens.
4. The second or third query is executed.

In some circumstances, 3 and 4 get swapped and then you have a race condition. This appears to be because the csv encoder abandons writing more of the response when it encounters an error. So when it is encoding the csv response it is receiving by reading the tables, it won't always read all of the tables when an error occurs (such as from `assertEmpty`). The csv encoder will stop reading results after it encounters an error and then it will asynchronously cancel the query and just leave it to be reaped on its own. So when the http response has finished, the query can still be running in the background.

This causes the race condition and why it sometimes succeeds. When the `to()` function writes the data before the second or third request, then the test will succeed. In times when it doesn't, such as when the goroutine for the `to()` function just didn't get to run yet, it will fail. This can be confirmed by either forcing the csv encoder to read all of the results on an error or by adding a sleep to the test harness.

I think a behavior that's currently undefined is "what is guaranteed to happen from side effects on a query's failure or cancellation?" It's unclear to me if this is expected or unexpected behavior.

One thing is clear to me though is that I think I understand this well enough to say I believe https://github.com/influxdata/influxdb/pull/18898 will remove the flakiness because it will avoid ever triggering the undefined behavior.

**Comment by adrian-thurston** [comment]
@jsternberg I like this explanation and decided to investigate it a bit, but there is one fact that I can't reconcile with the explanation ... in the first pass, when the tests are run and the data is to be written, there is no actual failure induced by the `assertEmpty`. The test case is changed so that `assertEmpty` doesn't execute. It's only in the second run.

**Comment by jsternberg** [comment]
I'll investigate that. For my tests, I changed `TestingInspectCalls` to `TestingRunCalls` to reduce the amount of output. I'm going to check to see if there's a difference.

**Comment by jsternberg** [comment]
This requires more investigation but I need to switch to work on another project temporarily. Unassigning myself in case someone else has the bandwidth to research this more.

**Comment by adrian-thurston** [comment]
Turns out use of `experimental.chain` does not eliminate the flaky test case runs, just reduces them. If we alter the test harness to 
1. Write using `to()`
2. Run `from(bucket)` and send that to the test case's `fn()` (necessary since it has the correct range) we still occasionally find no data produced. It appears that the `from()` following the `to()` will occasionally come up empty.

**Comment by adrian-thurston** [comment]
Quite certain now that the following issue is the root cause of our flaky tests.

https://github.com/influxdata/influxdb/issues/19017

**Comment by adrian-thurston** [comment]
Verified this eliminates the spurrious failures from the flux end-to-end tests that are of the form "got was empty".

It is still possible for end-to-end tests to fail due to the race for the NATs port. In this case end-to-end tests will race with launcher tests to grab a port. They don't race internally, since they deliberately serialize.

https://github.com/influxdata/influxdb/blob/master/cmd/influxd/launcher/launcher.go#L850
