### ISSUE TITLE
Selector transformations do not preserve empty tables (in some cases)

### ISSUE THREAD

**Issue by francky-powerfactors** [influxdata/flux#2967]
This is more of a question than an actual bug since I don't know what is the expected behavior. I asked the question in the influx slack channel and someone suggested I open an issue.

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I'm using the current flux script
```
import "csv"

csvData = "
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,string,string,double
#group,false,false,false,false,false,false,false,false
#default,,,,,,,,
,result,table,_start,_stop,_time,region,host,_value
,mean,0,2020-05-08T20:50:00Z,2020-05-08T20:51:00Z,2020-05-08T20:50:00Z,east,A,15.43
,mean,0,2020-05-08T20:50:00Z,2020-05-08T20:51:00Z,2020-05-08T20:50:20Z,east,B,59.25
,mean,0,2020-05-08T20:50:00Z,2020-05-08T20:51:00Z,2020-05-08T20:50:40Z,east,C,52.62
"
csv.from(csv: csvData)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  //|> aggregateWindow(every: 10s, createEmpty: true, fn: (column, tables=<-) =>
      //tables
        // |> last() or first()
        //|> mean())
  |> window(every: 10s, createEmpty: true)
  //|> map(fn: (r) => r)
```
2. set your date ranges from 2020-05-08T20:00:00 to 2020-05-08T21:00:00
3. running the script as is returns you all the windows, even the empty ones in the [v.timeRangeStart, v.timeRangeStop] range
4. if you uncomment the `map(fn: (r) => r)` function call, the empty window are removed

Also, the same goes for the `aggregateWindow` function. Depending on the function you select as the aggregating function the empty windows will be there, or not. For instance, using the `mean` function leaves the empty windows whereas using the `first` or `last` functions removes the empty windows.

__Expected behavior:__
Regardless of the aggregating function used, the empty windows should be present.

__Actual behavior:__
Sometimes the empty windows are removed from the output, sometimes they are in the output. It all depends on the aggregating function used.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
**Linux 4.15.0-1089-azure x86_64**

* InfluxDB version: Run `influxd version` and copy the output here
**InfluxDB 2.0.0-beta.13 (git: 86796ddf2d) build_date: 2020-07-07T13:01:06Z**

* Other relevant environment details: Container runtime, disk info, etc
I'm running influxdb in a kubernetes cluster, version 1.16.9

**Comment by sanderson** [comment]
@francky-powerfactors We may need to update the title of the issue. This isn't an issue with the behavior of `aggregateWindow()` and `window()` as much as it is an issue with the aggregate and selector transformations used. `aggregateWindow()` is a helper transformation that windows data, then applies an aggregate transformation. You can see the transformation definition [here](https://github.com/influxdata/flux/blob/master/stdlib/universe/universe.flux#L110-L118).

`window()` does preserve the empty tables, but aggregate and selector transformations behave differently. [Aggregate transformations](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/aggregates/) aggregate all values in a table and return a table with a single row containing the aggregate value. With empty tables, aggregate transformations return a single-row table with a `null` aggregate value. 

[Selector transformations](https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/selectors/) return one or more **unmodified** rows from each input table. If there aren't any rows in the table, selector transformations drop the table.

The same applies to your `map(fn: (r) => r)` call. If there isn't a row to map, `map()` won't build the new table.

I think there are some potential solutions here, but the Flux engineers will need to weigh in:

1. Update selector transformations to return empty tables if they exist. This could be done with a new parameter on each transformation.
2. Update map with the option to return empty tables if they exist. Again, this could done with a new parameter.
3. Update the documentation to clearly describe the behavior of these transformations.

Also, because this is a Flux-specific issue, I'm going to transfer it to the Flux repo.

**Comment by francky-powerfactors** [comment]
I agree with all of your comments.

I'll update the title to make is more specific to selector transformation behavior regarding empty tables.

Thanks for the quick reply.

**Comment by ivankudibal** [comment]
I can also reproduce this behavior, on min and max functions that are used as inner functions inside of the aggregateWindow function.

I also believe that removing empty windows is not a good idea. Because the charts in the UI then render differently.

This is the `mean` inner function and the chart is rendered correctly:

Flux 1:
```
from(bucket: v.bucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "system")
  |> filter(fn: (r) => r["host"] == v.linux_host)
  |> filter(fn: (r) => r._field == "load1" or r._field == "load5" or r._field == "load15")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: true)
```
Screenshot 1:
![image](https://user-images.githubusercontent.com/8028110/98141989-8a25f280-1ec7-11eb-8951-a71470e2527f.png)



Flux 2 (max):
```
from(bucket: v.bucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "system")
  |> filter(fn: (r) => r["host"] == v.linux_host)
  |> filter(fn: (r) => r._field == "load1" or r._field == "load5" or r._field == "load15")
  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: true)
```

Screenshot 2: chart is missing data in the query result (my rpi was simply turned off):

![image](https://user-images.githubusercontent.com/8028110/98142193-c6f1e980-1ec7-11eb-910b-0c0bf8a1aec8.png)


Solution proposed: The mean function does return all data correctly (because null is correct value too), and min, max and others should be adjusted according to behavior that is implemented in the mean.

**Comment by jsternberg** [comment]
We've fixed this to cause selectors used in `aggregateWindow()` to behave the same as other aggregates. This change only applies to uses of `aggregateWindow()` and won't affect selector behavior in other circumstances.

https://github.com/influxdata/flux/pull/3733
