### ISSUE TITLE
Add ability to inspect query log from within a pipeline test

### ISSUE THREAD

**Issue by fchikwekwe** [influxdata/flux#2976]
There are some cases where planner rule changes will not produce storage metrics to confirm that they have taken effect. 

Once the query log is logging the query plan, then we should add an implementation of the query log to our pipeline test harness so that we can inspect the query log for changes to the plan in order to make sure that updates to the planner have taken effect.

**Comment by nathanielc** [comment]
We decided to go a different direction. Instead of exposing the plan directly to the Flux script, we define options that can declare attributes that we expect the plan to have and then we implement those check in the test harness. This way the complexity of the comparison remain in the test harness while the test cases remain simple.
