### ISSUE TITLE
in range(), first takes integers, which behave unpredictably

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/flux#3090]
According to the documentation, range(), first can take a duration/time: https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/built-in/transformations/range/#start

However, I can submit the following:

```
from(bucket: "idping")
|> range(start: 0)
```

This retrieves the last few results, sometimes 1, sometimes a few.

```
from(bucket: "idping")
|> range(start: -1)
```
That seems behave the same as start: -1h.

```
from(bucket: "idping")
|> range(start: 1)
```
Sometimes results in an error, sometimes seems the same as using -1.

I would expect a type error, because I am supplying an int instead of duration. 

The documentation for durations does not say anything about automatic conversion: https://v2.docs.influxdata.com/v2.0/reference/flux/language/types/

**Comment by nathanielc** [comment]
This behavior is technically supported but we generally don't like it in hind sight. You can find some discussion about this here https://github.com/influxdata/flux/pull/2951#issuecomment-652549800 where we tried to remove this behavior. We looked into it  but found it was used in the wild so decided it was best not to break existing queries. 

The meaning of `range(start: 0)` is that 0 represents a number of nanoseconds since the unix epoch. 

That said we think it should be possible to deprecate this behavior using an AST rewriter for backwards compatibility but discourage it going forward.

**Comment by ChitlangeSahas** [comment]
#3103 We reverted that behavior. Sorry about the inconvenience.

**Comment by rickspencer3** [comment]
what does range(start: 1) mean?

**Comment by rickspencer3** [comment]
Ok, it appears that integers are an accepted data type, and represent nanoseconds relative to the unix epoch. We should at least update the documentation to reflect that.

**Comment by jsternberg** [comment]
As an aside, the current behavior is number of **seconds** since the unix epoch: https://github.com/influxdata/flux/blob/63ca1ccce0c0794c29a65b6f1ad82f51f6a051c5/compile.go#L381

I think that the integer syntax is useful because when you use write protocol to write data you write as an integer with the nanosecond relative to the epoch. That is _not_ the current behavior. If we keep this, we likely need to fix that behavior as I find it personally confusing.
