### ISSUE TITLE
Separate loading and reading storage in Flux end to end tests

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3123]
Flux's `testing` package has two options that allow tests to work with input and expected data:

https://github.com/influxdata/flux/blob/5e38d5fd3fe057f91b35f1b825521760991156da/stdlib/testing/testing.flux#L9-L10

Typically `loadStorage` is used to read input data to the test (usually called `inData` in test scripts) and `loadMem` is used to produce the expected result. In OSS `loadStorage` is [overridden](https://github.com/influxdata/influxdb/blob/ce443f832e87484582eb3d5c78c812c683299a06/query/stdlib/testing/end_to_end_test.go#L161-L166) to:
```
option testing.loadStorage = (csv) => {
	return experimental.chain(
		first:  c.from(csv: csv) |> to(bucket: bucket, org: org),
		second: from(bucket:bucket)
	)
}
```
This way when a test script uses `loadStorage`, the data is first loaded into influxdb with `to()` and is read back with `from()`. This works fine much of the time, but sometimes we want to load the data into storage once, and read it back several times. #3057 is an example of this.

We might consider refactoring our the testing package to have three options:
- `loadStorage`. Load the data into storage, but don't use the loaded data. In the `flux` repo, this would be a no-op, in `influxdb` it would be something like `csv.from() |> to() |> discard()`, if we had a `discard()` function that just consumes the data without producing any output.
- `readStorage`. In `flux`, this would just be `csv.from()`, but in influxdb it would be `influxdb.from(...)`.
- `loadMem` could stay the same. (I feel like this would be better renamed as `getExpected` though)

**Comment by nathanielc** [comment]
I like this a lot, a few thoughts/questions:

Should we reconsider the `loadMem` abstraction entirely? Could we not use `csv.from` in every case we use `loadMem`? If we did what do we loose?


For the `discard` function is the idea that it has an empty return type? I don't quite follow why the `to` function would need to be followed by a `discard` function? Meaning if you want to make it so that `loadStorage` doesn't return any data would this be sufficient?

```
loadStorage = (csv) => {
    csv.from(csv:csv) |> to()
    return {}
}
```

If we have both `loadStroage` and `readStorage` would we still have a common function that wraps them with `chain`?

```
load = (csv) => experimental.chain(
    first: loadStorage(csv:csv)
    second: readStorage()
)
```

Finally what do you pass into `readStorage` the data? Or a bucket name? Or maybe even the return of the `loadStorage` call?

**Comment by wolffcm** [comment]
> Should we reconsider the loadMem abstraction entirely? Could we not use csv.from in every case we use loadMem? If we did what do we lose?

I tend to agree that we would not lose much. One thing to consider is now that we have `array.from()` it would be nice to be able to start using it in these tests. It is so much easier to author tables compared to CSV.

> For the discard function is the idea that it has an empty return type? I don't quite follow why the to function would need to be followed by a discard function? Meaning if you want to make it so that loadStorage doesn't return any data would this be sufficient?
> loadStorage = (csv) => { csv.from(csv:csv) |> to()    return {}  }

This will still attempt to create a `_result` won't it? Or maybe not. I seem to recall that we don't insert an implicit `yield` if we have a terminal `to()` but I'd have to check.

> If we have both loadStroage and readStorage would we still have a common function that wraps them with chain?

I think we would need add a `load` field to the test object, and update `testing.inspect` to look like this? We need to ensure that `loadStorage` is run exactly once to completion before running the test case which may read the data several times.
```
inspect = (case) => {
    tc = case()
    got = experimental.chain(first: tc.load, second: tc.input |> tc.fn())
    dif = got |> diff(want: tc.want)
    return {
        fn:    tc.fn,
        input: tc.input,
        want:  tc.want |> yield(name: "want"),
        got:   got |> yield(name: "got"),
        diff:  dif |> yield(name: "diff"),
    }
}
```
Or maybe instead of `inspect` providing input to the test function, it could be up to `tc.fn()` to call `testing.readStorage` itself?

> Finally what do you pass into readStorage the data? Or a bucket name? Or maybe even the return of the loadStorage call?

Currently what we do in OSS is reference an option called `bucket` that is defined in a separate AST File, and that controls where the data piped to `to()` goes. I guess we could continue to do the same thing.

**Comment by nathanielc** [comment]
> One thing to consider is now that we have array.from() it would be nice to be able to start using it in these tests. It is so much easier to author tables compared to CSV.

+100 We should not force csv or any other way of encoding data for the test cases. The API should work with plain tables. Perhaps loadStorage should just take tables instead as well?


> This will still attempt to create a _result won't it? Or maybe not. I seem to recall that we don't insert an implicit yield if we have a terminal to() but I'd have to check.

I see its about suppressing the result to the client. We need a fix for that anyway I have it on my TODO to create an issue around it. I'll do that now and link here.

As for the inspect function and other design I feel that our current abstractions are too specific to past needs and not scaling well.  For example it would be nice to be able to create a test case that operates on basic Flux values instead of only tables. 

What if we took one more step back and defined a test case as a function the must run to completion without erroring. And then we build the `inspect` `run` helper functions to aid for the table based tests.


```
import "testing"

test add = () => {
  two = 1 + 1
  assertEqual(want: 2, got: two)
}

test filter = () => {
    testing.runStorageTest(case: {
        fn: filter,
        input: array.from(rows:...),
        want: array.from(rows:...),
    }).diff |> assertEmpty()
}
```

```
package testing


runStorageTest = (case) => {
    tc = case()
    input =  tc.input |> loadStorage()
    got =  readStorage(data: input) |> tc.fn()
    dif = got |> diff(want: tc.want)
    return {
        fn:    tc.fn,
        input: tc.input,
        want:  tc.want |> yield(name: "want"),
        got:   got |> yield(name: "got"),
        diff:  dif |> yield(name: "diff"),
    }
}


This kind of design would allow for writing tests that we do not intend to pass on InfluxDB without having to skip them because we can use a different set of test helper functions.  

These are just thoughts there are lots of details I am sure I am glossing over.
