### ISSUE TITLE
Exponent Operator always returns float

### ISSUE THREAD

**Issue by Bolladeen** [influxdata/flux#3196]
Currently, the exponent operator returns values of type float even if both arguments to the operator are of integer types. For example: `5^1` would return `5` as a float casted type. With the current setup of throwing type mismatch errors if parameters of differing types are operated on by multiplicative operators, code like `5^1*5` would throw an error as multiplying a float with an int is considered a type mismatch error.

**Comment by nathanielc** [comment]
Thanks for this issue! This is a case of Go's behavior leaking into Flux. In Go its not possible to do exponentiation with integers. See https://groups.google.com/g/golang-nuts/c/5V-k2GctXY8 which is an old discussion on this topic. It points to a few different way we could implement exponentiation using integers instead of floats. For example https://en.wikipedia.org/wiki/Exponentiation_by_squaring
