### ISSUE TITLE
Dictionary literals

### ISSUE THREAD

**Issue by jlapacik** [influxdata/flux#3321]
Instead of using `dict.fromList` to create a dictionary from a list, we'd like to have the following syntax for dictionary literals
```
| "a": 1, "b": 2, "c": 3 |
```

This requires

1. New `DictionaryLiteral` AST and semantic nodes
2. Update the parser to recognize the new syntax
3. Generate new type constraints for dictionary literals during type inference
4. Update the interpreter and compiler packages to be able to evaluate dictionary literals

Note, there's no need to update any of the type system's unification rules. This will have already been done in https://github.com/influxdata/flux/issues/3320.

Also note that
```
| "a": 1, "b": 2 |
```

is equivalent to
```
dict.fromList(pairs: [{key: "a", value: 1}, {key: "b", value: 2}])
```

It would be nice if this new syntax for dictionary literals was really just syntactic sugar for the above function call. If this were the case there would be no need for 4. This would require that `fromList` be an alias for an internal function that is not directly callable from a flux script, as well as a mechanism for transforming AST nodes. This is probably just as much work as 4. however once we have an API in place we'll be able to reuse it anytime we want to add syntactic sugar to flux.

DOD:
* Parser tests for the new literals
* Type inference tests for the new literals
* Interpreter tests for the new literals

**Comment by jsternberg** [comment]
I'd like to understand why we can't use the `[key: value]` syntax if possible. My understanding is that the reason is because it would cause the parser not to be `LL(1)` anymore and I'd like to understand why. To my understanding, we should be able to use left factoring to keep it as `LL(1)` just like we do with some of our other syntactic elements.

Non-factored grammar:

```
ExpressionList = [ Expression { "," Expression } ]
ArrayLiteral = "[" ExpressionList "]"
DictionaryLiteral = "[" PropertyList "]"
```

My understanding is that the reason why it wouldn't be `LL(1)` is because expression contains identifier and so does property list. I don't necessarily think this is a problem though. There's two ways where I believe this works and we can likely take either, but I think I have a preference for one because of simplicity to implement.

The **first** is to modify the literals so there's no conflict by not using `ExpressionList` and instead creating a new pattern modeled off of how paren expressions are implemented combined with how `PropertyList` is implemented. Then having a singular `ArrayDictLiteral`.

```
ArrayDictLiteral = "[" PropertyExpressionList "]"
PropertyExpressionList = [ PropertyExpression { comma PropertyExpression } ]
PropertyExpression = { ident colon } Expression
```

Then when we evaluate the AST and transform it into semantic graph, we would validate that it was an array or a dict based on the presence of the `ident colon` pattern. But, the AST would be permissive and allow this: `[a: 1, b]`. We do this presently for function calls so I think there's precedent to this and it is fairly simple to implement and understand. The `{ ident colon }` doesn't create an ambiguity because it can be resolved with left factoring.

```
PropertyExpression = ident PropertyIdentExpression
                   | Expression
PropertyIdentExpression = colon Expression
                        | ExpressionSuffix
```

The **second** is to use left factoring more aggressively in the same way as above, but to resolve the initial ambiguity.

```
ArrayDictLiteral = "[" ArrayDictExpression
ArrayDictExpression = ident ArrayDictIdentExpression
                    | ArrayExpressionList
ArrayExpressionList = ExpressionList "]"
ArrayDictIdentExpression = colon DictExpressionList
                           | ExpressionSuffix { "," ArrayExpressionList } "]"
DictExpressionListSuffix = { "," DictExpressionList } "]"
DictExpressionList = [ DictExpression { "," DictExpression } ]
DictExpression = ident colon Expression
```

I don't believe that's a complex syntax tree so it wouldn't be a copy and paste into the parser code. The left factoring is admittedly more complex, but it is possible.

One caveat with this syntax is that an empty literal for a dictionary wouldn't be capable of being disambiguated from an empty array. I still prefer this syntax and I think it would be easily possible to do something like `dict.empty()` or we can mimic groovy and allow `[:]` to be used. if we really needed empty dictionaries, but I thought I would mention that as a possible problem. The reason why I prefer the syntax is because I think it matches in symmetry with the array literal syntax and it also matches an existing language ([groovy](https://www.baeldung.com/groovy-maps)) so I think it has more precedent.

**Comment by nathanielc** [comment]
@jsternberg Its not just about identifiers, rather either arrays or dictionary keys can be arbitrary expressions as keys or elements to the array or dictionary. For example:

```
d = |
  1 + 1 : 2,
|

a = [ 1 + 1, 2]
```

We would not know until we see with the `comma` or the `colon` which kind of literal it would be. Can you left factor the entire Expression production rule?

**Comment by jlapacik** [comment]
@jsternberg like @nathanielc mentions, we can't left factor in this situation because a dictionary literal allows for arbitrary expressions to be used as key values (not just literals). We would really need an LR parser in order to support `[]` for both arrays and dictionaries.

**Comment by jsternberg** [comment]
I think the first example would work better then.

```
ArrayDictLiteral = "[" PropertyExpressionList "]"
PropertyExpressionList = [ PropertyExpression { comma PropertyExpression } ]
PropertyExpression = Expression { colon Expression }
```

In my opinion it's much more simple. You parse as an expression. Once you're done, you scan to see if there's a colon. If there is, you parse another expression. We then solidify whether it is a dictionary literal or array literal during the semantic pass or catch any problems in `ast.Check`.

I think if we tried to resolve this in the initial parser it would require a different character because we would have unbounded lookahead so my initial impression was wrong. I assumed that the key could not be a variable since the other locations where we do this require either an identifier or string literal.

We do this method for other things. For example, `foo(a: 2, b)` is allowed, but we explicitly catch this in `ast.Check` or somewhere else and raise it as an error.

If we decide we like the `|` syntax better that's one thing but I'd like us to choose the syntax we would prefer to see and write and not worry too much about the parser.

**Comment by jlapacik** [comment]
@jsternberg that's right, we'd need the semantic pass in order to resolve the type. I'm definitely not against that, but then we need to have a conversation on the empty array/dict literal `[]`. Resolving the correct type in this case would require changes to the type inference code. It would also require changes to the runtime (interpreter/compiler) since now `[]` would be polymorphic (representing either an array or dict).

I'm not opposed to doing this work, but it would require several issues and probably a design discussion. In this case I think I would be more in favor of the alternate syntax you proposed `[:]`.

**Comment by jsternberg** [comment]
Yea I like the idea of mimicking groovy. I think it has a certain elegance to it. That's what I'd be in favor of.

**Comment by jlapacik** [comment]
Closing in favor of https://github.com/influxdata/flux/issues/3365
