### ISSUE TITLE
Establish a way to ship the flux acceptance tests, executable from downstream consumers

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#3334]
If one does `go get github.com/influxdata/flux`, only the go files will be downloaded. In order to execute pure flux acceptance tests created from #3298, we must be able to ship the flux acceptance tests with go. Additionally, those tests need to be able to be imported, likely off-disk.

One option would be that the stdlib is a tarball downloaded as part of executing the test runner in downstream.

DOD:
  - A downstream consumer's test runner can download (or get access to) the flux acceptance tests in `.flux` format.

**Comment by jsternberg** [comment]
Just to confirm, this is intended to allow Go code to access the test files, correct?

**Comment by jsternberg** [comment]
Here are the methods I have found to be able to ship flux acceptance tests to downstream.

## As a zip file from GitHub

If you know the commit hash or tag number, you can download the zip file directly from GitHub. It would then be fairly trivial to run the tests directly from the zip file or to unzip the file and run them from there. This is shown in #3359 as an example of how this might be implemented.

This is probably the simplest and works best when acceptance tests are run as part of a separate step like other end to end tests. If you want to do something outside of the `go test` framework, this is probably the easiest one. But, retrieving a suitable hash might be difficult to get from the go tooling. Go doesn't appear to expose the git revision for dependencies. It does expose the module version which can be used to get the revision. For example:

```
$ go list -m -f '{{.Version}}' github.com/influxdata/flux
v0.95.1-0.20201123151947-9c3cf772426a
$ curl -o flux.zip -L https://github.com/influxdata/flux/archive/9c3cf772426a.zip
```

But if you have a released version, you would have to download by the tag. So there is some pattern matching and switching behavior depending on the output. But, this is a fairly reliable way to do the download.

## Using go modules to do the download

Vendoring strips files, but go modules doesn't. The go module download will always download the entire source so this can be a fairly reliable method to get the files in a repository without any additional logic.

```
$ go list -mod=mod -f '{{.Dir}}' github.com/influxdata/flux
/home/jsternberg/go/pkg/mod/github.com/influxdata/flux@v0.95.1-0.20201123151947-9c3cf772426a
```

You can then just use that directory and test all of the flux files the same as you would with a zip or tarball. Go takes care of all of that. Note the use of `-mod=mod`. In go 1.15, they changed it to use `-mod=vendor` if there was a vendor directory present. If you exclude the `-mod=mod` and there is a vendor directory, it will give you the vendor directory which isn't suitable for this use case.

## As embedded files in a Go package

If you want direct access to the files in code and not to bother with the filesystem, you can embed them with `go-bindata`. This is the tool of choice for embedding data until go 1.16 is released with embed support. We use this for shipping the UI in the OSS and it's a solid choice. You can see #3350 for how this might be implemented.

This would probably be the ideal way to implement this if we were integrating with `go test` because then we wouldn't have to worry about filepaths or how the files are on disk or where they are. You can also do this same thing in Rust and expose it through the Rust C ABI, but I am not as familiar with those tools.
