### ISSUE TITLE
InfluxDB 2.0 OSS: Flux strings.subString() is buggy

### ISSUE THREAD

**Issue by bacomalex** [influxdata/flux#3368]
Using Flux on InfluxDB OSS Version 2.0.0 (37cc047) strings.substring() does not return the correct substrings.

Taken the example from the [documentation](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/strings/substring/) a call to `strings.substring(v: "influx", start: 0, end: 3)` should return "infl" (4 characters). That would make sense. In reality it returns "inf" (3 characters).

# Steps to reproduce
```
import "strings"

from(bucket: "olmero")
    |> range(start: -5m)
    |> filter(fn: (r) => 
      (r._measurement == "cpu")
      and (r._field == "usage_idle")
      and (r.cpu == "cpu-total")
    )
    |> group()
    |> limit(n: 1)
    |> keep(columns: ["_value"])
    |> map(fn: (r) => ({
      r with
        aaa: strings.substring(v: "influx", start: 0, end: 0),
        bbb: strings.substring(v: "influx", start: 0, end: 1),
        ccc: strings.substring(v: "influx", start: 0, end: 2),
        ddd: strings.substring(v: "influx", start: 0, end: 3)
    }))
```

# Real result
| table | _value | aaa | bbb | ccc | ddd |
| --- | --- | --- | --- | --- | --- |
| 0 | 98.34475840142755 | i | i | in | inf |

# Expected result
| table | _value | aaa | bbb | ccc | ddd |
| --- | --- | --- | --- | --- | --- |
| 0 | 98.34475840142755 | i | in | inf | infl |

# Further trouble
Furthermore 

`strings.substring(v: "influx", start: 0, end: 13)` 

returns an error (indices out of bounds). That makes using subString in queries on real fields (where values can vary) complex. You need to call 

`strings.substring(v: "influx", start: 0, end: if strings.strlen(v: "influx") < 13 then strings.strlen(v: "influx") else 13)`

to use it in queries (and avoid errors). Would make way more sense if `subStr()` would simply return "influx" in this case.

**Comment by jsternberg** [comment]
@bacomalex thanks for submitting this issue.

For the primary issue, my understanding is the documentation is incorrect. The substring call for most programming languages has the end index by exclusive. This would be the case with Flux too. The documentation is indicating the numbers are inclusive. I would further expect `substring(start: 0, end: 0)` to return an empty string. It does not so that is a bug.

For the secondary issue, it should not be returning an error or panicking in anyway when the end exceeds the length of the string. That's also a bug.

I'll have a PR up shortly to fix these and also submit a fix to the documentation.
