### ISSUE TITLE
unexpected type error with union function

### ISSUE THREAD

**Issue by rogpeppe** [influxdata/flux#3408]
I get an error from the following Flux code:

```
import "experimental/array"
table=array.from(rows: [
    {kind: "first", bucket: 1, _value: 3},
    {kind: "first", bucket: 4, _value: 10},
    {kind: "first", bucket: 8, _value: 10},
    {kind: "second", bucket: 1, _value: 1},
    {kind: "second", bucket: 4, _value: 100},
    {kind: "second", bucket: 8, _value: 150},
])
grouped = table |> group(columns: ["kind"])
initial = grouped |> first() |> map(fn: (r) => ({r with bucket: -1, _value: 0}))
union(tables: [grouped, initial])
|> sort(columns: ["bucket", "value"])
|> difference()
```

The error is: 
```
 type error @12:25-12:32: found unexpected label bucket
```

I don't see why this would be a type error.

I've had similar code working OK in Cloud 2, although I did have the same error when I used a complete replacement struct in the `map` operation rather than using `{r with ...}`.

**Comment by wolffcm** [comment]
My thoughts on this one, from a slack chat:

 I think what may be going on here is that the type of union is

```
builtin union : (tables: [[A]]) => [A] where A: Record
```

The signature requires the types of the inputs to be exactly the same. When querying influxdb, we have precious little type info statically, so this is not normally a problem. But using `array.from` we know the exact type including all the fields, and static analysis will ensure that the types of the inputs match. Perhaps the error message is related to this. 

In the general case, we just expect `union` to merge the tables from two streams. If the tables have difference schema and we have sufficient type info, type checking will complain.

However in this case, the schema of the tables should be the same! So I don't know what's going on.

@jlapacik I'm curious to know your thoughts on this one ☝️

**Comment by jlapacik** [comment]
Yes it looks like this error is a result of union being called with tables having different schemas. The issue is the record extension in the call to `map`

> initial = grouped |> first() |> map(fn: (r) => ({r with bucket: -1, _value: 0}))

The records being passed to map are of type `{kind: string, bucket: int, _value: int}`, but the records being returned from map are of type `{kind: string, bucket: int, bucket: int, _value: int, _value: int}`.

This is due to a peculiarity of our record types in that they have scoped labels. This means it's possible to have two labels of the same name existing within a record at the same time. Because we don't have special syntax for updating an existing record label, the only workaround for this particular situation at the moment is to not use record extension in the call to map, but rather return the entire record like so
```
initial = grouped |> first() |> map(fn: (r) => ({kind: r.kind, bucket: -1, _value: 0}))
```

**Comment by rogpeppe** [comment]
> This is due to a peculiarity of our record types in that they have scoped labels. This means it's possible to have two labels of the same name existing within a record at the same time.

This seems like it's somewhat unintuitive, or arguably a bug. Might it be worth raising a issue to track this specifically?

**Comment by wolffcm** [comment]
I agree, I'll file some issues.
