### ISSUE TITLE
Types that are identical in practice are not considered equal by type checking

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3426]
This example is taken from #3408:
```js
import "experimental/array"
table=array.from(rows: [
    {kind: "first", bucket: 1, _value: 3},
    {kind: "first", bucket: 4, _value: 10},
    {kind: "first", bucket: 8, _value: 10},
    {kind: "second", bucket: 1, _value: 1},
    {kind: "second", bucket: 4, _value: 100},
    {kind: "second", bucket: 8, _value: 150},
])
grouped = table |> group(columns: ["kind"])
initial = grouped |> first() |> map(fn: (r) => ({r with bucket: -1, _value: 0}))
union(tables: [grouped, initial])
|> sort(columns: ["bucket", "value"])
|> difference()
```
It produces an error:
```
 type error @12:25-12:32: found unexpected label bucket
```

@jlapacik provides this very informative explanation: https://github.com/influxdata/flux/issues/3408#issuecomment-756494109
> The records being passed to map are of type `{kind: string, bucket: int, _value: int}`, but the records being returned from map are of type `{kind: string, bucket: int, bucket: int, _value: int, _value: int}`.

(Also, the error returned seems unrelated to what's actually going on)

For all intents and purposes, these two types will behave the same at runtime. Can we allow our type system to consider them as equal? I realize that this might have ramifications that I don't completely understand, but it seems like any label that is superseded by using `{r with ...}` could be reduced to a simpler type. Can we do this?

I'm marking this as a bug since the behavior is so unintuitive, but open to discussion on this.

(Tangential question: do we plan on ever supporting `{r without ...}`?)

**Comment by jlapacik** [comment]
I agree that scoped labels are unintuitive. To make matters worse, scoped labels should allow for two columns having the same name in the same table, but our engine does not support this.

However I think the confusion arises from a misunderstanding, or rather a poor specification, of record extensions
```
{r with bucket: -1, _value: 0}
```

We don't distinguish, nor do we have a way to distinguish, between record extension and record update. That is, does the expression `{r with bucket: -1}` extend `r` with a new label, or does it update `r` with an existing label. In my opinion, flux should be explicit about each of these two cases. In particular, I think we should have different syntax for each.

In addition, if we disallowed scoped labels, I think we could return helpful error messages such as
```
You are extending a record with a label that already exists. Try updating the record instead.
```

On a side note, it looks like it would be more beneficial if we returned the entire record type in the error message.

**Comment by wolffcm** [comment]
> We don't distinguish, nor do we have a way to distinguish, between record extension and record update.

I don't think this is true all the time:
```js
r = {num: 200, str: "hi"}

{r with num: 300}
```
For cases like this where a record type does not terminate with a variable, we _can_ make the distinction: either `num` is an existing field on `r` or it's not. I feel like in this case we can simplify the type of the resulting expression. I'm just suggesting that we adjust how we compute the type of `ObjectExpression` when there is a `with` and the type of the identifier is completely known. This would yield more intuitive behavior much of the time. 

Is your concern with conflating extension and updation about keeping the user from accidentally doing one when they meant the other? Or are you concerned with how it would affect what kinds type checking we would be able to do?

**Comment by jlapacik** [comment]
I guess it depends on what you assume the semantics of `with` to be. Our record types are defined such that
```js
{r with num: 300} = {num: 200, str: "hi", num: 300}
```

In words, we always extend the record with a new label.

> Is your concern with conflating extension and updation about keeping the user from accidentally doing one when they meant the other? Or are you concerned with how it would affect what kinds type checking we would be able to do?

Both. Mainly I'm concerned that we can't statically infer record extensions properly if extension and update are defined using the same syntax. But assuming that we can, I'm still not sure I like such implicit behavior as a user.

For instance, when would I want to use both extension and update? Only in the case that my rows have different schemas. If some rows have a `num` field, I want to update the value to be `300`. If others don't, then I want to add a `num` field with the value `300`. I think we want to push users toward uniform schemas vs non-uniform, in which case the aforementioned example would be an anti-pattern.

I'm not arguing to keep scoped labels though. In fact I'm in favor of removing them. But I do think we should/need syntax distinguishing between extending a record with a new label vs updating a record's existing label.

**Comment by adrian-thurston** [comment]
Please correct me if I'm wrong, but I'm understanding that we cannot have map inspect the input type and decide if "extend" or "restrict then extend" is the operation on the types. That's simply not how the type system works (hate those kind of statements, but the best I've got right now).

So we have to decide between
1. extend with scope
2. separate syntax, one that extends without scope (only if not present), and another restricts then extends.

I like the idea of removing the scoped labels from the type system and also adding a syntax to indicate that the label is updated. It makes sense to me that when a user encounters that error they will notice that the field is known to exist at compile time and therefore it must be "updated", not "withed". It's not unusual for us to do a bit more work as programmers to better specify our programs.

The reservation I have is that it is not corresponding with runtime behaviour. That runtime distinction doesn't exist, there is just "add if not there, replace if there". So there might be variying mental models between compile time and runtime, which might be confusing.

"with" is a compile time "add", and a runtime "add or replace"
"update" is a compile time "update" and a runtime "add or replace"

Perhaps these are just the quirks of our system, not sure.

**Comment by adrian-thurston** [comment]
I have to admit it is attractive to try to alter the type system such that scoped types can unify properly, but that doesn't solve the problem that scoped types don't have any real runtime representation.

**Comment by jlapacik** [comment]
@adrian-thurston I'm not sure if I can provide you with a satisfactory answer, but I can try to give an example of why conflating update and extend semantics is at the very least hard to define from the perspective of type inference.

Take the following function
```
f = (r) => ({r with x:1})
```

When assigning types to functions, we need to determine, statically, how to express the return type in terms of the input types. Right now, this function extends `r` with a new label `x`. And so the return type can be expressed in terms of the input type like so
```
(r: T) => {T with x: int}
```

Here `T` can be an arbitrary record type. Determining the type of `f(r: _)` is quite simple
```
f(r: {}) // {{} with x: int} = {x: int}
f(r: {a: 0}) // {{{} with a: int} with x: int} = {a: int, x: int}
f(r: {x: 0.0}) // {{{} with x: float} with x: int} = {x: float, x: int}
```

We just replace `T` with whatever the type of `r` is.

But if this function were to either extend or update `r` depending on whether or not `r` already has a label `x`, how do we express the return type in terms of the input type? It's not entirely clear. We can't keep the same type signature because if `r` is of type `{x: float}`, we want the return type to be `{x: int}`, not `{x: float, x: int}`.

Probably the best type signature that we could come up with is the following
```
(r: T | {T with x: S}) => {T with x: int}
```

Here `T` can be any record that does not have a label `x`.

`T | {T with x: S}` looks very similar to a polymorphic variant/sum type. While not trivial, such a type could certainly be added to the flux language. But this begs the question, how do we algorithmically infer this type? Notice that, originally `r` was a record type, and so `{r with x: 1}` was well defined. But now `r` is a variant type. What does it mean to extend a variant type with a label? Does `{r with x: 1}` return a record or a variant? Are all records now just variant types?

These are some of the questions that I have when conflating update and extend semantics. These questions might all have answers, but even if they do, it's clear that at the very least, conflating update and extend will require much more complex types. I'm not sure exposing such types to the user is a great experience. I think it's important to maintain a good balance between an expressive and simple type system.

**Comment by doivosevic** [comment]
Could you by any chance make a write up on these language features somewhere in the docs pages?

**Comment by philomory** [comment]
Maybe this is a stupid question, but why not just have `{x: float, x: int} == {x: int}`?

**Comment by jlapacik** [comment]
@philomory not a stupid question. It's actually the crux of this issue. Equating those two types in such a way that the following holds
```
{} != {x: float}
```

is not trivial. And the above inequality must hold in order for type inference to remain sound. At the moment it's not clear how to define the type system such that both are true.

**Comment by philomory** [comment]
@jlapacik I'll have to take your word for that. It certainly _seems_ trivial from the outside, but I'm far from expert on type systems and anyway things that seem trivial often aren't.
