### ISSUE TITLE
Problems trying to join 2 measurements

### ISSUE THREAD

**Issue by sgracia-hiberus** [influxdata/flux#3499]
Hi!

I am trying to perform the unification of two measurements, because I need to get the unified information from them.
I have the following two measurements.
- wmi_service_state: This measurement has the name of the service (name), the name of the vm (namehost) and the state of the service (I am interested when the state is equal to "stopped").
- wmi_service_start_mode: This measurement has the service name, the vm name (namehost) and the start mode of the service (In my case, the services that start automatically, "auto").

Making use of the join, I have tried to unify this information in only one, but it is not working as it should.

> import "experimental"
StateTable = from(bucket: "MyBucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "wmi_service_state")
  |> filter(fn: (r) => r["state"] == "stopped")
  |> filter(fn: (r) => r["_value"] == 1)
  |>group(columns: ["name", "host", "namehost", "url", "state"])
  |> yield(name: "state")
StartTable = from(bucket: "MyBucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "wmi_service_start_mode")
  |> filter(fn: (r) => r["start_mode"] == "auto")
  |> filter(fn: (r) => r["_value"] == 1)
  |>group(columns: ["name", "host", "namehost", "url", "start_mode"])
  |> yield(name: "start")
join(
  tables: {state_var: StateTable, start_var: StartTable},
  on: ["host", "namehost", "name", "url"]
)

The information I get is varied.
The first part is the first part of the query. That is, those services that have the state "stopped".
The second part is the second part of the query. That is, those services that are started automatically.

What I need is to get only those services that start automatically and are stopped. 
What am I doing wrong?

**Comment by sanderson** [comment]
@iFuSioNz This question may be better suited for the [InfluxDB Community](https://community.influxdata.com/) rather than a Github issue.

Do you have examples of input and output data for this query?

**Comment by iFuSioNz** [comment]
First of all, thank you very much for your response and for your time, @sanderson
I attach three images.
The first one shows you the list of services that start automatically by host.
![imagen](https://user-images.githubusercontent.com/56583010/108339083-48e7f300-71d7-11eb-949c-3ff4e1a583a2.png)

The second one shows you the list of the stopped services that each host has.
![imagen](https://user-images.githubusercontent.com/56583010/108340019-6b2e4080-71d8-11eb-8e53-06068e5e282f.png)

And the third one shows you the union of both queries. The question is that in the result of the query, it shows me everything, when it should show me only the union of everything.
![imagen](https://user-images.githubusercontent.com/56583010/108340133-89943c00-71d8-11eb-8923-672637d9f333.png)

My problem comes because I need to create a panel which shows me the services that are stopped and start automatically.

I have the input information defined (it was like this and there is no option to change it) as follows. 
The vm with windows raise a http which has its metrics there. With telegraf and Prometheus input, I connect to each vm and extract the metrics.

Telegraf Config:
> [[inputs.prometheus]]
  urls = ["http://X.X.X.X:9182/metrics"]
  interval = "30s"
  response_timeout = "20s"
  [inputs.prometheus.tags]
    namehost = "XXXXXX"
    prioridad = "Critical"

Example of metrics.

> wmi_service_start_mode{name="wmi_exporter",start_mode="auto"} 1
wmi_service_state{name="audioendpointbuilder",state="stopped"} 1

**Comment by sanderson** [comment]
@iFuSioNz I think you have the data where you want it, you just need one more operation to give you unique service values. Try using `unique()` after your join:

```javascript
// ...

join(
  tables: {state_var: StateTable, start_var: StartTable},
  on: ["host", "namehost", "name", "url"]
)
|> unique(column: "name")
```

**Comment by iFuSioNz** [comment]
@sanderson Thank you for your response. I think I explained myself badly. I just want it to show me the names of the services that meet both conditions.
With the unique, it only keeps one value per row.

I only want the last three values
![imagen](https://user-images.githubusercontent.com/56583010/108480260-01c13700-7297-11eb-8a22-c09b63aa9e49.png)
