### ISSUE TITLE
Dealing with data that is encoded as only changes from previous value is hard

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3501]
Some customers ingest data only when it changes from the previous value. The data might be very sparse, or it might not.

Normally, we have data that is collected on a regular periodic schedule, and we can use a window+agg pushed down to storage to get downsampling and reduce the amount of data we need to process in Flux. This generally results in a nice performance boost.

For data that is only recorded when it changes, the inclination is to make it uniform by windowing it with `createEmpty:true` and then use `fill(previous)` to make it into something closer to other workloads. However, this seems like it would have a negative effect on performance since it could _increase_ the amount of data that needs to be processed in the query engine.

Some operations that might be requested on data of this format:
- instantaneous value at some point in time
- Some aggregate value over a particular range of time
- Some aggregate value across multiple series for an instant or a range in time
- integral (this is sort of like an aggregate, but we do not seem to consider it as such on our stdlib/docs)
- What about time weighted average (docs suggest that it does linear interpolation, which is *not* what we want)

Users may reasonably expect that data presented in this way would be more performant since we shouldn't have to pay the cost of many redundant points. We should have a good story for ways to achieve this.

**Comment by deanasheehan** [comment]
To add a specific customer example from ENGIE Digital (a live opportunity right now).

They have lampposts that report instantaneous power setting (Watts) when the brightness changes - maybe a handful of time a day. 

They want to be able to calculate the power consumption per lamppost per day and then sum those across all lamppost.

We have a dataset (I'll attach) for 73 lamppost/30days. Calculating day by day city wide (73 lposts) takes 23s against Cloud 2 (my use of Azure US East). They expect to have 10,000 lampposts.

```
from(bucket: "engie-digital")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "LIGHTING_POWER")
  |> filter(fn: (r) => r["_field"] == "value")
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)
  |> fill(usePrevious: true)
  |> aggregateWindow(every: 1h, fn: mean)
  |> group() 
  |> aggregateWindow(every: 1d, fn: sum)
  |> yield(name: "city-consumption")
```

The above query generates 1 min means for each device and then fills previous to regularise the data -filling in the missing 1min slot values with previous based on the last value reported when the power usage changed.

It then determines a mean for an hour to get a Watt/Hour value (based on 1min quantised values), then de-groups and finally sum per day.

This generates a lot of intermediate data just to allow the maths to work.

It seems like a form of integral should work where it (fill's previous rather than supports linear interpolation) and we need to be able to find the starting 'last' value that might predate the entire window. That is - if I want daily energy usage for past 30 days across the city then I want to make sure that whatever the last power setting for each lpost before the 30 day window starts is brought forward and used as the starting power setting for each
[dataset_line_protocol.txt](https://github.com/influxdata/flux/files/5998503/dataset_line_protocol.txt)

We could use Flux Tasks to do some of the intermediate calculation in the background but it would seem that this will write a lot of data to Influx (assuming it is writing the minute by minute regularised data, like 1000x the source data) in order to support the calculation.

**Comment by deanasheehan** [comment]
To give a specific real world example for the above...

Lights sprinkled around a city report instantaneous power changes (Watts) when they bright or dim automatically in response to ambient lighting conditions. These devices don't report every minute or hour - only on change

If we wish to calculate the energy usage for an individual light (let alone sum across all devices in the city) you currently have to 

`from(bucket: "energy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "lights")
  |> filter(fn: (r) => r["_field"] == "value")
  |> filter(fn: (r) => r["device_id"] == "light1")
  |> aggregateWindow(every: 1m, fn: mean, createEmpty: true)
  |> fill(usePrevious: true)
  |> aggregateWindow(every: 1h, fn: mean)
`
This works but it synthesises a lot of intermediate data (n memory, not on disk) as it upscales to 1m (regularises the data per minute with full previous)

For <100 lights including a final hourly sum
`
  |> group() 
  |> aggregateWindow(every: 1d, fn: sum)
  |> yield(name: "city-consumption")
`
takes tens of seconds. To push to tens of thousands this becomes unworkable at the moment.

I believe there is an edge case not handled here as well where the device doesn't record a value for many initial hours at which point the previous is empty as the actual previous predates the range being considered.

**Comment by deanasheehan** [comment]
Here is an attempt at a use of reduce & map that almost works. I think I just have some math errors rather than logical errors.

```
import "experimental"
import "date"
  
  from(bucket: "energy")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "LIGHTING_POWER")
  |> filter(fn: (r) => r["device_id"] == "01b91c0d-8ea8-49de-8b57-5cebfb81de8a")
  |> filter(fn: (r) => r["_field"] == "value")
  |> window(every: 1d)
  |> reduce(
    fn: (r, accumulator) => ({ 
      previous_value: r._value,
      previous_time: r._time,
      wattMinutes: if int(v:accumulator.previous_time) == 0 then 0.0 else accumulator.wattMinutes + float(v:(int(v:r._time)/10000000000)-int(v:accumulator.previous_time)/10000000000)*accumulator.previous_value}),
    identity: {previous_value: 0.0, previous_time: time(v:0), wattMinutes:0.0}
  )
  |> map(fn: (r) => ({ 
    _start: r._start, 
    _stop: r._stop,
    _value: if int(v:r.previous_time) == 0 then 0.0 else (r.wattMinutes + float(v:(int(v:experimental.addDuration(d:1d,to:date.truncate(t:r.previous_time,unit:1d)))/10000000000)-int(v:r.previous_time)/10000000000)*r.previous_value) / 1440.0
  }))
```

The reduce looks at the energy changes for a day and works out the number of minutes spent at each power level (time difference in minutes * power level). The map then takes care of the very last entry (that ends the day) and then finally averages throughout the day by dividing by number of minutes in a day.

**Comment by wolffcm** [comment]
@deanasheehan I think the math error you've mentioned is that you need to divide by 60,000,000,000 (the number of ns in a minute).

Even with that fix, it seems like there is a problem because we can't know the last value of the measurement from the day before. If a lamppost had only one change in a day, for example, we wouldn't have any way to calculate the change in a day.

@jlapacik You did the time-weighted average function, I wonder if you have any insights into this problem?

**Comment by deanasheehan** [comment]
@wolffcm thanks for the  60 v my 10!

Yes, the pre-window (pre-range) last is a problem as noted. This is a problem in a number of situations - for example looking at level changes to raise alerts, what was the level before the window.

Having a better approach to the LAST before the INTERESTING time window would be good.

**Comment by deanasheehan** [comment]
I'm struggling to come up with a way of getting the previous days last available to 'this days' reduce and then the final piece would be the pre range last for each device.

As a thought process, both range and window seem like candidates for an incLast:bool parameter. I can see window handling that well but not range.

Alternative to range enhancement would be to have another range, the earlier range, of time in which you would consider looking for last values per device, and then union in that stream with the range of interest and to window(every:1d,incLast:true) would go to work. Finally my reduce above (with a slight mod for the maths on the pre-window value needing partial minutes contribution as it crosses into the day boundary) would work.

From a performance impacting perspective the additional range is expensive. The window(incLast:bool) should be trivial. I know from the test of my reduce across all the test data I have it is showing a 15x performance improvement over the upscalling with intermediate 1 minute window and fill previous.
