### ISSUE TITLE
Strange behavior for date.truncate(... ,unit:1w)

### ISSUE THREAD

**Issue by jennerwein** [influxdata/flux#3538]
The problem is the unit `1w`. Normally a week runs from monday to sunday. But in flux the week runs from tuesday to wednesday.

**Steps to reproduce:**
Test the function `date.truncate` with:

```
import  "date"
jetzt = 2021-03-06T06:31:15Z
from(bucket: "finanz")
  |> range(start: -12d, stop: date.truncate(t: jetzt, unit:1w))
```

**Expected behavior:**
It should stop at a sunday.

**Actual behavior:**
In my case it stopped at `2021-03-03T23:54:00.385770457Z` , which is wednesday evening.

**Environment info:**
InfluxDB Version 2.0.4 (4e7a59b)

**Comment by jsternberg** [comment]
Hi, this is an artifact of the epoch. January 1, 1970 is the epoch and it's also a Thursday. This means that when calculating based on weeks you will get Thursday as the start of the week. In the future, we're hoping to provide a way to customize the epoch to a different date so that a person could choose to use a different value for that such as January 1, 2001 which is on a Monday or January 1, 2006 which is on a Sunday.

I apologize that this behavior was not the first intuition and I see that it's not documented as being that way.

**Comment by pavanvora** [comment]
Hi @jsternberg ,

I see that this issue is somewhere related to the unexpected result of my query when I try to query `aggregateWindow` for `every 1week` so I just wanted to confirm that the issue which I'm facing is also affected because of the epoch.

Here's what is happening,

I have few months of ohlcv stock market data for 1-minute intervals and I'm able to aggregate it to 5m, 1h, 1d but when I do aggregateWindow for 1 week it considers Thursday as the starting of the week.

Is there anything I can do to make the first day of the week as Monday and not Thrusday?

**Comment by nathanielc** [comment]
We have this proposal for allowing a user to control the epoch and thus control what marks the begnning of a week. See https://github.com/influxdata/flux/issues/2093

**Comment by alksinflux** [comment]
@nathanielc - do you know whether we will have a fix for this in near future?

**Comment by ronyeh-lb** [comment]
any update on this?
and how this is not documented?

 this is really one of the weirdest inherent behaviour i can expect.
 when i query for
`window(every: 1w, createEmpty: true, )`
the first window is always stops on Thursday 
we just need a **fixed** interval, regardless epoch concerns, that always starting from 
`range(start: xxxx-xx-xxTxx:xx:xx.xxxZ)`
and ends exactly et the end of the interval.
this is so basic.

**Comment by SokoFromNZ** [comment]
I ran into the exact same issue here:
I want to summarize my numbers for the current week using `range(start: date.truncate(t: now(), unit: 1w))`.

Even more strange to me:
I thought "if `this week` doesn't work, I go for the last 7 days" with `range(start: date.truncate(t: now(), unit: 7d))`.
But this seems to have the same issue?!?

Does anyone have a workaround for this?

**Comment by onelson** [comment]
I wonder if `experimental/date/boundaries` could be used for this.

`boundaries.week()` should be able to give you the start/end of a given week relative to `now()`.
https://docs.influxdata.com/flux/v0.x/stdlib/experimental/date/boundaries/week/
