### ISSUE TITLE
Error querying empty time range

### ISSUE THREAD

**Issue by heliodor** [influxdata/flux#3543]
Problem:
Querying an empty time range returns the error `cannot query an empty range`.

Expected behavior:
Return an empty data set.

The statement `WHERE date >= 2021-01-01 AND date < 2021-01-01` (pardon the use of SQL) is programmatically correct though seemingly invalid from a human point of view. Flux should comply with the request and return an empty data set.

Relevant code location:
https://github.com/influxdata/flux/blob/0f51f73f7773e149dfb9ed8132af49750fbb3298/stdlib/universe/range.go#L110

**Comment by ulbi** [comment]
I run into this as well. Just describing my use case (in case there are other solutions)
I've two buckets - one stores all values downsampled to hourly or daily values - longterm, the other one contains the current values as they come in (retention 30d) - current.
Both buckets overlap with respect to the covered timeranges - downsampling happens every 5 days.
For energy consumption I do store the increments consumed. In order to get daily, monthly and yearly values I need to query both buckets.

In order to get the yearly powerconsumption I would like to query:
current (start: -10d)
longterm (start: beginning of the year, stop: -10d)
This does fail with the error "cannot query an empty range".

Same applies to the first days in a month.

Any other options to ensure, that I skip the overlap and still can query both buckets correctly?

For now I will propably end up in a rather complicated logic to figure out, whether the year or month start is more or less than 10 days ago and act accordingly...

**Comment by steinnhauser** [comment]
I was having issues with this error message for a while. I was trying to query for values which were 1hr ago, but I kept getting this error. I learned that InfluxDB always operates in the UTC timezone, so when I was trying to query from the "Europe/Berlin" TZ I was essentially querying for a `start: ...` which was in the future to Influx. 

It might be helpful to add more descriptive InfluxDB errors when the start/stop times requested are nonsense (such as `start` being more recent than `stop`, or `start` being in the future relative to `now()`). The error `cannot query an empty range` was not very helpful here.

Hopefully this can help someone experiencing something similar.

**Comment by heliodor** [comment]
What an terrible way to deal with bug reports! Commenting to keep it open.

**Comment by sumitshinde-84** [comment]
Getting same error, i am trying to get data from specific date and time 

 ```let start = global.get('rangeStart');
let startFormattedDate = new Date(start).toISOString();
let endDate = new Date("2023-11-02T09:12:20.41Z").toISOString();

msg.query = `
  from(bucket: "youtube-tutorial")
  |> range(start: ${startFormattedDate}, stop: ${endDate})
  |> filter(fn: (r) => r["_measurement"] == "feelslike")
`;

return msg;
```

**Comment by ulbi** [comment]
I think there is no hope to get this fixed - when following this thread:
https://community.influxdata.com/t/is-flux-being-deprecated-with-influxdb-3-0/30992

Maybe there is a fork of it, I did not yet went through all of it.
