### ISSUE TITLE
histogram: bucket confusion

### ISSUE THREAD

**Issue by cgudrian** [influxdata/flux#355]
Hi! 

Given the buckets [0.0, 100.0, 200.0, +Inf] a value of 123 is placed into the buckets 100.0, 200.0 and +Inf.

I was expecting it to be only placed in the 100.0 bucket.

Is this intentional?

Christian

**Comment by sanderson** [comment]
@cgudrian with the current implementation of the histogram function, this is intentional. Currently it generates a cumulative histogram, meaning that each bucket has only an upper bound and contains all points below its upper bound. From what I understand, normal histograms, those with buckets that have upper and lower limits, are planned but not yet implemented.

**Comment by blu3r4y** [comment]
I also stumbled across this behavior and was very confused at first.

Although the documentation says this clearly, I think the function should be renamed to `cumulativeHistogram`, otherwise this is very misleading.
