### ISSUE TITLE
Currently doing public `use` of `std::fmt` in libflux

### ISSUE THREAD

**Issue by pierwill** [influxdata/flux#3605]
In the following code, it is curious that this statement is a `pub use` instead of the common `use std::fmt`. I wonder if this is necessary/intentional.

https://github.com/influxdata/flux/blob/2bb7052167653928efc020aa16271fe50fbcab6d/libflux/core/src/lib.rs#L21

**Comment by rockstar** [comment]
Getting to the bottom of this was a hilarious rollercoaster of emotions. Buckle up for an explanation.

I recall having seen this error, and `git blame` indicates I added this line. I originally just thought "Oh, I'll remove the `pub` and we'll be good to go." I removed it, and the compiler complained that it was not used. Removed it entirely, and everything built. However, when running `cargo test`, the doc tests (of which we have none) failed with a number of lines that look like this.

```
error[E0433]: failed to resolve: could not find `fmt` in `core`
  --> /Users/user/Projects/flux/libflux/core/src/lib.rs:32:17
   |
32 | #[derive(Debug, Display, Clone)]
   |                 ^^^^^^^ could not find `fmt` in `core`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

`git blame` says I added `pub use std::fmt`, and seeing the patch helped me swap in some knowledge. However, it still seemed fishy to me that a macro wanted something in the crate's public interface. Why didn't I catch this before? Maybe I was tired or something. I dug in some more this time, rather than take things at face value.

As it turns out, we named our crate `core`, but there is [a rust crate called `core`](https://doc.rust-lang.org/core/) that we end up hiding as a result of our crate's name. When the macro tries to `use core::fmt`, it gets our `core` crate instead of the rust `core` crate, and then complains about missing interfaces.

A seemingly small documentation issues uncovers a pretty big oversight on our part that should probably be addressed with haste, before it becomes a bigger problem later on down the road.
