### ISSUE TITLE
Create an interpolate.previous function

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#3624]
We have a function `interpolate.linear` that can interpolate missing points and normalize the times of samples:
https://github.com/influxdata/flux/blob/7da26c243c15752b88be0b46dfc076cc946e6fd9/stdlib/interpolate/interpolate.flux#L23

Frequently users have data that is recorded only when there is a change. Flux tends to work best with data that has samples at regular intervals though. So an `interopolate.previous` function would come in handy.

It might work like this for example:
```js
// interpolate flux

builtin previous : (
    <-tables: [{T with
        _time: time,
        _start: time,
        _stop: time,
    }],
    every: duration,
) => [{T with
    _time: time,
    _start: time,
    _stop: time,
}]
```
```js
import "array"
import "interpolate'

array.from(rows: [{v: 111.1, t: 2021-01-01T00:00:00Z}])
  |> range(start: 2021-01-01T00:00:00Z, stop: 2021-01-01T00:05:00Z)
  |> interpolate.previous(every: 1m)
```
This would produce:
```js
[
  {v: 111.1, t: 2021-01-01T00:00:00Z},
  {v: 111.1, t: 2021-01-01T00:01:00Z},
  {v: 111.1, t: 2021-01-01T00:02:00Z},
  {v: 111.1, t: 2021-01-01T00:03:00Z},
  {v: 111.1, t: 2021-01-01T00:04:00Z},
]
```
In effect, for any given flux table with `_time`, `_start`, and `_stop` columns, it would ensure that there is a row at each interval defined by `every`, whose columns (besides `_time`) contain the values of the previous row. The resulting table would contain all such rows in `[_start, _stop)`.

**Comment by nathanielc** [comment]
A few questions:

* Should the type signature have a `_value` column that is the column that is interpolated? I.e. which column's value is being used as the previous value?
* How should _start and _stop be used? Should we used the stream context instead? If we use _start _stop should we enforce that they are part of the group key? How does interpolate.linear do it? And if we use _start and _stop to extend the rows in the table does this function belong in an `extrapolate` package? 

If we use _start and _stop then we should enforce they are part of the group key.

**Comment by wolffcm** [comment]
The current behavior of `interpolate.linear` is:
- It doesn't look at `_start` or `_stop` at all. 
- All columns except `_value` must be in the group key

For `interpolate.previous` we may want to:
- use `_stop` to determine when to stop propagating previous values forward. If `_stop` varies (perhaps because it's not in the group key, return an error
- Propagate forward all values that are not in the group key

**Comment by jsternberg** [comment]
I have a few concerns with `interpolate.previous` that I'll try to voice here so we can start a discussion. My concerns are multi-faceted so they don't necessarily build on each other, but are small red flags for me that indicate this might not be the best idea.

I think my first primary concern is that it duplicates an existing design. This behavior is supposed to be implemented by `window(createEmpty: true) |> fn() |> fill(usePrevious: true)`. My understanding is that this doesn't work because when `fn()` is a selector, it doesn't produce a null value to fill so the fill doesn't work. But this has been recorded as a bug multiple times (#3428, #3064, #2967). It seems like it would benefit us to fix that issue so we can use fill as it was originally intended. I'd like us to think about the response to those issues before we think about adding a new function. If our thought is "aggregate window's create empty does not function with selectors" and that's our answer as a team, then I think we can discuss the design of this function for this use case. My position is that create empty should work with selectors when used within aggregate window because aggregate window is intended to perform aggregations even when a selector is used.

After that, I have concerns about `_start` and `_stop` and using those values to perform the interpolation.

My first concern is that this behavior is inconsistent. There's no other function that does this or uses `_start` and `_stop` in any meaningful way. So this function would be the first one. I think we should ensure that the API design of the standard library is consistent and not just becoming additive to fix whichever problem we happen to have. I appreciate that we might try something different, but I think this might go a bit too far. Especially since the other interpolate function in this same package doesn't perform this behavior and the behavior we're implementing isn't interpolation, but extrapolation. If `interpolate.linear` used `_start` and `_stop` or if `interpolate.linear` didn't exist, my position would be different.

My second concern is that `_start` and `_stop` have seemingly been confusing for users to understand. It's very common for people to drop those group key values from their queries. This becomes problematic because `drop()` will stop any additional push downs. `_start` and `_stop` will also interfere with things like `experimental.join()` when you are attempting to read from two different ranges, use time shift, and then join them together to perform some analysis based on a previous time interval. While `_start` and `_stop` are useful outputs from the window function, I haven't personally had a use for them outside of that and I haven't seen a use for them.

The primary function that generates `_start` and `_stop` is `window()` and `aggregateWindow()`, but we've noted that these functions have substantial performance problems due to the cardinality explosion that occurs when using them and we've considered refactoring `window()` to not exist and `aggregateWindow()` to be a builtin that operates in a different way. This change seems inconsistent with that refactoring because there wouldn't really be any functions that use `_start` or `_stop` if `aggregateWindow()` didn't exist in its current form anymore.

I do think there's a future conversation about stream context, `_start/_stop`, and how we should handle windows in general and I think it's important to have that discussion. But, I don't think this is the issue to have that discussion. I think there's an easy way to implement the functionality for this function that would take less than a day. I think we add a builtin that inserts an empty row when a table is empty and then modify `aggregateWindow()`.

```
builtin _defaultWindow : (<-tables: [A]) => [A]

aggregateWindow = (tables=<-, fn, createEmpty, every) => tables
    |> window(every: every)
    |> fn()
    |> ((tables=<-) => if createEmpty then tables |> _defaultWindow() else tables)()
    |> duplicate(column: "_stop", as: "_time")
    |> window(every: inf)
```

Then they could just use `fill()` and we'd also fix a bug at the same time.

**Comment by wolffcm** [comment]
@jsternberg Thanks for making your concerns clear.

> I think my first primary concern is that it duplicates an existing design. This behavior is supposed to be implemented by `window(createEmpty: true) |> fn() |> fill(usePrevious: true)`. 

I agree we should fix selectors so they don't drop empty tables and introduce null values instead, or make this behavior possible in some other way. Then at least users would be able to express the semantics they want with composable primitives.

Even with such a fix in place, there still remains a problem with that approach which is that it tends to use a lot of memory. Cloud users would be quite limited in how much data they can process. Do you see that as a problem? I know you've brought forward some ideas, but I don't know that we've discussed them as a team and a solution seems a ways off. I'm wondering if we could manage something in a shorter time frame.

> the behavior we're implementing isn't interpolation, but extrapolation. 

Would it help if we placed it in a different package then, like `extrapolate.previous`?

What if we wrote a builtin that simulates the behavior of `window(createEmpty: true) |> fn() |> fill(usePrevious: true)`? It would differ a bit from the behavior I've described here, but not by much. Then when we have a better solution for the cardinality explosion of the general case, we can rewrite `extrapolate.previous` in terms of lower level composable functions. If we do this I guess we need to decide between using `StreamContext` or `_start` and `_stop` to figure out the range. But if we can resolve that, would it sit okay with you?

**Comment by jsternberg** [comment]
> Even with such a fix in place, there still remains a problem with that approach which is that it tends to use a lot of memory. Cloud users would be quite limited in how much data they can process. Do you see that as a problem? I know you've brought forward some ideas, but I don't know that we've discussed them as a team and a solution seems a ways off. I'm wondering if we could manage something in a shorter time frame.

I'm working on an issue to try optimizing window at the moment. It might be good if we looked at that implementation and tested if it was feasible.

> Would it help if we placed it in a different package then, like extrapolate.previous?

I'd say yes. Especially if we put it into an experimental package I'd be more comfortable with trying out something new. My ideal is that we test an optimized window and fix the selector problem, but I think this is also a good way forwards and I'd be more open to experimenting with using `_start` and `_stop` since it's a new package and that package can be documented as using `_start` and `_stop`.

> What if we wrote a builtin that simulates the behavior of window(createEmpty: true) |> fn() |> fill(usePrevious: true)? It would differ a bit from the behavior I've described here, but not by much. Then when we have a better solution for the cardinality explosion of the general case, we can rewrite extrapolate.previous in terms of lower level composable functions. If we do this I guess we need to decide between using StreamContext or _start and _stop to figure out the range. But if we can resolve that, would it sit okay with you?

I'd definitely say yes to this. If my window optimization work isn't good enough, the next way forward I was going to try was just to include a builtin aggregate window for the common aggregates and selectors.

My preferences in order:

1. Test if the window optimization makes processing data fast enough and fix the selector create empty stuff.
2. Create an `extrapolate.previous()` in experimental.
3. Builtin aggregate window.

I like 3 but it seems like more work than 2.

**Comment by wolffcm** [comment]
After some discussion, we've decided to make improvements to how `aggregateWindow` deals with selectors like `last()`, etc, in lieu of creating a new builtin transformation. This will address the existing bugs we have (#3428, #3064, #2967) and should also be performant, since we will be able to push down operations into storage. The epic to capture the work for this is here: https://github.com/influxdata/flux/issues/3681

The net result of this is that we'll be able to write a function like `extrapolate.previous` in Flux code like this:
```js
extrapolatePrevious = (tables=<-, every) =>
  tables |> aggregateWindow(every: every, fn: last, createEmpty: true)
  |> fill(usePrevious: true)
```
Probably something like this will end up in the Flux library.

**Comment by stavr666** [comment]
Is there any timeline for this new (createEmpty:true working with single-value aggregations) behavior implementation?

We use custom functions for now, standard consistent approach will be appreciated.
