### ISSUE TITLE
formatting not working when code is all on a single line

### ISSUE THREAD

**Issue by russorat** [influxdata/flux#3798]
My expectation when i hit `Format` is that each `|>` is brought to it's own line, with spacing so that it is aligned with the other `|>`s.

What happens is if you have your entire script on a single line, only the last `|>` is brought to it's own line. Running format again has no effect.

![Kapture 2021-06-10 at 11 09 16](https://user-images.githubusercontent.com/4805997/121575686-810c7f00-c9dc-11eb-89e8-e92c052822b8.gif)

If you add a newline before the first `|>`, the formatter behaves as expected:
![Kapture 2021-06-10 at 11 13 43](https://user-images.githubusercontent.com/4805997/121576316-190a6880-c9dd-11eb-8291-8537595ab4f6.gif)

**Comment by skartikey** [comment]
This is because we have a pipe depth level set to 2 which means the first 2 pipes will not be sent to the new line. So from 3rd pipe onwards, you will see it's going to a new line when formatted. https://github.com/influxdata/flux/blob/master/libflux/flux-core/src/formatter/mod.rs#L828

Passing depth as 0 to at_least_pipe_depth(0, n) will work as expected in this issue -
 
`from(bucket: "OSS_metrics") |> range(start: v.timeRangeStart, end: v.timeRangeEnd) |> filter(fn: (r) => r["_measurement"] == "influxdb_oss") |> filter(fn: (r) => r["field"] == "boltdb_reads_todtal")`

to

```
from(bucket: "OSS_metrics")
    |> range(start: v.timeRangeStart, end: v.timeRangeEnd)
    |> filter(fn: (r) => r["_measurement"] == "influxdb_oss")
    |> filter(fn: (r) => r["field"] == "boltdb_reads_todtal")
```

but then this will also change below expressions - 

`"(a() |> b()).c"`
to
`"(a()\n    |> b()).c"`

`"(() => 1)\n    |> f()"`
to
`"(() => 1)
       |> f()"`

`"(tables) => tables |> a()"`
to
`"(tables) => tables\n    |> a()"`


I tried passing 1 as a depth, in that case, all tests passed but the output of the formatted script will have 1 pipe expression in the first line like this - 

```
from(bucket: "OSS_metrics") |> range(start: v.timeRangeStart, end: v.timeRangeEnd)
    |> filter(fn: (r) => r["_measurement"] == "influxdb_oss")
    |> filter(fn: (r) => r["field"] == "boltdb_reads_todtal")
```

**Comment by skartikey** [comment]
As this is not a high-priority task, I am removing it from the milestone.
