### ISSUE TITLE
to() in function called via map() not writing to bucket

### ISSUE THREAD

**Issue by abalone23** [influxdata/flux#3893]
I have a function that writes to a bucket in [InfluxDB Cloud](https://us-east-1-1.aws.cloud2.influxdata.com/). If I call it directly, it writes successfully. If I call it via `map()`, it doesn't write to the bucket, but it doesn't return an error either:

```
import "influxdata/influxdb/schema"

get_tag_values = (measurement) =>
{
    schema.tagValues(
        bucket: "telegraf",
        tag: "host",
        predicate: (r) => r["_measurement"] == measurement
    )
    |> rename(columns: {_value: "host"})
    |> group(columns: ["host"])
    |> map(fn: (r) => ({r with _time: now()}))
    |> set(key: "_measurement", value: measurement)
    |> set(key: "_field", value: "dummyfield")
    |> set(key: "_value", value: "1")
    |> to(bucket: "targetbucket")

    return true
}

// get_tag_values(measurement: "cpu")

schema.measurements(bucket: "telegraf")
  |> filter(fn: (r) => r._value == "cpu")
  |> map(fn: (r) => ({r with ph: get_tag_values(measurement: r._value)}))
```

Calling the function directly works fine:
```
get_tag_values(measurement: "cpu")
```

To determine whether it wrote successfully, run the following in a separate query:
```
from(bucket: "targetbucket")
  |> range(start: -5m)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
```

**Comment by jsternberg** [comment]
It might be difficult for us to fix this query as it might require a decently sized rework to the engine or parts of the engine. I'm not sure the scope which is why I'm being cautious about the size of the work involved.

First, as a workaround, you might be able to use `findRecord` to get what you want.

```
import "influxdata/influxdb/schema"

write_tag_values = (measurement) =>
    schema.tagValues(
        bucket: "telegraf",
        tag: "host",
        predicate: (r) => r["_measurement"] == measurement
    )
    |> rename(columns: {_value: "host"})
    |> group(columns: ["host"])
    |> map(fn: (r) => ({r with _time: now(), _measurerment: measurement, _field: "dummyfield", _value: 1}))
    |> to(bucket: "targetbucket")
    |> group()
    |> count()
    |> findRecord(fn: (key) => true, idx: 0)._value

schema.measurements(bucket: "telegraf")
  |> filter(fn: (r) => r._value == "cpu")
  |> map(fn: (r) => ({r with ph: write_tag_values(measurement: r._value)}))
```

I think this will work as it will force the query to run within the map.

The reason that the above query doesn't work in the existing engine is because the result of the `to()` call is not directly used by anyone and we do not register expression side effects if they happen outside of the top level statements. When an expression is seen at the top level in the main package, an implicit `yield()` is added to the end to force the expression to run. If you include multiple expression statements, this creates a conflict since there are now multiple yields with the same name and we don't allow that.

The `yield()` creates a forced side effect that causes any parent transformations to run.

When you are doing this inside of a function, such as the one invoked from map, this doesn't happen. And since there are no "side effects" from the execution, that portion of the query never gets invoked.

Hopefully this explanation helps. It might be good for us to investigate the interaction of side effects and function calls to see how we want to handle side effects as we might be able to improve how we handle queries like this.

**Comment by abalone23** [comment]
When I try that I get an error:
`compilation failed: error at @15:8-15:52: pipe destination must be a function call`
on the `findRecord()` line.

**Comment by abalone23** [comment]
This works:
```
import "influxdata/influxdb/schema"

write_tag_values = (measurement) =>
{
    schema.tagValues(
        bucket: "testabc",
        tag: "host",
        predicate: (r) => r["_measurement"] == measurement
    )
    |> rename(columns: {_value: "host"})
    |> group(columns: ["host"])
    |> map(fn: (r) => ({r with _time: now()}))
    |> set(key: "_measurement", value: measurement)
    |> set(key: "_field", value: "dummyfield")
    |> set(key: "_value", value: "1")
    |> to(bucket: "perf")
    |> group()
    |> count()
    |> findRecord(fn: (key) => true, idx: 0)

    return true
}

schema.measurements(bucket: "testabc")
  |> filter(fn: (r) => r._value == "cpu")
  |> map(fn: (r) => ({r with ph: write_tag_values(measurement: r._value)}))
```

For some reason, if I use:
```
|> map(fn: (r) => ({r with _time: now(), _measurement: measurement, _field: "dummyfield", _value: 1}))
```

instead of:
```
|> map(fn: (r) => ({r with _time: now()}))
|> set(key: "_measurement", value: measurement)
|> set(key: "_field", value: "dummyfield")
|> set(key: "_value", value: "1")
```

No points are written even though there is no error.

**Comment by jsternberg** [comment]
Hm, it seems like the `findRecord` forces the query to execute. Not what I was originally thinking, but that works.

I'm not sure about why the map doesn't work. I wonder if it has something to do with the group key? We'll have to investigate that when we investigate other portions of this. I'm just glad we have a workaround.

I also suspect that the reason my query may have not worked is just because of parsing. Something like:

```
result = ... |> findRecord(fn: (key) => true, idx: 0)
return result._value
```

That might work. Either way, yours seems to work and the value doesn't matter anyway.

**Comment by jsternberg** [comment]
After looking at this with @scbrickley, I think that this might just be because the compiler doesn't support expression statements or side effects at the moment and we take an overview of the design. The filter and map function use this section of code to run their lambdas.
