### ISSUE TITLE
[mqtt.to()] Make `timeColumn` optional

### ISSUE THREAD

**Issue by samhld** [influxdata/flux#3917]
The requirement to send a valid line of Line Protcol seems arbitrarily restrictive here:

1) MQTT topics are often comprehensively descriptive and shouldn't require anymore information than the user decides to include.  Example: I have a topic `/things/temperature/average_5m` that is for the average temp of all things for the last 5 min.  The only information I would need in the MQTT payload is the value, itself.  I don't necessarily need a timeColumn, or Tags, or anything else.

2) Payloads should accept JSON, CSV, and any other format we support.

**Comment by alespour** [comment]
Could you elaborate a bit on 2) please? Should there be an option to specify that data (tables) are serialized into JSON or CSV format payload, in addition to line protocol as it is now? Is there a formal requirement or feature request for that with details? Thank you.

**Comment by samhld** [comment]
@alespour The payload of the MQTT message that Flux publishes (I believe this is the `message` parameter) should not require that it is line protocol.  Other subscribers to the target broker may not know how to deal with Line Protocol.  Flux can be used to output a single value or some JSON object, etc.  A user will want to have these as options for the body of the published message. In most cases, these message bodies will likely _not_ be Line Protocol.

**Comment by alespour** [comment]
In the current implementation, `message` parameter content is sent as MQTT payload as is. When this parameter is omitted (or its value is empty string), then input tables are serialized into line protocol and that is sent to MQTT.

However, the implementation is broken a bit I think. The `to` function cannot be used standalone, outside the pipeline. The documentation contains an example with `message` parameter used, but the function requires table object input (`<-tables`) and the example does not work. Or at least I could not find figure out how send a single message without a workaround of a pipeline with single-row table as input, like
```
import "generate"
import "experimental/mqtt"

generate.from(count: 1, fn: (n) => n, start: 2021-01-01T00:00:00Z, stop: 2021-01-02T00:00:00Z)
  |> mqtt.to(broker: "tcp://mqtt.eclipseprojects.io:1883", message: "hi there", retain: true, topic: "test-influxdb")
```

Based on what I've learned so far from various notification platforms support packages in Flux (like Slack or PagerDuty), I guess there should be two functions - one for standalone use with arbitrary message, and the other for pipeline to send query results.

**Comment by samhld** [comment]
Thanks for writing this up, @alespour! Is there a reason there would have to be two functions here?  The `to()` function defaulting to Line Protocol is fine but I think it should be extended, no?  

Here's an example to illustrate why I wrote this issue.  The below query is designed to write an average value to MQTT. It wants to write just the value as the information the subscribing clients is in the `topic`.  Right now, the function doesn't accept anything that isn't an input table (or at least Flux record)?
```
import "experimental"
import "experimental/mqtt"

topic = "things/temp/average"
broker = "broker:1883"

from(bucket: "mqtt")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "temp")
  |> mean()
  |> group()
  |> mean()
  |> experimental.set(o: {_time: now()})
  |> mqtt.to(broker: broker, topic: topic, name: "temp", clientid: "flux", timeColumn: "_time", valueColumns: ["_value"])
```

Ideally we would have something like this:
```
data = from(bucket: "mqtt")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "temp")
  |> mean()
  |> group()
  |> mean()   // reduced to single table with single record but still a lot more info than we want to publish

data 
  |> mean() 
  |> findRecord(fn: (key) => true, idx: 0))._value      // reduces the single record to a single scalar value
  |> mqtt.to(broker: broker, topic: topic, clientid: "flux")
```

In the above query, we're just writing a value to the topic and that's it.  Flux was used to strip all the information wrapping the value so we just have a raw value left...but the `mqtt.to()` function currently doesn't allow this behavior at all.

**Comment by alespour** [comment]
Thank you, that explains a lot. I thought there were 2 use cases - one for writing query results ie. tables, like other [output functions]((https://docs.influxdata.com/flux/v0.x/function-types/#outputs)) typically do. And another for sending arbitrary data ( like single scalar value in your example) from anywhere in a script, even outside Flux pipeline. With a new function that does not require table input, the example would then look like
```
...

r = data 
  |> mean() 
  |> findRecord(fn: (key) => true, idx: 0))

mqtt.to(broker: broker, topic: topic, clientid: "flux", message: string(v: r._value))
```
Or similarly using `findColumn` function. These extracting functions effectively stop the pipeline, there cannot be any other function called later as no tables are passed along anymore, and they return a value.

---

I find current `message` parameter confusing, because it allows to send anything, but the `mqtt.to` function still requires table input so it  must be called from pipeline even though it does not use the table input at all, and just sends `message` regardless.

So i think there are two possible solutions if both use cases are valid. First is to try somehow find out how to make it send just the value(s) as a payload. Second is to add a new function that takes `message` parameter for payload.

The former solution could be a bit tricky considering existing built-in fallbacks for `timeColumn`, `nameColumn` and `valueColumns` when they are not passed as parameters, maybe somehow doable I guess. For example, if uses would pass 1) empty string for `name`,`nameColumn` and `timeColumn`, it would send just the value (`_value` by default) as payload. It feels a bit hackish though.
Please note that if the input table would have more rows, the message payload would be multiline text.

**Comment by samhld** [comment]
Yeah, you're right, this could/should be another way to do this:
```
mqtt.to(broker: broker, topic: topic, clientid: "flux", message: string(v: r._value))
```
I can imagine a case where you'd want to the `mqtt.to()` effect to be a "side effect" and not the end of the query/pipeline so the above is a good option to keep around. 

There is currently an issue (not being worked yet) to make functions like this act as side effects: https://github.com/influxdata/flux/issues/3989

Ultimately, the goal is to have this function be used to "fan out" payloads to many topics dynamically.  By having it take one topic per call, it would have to be included in a call to map, or in some other wrapper function.  Note the function I wrote in this issue's example (does not currently work as expected given the issue linked above): https://github.com/influxdata/flux/issues/3825

**Comment by alespour** [comment]
I think what you have tried to do in #3825 demonstrates why there should be `mqtt` package function for sending payload that is passed as ordinary parameter and which does not take/require table input.

```
builtin send : (broker: string, topic: string, message: string, ?qos: int, ...  !!!but not timeColumn etc) : bool
```

```
toMQTT = (tables=<-, broker) =>
  tables
    |> map(fn: (r) => { 
                        mqtt.send(
                                broker: broker, 
                                topic: genTopic(source_name: r.host, source_measurement: r._measurement)) ,
                                message: string(v: r._value) // or eg. message: string(v: json.encode(v:  r))
                        return r
                        } )
```

**This would give user control over what and how encoded it is send to MQTT.**

Change from current implementation: one row => one message (as of now, table is encoded as a whole and send in one message; but I guess is it not typical case but some aggregation to single row is typically used)

If the package will be refactored, I would also remove columns selection parameters of `to` function. In output functions group, it is not common. Instead it is relied upon `keep` and `drop` being called before `to`.

**Comment by samhld** [comment]
@alespour I'm still a little unclear on why there would need to be two functions for this.  In one case, `mqtt.to()` could simply act as it does today if left to all defaults.  In another case, you could just perform an operation like the `toMQTT()` function above does.  Right?  Or am I missing something?

**Comment by alespour** [comment]
To me the two functions would be cleaner solution.

Anyway, one way I found to use existing `to` in `toMQTT` to work around the side-effect issue.

```
toMQTT = (tables=<-, broker) =>
  tables
    |> map(fn: (r) => ({ r with _x:
            mqtt.to(
                tables: array.from(rows: [r])
                broker: broker, 
                topic: genTopic(source_name: r.host, source_measurement: r._measurement)) ,
                message: string(v: r._value)
           ) |> findRecord(fn: (key) => true, idx: 0) == {}
       })
   )
   |> drop(columns: ["_x"])
```
`_x` is boolean column, useless, so its drop afterwards.

```
data
  |> toMQTT(broker: b)
```

This works for me with `message` param passed, the value is sent to MQTT.

If I omit it to make `to` process and send passed `tables`, it fails with `invalid name` error and I haven't figured out how to check what the stream of tables created with `array.from(rows: [r])` look like.

**Comment by alespour** [comment]
So, my proposal is

- leave `to` as is, but deprecate `message` parameter (in documentation) because it makes little sense to send a message with content that is unrelated to query result _or maybe just drop the parameter since the package is experimental and such changes are possible_ ?
- add `publish` function for sending arbitrary data in `message` parameter, for per-row parameterization use cases like the above `toMQTT`

This would preserve backward compatibility and improve flexibility when interacting with MQTT.

**Comment by nathanielc** [comment]
@alespour @samhld Great discussion. I have read through and I agree, we should have a `to` function that sends data from a pipeline and a publish function that sends arbitrary data much like http.post.

I think we can just remove the `message` parameter entirely from the `to` function as it is still experimental. This is the kind of UX that we want to learn while a package is still experimental.
