### ISSUE TITLE
Resolve build errors from Rust 1.55 upgrade

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#4039]
The Flux release into influxdb experienced some strange CI errors that we believe were caused by the upgrade to Rust version 1.55 in the Flux docker container.

#4038 downgraded the rust version back to 1.54 to unblock the release, but we will eventually want to go back to 1.55, once we figure out how to resolve these issues.

DOD:
- The flux docker container uses Rust 1.55
- We can release into influxdb without issue
- If we need the new `math` lib (aka `-lm`) to be linked lets make sure we understand why, possibly file Rust bug if this was a breaking change on their side.

**Comment by nathanielc** [comment]
Relevant comment about the current errors https://github.com/influxdata/flux/pull/4038#issuecomment-919308517

**Comment by jsternberg** [comment]
Found in a Linux man page.

```
FMA(3)                                                           Linux Programmer's Manual                                                           FMA(3)

NAME
       fma, fmaf, fmal - floating-point multiply and add

SYNOPSIS
       #include <math.h>

       double fma(double x, double y, double z);
       float fmaf(float x, float y, float z);
       long double fmal(long double x, long double y, long double z);

       Link with -lm.
```

**Comment by fchikwekwe** [comment]
This is an interesting issue that is possibly related. https://github.com/rust-lang/rust/issues/88817

**Comment by fchikwekwe** [comment]
Also, looking at the files that were failing the previous build, it looks like f32.rs and f64.rs are affected. There is a new linear interpolation method (`lerp`) in each file that references the intrinsics `fmaf32` and `fmaf64` respectively via the `mul_add` function. The direct use of the `mul_add` function and the import of these float types seem to be the reasons that we need the math library linked all of a sudden. This seems to be due to an inconsistency in how intrinsics are referenced as seen in the issue I linked in the previous comment.
