### ISSUE TITLE
Type inference for each package should use its own fresher instance

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4045]
Type inference will use a fresher to create new tvars when analyzing a file. These tvars are then later used to unify constraints and substitute type variables. At the moment, when we analyze the standard library, we reuse the same fresher for the entire standard library. This means that if we have package `a` and package `b` and we make a change to package `a`, then the tvars in package `b` will also be modified.

This is done out of an abundance of caution to ensure that we aren't accidentally assigning two tvars to different types. On the other hand, when we import a package, it's not really possible to ever use any of the tvars from the imported package. This is because when we invoke a function, we create a new instantiation of the type by refreshing all of the tvars and performing type inference on that new instantiation.

A more concrete example.

If we have the identify function:

```
identity = (x) => x
```

This will generalize into a polymorphic function where `x` is the tvar `t1`. When the function is later invoked, `identity` is instantiated to replace all of the tvars with new ones. At the point of invocation, the function signature changes to `t2 -> t2` and the constraints are maintained. Type inference then runs on `t2` independently.

Because of this, it should be safe for us to analyze each package with its own fresher instance rather than having them share the fresher. A type for a tvar will be valid from within the package and will generally not be mixable with tvars that were inferred from a different package.

This is required for https://github.com/influxdata/flux/pull/3623 to be merged. It was reverted [here](https://github.com/influxdata/flux/pull/4044).

**Comment by jsternberg** [comment]
This is the instantiation code that I reference in the description above: https://github.com/influxdata/flux/blob/9b9575705d78fe818e2d51b3318c2dd32f483e35/libflux/flux-core/src/semantic/infer.rs#L145-L180.

The big unknown with this is likely how it interacts with the Go runtime. I suspect the Rust type inference will just work with this change and it won't have any problems with using a new fresher for each import. The Go runtime might need to get tested because it's possible it does something not allowed by the type inference algorithm. This is primarily because the Go runtime predates algorithm w and was only modified in a way to just make it work, but it's been in deep need of a refactor or rewrite to further embrace algorithm w.

The place where I most suspect the Go runtime to have a problem with is understanding the type of functions it invokes. I think this might be a presently existing bug in the interpreter though and the compiler package might do the correct thing.

**Comment by nathanielc** [comment]
>  This will generalize into a polymorphic function where x is the tvar t1. When the function is later invoked, identity is instantiated to replace all of the tvars with new ones. At the point of invocation, the function signature changes to t2 -> t2 and the constraints are maintained. Type inference then runs on t2 independently.

This is correct in that for let-polymorphism to work we instantiate a new instance of the function type. It is not correct that this protects us from reusing tvars from new freshers. You mention that during instantiation we create fresh tvars and maintain the constraints. We maintain the constraints by looking up the set of constraints associated with `t1`. 

Take this example:

```
// a.flux
package a

identity = (x) => x
```
```
// b.flux
package b

f = (x) => x / 10
```

```
c.flux
package c

import "a"
import "b"

a.identity(x: b.f(x:50)) // 5
a.identity(x: "str") // this should work but if we collapse the tvars it will fail
```

When running type inference for `c.flux` if both `a` and `b` packages used `t1` for their type of `identity` and `f` respectively. Then the constraints of `t1` would be that is must be `Divisible` because of the `f` function. When we instantiate the second call to `a.identity(x: "str")` it will fail type inference because it will create a fresh tvar with the `Divisible` constraint but a string doesn't satisfy that constraint.



How would I solve this problem? Formalize how we treat tvars from inside a package import. We don't really have logic for this yet but will need it when we do user packages anyways so I think we should move in this direction. My general idea is that we use one global fresher when analyzing the stdlib but instead of then directly serializing the resulting types with their tvars we would add a normalization step. This step would rewrite all the tvars in the package to start over from t1. Then during import , at query time not stdlib time,  we again rewrite all the tvars from the package to be fresh according to the current fresher. This way we ensure that there are never conflicts of tvars from package to package. 

Technically you could do the above with a new fresher for each package during stdlib analysis as well, the important part is the normalize step during import. 

Thoughts?

**Comment by jsternberg** [comment]
@nathanielc and I discussed this off the github issue on Friday and I forgot to put our conversation into this issue.

When we took a closer look, we believe the example above doesn't end up applying or causing a problem. The reason for this is that the code that uses a variable always instantiates a new version of the type variables each time it is used and, in that local scope, those new type variables are used. The instantiation is done using the fresher for the local area of code.

Since the only way to access something in an imported package is through an identifier and a polytype, we never get access to the original monotype and the specific type variables don't end up meaning anything in files that import other files.

This means that we believe we can use a new fresher for the type inference for each package. Within a package, we need to continue to use one fresher to infer the entire thing because it might be possible for those to accidentally mix if we tried to use a new fresher for each statement. But, type variables seem to be scoped to the individual package.

If this wasn't the case and we had to worry about type variables from different packages colliding, I think what @nathanielc proposed would be the correct solution. Since the above is true, I think it ends up being simpler to just restart the fresher for each package.

We should make sure there are tests though to ensure that we have thoroughly tested this.
