### ISSUE TITLE
Implement Location option

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#406]
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#location

The fixedZone and loadLocation functions should also be implemented.

**Comment by m50434** [comment]
Are there any news to this?
I would really appreciate to get a possibility to set the timezone in Flux as soon as possible.

**Comment by coussej** [comment]
We've been using flux for a while now, and while we can do a lot more than with InfluxQL, this seems to be the only thing that we could do using InfluxQL and that doesn't work in flux yet. A lot of our clients rely on the TZ() clause for daily /weekly aggregates, so would be nice to see this in a next release!

**Comment by vaclavh** [comment]
Is any progress on this feature right now? It would be very helpful. Thank you.

**Comment by xabinapal** [comment]
With Flux being used as the new InfluxDB query language, this should be a mandatory feature. Without it, it’s impossible to use a timeseries database in any real-life scenario for anything besides storing data, which makes it pointless. That’s because any daily, weekly, monthly or yearly aggregation can not be done.

Two workarounds can be used to perform these aggregations, offset parameter of window function or timeShift function. But even with these workarounds, timezones with DST shifts will return wrong aggregation results with specific timestamps.

This issue was opened two years ago, and it seems that it has received zero attention. Even InfluxDB team said in the 1.8.0 release that Flux was “production ready” (that’s why we started to experiment with it). For this statement to be true, this should be implemented ASAP.

**Comment by QcPerreault** [comment]
Any news on this? @russorat

**Comment by drewstreib** [comment]
I'll add a 2021 pile-on to this. I'm also using the docker image, which doesn't appear to respect the "local" time zone even if set properly with TZ in the docker environment. This was my hopeful workaround with a timezone default for window() calls.

I'm hacking around it now with manual window offsets, but this feature seems pretty baseline and really needs to be implemented.

**Comment by shortcodes** [comment]
Still nothing on that!? @nathanielc C'mon guys ...

**Comment by cranphin** [comment]
Since docker latest got changed to 2.0, this just became important to me (was using old query language before)

**Comment by Maaxion** [comment]
Also facing issues with this.

**Comment by Pedrat** [comment]
Same here, really a shame

**Comment by giter** [comment]
@nathanielc

**Comment by coalpower** [comment]
Hi everyone!
The workaround for this issue is to continue to use InfluxQL only for the query where timezone is necessary. 
You still can use InfluxQL with InfluxDB 2.0. There is some commands to map a RP to a bucket and adding V1 Auth and then, it work as it was before.
https://docs.influxdata.com/influxdb/v2.0/reference/api/influxdb-1x/

**Comment by OlafHaalstra** [comment]
Hi @coalpower, is it also possible to combine it with Influx 2.0 queries? There is some new functionality in there that I would like to combine with the timezone feature.

**Comment by pavanvora** [comment]
Hello everyone,

Any update on this issue?
Or is it possible to set the default timezone for all the queries, something like setting the timezone somewhere in influxDB config file?

**Comment by GillesBodart** [comment]
Hello everyone any news ?

**Comment by mirkocomparetti-synesis** [comment]
Hello, any news on this?

**Comment by teu** [comment]
It would be really useful. This keeps us stuck with compatibility endpoint with influx 1.

**Comment by rclakmal** [comment]
Is there a planned release for this option? Being two years since reported :-(

**Comment by ben-64** [comment]
Do you have a workaround for that ?
Is someone can give me an example of flux query with the `aggregateWindow` function ?
I just migrated to influxdb 2.0 with flux, thinking that it was now mature, and I realise that this mandatory (and basic) feature for me is not working :(
I would appreciate a lot a workaround example.

**Comment by akazwz** [comment]
> Is there a planned release for this option? Being two years since reported :-(

Almost 3 years

**Comment by pportelaf** [comment]
Hello, any news?

**Comment by elliebas** [comment]
I will just add my voice to many others crying here.
We are currently able to consider TZ in our queries using timeShift() function but there is still no solution for daylight saving time.
Is it possible that it will be ever implemented in InfluxDB?

**Comment by sanderson** [comment]
@elliebas The groundwork for location support was introduced in Flux 0.132.0 and 0.133.0. There is still a little more work to be done, but it is very close and documentation covering how the `location` options works will soon be available.

**Comment by jkreileder** [comment]
We're using Flux from Influx 2.1.1.  For at least one timezone (America/Phoenix) the location code is broken, see https://github.com/influxdata/flux/issues/4312 for details.
