### ISSUE TITLE
Feature Request: |> delete()

### ISSUE THREAD

**Issue by asalem1** [influxdata/flux#4118]
### Issue

Right now it's possible to write a flux query to delete whatever data we want based on a specific predicate. However, the problem with this approach is that it requires the user to know exactly what they want to delete prior to deleting it. This puts a lot of responsibility on the user's knowledge of the existing data set without giving them, but keeps them in a static pattern of:

1. Investigate data
2. Decide what is irrelevant
3. Write a query to delete the irrelevant data
4. Run another query to verify that the data has been deleted (last step, optional)

### Solution

My proposed solution here would simply be to add a `delete` function whereby a user can run a query, then simply pipe all the returned data to be returned. This drastically simplifies the deletion process AND allows a user to iterate on an existing query in order to fully encapsulate what data they want to delete

**Comment by nathanielc** [comment]
@asalem1 I think I understand what you are asking but I am not sure. Can you provide a Flux example of what you would like to work? 

I see two problems with this approach but am open to discussing the idea further:

1. Deletes are a storage layer concern, Flux will end up consuming the delete with predicate API that already exists
2. Piping into `delete()` implies we can understand  where the data came from, what if I do `from |> range |> filter |> mean |> delete`? How do I delete the `mean` results as they are not even stored in the database.

Perhaps there is a different solution to the problem you are looking to solve. An example will help us explore that.

**Comment by knarrff** [comment]
I found this bug report as I was looking for a solution to the following problem, which might be one example that was asked for:

I do have a few environmental temperature sensors that, from time to time, send bogus data. Most often, those bogus data are outside the range of, e.g. "the other values this week". I do not want to automatically discard those values (would be nice, too - but only in addition), because I would like to monitor these "off-times". Most of the time, something like "select X" -> filter ">threshold" -> "delete" would be nice, with the idea being: delete all entries (in whatever measurement I specified) where the timestamps do exactly match. I would not include an aggregation function like mean() here.

At the moment, I have to manually find all the timestamps and write delete queries from those. Ideally, I would like to have a pre-written query with just a value range I always adjust and re-use that.

**Comment by sanderson** [comment]
> Most of the time, something like "select X" -> filter ">threshold" -> "delete" would be nice, with the idea being: delete all entries (in whatever measurement I specified) where the timestamps do exactly match.

@knarrff Unfortunately, the InfluxDB delete API doesn't support this type of delete operation. It requires a [delete predicate](https://docs.influxdata.com/influxdb/v2.6/reference/syntax/delete-predicate/) and a time range in which to delete points. This is a limitation of InfluxDB, not Flux.

> At the moment, I have to manually find all the timestamps and write delete queries from those. Ideally, I would like to have a pre-written query with just a value range I always adjust and re-use that.

There likely is a way to do this in Flux, but it wouldn't be pretty and it would likely be very slow. Essentially you'd use Flux to filter by data with values above your defined threshold, and then map over each row and call the `/api/v2/delete` API using the row's timestamp to set time bounds and the tag set to identify the point to delete (without accidentally deleting other points). Where this is a destructive process, I'd be really careful trying to do this.

**Comment by paulwer** [comment]
Customers can set options on their machines, how their data can be processed by us, which also results in an entry within the bucket. These settings also includes rentention times of each measurement, which we process by cron jobs to be met. Multiple buckets are not an option, because it would increase complexity while data fetching, when there are multiple customers with multiple buckets...

We also have a custom mapping of external input by a webhook in place, which is evolving over time to match the current usecase. At latest we had to change extisting data and rename tags too. Replacing existing data through flux or the ui is no problem, but deleting requires each time an extra step and is a break of applications. This feature will not be required for this but helping alot. Maybe a ui mask to do this task seperatly would be a good start, if there is no option for flux.

**Comment by knarrff** [comment]
Dear github-actions bot,

why do you make us users write something meaningless into issues that have not seen activity for some time? If an issue is not closed, it most likely has not been dealt with. If that is the case, it should not be closed. Closing an issue for the only reason of not seeing activity for some time is disrespectful of the users that opened them, wasting their time. It makes them less likely to report issues in the future, hurting the project.

thanks, a user.

**Comment by paulwer** [comment]
I found an other use case:
we would like to aggregate timeseries-data, which represents status values to a timeseries, where only changes are saved. If timeseries data is updated, a flux query, which both removes old data from the aggregation-location and creating the new data would be great.

In this case the _time parameter is urgent and is not the same in each run. Therefore we like to remove old data first.

(Just an Idea... we will most likly call the delete api-endpoint first and run the flux query afterwards at givven moment)

**Comment by knarrff** [comment]
Dear github-actions bot,

why do you make us users write something meaningless into issues that have not seen activity for some time? If an issue is not closed, it most likely has not been dealt with. If that is the case, it should not be closed. Closing an issue for the only reason of not seeing activity for some time is disrespectful of the users that opened them, wasting their time. It makes them less likely to report issues in the future, hurting the project.

thanks, a user.

**Comment by paulwer** [comment]
Dear github-actions bot,

why do you make us users write something meaningless into issues that have not seen activity for some time? If an issue is not closed, it most likely has not been dealt with. If that is the case, it should not be closed. Closing an issue for the only reason of not seeing activity for some time is disrespectful of the users that opened them, wasting their time. It makes them less likely to report issues in the future, hurting the project.

thanks, a user.

**Comment by paulwer** [comment]
@nathanielc are you able to reopen this issue?
