### ISSUE TITLE
Google Bigquery SQL Driver fails to connect

### ISSUE THREAD

**Issue by galamit86** [influxdata/flux#4176]
Driver fails when trying to load data from BQ to Influx Cloud dashboards with Flux using `sql.from.`

I am using the cloud interface, and have the following query written (following this):

```
import "sql"
import "influxdata/influxdb/secrets"

projectID = "my_project"
apiKey = secrets.get(key: "BIGQUERY_APIKEY")

sql.from(
  driverName: "bigquery",
  dataSourceName: "bigquery://${projectID}/?apiKey=${apiKey}",
  query: "SELECT * FROM my_dataset.my_table"
)
```
but getting the following error:
```
failed to initialize execute state: data source did not pass url validation: lookup my_project on 10.85.0.10:53: no such host
```
The `apiKey` variable holds a string created via these instructions. `my_project` definitely exists, as well as the bq datasets and tables.

**Comment by rubbs** [comment]
Is there anything I can help with?

**Comment by IoTRoetz** [comment]
Hey - is this still on the roadmap?

Otherwise I need to start looking for different solutions - so knowing what's planned would be very helpful. Thanks!

**Comment by galamit86** [comment]
Hey, is this still planned to be addressed? I see Sprint 21-Q4-2 is closed, and this issue isn't attached to any other sprint.

If this isn't going to be addressed soon, I need to start looking at other solutions, so that information would be helpful, thanks!

**Comment by rubbs** [comment]
any update on this?

**Comment by onelson** [comment]
Looks like there's a source validation step applied to each DSN `sql.to` and `sql.from` receive. The validation seems to be incorrectly treating the project name as if it were a hostname.

This _shouldn't happen_ since BigQuery DSNs don't contain any host information - the host details are all controlled by the driver itself.

Seems like it shouldn't be a big lift to get a patch out for this. No ETA just yet, but I'd guess "near term."

---

As an aside, I was working with BigQuery in vanilla flux (on the CLI) where the URL validation doesn't apply and had trouble connecting with an API Key. Google rejected my connection with a message suggesting API Keys were not permitted for BigQuery any longer and you're required to supply a full oauth credential.

My assumption was maybe I just provisioned my API Key incorrectly, but in the event this is a legit thing that changed on the Google side, a patch for the URL validation might not solve the entire flow. If API Keys are no longer allowed, then I think we'd need to expose some new way to supply credentials and I'm not sure what that would look like.

**Comment by onelson** [comment]
For whenever this gets prioritized, it seems like the `validator.Validate()` call here

https://github.com/influxdata/flux/blob/master/stdlib/sql/source_validator.go#L125-L127

could be skipped entirely when `driverName` is `bigquery`, or else we'd need to have each implementation of the `Validator` interface check to see which driver name is in use and push this branching behavior down. The root of the issue is the the validator will take the project id from the DSN and try to validate as if it were a domain, but it isn't.

**Comment by galamit86** [comment]
@onelson - thanks for taking this further.

I still can't get the connection to work - using the same query as mentioned in the original post, the error message is now different: `An internal error has occurred`.

I've also tried replacing the API Key with JSON credentials, using the following query (only changing the `dataSourceName` string):

```
import "sql"
import "influxdata/influxdb/secrets"

projectID = "roetz-life-data-dev"
apiKey = secrets.get(key:"BIGQUERY_APIKEY")
credentials = secrets.get(key:"BIGQUERY_CREDENTIALS")

sql.from(
  driverName: "bigquery",
  dataSourceName: "bigquery://${projectID}/?credentials=${credentials}",
//   dataSourceName: "bigquery://${projectID}/?apiKey==${apiKey}",
  query: "SELECT * FROM modules_status.modules_summary"
)
```

and gotten the same error message.

@rubbs , or anyone else - have you been successful in querying BQ? I'd appreciate getting a pointer on whether this is a still an influx bug, or something I'm doing wrong.

**Comment by onelson** [comment]
@galamit86 the following is working for me today (in cloud2):

```
import "sql"
import "influxdata/influxdb/secrets"

projectID = "xxxx"
dataset = "xxxx"
credentials = secrets.get(key:"TEAM_FLUX_BQ_CREDS")

sql.from(
  driverName: "bigquery",
  dataSourceName: "bigquery://${projectID}/?credentials=${credentials}&dataset=${dataset}",
  query: "SELECT * FROM xxxx"
)
```

Without a more detailed error message, it's hard to say what's failing for you.

The credentials in my case are a base64 encoded string of the json credentials, which I generated by downloading the json file from gcloud, running `base64` on the file, then removing all the linebreaks.

The only other thing I notice is you haven't specified a `dataset` to use, but I'm not sure that's required.

**Comment by onelson** [comment]
And now that I thought about how silly that "removing all the linebreaks" step was, I checked the `base64` manpage. Of course, TIL you can pass `--wrap=0` or `-w 0` to disable the linebreaks in the output.

**Comment by galamit86** [comment]
@onelson - that did it for me as well, thanks for the quick reply.

My problem was not encrypting the credentials first.

BTW - in OSX `base64` does not have a `wrap` option, so `cat credentials.json | base64 > encrypted_credentials.txt` does the same trick.
