### ISSUE TITLE
Get offset of local timezone

### ISSUE THREAD

**Issue by sanderson** [influxdata/flux#4287]
With the introduction of the `timezone` package and the `location` option, a lot of users are expecting timestamps to actually get updated based on their specified timezone. I'm wondering if we should add functions to the `timezone` package that can actually apply an offset based on a location-based timezone.

```js
location = timezone.location(zone: "America/Los_Angeles")

_currentLocalOffset = (time: 2021-01-01T00:00:00Z, timezone: location.zone) => //...
    //... Returns the current duration offset of the specified timezone at the specified time (because this can change)

applyOffset = (tables=<-, timeColumns: ["_time", "_start", "_stop"]) => tables |> // ...
    // something to iterate over rows and apply _currentLocalOffset to each column.
    // I'd say lets use timeShift here, but it doesn't conditionally apply an offset like you'd need to.
```

**Comment by nathanielc** [comment]
> a lot of users are expecting timestamps to actually get updated based on their specified timezone.

Can you expand on this? Can you point to an example of what users are expecting?

**Comment by sanderson** [comment]
https://community.influxdata.com/t/howto-migrate-utc-timestamp-to-local-time/22355

**Comment by jsternberg** [comment]
I think this is the same as https://github.com/influxdata/flux/issues/4260.

The main problem seems to be that `today()` is not respecting the location. `today()` is implemented with `date.truncate`.

```
// today returns the now() timestamp truncated to the day unit
today = () => date.truncate(t: now(), unit: 1d)
```

**Comment by dsilletti** [comment]
@jsternberg exactly, all the functions in the date package are not respecting the option location.

**Comment by garylfowler** [comment]
I experienced both of the items mentioned in the above comments in working with flux as a new user.

My use case is fairly simple:  I am using an API from my solar panel provider to pull energy usage and consumption information for my home electrical usage.  I then write that information to an InfluxDB bucket.  I wanted to do a simple query to show me my energy usage for the current day, in my local timezone (-10 utc).   If I use "today()" then I get the UTC today - which is 10 hours ahead of me, which will then exclude some information that is outside my own "today" that I may want.   So I searched the docs and found the import timezone and set the location information - thinking maybe that was a solution to my problem.   Might have been a stupid thought, but that was the only thing I found that might help.  I also tried adding a -10h after today(), but that didn't work (still learning flux syntax, so that was probably illogical as well).  Neither of those things worked.  @sanderson - gave me a tip for timeshift - which I hadn't stumbled across in the docs.  That actually helped a lot and my query was working exactly as expected.... until..  I hit 2:00pm my time which is tomorrow in UTC time and now I have very little data in my data set because it is only data from after 2:00pm. 

My next step will be to try to parse out today's datetime and offset by -10 and try to do a string comparison of the left side of the time to see if the date matches the current date - but being new to flux, I don't know how to do that yet.  But it definitely seems like there should be an easier way (and I am sure there is - I just don't know what it is).  Just sharing all this to give an example of a novice user getting confused and not knowing what the location setting actually does or how to easily work with data in their own timezone.
