### ISSUE TITLE
Operator profiler inflates durations for sources

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#4311]
When the `operator` profiler is active, the source will typically wait for each output table to be consumed before producing another table. The timings reported by the operator profiler will reflect this. This means the result of the operator profiler for sources is not particularly useful, since it doesn't isolate the time actually spent receiving data and/or creating tables.

One could think of this as a bug, maybe.

If this proves very challenging, maybe this is a design issue, with follow up issues to do the work of implementation. Or maybe it's actually easy and can all be done in this issue

DOD:
- The timings reported by sources in the operator profiler does not include time waiting for successor transformations
- There should be a common framework that works for all sources, but just the most common ones.

**Comment by jsternberg** [comment]
I'm not sure but it might be easier to wrap the created table in another table which counts the idle time when invoking the column reader. Something like:

```
type Table struct {
    in flux.Table
    idleFor time.Duration
}

func (t *Table) Do(fn func(flux.ColReader) error) error {
    return in.Do(func(cr flux.ColReader) error {
        start := time.Now()
        err := fn(cr)
        t.idleFor += time.Now().Sub(start)
        return err
    })
}
```

Then use the idle time and subtract it from the total duration. The reason is it's possible for the source to be doing work when `Do()` is invoked on `flux.Table`. But, when it has the `flux.ColReader` and is sending that it is mostly waiting for the transformation to process the table.

I don't think this will give 100% accurate numbers but it might get us close enough.

**Comment by jsternberg** [comment]
I'm highly suspecting that it would be easier for us to refactor how sources interact with the engine rather than to fix this directly. When I took a look at how the operator profile interacts with sources, it seems to make this very difficult to do.

For some background, here is how a source may spend time that needs to be accounted for.

1. There is an outer loop to do work such as determine series keys, organize them, and generally set up the entire source.
2. There is setting up the metadata for starting to read a single series. This happens immediately after 1 so there's no delay.
3. The table is then sent downstream. The source is idle at this point and the time waiting should not be accounted for. This step is also **optional** and is up to the individual source to implement.
4. The table is read in another transformation. The time spent for processing this counts against the transformation that read it and not the source. This _looks_ like idle time for the source though because it is waiting.

It starts to become really difficult to account for this time correctly because of how the sources are currently set up. This was previously required because the `flux.Table` interface needed to be read completely by a downstream consumer for it to start reading the next table. It also doubles as backpressure of the firehose.

The problem is that from the flux engine perspective, the source is a firehose. From the source perspective, it's spending time idle. And there's also additional potential network time being spent in the source that should be accounted for by the source, but is time spent within the next transformation.

It might be good to merge this kind of work into a refactor of how the sources work. I'd like it if flux sources were designed to implement backpressure on their own rather than to have that implemented by the sources.
