### ISSUE TITLE
Sample data should be modified

### ISSUE THREAD

**Issue by LLThomas** [influxdata/flux#4378]
I find something wrong when execute a query below.
```
import "influxdata/influxdb/sample"

sample.data(set: "usgs")
  |> filter(fn: (r) => r._field == "mag" and r._measurement == "earthquake" and r.id == "av91449451")
  |> filter(fn: (r) => r._value > 0.0)
```

The error information is as follows.
```
Result: _result
runtime error @4:6-4:102: filter: cannot compile @ 4:17-4:101: unsupported binary expression string > float
Error: failed to execute query
```

However, when I check the raw data, I find _value type is float.
```
import "influxdata/influxdb/sample"

sample.data(set: "usgs")
  |> filter(fn: (r) => r._field == "mag" and r._measurement == "earthquake" and r.id == "av91449451" )

```
```
Result: _result
Table: keys: [_field, _measurement, code, id, magType, net, title]
         _field:string     _measurement:string             code:string               id:string          magType:string              net:string                               title:string                      _time:time                  _value:float  
----------------------  ----------------------  ----------------------  ----------------------  ----------------------  ----------------------  -----------------------------------------  ------------------------------  ----------------------------  
                   mag              earthquake                91449451              av91449451                      ml                      av  M 1.3 - 23 km WNW of Anchor Point, Alaska  2021-12-22T23:54:41.710000000Z                          1.25  

```
I check the sample data in https://github.com/influxdata/influxdb2-sample-data/blob/master/usgs-earthquake-data/all_week-annotated.csv and find that this issue caused by different datatype in that csv file.
![image](https://user-images.githubusercontent.com/49053546/147194168-10422b1a-d352-44c8-b83f-ca607290777d.png)

The top data will make query failed.
Should we delete it ?

Related to #4084

**Comment by onelson** [comment]
Part of the challenge here is in how the sample data is prepared. We've got a github action that runs periodically. The tasks fetch new data from various sources, then run them through influxdb to produce the annotated csv files that get committed to the repo.

This is to say, we'd need to add something to the workflow to omit either the tables with floats or the ones with strings.

As it turns out, the data in the repo today has an almost even split of table headers:
```
influxdb2-sample-data on  master [?] via 🐍 v3.8.10 (venv) 
❯ grep 'dateTime:RFC3339,string' usgs-earthquake-data/all_week-annotated.csv | wc -l
6

influxdb2-sample-data on  master [?] via 🐍 v3.8.10 (venv) 
❯ grep 'dateTime:RFC3339,double' usgs-earthquake-data/all_week-annotated.csv | wc -l
5
```

Since the data changes over time (in principle) it's probably not fair to drop one or the other based on today's counts since the ratio tomorrow could be radically different.

If we were to take any steps to correct this, maybe we could split the data set into two?
It's conceivable we could produce two files instead of one, using `type.isType` to filter the records for each case here:

https://github.com/influxdata/influxdb2-sample-data/blob/15bf74a1605cfd42c22db52be482ba9b15f95c5b/.github/workflows/main.yml#L89-L94

That said, `type.isType` could also be employed here at the query side to avoid the error.

**Comment by onelson** [comment]
After discussing with the team, it seems I overlooked a detail and this issue is not quite what it seemed at the start.

The filters as written in the initial report should have:
- first, restricted the scope to records of a single series (with all floats for `_value`)
- then filtered based on `_value`, which in this narrowed scope should been safe to do

What appears to actually have happened is the `MergeFiltersRule` planner rule kicked in, combining the two filters into a single step. With the filters combined, the type checks are applied before any of the boolean logic short circuiting happens, and so the type check for the `_value` comparison fails (because the data set the float comparison happens on is _much wider than intended_).


This behavior appears to be limited to _just the flux CLI_. This planner rule seems to be disabled in other environments.
Running a similar query (changing only the id) in cloud works today, for example.

I've field a separate issue to disable it in the CLI so we have consistent behavior across the board.

**Comment by onelson** [comment]
#4437 has just been merged into flux@master, and once released it should make the query in the OP work as-written in the CLI. The query should work in other envs, such as the Web UI, already.

There will need to be further work done (or possibly not, depending on how we want to go) to allow all the two filters to be combined, either explicitly by the script author (as in #4084) or via a planner rule such as `MergeFiltersRule`. This will be explored in #4438.
