### ISSUE TITLE
timezone.location() gives error: "unknown time zone"

### ISSUE THREAD

**Issue by Kortenbach** [influxdata/flux#4382]
**Flux script example copied from docs:**
import "timezone"
timezone.location(name: "America/Los_Angeles")

**Executing in Influx UI gives me an error:**
error calling function "location" @3:1-3:47: unknown time zone America/Los_Angeles
In fact *any* timezone gives this error, except "UTC"
Running on Windows 10.
This seems to be related to GO missing some package.

This problem does not exist if I run InfluxDB  from a Docker container.
So it seems to be related to running InfluxDB from Windows.

**Comment by Gonzo4** [comment]
Same problem here using Windows Server 2012 R2 ...

**Comment by nathanielc** [comment]
The tzdata database needs to be installed on your systems. Is this for an OSS installation of InfluxDB? 

On Windows you likely need to install the package by downloading the database and using the ZONEINFO environment variable to tell Go where to find it. See https://pkg.go.dev/time#LoadLocation 

We could consider included the embedded tzdata database for builds of OSS. 

@jsternberg @dgnorton Thoughts on including the embedded tzdata for OSS builds? It add about 450K to the binary size.  See https://pkg.go.dev/time/tzdata@go1.17.6

**Comment by jsternberg** [comment]
Because of how we had to implement the timezone support (duplicating the go timezone library), we don't have access to that embedded timezone database. We'd either have to duplicate the embedding code or get the Go standard library to expose the information we need.

**Comment by jsternberg** [comment]
It looks like Go's default code for a timezone database on Windows only works if Go is installed.

https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/time/zoneinfo_windows.go;l=14-16

We'll have to discuss a way to get the timezone database properly on Windows. We may have to do some form of embedding maybe just for Windows. I don't think we should embed it on Linux as the system installed one is likely to be more updated. We don't necessarily want to require an upgrade of influxdb each time that the timezone database gets updated.

**Comment by jsternberg** [comment]
This likely seems like the best solution. We should make sure that we either expose an option in the configuration file for the zoneinfo location (might be difficult to do) or that `ZONEINFO` works properly.

**Comment by Kortenbach** [comment]
Thanks for picking up on this. I'm looking forward to a solution!

**Comment by Gonzo4** [comment]
Yes I'm using the open source version (OSS?).
I have installed GO on my server but nothing has changed, but I think it only would work if the default go implementation would be used? :smirk:
So I'm also looking forward for the solution :thumbsup:

**Comment by jsternberg** [comment]
@Gonzo4 if you go with installing Go on your server, remember that you need to set `$GOROOT` so that the runtime can find the location. I don't think there's a standard location on Windows but I admit I don't have a Windows computer and I have only ever used Windows in a personal computer environment and never as a server.

If you have Go installed on your server, you may also find it useful to locate the `zoneinfo.zip` file and set `$ZONEINFO` for the server process to point to the exact file location. I believe this should cause the code to load the file. If you're in an environment where installing Go is a no-go (pun not intended, but I find it funny), you can extract the `zoneinfo.zip` from the latest Go release and copy that to any location and set `$ZONEINFO`.

Please tell me if this ends up working for you. If it does, we'll update the documentation for this circumstance and we may consider trying to embed the zoneinfo data for Windows and only Windows just because of the difficulty involved with getting the zoneinfo there. We're really hesitant though to embed the zoneinfo data as we generally don't want to have to upgrade the Go version we use to compile just to handle last minute timezone changes. It's generally impossible for us to respond fast enough when that happens.

**Comment by Kortenbach** [comment]
Installing Go hardly seems like a solution for the average user.
There must be a better way (?)

**Comment by Gonzo4** [comment]
@jsternberg setting the GOROOT doesnt't work but setting the ZONEINFO as following has worked, thanks 👍 

![grafik](https://user-images.githubusercontent.com/6013729/149573421-b47518e1-253b-4d9e-b87e-a3c2c9d98db9.png)

**Comment by jsternberg** [comment]
@Kortenbach you can download `zoneinfo.zip` from the Go distribution, copy it somewhere, and set `%ZONEINFO% as shown above.

**Comment by nathanielc** [comment]
@jsternberg Thanks for figuring out how to make this work for Windows. We should document this for others to make it easier to find.

**Comment by nathanielc** [comment]
Closing as documentation issue has been created
