### ISSUE TITLE
How to handle type checks while processing "unknown" records

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4438]
We met and discussed the thread that follows below, and here at the top are some of the action items we came away with.

Per Jonathan:
- keep existing filter as is (don't touch)
- explore dynamic type
- explore stdlib impact for pivoting as the norm
- read polymorphic labels PR in detail

Per Chris:
- reshape sample data to split by measurement/field
- make sample data easier to work with

Nathaniel:

- path forward is homogeneous 

Since there's a lot of different paths outlined in the above, we're restricting the DOD for this ticket, here:

https://github.com/influxdata/flux/issues/4438#issuecomment-1039279550

Summary of discussion here:
https://github.com/influxdata/flux/issues/4438#issuecomment-1039814667

Pending action items have been filed as issues here:
https://github.com/influxdata/flux/issues/4480

---

Original content (prior to WG) follows:
---

Refs: #4084, #4378

Today, when the input to `filter` has varying types for a given field (such as `_value`), we can see a type error when this field is used for comparison. In order to avoid the type error, you need to split the `filter` into two:

- one to narrow the data to the point of giving a homogeneous stream of records (regarding the fields that will be compared).
- a second to filter based on the specialized types for the given field.

The team has a couple solutions for this in mind, discussed below.

## Improved Short-circuiting

The high-level idea would be to tweak the evaluation of boolean expressions to defer type checks until as late as possible such that earlier expressions can be used to filter out records that wouldn't match later typing requirements.

Here are a couple of tests that illustrate how things could work if we were to address this by using short-circuiting (which is one possible solution):

```
package universe


import "testing"
import "csv"

inData =
    "
#datatype,string,long,dateTime:RFC3339,double,string,string
#group,false,false,false,false,true,true
#default,_result,,,,,
,result,table,_time,_value,_measurement,_field
,,0,2021-01-30T00:00:00Z,1.0,foo,number

#datatype,string,long,dateTime:RFC3339,string,string,string
#group,false,false,false,false,true,true
#default,_result,,,,,
,result,table,_time,_value,_measurement,_field
,,1,2021-01-30T00:00:00Z,hello,foo,string
"
outData =
    "
#datatype,string,long,dateTime:RFC3339,double,string,string
#group,false,false,false,false,true,true
#default,_result,,,,,
,result,table,_time,_value,_measurement,_field
,,0,2021-01-30T00:00:00Z,1.0,foo,number
"

testcase bool_expr_in_filter_should_short_circuit {
    // There's an issue where when the input to a filter includes varied
    // types for a given field, type checking fails even if an earlier part
    // of the predicate should prevent the comparison from ever taking place.
    // Ref:
    // - https://github.com/influxdata/flux/issues/4378
    // - https://github.com/influxdata/flux/issues/4084
    got =
        csv.from(csv: inData)
            |> filter(fn: (r) => r._field == "number" and r._value > 0.0)

    want = csv.from(csv: outData)

    testing.diff(want: want, got: got) |> yield()
}

testcase bool_expr_in_filter_should_short_circuit_separates {
    // These filters should work today (so long as the `MergeFiltersRule` is
    // _not enabled_). If the short circuiting is working, such that the
    // `bool_expr_in_filter_should_short_circuit` passes, then this one should
    // also pass regardless of whether or not the merge rule is applied.
    // Effectively, when the merge rule is applied, this query will be rewritten
    // to look like the one in `bool_expr_in_filter_should_short_circuit`.
    got =
        csv.from(csv: inData)
            |> filter(fn: (r) => r._field == "number")
            |> filter(fn: (r) => r._value > 0.0)

    want = csv.from(csv: outData)

    testing.diff(want: want, got: got) |> yield()
}

```

Today, the `bool_expr_in_filter_should_short_circuit_separates` testcase will pass, but only when the `MergeFiltersRule` is not being applied. In fact, the reason this rule needs to be disabled for the test to pass is it rewrites the query to look like `bool_expr_in_filter_should_short_circuit`. Currently the single filter version fails because of a too-eager type check on the `_value` field which leads to an error about `unsupported binary expression string > float`.

Assuming the type check for the `_value` field is only performed after the earlier boolean expressions in the filter have been checked, both the single and double filter queries should work. In fact they should be equivalent to the point the `MergeFiltersRule` could effectively rewrite the double filter version into a single filter.

Additionally consider a contrived test case like which passes without error today:

```
testcase unfiltered_is_ok {
    got =
        csv.from(csv: inData)
            |> filter(fn: (r) => r._field == "number" or r._field == "string")

    want = csv.from(csv: inData)

    testing.diff(want: want, got: got) |> yield()
}
```

Here, we've effectively written a NOOP filter that returns the entire data set.
In this case, the resulting `want` includes a mix of types for `_value`. Since we don't actually reference the field in our predicate, the query is valid.

A question for us is: should the types be strictly enforced even when we aren't explicitly referencing the fields in question? If not, we're possibly promoting asymmetry in our semantics, which can introduce confusion or worse require users to perform "chicanery" to navigate.

**Comment by jsternberg** [comment]
I think the underlying problem lies with merge filters and the assumption that we could combine multiple filters into a single one and they would be the same.

If we were to short-circuit type checking based on a condition, then whenever we have an `and` or `or` we could never error out for type inference. We could never say any expression with a condition might not be a valid type without also having the associated value. Imagine the expression: `r.a == "a" and r.b == 0`. If I tell type inference that `r` is of type `{a: string, b: int}` we would not be able to give a type error. This effectively defers all type checks to runtime. This is the equivalent of the dynamic type. The dynamic type is a way where the language could allow any type and then, when you try to use it with a specific type, it checks out the runtime type to see if it works in that situation. It comes with a real cost.

Now I don't think we should do that. To me, I come to the following conclusions:

1. The flux type system is correct.
2. Merge filters is wrong.
3. Filter should be more efficient so that merge filters is unnecessary.
4. The storage filter push downs need to enforce this behavior correctly.

At the current moment, the storage filter push downs act as if all expressions were divided into multiple filter expressions except with the addition that `or` is also possible in different filters. I think we would need to improve the behavior so that the storage push down keeps different filters separate and enforces the types with a short-circuit pattern between different filters.

So if we have the following filters:

```
|> filter(fn: (r) => r._measurement == "m0" and r._field == "f0")
|> filter(fn: (r) => r._value > 0)
```

This would send storage two predicates instead of sending one predicate with an and. After it evaluates the first predicate, it would only evaluate the second one if it passed the first one. But, if it evaluates a predicate and there's a type error, it reports an error. So if we manually combined these, then it would return an error from the storage push down.

Just quickly, I generally think the dynamic type is not practical for the language we want to make. I think there will be places where we might want to consider a dynamic type, but this isn't really the place.

If we were to short-circuit type checking based on a condition, then I think type inference

**Comment by Marwes** [comment]
The flux interpreter is effectively using dynamic types already, else we would reject the query when we notice that `from()` returned the wrong type or record. So it is just the executors and the storage layer that enforce type checks eagerly. The storage layer can't handle type mismatches but the executors could (best I can tell). So `MergeFilters` is only an issue if it causes problems for the storage layer. However, the storage pushdown are already capable of splitting filters on `and` expressions.

```
|> filter(fn: (r) => r._measurement == "m0" and r._field == "f0")
|> filter(fn: (r) => r._value > 0)

// Mergefilter runs

|> filter(fn: (r) => r._measurement == "m0" and r._field == "f0" and r._value > 0)

// When storage pushdown runs it splits on `and` and tries to pushdown each part in turn
// So it should see that the first two can get pushed down and only stop when it sees the type mismatch
// on the third (in theory, maybe it can't handle it right now)

from(r._measurement == "m0" and r._field == "f0")
|> filter(fn: (r) =>  r._value > 0)
```

**Comment by jsternberg** [comment]
That's not completely true. The flux interpreter is using static types, but it sometimes has to defer the instantiation of those types to runtime. That's not the same as a dynamic type. A dynamic type would have to be checked each time the expression was invoked. The flux compiler only checks it once when it instantiates the functions with the known types.

**Comment by Marwes** [comment]
No, but for the purpose of this, I don't think there is much of a difference. Looking through `compiler/compiler.go` I think the binary expression lookup is the only part that can actually fail due to a type mismatch during compilation (logical expressions are only checked when it is evaluated, for instance).

**Comment by jsternberg** [comment]
That's true for this implementation of the compiler, but that's because this compiler has never really been optimized to work the way it should work.

Just for discussion, we could also choose to take types that are not decidable at runtime and include them as a kind of "dynamic" type. A dynamic type would be backed by a runtime check to determine whether a cast is successful or not. In a simple IR, it might be represented like this:

```
%1 = getmember %r, "_value"
%2 = asInt %1
%3 = eq %2, 0
```

In the context of an `and` statement, the `asInt` would do a dynamic check to see if it is an integer and would return an error if it's not. That would mean it would only cause an error when `asInt` is invoked so in an `and` statement it might not error out if it short-circuited. Implementing the `asInt` instruction though would create an additional burden on the runtime that wouldn't be as fast as if we didn't have to maintain that runtime type information.

**Comment by Marwes** [comment]
Yeah, I would very much like it if we could enforce type checks earlier and utilize them. However I also think that ship may have sailed since we do allow the static and runtime type to be different (in the interpreter). Having it be allowed in the interpreter and disallowed when in the compiler is a bit arbitrary and not clear for users.

As I have understood it, the type system is mostly a way to assist users and enforcement at runtime is secondary. Based on that and in the interest of preserving backwards compatibility I am leaning towards emulating the interpreter more rather than enforcing type checks earlier.

> %1 = getmember %r, "_value"
%2 = asInt %1
%3 = eq %2, 0

As long as we use a catch-all `Value` type any `Int()/String()/etc` extraction function will always need to check that the `Value`  is a `int/string/etc` before extracting so some sort of type check will always remain.

**Comment by jsternberg** [comment]
The interpreter allowing types to be different is just a bug because the type system was mostly created after the interpreter and due to another bug in instantiating functions. It's not really intentional. I wouldn't say the ship has sailed because it's mostly edge cases that I'd consider to be bugs. If we formally allowed type checks to short-circuit, then the ship has sailed because it's an officially sanctioned behavior of the language to treat everything as a dynamic type rather than a bug.

**Comment by onelson** [comment]
I wonder if it's useful to consider the ergonomics or UX before the perf or other implementation impact.

I'm new here, so my observations are likely not as well developed as y'all but to my view, today:
- external sources produce streams of values that are difficult if not impossible to represent in "static flux" (eg at compile time)
- these "impossible" values are real and expected (we expect `_value` will be different from field to field, right?)
- the "impossible" is made valid only by avoiding inspection of fields that don't match what flux thinks is happening

So, right now it feels to me like the job of the developer is to "put blinders on" to avoid flux looking at things that it may regard as invalid. It's a lot like walking on eggshells - doesn't feel great.

In terms of ergonomics, there's a spectrum:

- permissive:
  - more accessible and forgiving
  - less easy to debug
  - less help when things aren't going the way the developer expects
  - "silent swallowing"
- strict:
  - less accessible
  - requires more upfront understanding of the schema/types of the incoming data set
  - higher precision feedback when reality doesn't match program specification

I'd like to know where we want to fit in the permissive/strict scale since it might guide us in this.

It seems like we want to be on the strict side, but without some sort of amnesty at the source to funnel arbitrary values until they conform to a strict spec, we can't get there.

---

Ergonomics aside, in the specific case that led us to this discussion, a question was if (forgive the pseudo-code):

```
// 2 separate filters
xs => filter(g, filter(f, xs))
``` 
should be equivalent to
```
xs => filter(x => f(x) && g(x), xs)
```
or, more as it would be today (with no short circuiting):
```
xs => filter(x => { 
  // both fns run, no matter what...
  a = f(x)
  b = g(x)
  a && b
}, xs)
```

If we say there _should be_ distinct (separate) filters (`f` and `g`) in order to explicitly narrow the record types such that `g` can run safely on the collection it receives, I think that's fine. The semantics for map fit this - you expect to have to transform data from type to type in order for some other receiver to accept the collection.

Still, looking at the 3 blocks of pseudo-code I'd say the 3rd one is the most unexpected looking. It's almost like we're trying to _pretend runtime is compile-time_, which feels a little disingenuous to me.

**Comment by onelson** [comment]
I was thinking about how other langs approach this situation. Rust is more strict than Scala, but the patterns between them are similar.

In Scala, you'd use pattern matching to interrogate values as you filter:

```scala
trait Animal

case class Cat(name: String, age: Int) extends Animal
case class Dog(name: String, age: Int) extends Animal
case class Fish(name: String) extends Animal

val xs: Seq[Animal] = Seq(Cat("Stanley", 15), Dog("Vinnie", 19), Fish("Sandra"))

// Exhaustive pattern (dropping Fish)
val ages: Seq[Int] = xs.flatMap {
  case Cat(_, age) => Some(age)
  case Dog(_, age) => Some(age)
  case _           => None
}

println(ages)

// Runtime exception!! because Fish doesn't match a pattern
val ages2: Seq[Int] = xs.map {
  case Cat(_, age) => age
  case Dog(_, age) => age
}

println(ages2)
```

It'd be a huge lift for us, but if sources produced a stream of `T` where `T` is a union of each record type discovered as we read from the source, _add assuming we had ways to pattern match or otherwise interrogate each value safely_, it would allow us provide these sorts of filtering/mapping in a type-safe way at runtime.

We could require a catch-all case for the things that don't match...

**Comment by Marwes** [comment]
> external sources produce streams of values that are difficult if not impossible to represent in "static flux" (eg at compile time)

I'd say the first problem is that we do not consider what `from()` etc actually returns, we only consider how the values are used after the fact.

```
from()
// We infer that the stream has the `a: Int` field, but we do not know that `from()` actually returned such a stream until we run it
  |> map(fn: (r) => { a : r.a + 1 })
```

Since we are only informed about types because of how we use them it becomes likely that static and runtime types do not match, especially in the case where we join multiple data sources.

I have thought a little about having union types like that, however it is not a straightforward feature as it is easy to be too permissive and give nonsense types.

For instance:

```
if x then
  1
else
   ""
``` 

Should that be a type error or typed as `int | string`. When you have an `int | string` type do you allow `+` if both sides are `int | string`? (and so on)

**Comment by onelson** [comment]
I agree that if we allow users to annotate `from()` etc, such that the types are known and enforced at the source, rather than being inferred by downstream nodes, it does seem like it solves a lot of this.

On the permissive/strict scale, it's hard to place this since on its face, it feels ultra-strict to require the user to know all the types of records that are expected from a source.  
We could add some permissiveness by way of something like record extension where the annotation is weaker, ex: "I expect fields a, b, c but others are fine" as well as some sort of way to specify how to handle things that don't meet the specification.  
Perhaps we can thing of this like applying encoding to raw bytes - often you can specify failure modes like: drop, replace, error (where "replace" will remove code points that don't align with the target charset with a placeholder value like `?`).

Representing reality for sources is still problematic without something like unions to describe the different types of records that a source can give.

Coming from a Rust or Scala perspective, unions make the most sense for this, but is there another approach? For Scala, unions come in a select few forms, namely by using traits as shown in my example above, or using a wrapper type like `Either[A, B]`.

In Typescript, it's all structural matching and gradual typing, so the nonsense case Markus gave would be quite legal, but operations like `+` would require the compiler to see runtime checks that narrow the type.

For example:
```typescript
let x: number | string;

// TS will complain that false is always false if
// we don't hide the value behind a function call...
function cond(): boolean {
    return false;
}

if (cond()) {
    x = 1;
} else {
    x = "hello";
}

if (typeof(x) === "number") {
    console.log(x + 2)
}

if (typeof(x) === "string") {
    console.log(x.toUpperCase())
}
```

[(playground link)](https://www.typescriptlang.org/play?#code/DYUwLgBAHgXBB2BXAtgIxAJwgHwgZzAwEt4BzAbgChKB6GiAFQGUIB3I4YCAYwHtkADsACGJCGAAWwyADNhwPCAhE8Eea2EBPVXIVKiM2vVZKAJr3gBySBKKmlkpQDd5iJelvxTaiDMTxuMCILHnlgADpIyj8AoJC+LwAKAEo4VF5eUGF4CABvSghCiAxwRAwc3UUqAF9qAwhEhNMU5LyCoqgIAF4IAEYaiBA9NqLobogAIgkh4F4JmrqZBrBNARBeGUSoVq7dyaQ0TAnW-NGEvEyQcNnSLYgAaggAJmTKWsp6xJW1ja2dvYmBGIZGOIyK50u114tyg4TAvAAqgI1hgAMLCRQtN5AA)

For Typescript, you have to prove to the compiler you've interrogated the value to the point of removing ambiguity, at least as is relevant for the specific operation you want to do.

**Comment by Marwes** [comment]
> We could add some permissiveness by way of something like record extension where the annotation is weaker, ex: "I expect fields a, b, c but others are fine" as well as some sort of way to specify how to handle things that don't meet the specification.

This is effectively how things work with row polymorphism right now, you can specify the fields you need but still allow for others to exist.

Something like typescript is probably the model that makes the most sense for flux, we are really just dealing with primitive types, sequences (arrays) and records. `enum`s like in Rust seems out of place and I wouldn't expect most users to want to deal with defining explicit types and wrapping them in constructurs and explicitly deconstructing things

**Comment by Marwes** [comment]
I don't think anyone is proposing that we actually short circuit typechecking (that is on the actual, typechecking done in rust). However typechecking during runtime alternates between fairly eagerly like here and lazily in the interpreter which is confusing for users. I would like it if we could force these checks eagerly however that would be a breaking change so we need to be sure we can do it. At the other end of the spectrum we perform typechecks as lazily as possible like the interpreter currently does which would not break anything since it allow for strictlly more code to run.

Having something in between these two extremes as we currently do will likely only bring more confusion as we will need to specify when types are checked eagerly vs lazily.

```
|> filter(fn: (r) => r._measurement == "m0" and r._field == "f0")
|> filter(fn: (r) => r._value > 0)


|> filter(fn: (r) => r._measurement == "m0" and r._field == "f0" and r._value > 0)
```

From a type perspective I'd argue that these are equally wrong (or right), splitting up the filter into two doesn't actually change the type of `r` in either closure they are both `{ A with _measurement: string, _field: string, _value: int }`. So either we check the actual runtime type lazily and both work or we check it eagerly (even before it gets into the first `filter`) and both are errors.

> First, there's the push down. I think the push down needs to be modified so that it keeps the different conditions separate. I think short-circuiting then needs to be implemented between these conditions in the storage layer. 

Is that reasonable to expect everywhere? For instance in iox we generate a single SQL query so I'd expect it to typecheck the entire query eagerly which would cause a type mismatch.

**Comment by jsternberg** [comment]
I'm a bit confused. Where are types checked lazily in the interpreter? Do you mean the compiler? Mistyped programs will generally never get into the interpreter, but the interpreter also has a decent chance of running without knowing all of the types.

You actually bring up something that I forgot to mention and I want to talk about. Filter is strange in that we can get some pretty strange types. If we do this:

```
|> filter(fn: (r) => r._measurement == "cpu")
|> map(fn: (r) => ({r with v: r._value + 1}))
```

The `r` for filter will infer that `_value` is an integer because of map and will reject valid tables that would have been filtered. There's an issue for this somewhere but I can't find it.

> Is that reasonable to expect everywhere? For instance in iox we generate a single SQL query so I'd expect it to typecheck the entire query eagerly which would cause a type mismatch.

It might not be. Definitely worth having a more in-depth conversation.

**Comment by Marwes** [comment]
> Where are types checked lazily in the interpreter? 

In the interpreter `(r) => r._measurement == "m0" and r._field == "f0" and r._value > 0`, `r.value == int` is only checked if `r.value > 0` is evaluated so if `value` is actually a string and the code never reaches that last predicate the code "works"

> The r for filter will infer that _value is an integer because of map and will reject valid tables that would have been filtered. There's an issue for this somewhere but I can't find it.

Yes, that is how type inference works. `filter` is a function that accepts records of type `A` and outputs records of type `A` which are passed to `map`. Therefore `r` has the same type in both functions. I guess we might envision some type system where types only flow "forwards" or doesn't flow "backward" in the specific case of `filter`, but I haven't seen anything like that before so I am not sure how it would work.

`builtin filter : (<-tables: [A], fn: (r: A) => bool, ?onEmpty: string) => [A] where A: Record`

**Comment by nathanielc** [comment]
DOD:

- Document conclusion from team discussion
- Create issues for next steps

**Comment by onelson** [comment]
# Summary of Working Group Discussion

The first look at this issue focused on _fixes for filter_ et al, but really the root cause is sources that can give heterogeneous records (ie, more than 1 table or schema).

With sources yielding strict schema-conforming records, the type mismatch we saw in the original issue (where the `MergeFiltersRule` caused a problem)

We noted that we could rely less on inference for sources if we could do a schema read before fetching data __if not for the fact that__:
- schema reads are historically _very expensive_.
- if the range/window of the dataset is non-exhaustive then the alleged schema could be just as incorrect as inference.

It seems that even with a strict schema for sources, we still have problems at runtime, ex:
- null fields (which can become apparent later than we'd really like)
- other kinds of sources (like things coming from http or csv?)

As a solution for these cases, we might consider adding a `Dynamic` type. The ad-hoc runtime type checks we have today are more expensive than they need be if we properly designed and implemented a `Dynamic` type. Still, there's risk of "infection" with this approach - weakening the type system overall.

If we are to drive towards having strict schemas for sources, there's a desire to take another look at the stdlib and try to revise the designs to better reflect the way things should be, reducing the complexity given by all the uncertainty we have today.
