### ISSUE TITLE
Parser treats 24h00m as duration + integer + duration

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4471]
The parser doesn't expect whitespace around duration or integer literals, which is probably correct. However this has a weird edge case where a typo in a duration literal will get parsed into a valid Flux script but that will have a very different meaning than what was intended.

For example

```
x = 24h01m
y = 07h01m
```

That text is parsed as a duration literal (24h) an integer literal (0) and a duration literal (1m). This is clearly not what the user intended and it is a surprising result. 

We should find a way to make this an error or otherwise inform the user about their typo.

DOD:
 - Find sane solution to parsing the above, potentially make it valid and make sense or potentially make it an error or any other sane solution. Sane meaning is doesn't violate the principal of least surprise. 
 - Add/Update test

**Comment by jsternberg** [comment]
This is interesting. I agree this is probably not ideal. We might just want to change the scanner grammar to be a bit more lenient on what it considers to be an integer literal to include leading zeros. At the moment, this is the scanner definition for integer literals: `"0" | (digit - "0") digit*`.

This is to prevent `0123` from being an integer literal. The scanner definition, in my opinion, is correct. But, it has this unfortunate side effect where `00` is considered to be two integer literals instead of just an error.

I propose we change the integer literal definition to `digit+` and we catch this error when parsing the integer literal.

The reason I'm mentioning integer literal rather than duration literal is that duration literals are defined as `int_lit duration_unit` and this same use case would happen for integer literals too.

**Comment by Marwes** [comment]
When I was arguing for leading zeroes that was under the assumption that `61m` would be invalid due to being out of bounds (specify it as `1h1m` instead), but that seems to not be the case and each number should be treated as an arbitrary integer. So making a leading zero be an error may make more sense then.

**Comment by onelson** [comment]
Maybe I misunderstood here, but since we're talking about duration, not clock times, there shouldn't be any upper bounds (based on clocks, anyway). I'd expect `8h120m` to be equivalent to `10h` as well as `600m` (regardless of leading zeros).

**Comment by jsternberg** [comment]
Whoever picks up this issue is responsible for creating a meeting for us to decide the proper way to fix this. The implementation will follow from whatever we decide should be allowed/disallowed.
