### ISSUE TITLE
array.from() does not work with the output of json data

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4479]
The `array.from()` function does not work with the output of json data. At the moment, the code checks to make sure that the array element type is receives is a record based on the information from the type system. When the type is unknown or dynamic, such as parsing json, the check fails.

The line of code that is causing this error is here: https://github.com/influxdata/flux/blob/f717e059924b8bdd59fa1f1de0e0ef18a97485db/stdlib/array/from.go#L120-L122.

DOD:
- Investigate/Fix static type behavior of `array.from`
- Flux acceptance tests are added showing how to use dynamic to consume JSON and produce a table.
- Add doc examples to source code showing this workflow of using dynamic type.

**Comment by jsternberg** [comment]
The cause of this problem is related to the [dynamic type proposal](https://github.com/influxdata/flux/issues/4483) and may be something that gets fixed by it, but we should still fix it in the existing system even if dynamic would make it more clean.

**Comment by Marwes** [comment]
Another way of looking at the issue is to view it as an issue in the `from` signature.

```
builtin from : (rows: [A]) => stream[A] where A: Record
```

This forces the type variable `A` to have the record kind, however that doesn't make the `data` binding to have the `Record` (object) type. If allow record types to be polymorphic, without requiring any specific fields we could define `from` as

```flux
builtin from : (rows: [{ A with }]) => stream[{ A with }]
```

Type inference would then see that `data` is an array of records instead of an array of type variables of kind record which would  be reflected in the static type checked on the go side making the check against the static type redundant (could still get dynamic errors from `json.parse` however).

Currently this is not possible because the record type is defined to either be empty or have a field with a possibly polymorphic tail.

```
pub enum Record {
    /// A record that has no properties.
    Empty,
    /// Extension of a record.
    Extension {
        /// The [`Property`] that extends the record type.
        head: Property,
        /// `tail` is the record variable.
        tail: MonoType,
    },
}

```

**Comment by onelson** [comment]
Just to reiterate Markus' point re: `dynamic`, #5286 included changes to make sure `dynamic` will fail to constrain to `Record` and so trying to feed the output from `dynamic.jsonParse()` into `array.from()` will fail at compile time.
This should force callers to convert out of `dynamic` beforehand.
