### ISSUE TITLE
Filter does not drop empty tables when it is not pushed down to the storage engine

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#45]
The storage engine will not include empty tables when they are filtered out because of a tag, but the filter function inside of flux just leaves the table empty so you end up with different results depending on whether that optimization happened or not.

**Comment by nathanielc** [comment]
We need to specify how to treat empty tables:

Should empty tables be filtered?
Should they be filtered only if its filtering on the group key?

How could we return empty tables from storage if no data exists for a range or because of a _value filter?

The answer seems to depend on how filter interacts with the group key.

**Comment by aanthony1243** [comment]
this came up in discussion today.  One need for empty tables is so that `count()`  gets a correct number where a user will want to know if a group key has 0 results.  This is probably the most prominent case, but any aggregator will generate a similar discussion.  Empty tables mean something when you aggregate.

**Comment by juliusv** [comment]
This is hitting me when filtering, then aggregating, and then processing the result further. I end up getting a lot of tables with `null` values in the second step, which breaks further processing (e.g. I want to apply another `filter()` on the aggregated result to only keep aggregations with a certain `_value`, but having `null` values in filter conditions results in an error).

**Comment by juliusv** [comment]
Counter to my comment above, keeping empty windows can also be useful in some situations of my PromQL->Flux transpilation work. When implementing Flux versions of PromQL functions such as [`time()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#time) or [`absent()`](https://prometheus.io/docs/prometheus/latest/querying/functions/#absent), there may be no underlying data to work with, but I still require one output row per original window, even if it's empty. Especially for `time()` I would want to create windows that aren't even based on any selection from a datastore at all. If that's not possible, I could still generate windows manually in the corresponding custom Flux functions, but it would be nice to reuse `window()` for windowing in those cases.

**Comment by jsternberg** [comment]
Fixed by #2278.
