### ISSUE TITLE
Explore the concept of bounded variadic record extensions

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4513]
The flux type system allows us to extend a record with the `with` keyword to include additional named columns:

```
{r with a: 1, b: "foo"}
```

This works well for many situations, but it can be quite difficult in some circumstances when we want to wrap common functionality in another function. For example, say I wanted to turn the above into a function like this:

```
extend = (keys) => (r) => ({r with keys})
extend(keys: {a: 1, b: "foo"})
```

This isn't possible even though it would technically be possible for me to expand the input record and write the same syntax.

I'd like us to explore the idea of allowing variadic record extensions where the above might be written like:

```
extend = (keys) => (r) => ({r with keys...})
```

It would only work if the input to keys was bounded.

DOD:

- Write proposal for new syntax and new semantics
- Explain feasibility of the new feature (i.e. convince us that it can be implemented)
- Working group to discuss and present proposal

**Comment by Marwes** [comment]
To support the `extend` function we would need to allow `...` to work with unbounded records (try writing the type for `extend`). The `...` syntax itself could be an easier first step though as we could directly force any record used in `...` to be bounded during typechecking which ensures the easier semantics of bounded records (since we know all the fields, it is equivalent to the user just writing  out `{ r with x: keys.x, y: keys.y }` etc).

For possible semantics with unbounded records we have https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/scopedlabels.pdf as a good resource.

**Comment by Marwes** [comment]
I think this could be done fairly simply.

1. Add a syntax for record extensions. The trailing `...` seems prevalent in other languages like typescript as well so seems reasonable to me at least.
2. Thread the logic for that syntax through the AST, semantic graph and go interpreter. Since we limit this to bounded records, the semantic of extending a record is the same as explicitly listing the fields.
```
x = { a: 1, b: "" }

y = { r wtih x... }
// Equivalent to
y  = { r with a: x.a, b: x.b }
```
(If we want to avoid updating the semantic graph on the go side we could add a transformation step after type inference to do the rewrite above as we would know the type at that point).
3. To prevent users from passing in unbounded records we do another pass over the semantic graph after type inference concludes and check that the type of `x...` is bounded (check that the type ends with  `Record::Empty`)

**Comment by nathanielc** [comment]
@Marwes Do you expect that the inference logic has to change? For example what is the inferred type of `y` in your example. If at a final pass we know `x` how do we know what `x` is while doing inference so that we can correctly type `y`? The record extension type won't let us extend both `r` and `x`.

**Comment by Marwes** [comment]
Oh, damn. True, type inference would require changes as well. Didn't think that through fully.

**Comment by wolffcm** [comment]
> However that would act as a "firewall" where we could not infer any more fields on s after the extension expression.

Would this limitation still allow for the use cases we want to enable in the stdlib? I guess it would not, but I am forgetting the connection between this type system feature and the kinds of backwards compatible changes we want to make to the stdlib.

**Comment by Marwes** [comment]
Do you mean `extend = (keys) => (r) => ({r with keys})`? That would require the extension to support unbounded records as you would need to type `extend` as `(keys: { K }) => (r: { R })  => { R with K }`.
