### ISSUE TITLE
semantic::nodes::Package.loc is incorrect

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#4524]
When analyzing an ast package with more than one file, `semantic::nodes::Package` has a `loc` field that is created with `ast::SourceLocation::default` but never then updated. This means that the `start` and `end` positions are `0`[1], and the `source` and `file` are both `None`. This kinda removes the value of having the `SourceLocation` in the first place.

[1] Line `0` and Column `0` are both invalid positions, so _maybe_ there's value in having them set to zero to signal some issue, but I don't think they should be the default, but maybe it's a sign that _any_ default implementation would be wrong.

**Comment by rockstar** [comment]
I looked at this for a timeboxed 30 minutes this morning. It looks `SourceLocation::default` is used to indicate an error state, and is particularly important in deserialization, where we (a) can't validate it beforehand and (b) can't error. It's definitely not a 30 minute fix, and probably needs a conversation around what the valid paths forward are.

**Comment by Marwes** [comment]
I think this is just a consequence of every variant in `Node` needing to hold a `BaseNode` since `Node` has the `fn base(&self) -> &BaseNode` function. Since a `Pacakge` has neither file or location there isn't a `BaseNode` that makes sense for it so we either have to accept having a "null" value, remove `Node::Pacakge` or make `Node::base` return an `Option`.
