### ISSUE TITLE
Move libflux to its own repository

### ISSUE THREAD

**Issue by driesmp** [influxdata/flux#4535]
Packaging for FreeBSD would be a lot easier if we could decouple the rust code from the GO code. Most major reason is easier packaging. Right now during a GO build libflux wil want to fetch rust crates, which is not allowed in our infrastructure. 

Everything under influxdata/flux/libflux could be moved to influxdata/libflux (a RUST only repo). 
The influxdata/flux rep would then contain the GO bits.

Thoughts?

Related ticket at influxdb repo: https://github.com/influxdata/influxdb/issues/23009

**Comment by driesmp** [comment]
Another way is that I split up the build process of libflux from the go bits. But then my question is, can I preseed to libflux.so library to the GO build? Does the GO build use pkg-config or a similar tool to search for installed libraries on the system?

**Comment by jsternberg** [comment]
Hi. I'm curious what you're trying to do, but I can likely explain the build process a bit since I think it is amenable to what you want to do without any changes to the existing build.

First, a quick explanation. The Go code will compile and link to whatever `pkg-config` tells it for the `flux` library. It invokes `pkg-config --cflags flux` and `pkg-config --libs flux`. Everything else is window dressing for convenience in our build process. So the answer to your question is yes you can use `pkg-config` to control how to link to libflux for the Go build.

I can likely explain why the current build process is the way it is and then why that's not really relevant to package management.

The big problem from a development perspective with trying to decouple the two is that libflux doesn't really follow any kind of specific semantic versioning. This is because we mostly just build the two when the are together as a kind of semi-monorepo. Any outside projects, like the LSP, that use it will also match to a specific version. That means that version `X.Y.Z` of Go is really only guaranteed to be compatible with `X.Y.Z` of libflux in Rust. This is especially true for development where there's a certain expectation that if I modify the Rust code I'll see the change in the Go code even though they're two different versions.

That's why the `pkg-config` program exists. It's just to help with our personal development and deployment. It takes care of all of the ugly stuff of making sure that development version `X.Y.Z-randomhash` is both compatible and linked to development version `X.Y.Z-randomhash` of the Go program. Outside of our personal development and deployment, it's both not important and also not needed. These issues don't arise as much in package systems because they don't have to deal with an infinite different amount of development versions.

From the Go code perspective, it is not aware of anything being special and it _thinks_ it is already using a package management version of the library. The Go code invokes whichever version of `pkg-config` it has been configured with to determine the cflags and ldflags.

That means that instead of using our `pkg-config` helper tool, you can build a libflux package completely separately and install a `flux.pc` somewhere of your own handcrafting. See [this section](https://github.com/influxdata/pkg-config/blob/master/libs/flux/build.go#L258-L291) of code for how the helper tool dynamically generates the file. In a package management context, you can statically build this file and install it on the machine alongside your compiled version of the code. You can also have it link `-lflux` instead of `-lflux-buildid`.

For separating them into a different repository, this would add a lot of friction for our own development. Rust changes are commonly accompanied by Go changes and the two aren't really considered different libraries at this point. When the language is more mature, we might try to stabilize the libflux ABI so this isn't the case, but we'll still likely keep the two connected because for our own personal deployments there's never a time when we want to use an older version of libflux in our Go code.

If I remember package management systems correctly, it should be possible to build multiple packages from a single source repository so I don't think there's anything we would need to do to make creating suitable filesystem packages. I think the only downside is that you would need to have the packages depend specifically on the exact same version so you'd need to `X.Y.Z` of the Go package to depend exactly on `X.Y.Z` of the Rust library.

**Comment by driesmp** [comment]
Very clear thanks. This has helped a lot already. So my current idea is to use one versioning scheme that will create two packages. Versioning scheme will follow the flux repo versioning. The two packages will then be, 1) libflux (rust bits) 2) flux (the go bits). Package 2 will depend on package 1. Is there a way to make the tool create the file ((lib)flux.pc) or will I have to do that manually for now? Would be create if it could be generated.
