### ISSUE TITLE
Multi file packages only work if the files are ordered perfectly

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#4538]
Consider the following two files, in the same directory.

```
v = {id: "123", duration: -12h}
```

```
from(bucket: "my-bucket")
  |> range(start: v.duration)
  |> filter(fn: (r) => r.tag == "my-tag")
```

When made into an AST or semantic graph, the resulting `files` property _must_ have the the right order (usually by random luck) in order for the `v` to be defined by the time it's used in the second file.

I couldn't find a definition in the spec for how these files should be ordered, or whether they should be ordered. If they aren't supposed to be ordered, I think there's a significant lift in how flux works, because currently the following won't work:

```
from(bucket: myBucket)
  |> range(start: myRange)
  |> filter(fn: (r) => r.tag == myTag)

myBucket = "an-bucket"
myRange = -1m
myTag = "an-tag"
```

**Comment by nathanielc** [comment]
The design in the SPEC is that the order of assignments should not matter, including across files. From the [SPEC](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#assignment-and-scope):

> An assignment binds an identifier to a variable, option, or function. Every identifier in a program must be assigned. 
> Flux is lexically scoped using blocks:
    - The scope of a preassigned identifier is in the universe block.
    - The scope of an identifier denoting a variable, option, or function at the top level (outside any function) is the package block.
    - The scope of the name of an imported package is the file block of the file containing the import declaration.
    - The scope of an identifier denoting a function argument is the function body.
    - The scope of an identifier assigned inside a function is the innermost containing block.
> Note that the package clause is not an assignment. The package name does not appear in any scope. Its purpose is to identify the files belonging to the same package and to specify the default package name for import declarations.


The language of the SPEC is that identifiers belong to blocks. It is implied that the order of statements within these blocks is not important rather that any identifier defined within a block is available to other statements within the same block.  The SPEC separates out package scope from file scope. Meaning that an identifier defined in one file is available in any other file, it is implied this is independent of any order of the files.

Perhaps we should make the implication that order is not important explicit within the SPEC? 

This means that we need the scopes to work like you suggest in your second example, where the assignment can appear after the usage. I am not sure how difficult this is to solve and we could consider a different solution if one is proposed. However we do not want file order to matter for exactly the reason in that there is not a clear order in which the files should exist. It would be surprising to rename a file and discover that your package broke because of the change. This is why the SPEC defines scope independent of order as its what the user expects.

Thoughts?

**Comment by rockstar** [comment]
> we need the scopes to work like you suggest in your second example, where the assignment can appear after the usage.

This is the answer I suspected would be The Right Thing™ in this situation.

> It would be surprising to rename a file and discover that your package broke because of the change. 

Yeah, that's why the hack in the lsp is the grossest kind of hack. Unless you know what you're doing (and we'll have to tell the UI team who drove this work), you could easily get into a really confusing situation, not to mention file names don't really matter for other similar package systems.

I, too, don't really know what's required here, but I think we should prioritize this work relatively soon, as ambiguity is only going to get worse as we start working towards more of our goals, e.g. user defined packages.

**Comment by Marwes** [comment]
It is not possible to allow a binding to be used before it is assigned in all cases. Some cases where it could work also leads to confusing code (IMO).

```
// Functions work
f = () => g()
g = () => f()

// Doesn't work
y = x + 1
x = y + 1

// Could work, but it is rather confusing that `x + 1` would refer to the `x` inside the function
x = ""
z = () => {
    y = x + 1
    x = 1
    return y
}
```
