### ISSUE TITLE
Impossible to build flux, since it depends on… flux

### ISSUE THREAD

**Issue by dmilith** [influxdata/flux#4634]
Basically:

`go build -o ${PREFIX}/bin/flux ./cmd/flux`

is crashing with

```
# pkg-config --cflags  -- flux
Package flux was not found in the pkg-config search path.
Perhaps you should add the directory containing `flux.pc'
to the PKG_CONFIG_PATH environment variable
Package 'flux', required by 'virtual:world', not found
pkg-config: exit status 1
```

So it depends on itself… while the project doesn't contain any *.pc files.

**Comment by rockstar** [comment]
This error can definitely be confusing. What it's trying to say is that it can't find `libflux`, which is a library that provides the scanner/parser/semantic analysis. What's failing here is a shim that we created so that when you build flux, it implicitly will build `libflux` (written in rust) as part of the build process, and then link that library to flux.

Check out the [Getting Started section of the README](https://github.com/influxdata/flux#getting-started), where you can read about configuring the shim (which we probably poorly named `pkg-config`). If you get that set up, you'll be able to `go build ...` flux.
