### ISSUE TITLE
Spike Preview function

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4659]
In order to enable rapid iteration on complex queries we could add a `preview` function. This function would only produce a subset of the data requested by the query optimizing for minimizing the time to run the query. The concept is that by adding a preview function a user can iterate on their query getting enough feedback that they are building the correct query but not having to deal with long wait times for large queries.

Currently users simply reduce the time range of their query to reduce the work of a query. This does not always work and its worth investigating a more direct approach to this problem.

## Proposal

Add a `preview : (<-tables: stream[A]) => stream[A]` function to the stdlib. This function will produce a subset of the results at the cost of producing accurate results. For example this query the `preview` function could act similar to a limit on tables and rows:

```
from()
   |> range()
   |> filter()
   |> preview()
```

However for this query the `preview` function would be more aggressive:

```
from()
   |> range()
   |> filter()
   |> sort(column:["a"])
   |> preview()
```

If we wait for the `sort` to complete and then simply limit the result we have not accomplished our goal as the query still has to pay the cost of doing the full sort on all the data at which point we could have just returned all the data to the user. 

In other words `preview` is not simply a limit on the query rows or tables, rather a more complex operation.

### ~Execution aware preview~

We could rewrite the preview out of the plan DAG but then set some properties on the execution engine to watch the transports and introduce limits. Something like never pass more that 10 chunks between transformations. Perhaps this could be somewhat _smart_ in that the execution engine enters a mode that prioritizes processing data as deep as it can through the execution DAG and only processes data of predecessors until data for a client is produced. 

### ~Chunk Limits~

Another approach could be to have a planner rewrite rule that rewrites `preview` operations into a chunk limit transformation that gets pushed as close to the sources as possible. This way we don't have to implement any special logic the pause and resume the execution engine. However there is a risk that the query doesn't produce any data.

### Anything Else?

Part of this issue is to explore other possible implementation and maybe even try them out and report on how they worked.

### Source Limit (aka Preview the source)

Implement the preview as a subset of the raw data from the source, make this behavior super clear to the user by using `preview` inplace of `from`. 

```
preview(bucket: “my bucket”) |> your_query() 
```

Advantages:

- Could generate synthetic data based on the schema of the buck
- Could have parameters for how much data to preview etc

## Questions to Explore

- Pivoted data? How can we be sure we get all of the fields? We want a spread over time and at least some data from all fields 
- Synthetic data? - semi synthetic data, use the tag key and tag values to generate rows (perhaps this would be very confusing)
- How often does it occur that a secondary filter removes all previewed data?

DOD:

- Time box exploration of a preview function as a source limit i.e `preview(bucket: “my bucket”) |> your_query() `
- Document learnings
- Create next step issues from learnings

**Comment by jsternberg** [comment]
Initial update on this. I tested this out by adding a new preview function and having it be a storage primitive. Then I wired it into influxdb. I generated 50,000 points of test data with a cardinality of 50. I set it so preview restricts the cardinality to 10 and to reading 1 block of data (so 1,000 points usually).

So far, I would say that it is overall positive. The query that I did took 800ms when running the full thing and 100ms after I used preview. That's a pretty dramatic improvement. One thing I learned though is that aggregate window's default behavior is not ideal when doing this. Since create empty is the default and I am arbitrarily limiting the range, aggregate window starts creating null windows like crazy. This might limit the utility.

I'm going to explore the idea of using an option for preview mode where the option disables create empty. I'm not sure if that's a good idea or not. My personal preference is that aggregate window shouldn't have create empty be the default, but that ship sailed long ago.

@nathanielc thoughts on the above? I don't really like my proposed solution for aggregate window, but I can't think of anything else at the moment.

**Comment by jsternberg** [comment]
I'm having a lot of difficulty getting the option to be readable. We have a `GetOption` function, but it doesn't seem to work properly with universe. I thought it might be an easy change but it doesn't seem to be.

I think I might be convinced this is a reasonable course of action and that I've learned enough we can plan other issues and design what it might look like. I'm going to ask around to see if there's anything else we want to test before closing this, but I'm pretty convinced the above is correct and would be useful. The aggregate window stuff may even be optional. The key takeaway is that the push down needs to be involved with preview and I actually quite like the preview function syntax as I think it's more explicit than an option.

**Comment by jsternberg** [comment]
I created a working group for this. I will reopen if there are additional questions that need to be researched that come out of that working group.
