### ISSUE TITLE
POC: Introduce the concept of node attributes to the planner

### ISSUE THREAD

**Issue by scbrickley** [influxdata/flux#4678]
In order to implement #4628, the planner needs to understand what nodes do and don't disrupt sorting. It would be helpful if each node had a list of attributes that the planner could reference when making judgments about how to rewrite the query plan.

Their is some prior art for this regarding parallel queries. Using that work as a reference, and generalizing it to handle other node attributes should get us the functionality we need.

@jsternberg Has a POC that may be useful to review for whoever picks up this issue: https://github.com/influxdata/flux/issues/2131

We should be able to look at a plan and verify that `MergeJoin` is receiving data sorted by the columns defined in the `EquiJoinProcedureSpec`

We should have a way of verifying that a physical plan nodes required attributes are satisfied by its predecessors. We do not want to accidentally remove a necessary sort node, or otherwise create an invalid plan. Perhaps we need a final validation step in the planner.

We also want to make sure that we can propagate certain attributes across the query plan. Nodes should be able to "ask" their parents about the attributes they provide. If the answer is unclear, those nodes should reference their parents, and so on and so forth.

DOD:

- A `PhysicalAttr` exists that signifies whether or not a node outputs/preserves sorted data, and if so, which columns that data is sorted by
- The solution should be able to support other types of attributes too
- If needed, follow-up issues are created to track work on a finished implementation

**Comment by onelson** [comment]
Probably needs a design/working group session to decide how to proceed.

**Comment by onelson** [comment]
# Prior Art

The work done towards parallel execution of portions of the plan has introduced the concept of _attributes_ which are used to signal properties/qualities of the nodes in the graph.

I first came into contact with this while working on #4465 since there were some overlapping concerns around calculating the concurrency quota for a plan.

In the executor, I saw access to `ppn.OutputAttrs`, which is one of 2 attribute sets on a `PhysicalPlanNode`.

https://github.com/influxdata/flux/blob/03b81dd347830e679f169a45ee04e48ed23b8605/plan/physical.go#L282-L286

In the executor, as we visit the nodes in the plan, we can inspect the attributes and possibly extract values they might be carrying.

https://github.com/influxdata/flux/blob/03b81dd347830e679f169a45ee04e48ed23b8605/execute/executor.go#L174-L198

From what I could tell, the pattern in this case is for attributes to be initialized during planning, then consumed during execution.

**Comment by wolffcm** [comment]
Here's an overview of how things currently work with attributes for parallelized execution. We can parallelize queries of the form
```
from |> range |> filter |> aggregateWindow |> to
```

This works by planning the query as normal, so it looks like this
```
ReadAggregatewindow |> to
```

There is an additional planner phase (with some special rules related to parallelization) that transforms the above to:
```
ReadAggregateWindow[parallel] |> To[parallel] |> PartitionMerge
```

The rule that makes this transformation sets some attributes on these nodes:
- `ReadAggregateWindow` and `To` get the `ParallelRun` attribute set in their `OutputAttrs` for their plan nodes
- `PartitionMerge` gets the `ParallelMerge` attribute set on its `OutputAttributes` and has `ParallelRun` set on its `RequiredAttrs`

When planning is complete we do a check that any node that has `RequiredAttributes` has them satisfied by predecessors (this part is already generic):
https://github.com/influxdata/flux/blob/e1d08a146b9b7a4f6e57cbaaa5fd44b271da0bb4/plan/physical.go#L113-L134

Finally, when we build the execution graph, we look at the plan node attributes to determine how many copies of each parallelized section of the plan to create.

## Generalizing Attributes

Thinking about how the current start of can be generalized a few concerns come up:
- Sometimes a plan node provides an attribute because the transformation it represents enforces it. E.g. a sort node would provide a `SortedTable([colA, colB,...])` property
- Sometimes a plan node provides an attribute because _we say that it does_ in a planner rule. For example, setting `Parallelrun` on `ReadAggregateWindow` will parallelized branches in the execution graph to be created. (It seems strange that an attribute would alter the behavior of a node---this could be an anti-pattern?)
- Sometimes a plan node provides an attribute because its input provides it, and it doesn't do anything to perturb it. For example a `filter` that succeeds a `sort` node will still produce sorted output, even though `filter` does not do any sorting itself.

For nodes that propagate inherited attributes, it seems like a bad idea to store the attribute on the node itself during planning. The planner could alter the plan such that it no longer provides the attribute. It seems better (at least for now) to traverse the predecessors of nodes to find out if the desired attribute exists. This would be a divergence from the current implementation of the parallelization attributes.

## More Prior Art
The open source project Apache Calcite is an implementation of Volcano implemented in Java. They have a concept of "traits" on the relational (plan) nodes here:
https://github.com/apache/calcite/blob/d9a81b88ad561e7e4cedae93e805e0d7a53a7f1a/core/src/main/java/org/apache/calcite/plan/RelTrait.java#L25-L40
I'd like to look at how they handle some of these challenges to see if anything might apply to Flux.
