### ISSUE TITLE
Possible Performance Bottleneck with Many Small Groups

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#4679]
The design of our execution engine makes it more performant when there are few groups and many rows in those groups. For the opposite case, where there are many small groups, we incur a high overhead for each operations that is processed by each group.

Consider a query like this one, where source data has group key columns `host` and `region`. `host` has high cardinality, and `region` low:

```js
source() |> group(columns: ["region"]) |> sum()
```

The `group` transformation will need to process every table from `source`. For a small fixed number of regions, this query will perform more poorly as the number of hosts increases. In general it will hold that for a fixed number of total rows, the same query will perform worse if the number of groups increases, since message processing overhead will increase as well.

Here's some suggestions to work around this limitation. These are some thoughts around the long term design of the execution engine and are intended to provide some context for a larger discussion.

## Allow transformations to process multiple groups in a single message

If each transformation was able to process multiple groups in a single invocation, then we could reduce the overhead of the transport layer of execution. We might consider modifying sources to produce batches, regardless of the group key (like a fixed size of 1000 rows, or some other number based on the number of columns), with the caveat that batches must all have the same schema.

This idea is important when considering the item below.

## Don't put `group` in initial query plan

Let's step back and think for a moment about how a conventional relational engine might plan the above query. Many relational query engines have two different ways to aggregate data:
- Serially, by ordering the data such that rows in the same group are all adjacent. This can be achieved by scanning a table with an appropriate index, and it can also be achieved by sorting the data at runtime. This is friendly to streaming, provided an index is available. Sorting requires buffering the rows.
- With a hash table, aggregation will buffer data, but input data does not need to be in any particular order.

In a relational engine, hash aggregation and serial aggregation are modeled as distinct operations, since they have different characteristics in terms of utilization of CPU and memory. A planner that knows about its input data can create an optimized plan by estimating resource usage at runtime, e.g., choose the fastest plan (lowest CPU cost) that doesn't need more than _x_ GB of memory.

But significantly the `GROUP BY` clause in a SQL statement does not itself have any particular operation in the query plan. If the planner chooses serial aggregation, we may see a `sort` node in the query plan that allows for it, or we may see the planner choose an appropriate index to scan the table's rows.

The sample query above would be similar to a SQL statement like 
```sql
SELECT tag0, tag1, ..., SUM(field0), SUM(field1), ... FROM t GROUP BY region
```

And a plan that performs hash aggregation might look like this, in pseudo-Flux syntax:
```
scan(table: "t") |> hash_aggregate(fn: sum, group_by: ["region"])
```

If we now turn our attention to Flux, the concept of a table's "group key" has these semantic implications from the user's perspective:
- When narrow operations are applied, like aggregation, selectors, or other transformations like `difference` and `derivative`, those operations are applied _per group_.
- When the results are returned to the client, they are grouped by the group key.

Nothing about these two bullet points prescribe that `group` is a physical operation that must be performed during execution. Similar to a conventional engine, the planner could choose to insert a physical `group` operation into the plan, or it may not, depending on the affected operations.

The current implementation of `group` does not do very much work at all, and really just serves to partition the data in such a way as it can be consumed by downstream transformations. If downstream transformations do not require this partitioning because they can process multiple groups per message, then `group` could often be unnecessary.

For example, we might decide that it's okay to omit any physical grouping operation at runtime for aggregation. If we know that the incoming data is sorted amenably, we can aggregate serially, and if not, hash aggregation is always an option. (Given that we don't know all the tag keys on InfluxDB data during planning, it would be hard to decide between serial and hash aggregation for the plan. I wish that we could!)

## Putting it all together

With the above suggestions in place, the query above could be  expressed as a two-node plan similar to the SQL plan above. It would be faster than how our existing engine performs, and would scale more closely with the amount of data processed rather than the number of rows, given that:
- The `source` produces batches of rows that may include multiple groups in a 
- The aggregate node that follows the source can process batches that contain multiple groups
- The intermediate `group` transformation is no longer needed at all

This is a simple example, but it seems possible to extend it to the other operations that Flux supports to achieve similar gains.  Some operations can be performed efficiently only if the rows are in the same group are adjacent, so some sort of physical grouping would still be necessary. `difference` and `derivative` come to mind. But this design could provide several advantages over the current state of affairs.

**Comment by jsternberg** [comment]
This is an important thing for us to check. There's some caveats in the description though.

First, it's likely inaccurate to say that this chunk thing is new. The group transformation has used chunks for awhile. The difference is it grouped all of the chunks together and sent them at the same time. For example, if I had a cardinality of 10 and used group to put them all together, it would send one table, but 10 chunks within that table. This was represented by calling the `Do()` method.

But there is a difference from the proposed new method of interacting with table chunks. In the old way, we would know that all of the table chunks for a group key would be processed together and we could perform any "full table operations" over the entire thing. Things like normalizing the schema, compiling functions for filter/map, and anything else that relied on full knowledge of all of the chunks, could be done once, stored in a local variable, and then used right then.

With the new architecture, that's a bit harder. Since group keys can arrive out of order, that local state has to be saved somewhere so it can be restored. It's likely good to investigate that and see if we can optimize that process. Alternatively, we can determine that it's causing problems and go back to batching table chunks of the same group key together.

We also haven't enabled the table chunks for the group or aggregate functions yet. There were some lingering questions and our data didn't show clear performance improvements so they didn't get enabled. It's likely good to revisit this so that we can enable them if they are working properly or revisit why they aren't giving us the performance or throughput we're looking for.

**Comment by wolffcm** [comment]
@jsternberg I have completely rewritten the prose above that captures better what I'm trying to express.
