### ISSUE TITLE
Planner rules sometimes do not fire when they could

### ISSUE THREAD

**Issue by wolffcm** [influxdata/flux#4699]
Consider this test case
```js
testcase sort_limit_zero_row_table {
        input = array.from(rows: [{foo: "bar", _value: 10}])
                |> filter(fn: (r) => r._value > 10, onEmpty: "keep")
        want = input
        got = input |> sort() |> limit(n: 5)
        testing.diff(got, want)
}
```

The plan for this looks like so:
```mermaid
graph TD
  array.from0
  filter1
  sort2
  limit3
  diff4

  array.from0 --> filter1
  filter1 --> sort2
  sort2 --> limit3
  filter1 --> diff4
  limit3 --> diff4
```

There is no reason why we should not be able to merge the `sort |> limit` part of the graph into a `SortLimit` node. However, the planner has some checks that prevent this from happening. When we check pattern for the `SortLimit` rule, we start by matching in the `Limit` node, which passes, and then it recursively checks that the `Sort` part of the pattern also matches. However, this part fails to match because the predecessor of the `Sort` has more than one successor. That causes this check to fail:
https://github.com/influxdata/flux/blob/1c35d563c72e9cf79f60666fad8881ac41fda607/plan/pattern.go#L99-L104

DOD:
- update the planner such that we can transform a graph like this
- Add a test that shows it works
- Update the `sort_limit_zero_row_table` test case.

**Comment by jsternberg** [comment]
This might be caused by how I coded the pattern. I had to use `any |> sort |> limit` because when I did `sort |> limit` it seemed to insist that the sort should have no predecessors (aka a source). This caused the rule not to fire so I thought that I needed to add the any at the beginning to tell it that sort would have one predecessor. This seems to be interfering with the rule firing in the above situation. We might want to fix the cause of what I originally ran into and then change the rule to be only `sort |> limit`.

**Comment by nathanielc** [comment]
I recently also ran into this bug when trying to join an input table with itself. @wolffcm and I chatted about this and we think we have a solution. 

The core of the problem is that the pattern matching logic expects there to be only a single edge between a node and its matched predecessor. This works and is required for rules that intend to merge the matched nodes into a single node. For example From -> Filter, if the from has other successors you can't merge the filter into the from. In other cases this restriction is not needed and prevents the rule for matching when it is safe to do so. For example a join node whose predecessor has a different successor, since the join rule doesn't rewrite its predecessors it doesn't matter if they have other successors. 

To solve this we need to be explicit about whether a pattern match can have multiple successors or not. I propose we replace the existing `plan.Pat` function with two functions `plan.Multi` and `plan.Single`. `plan.Multi` will match a node and will allow that node to have multiple successors, while the `plan.Single` will match a node and that node must have exactly one successor. This changes two things about current patterns, first it makes the number of successors expected explicit in the pattern, second it moves the specification of which nodes can have multiple successors and which cannot on the pattern that matches the node instead of the successor of the node. Additionally `plan.Any` will allow multiple successors. 

How does this look for existing patterns? Here are three existing patterns and how they would be refactored using these new semantics.

```
// EquiJoinRule - Original
plan.Pat(Join@Kind, plan.Any(), plan.Any())
// Refactored
plan.Multi(Join2Kind, plan.Any(), plan.Any())

// MergeFilterRule - Original
plan.Pat(universe.FilterKind, plan.Pat(FromRemoteKind))
// Refactored - here we are explicit that From node must have exactly one successor, aka the filter node
plan.Multi(universe.FilterKind, plan.Single(FromRemoteKind))

// SortLimitRule - Original, this has an extra Any so that the predecessors to sort may have extra successors
plan.Pat(LimitKind, plan.Pat(SortKind, plan.Any()))
// Recactored - here we are explicit that there must be only one successor of sort so that we can merge the limit node into it
plan.Multi(LimitKind, plan.Single(SortKind))
```

**Comment by wolffcm** [comment]
One scenario that I'd like to see addressed is being able to deal with what happens when a node is removed from the plan altogether. Consider `RemoveTrivialFilterRule` as it is today:
```
func (RemoveTrivialFilterRule) Pattern() plan.Pattern {
    return plan.Pat(FilterKind, plan.Any())
}
```
If we were to remove the `Any()` from the end of the pattern, then it would match any filter even if its predecessor has multiple successors. For a case like this one:
```
src = from(...)
g = from |> filter(fn:(r) => true)
g => yield("0")
g |> map(...) |> yield("1")
src |> some_other_transformations |> yield("2")
```
Here is a graph of what the planner sees. I have chosen to put the successors at the top and the predecessors at the bottom, more like an expression tree. I wish I could make the arrows go the other way. In any case I find this easier to visualize and it looks like what the planner sees.
```mermaid
graph TD
  trivial_filter --> from
  yield0 --> trivial_filter
  yield1 --> map
  map --> trivial_filter
  some_other_transformations --> from
  yield2 --> some_other_transformations
```
And we want the planner to generate this:
```mermaid
graph TD
  yield0 --> from
  yield1 --> map
  map --> from
  some_other_transformations --> from
  yield2 --> some_other_transformations
```  
In this case the planner rule would need to return the predecessor to the filter, the `from` node, and the planner in turn would need to know to merge the successors of the deleted node with the successors of the deleted node's predecessor. The planner currently has some logic for this invoked here:
https://github.com/influxdata/flux/blob/e811f6c85a48d1dc39ae62201194f971f42b427c/plan/heuristic_planner.go#L136
But I don't think it will work quite right. I'd like to see a solution that can handle this.

**Comment by nathanielc** [comment]
Additionally we need to handle the case where we are currently too restrictive in matching. See this test case added in my PR https://github.com/influxdata/flux/pull/4981/files#diff-c294ef316fa13418a60ccc6171d3931270831403553ddf531abd9c7b7ef68349R285-R309

In short we have a graph like:

```mermaid
graph TD
    A --> join
    B --> join
   A --> C
```
The current UnionKindPattern enforces that predecessors have only one successor, so the equijoin rule doesn't match when its perfectly safe for it to match. However there are other cases where we do want to constrain the pattern to only have a single edge between matched nodes. For example this graph:


```mermaid
graph TD
    filterA --> from
    filterB --> from
```

We can't lets the filter from rule match here because it intends to modify the `from` node, i.e. this plan is not equivalent

```mermaid
graph TD
   filterA --> fromFilterB
```

In order to handle both flavors of rules, ones that don't care about other successors and ones that do we need to be explicit about not only the kind of nodes we match but also the edges between those nodes. This is what https://github.com/influxdata/flux/pull/4981/ addresses by having patterns that explicitly match node that have exactly one successor or any number of successors.
