### ISSUE TITLE
Clear distinction of Sources and data Transformations

### ISSUE THREAD

**Issue by affo** [influxdata/flux#474]
A simple flux query:

```
from(bucket: "test")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> filter(fn: (r) => r._field == "usage_idle")
    |> max()
```

The first 4 operations are dedicated to _data extraction_, the remaining one to data transformation:

```
from(bucket: "test")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> filter(fn: (r) => r._field == "usage_idle")

    // ok, now we transform data

    |> max(columns: ["_value"])
```

Indeed, the first 4 operations are pushed down to storage and not performed by the query engine.
  
One thing I asked myself is: _why aren't we clearly separating extraction from transformation_?

Given that one must limit the results of a `from`, why don't we simply:

```
from(bucket: "test", range: {start: -1h})
    |> // ...
```

Why shouldn't a user be clear about the schema of a stream as a result of `from`?  
Is it sometimes the case that a user can handle mixed schemas in the same stream with a single transformation? This would imply he/she is able to write, for instance, a `map` that operates on values of different type (e.g. `int` and `string`).  
The user will likely specify some values he/she wants to operate on, thus the filtering on `_measurement` and `_field` above. What it is particular in that filtering is that it does not involve data attributes like "filter out records that have a usage below some threshold", but it is on _metadata_ and it is used by the source (i.e. storage). So, why don't:

```
from(bucket: "test", range: {start: -1h}
         measurement: "cpu", fields: ["usage_idle"])
    |> max(columns: ["usage_idle"])
```

This is really clear in its intent and doesn't mix data transformation with data extraction (i.e. filtering records based on metadata).

As other examples, let's think of processing data from MySQL. We have a table of orders and we want to compute the amount of every order in that table:

```
from(db: "test", table: "orders", select: "amount")
    |> mean(columns: ["amount"])
```

Or counting clicks on a web page from a Kafka topic:

```
from(topic: "clicks", partitions: "*", serializer: "JSON")
    |> count()
```

Now, looking closer to the first query and comparing it with the MySQL and Kafka ones, it seems that data transformations are erroneously applied to properly extract information from InfluxDB. In the latter queries there is no notion of `range`, nor would be filtering on metadata required, because it is natural to segregate data extraction in the source of data. Especially with namespaces, it is reasonable that every `from` (e.g., `influx.from`, `mysql.from`, `kafka.from`) has its specific parameters to extract the information from its source and that's it, without the user adding any further transformation.

What could we gain from this approach?

 - __Invariants__: after data extraction has been performed, we can rely on _typed streams_ (i.e., streams with a well-defined schema) and avoid issues with mixed types downstream.
 - __Not "stream of tables", but "_stream of records_"__: a much more flexible model, that directly resembles what the user writes into a flux query (flux, as language, is record/row oriented). Tables would stay where they are, not as InfluxDB tables, but _batches_ of records that can grow/shrink to increase/decrease the throughput/latency of the pipeline. The concept of batch should be orthogonal to the data model and influence performance metrics only. This allows to cover a handful of streaming use cases, such as a "rolling average" on incoming records with microsecond latency.
 - __Clarity__: the user has more bounds when writing down his/her query, this leads to a better usage of flux and less errors from users. Moreover, the user himself has a clear understanding of what is delegated to the source (i.e., in the case of InfluxDB, is pushed down to storage) and what is not.
 - __Simplicity__: a database provider (or others) has only to implement its `from`, without push-down logic. Flux optimizations will only cover transformations.

**Comment by nathanielc** [comment]
@affo These are good questions let me address them.

> from(bucket: "test", range: {start: -1h})
    |> // ...

Should the `from` function just have parameters for filtering etc? This question has come up a lot and there are two parts to the answer:

1. Flux follows the "unix philosophy" of doing one thing and doing it well. Each transformation should be small and well defined. 
2. Flux transformations are composable. This means that you can combine the smaller transformation into larger composite transformations.

For example instead of having a from transformation that does a from+range+filter all on its own you can easily define one yourself. Lets call it `select`.

```
select  = (bucket, range, measurement, fields) => 
    from(bucket:bucket)
        |> range(start:range.start, stop:range.stop)
        |> filter(fn:(r) => r._measurement == measurement and r._field in fields)
```

In fact this question and suggestion has come up in the community https://community.influxdata.com/t/get-good-series-names-in-flux/7659/6?u=nathaniel

Now a follow on question then is why do we not have a `select` like function built into the language? Why are we making users repeat the same from+range+filter pattern ad nauseam?

We wanted the first release of Flux to the community to be vanilla, we wanted to first see what the community would build with the small building blocks before we started constructing the larger ones ourselves. Both your feedback and the communities feedback are helping us define exactly what the best `select` function would look like. In other words we plan to ship a `select` function in the future, we just wanted more raw community feedback before we did. Another small issue is we are waiting for namespaces to exist before we start adding lots of these helper functions. FWIW, only one helper function was shipped with 0.7.0 of Flux and that was the aggregateWindow function, that was because internal user testing showed that it was a very common stumbling block that we wanted to address. 

> Invariants: after data extraction has been performed, we can rely on typed streams (i.e., streams with a well-defined schema) and avoid issues with mixed types downstream.

> Simplicity: a database provider (or others) has only to implement its from, without push-down logic. Flux optimizations will only cover transformations.

I'll address these two together. First you may have noticed that above I always referred to `from` as a transformation, this is because the invariant that Flux wants is that every thing that processes data is the same. Meaning that if everything is a "transformation" then Flux can rearrange them as needed. There is no need to separate out functions that are part of the extraction phase versus the transformation phase of a query. If every thing is a transformation then Flux's planner can treat them all the same.  For example if all `filter` logic was placed into each of the "extraction" functions then how would you describe a filter that occurs on transformed data (i.e. a SQL HAVING clause)? You would need an explicit filter function for that. So now you have both filter logic inside each source and as a stand alone transformation. Why not just use the same filter function to define both?

A design goal of Flux is to abstract away what the storage engine does versus what the query engine does. To the user there is no difference, so Flux is free to pick the implementation that it expects to be most efficient.  This design is really important to Flux, there are two basic ways to describe a query. First you can use an imperative style, for example a map reduce job on a hadoop cluster. Second you can use a declarative style, for example SQL. The declarative style is much easier to optimize because the user has only specified what data they want, not how to compute it. In an imperative style the kinds of optimizations you can perform on the code are limited because you have to follow exactly what was written. Experience has shown that trying to optimize map reduce jobs is difficult and requires the programmer to hand tune the code, while SQL like databases have been doing query optimization since their first implementations. In fact many NoSQL stores now come with some kind of optimization pass including Spark.  Flux has chosen a function style of programming because it is still composable and expressive while being able to easily optimize since each function has the same signature.  Said another way; A design goal of Flux is that a user does not need to think about how data is computed, they only have to describe what data they want computed, then Flux will find the optimal approach.

OK, there is still the question about well-defined schemas versus flexible dynamic schemas. We do not have a good answer to this one yet, except that for legacy reasons we need to support flexible schemas. In general InfluxDB is schema-less in that you do not have to specify the schema ahead of time, which is a blessing and a curse. I am open to ideas on how to address this specific issue. 

> The concept of batch should be orthogonal to the data model and influence performance metrics only. 

I agree and it is. Tables are not a batching mechanism, they are a logical partition of the data. Tables themselves can and are batched. For example the InfluxDB storage implementation batches tables into 1000 row chunks. That batching size can be changed arbitrarily, independent of the table partitioning scheme. Tables represent a logical grouping of the data which allows the user to apply transformations on different groups of data. For example computing the mean CPU usage by host requires that data be grouped into a table for each host.

> Clarity: the user has more bounds when writing down his/her query, this leads to a better usage of flux and less errors from users. Moreover, the user himself has a clear understanding of what is delegated to the source (i.e., in the case of InfluxDB, is pushed down to storage) and what is not.

I think I address this above, but I'll state it clearly here. I agree, the point of Flux is to provide a healthy abstraction such that the user can define queries without having too many places they can make mistakes. We plan to address this by adding helper functions that are composed of smaller functions. These functions do not exist yet as we have not decided exactly what they look like and are collecting user feedback to decide. 

Thanks for the great questions! I hope I have answered clearly. Feel free to ask follow up questions.

**Comment by affo** [comment]
Thank for the great answer! It helped me see things from another point of view. I am very used to different models like Flink's or Spark's. I do like the unix-philosophy of doing one thing well 😃 

> First you may have noticed that above I always referred to from as a transformation, this is because the invariant that Flux wants is that every thing that processes data is the same. Meaning that if everything is a "transformation" then Flux can rearrange them as needed.

Got it. But, is `from` really a transformation? I mean, it is _special_, it has no input and so it is different from the others, like `to` has no output. Do you expect them to be rearranged somehow?

> For example if all filter logic was placed into each of the "extraction" functions then how would you describe a filter that occurs on transformed data (i.e. a SQL HAVING clause)? You would need an explicit filter function for that. So now you have both filter logic inside each source and as a stand alone transformation. Why not just use the same filter function to define both?

In my opinion it is not the same filtering logic. A "filter" on metadata, is not the same as a filter on data. I think that filtering by "records that have a usage below some threshold", and projecting (selecting) some columns in a table should be two different operations. For example:

```
from(bucket: "test", measurement: "cpu")
    |> range(start: -1h)
    |> select(fields: ["usage_idle", "usage_user"])
    |> filter(fn: (r) => r.usage_idle > 0.8 and r.usage_user <= 0.5)
    |> count()
```

Seems much more readable and clear in its intent than:

```
from(bucket: "test")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> filter(fn: (r) => (r._field == "usage_idle" and r._value > 0.8) or
                         (r._field == "usage_user" and r._value <= 0.5))
    |> count()
```

And it could also be possible to make plans that use `influx.from` and do not push down a selection fail, just to enforce users to have a single schema per stream.

> Tables are not a batching mechanism, they are a logical partition of the data. Tables themselves can and are batched. 

I see, so you could have tables with 1 row to achieve low latency (and low throughput), right?

This is great. What I still found tricky is that tables with different schemas can still belong to the output of one transformation. I am so used to _typed streams_. The "one-stream-multiple-schema problem" seems confusing when writing the query and it causes errors. I think this should be warned somehow to user, like "pay attention, the last operation output contained records with different schema", because, as I said above, it could seldom be a user's choice.

I think this is the main problem with `from`, that it outputs heterogeneous schemas and only further transformations can shape them to one. However, if one omits those transformations can incur in bad logic and errors.

Anyhow, thank you for the mental stretching. You convinced me about a bunch of stuff and this answer does not "break" anything in the current implementation, but it only contains ideas for features that could be implemented in the future, actually (like selection vs filtering)!

One thing I think could be improved is how the data model and `from` are presented in the SPEC. If somebody starts by reading it (as I did) he could be unaware of the problems that could happen when not filtering and so on (maybe I was only a bit superficial while reading it). If you agree, I could read again that part and try to give a different description, if necessary.

**Comment by nathanielc** [comment]
> Got it. But, is from really a transformation? I mean, it is special, it has no input and so it is different from the others, like to has no output. Do you expect them to be rearranged somehow?

You are right sources are special as they do not have an input. That is only difference, in fact `to` does have an output and acts just like any other transformation. The only way `to` is special is that is has side effects (i.e. it send the data to an external system).

So `from` can not be swapped with other transformation since it is a source, but that is the only difference. So the planner only has to understand sources and transformations.


> In my opinion it is not the same filtering logic.

This is more of a data model question than a filtering logic question. 

```
from(bucket: "test")
    |> range(start: -1h)
    |> filter(fn: (r) => r._measurement == "cpu")
    |> influxdb.fieldsAsCols()
    |> filter(fn: (r) => r.usage_idle > 0.8 and r.usage_user <= 0.5)
    |> count()
```

Both filters do the same thing, they are described in the same way. Flux makes no distinction between "metadata" and "data". Everything is a column and you can choose to filter on it or not. This simplifies the mental model of the data, at the cost of complexity in the Flux implementation to correctly use indexes efficiently for "metadata". We do not want to require users to think about "metadata" vs "data", they can if they want, but it should not be required.

> I see, so you could have tables with 1 row to achieve low latency (and low throughput), right?

Let's take an example to make this more clear. If you select data from InfluxDB that has a million rows then the "table" in Flux has a million rows. But internally we break that table up into chunks of 1000 rows. See the ColReader type for how we do this. So a table's row count is not about batching and latency vs throughput, rather a table's rows are defined in terms of completeness. 

> This is great. What I still found tricky is that tables with different schemas can still belong to the output of one transformation. I am so used to typed streams. The "one-stream-multiple-schema problem" seems confusing when writing the query and it causes errors. I think this should be warned somehow to user, like "pay attention, the last operation output contained records with different schema", because, as I said above, it could seldom be a user's choice.

I agree this is a serious problem. I wish we had a simple solution. Right now my approach is that we keep fixing the user experience issues as we run into them and see if we can approach or more friendly model. The idea to include type as part of the group key makes a lot of sense to me since it will avoid errors and breaking the query. Then it just becomes a data clean up problem to ensure things have the correct type. We can build tools around that problem much easier.
