### ISSUE TITLE
Feature Flags in Test Cases

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#4777]
We would like to be able to set feature flags in test cases. This makes testing that behavior is the same before and after a feature flag is enable easier as we can leverage test extension. Additionally this allows for adding tests for feature behind flags.

We would like the follow behavior:

* Feature Flags can be defined with Flux source code within the scope of a single `testcase`.
* Flags apply to a single test case
* Flag are applied as early as possible in the process to maximize the code that can leverage feature flags.
* Flags carry down into downstream projects running the test harness (i.e. OSS/IDPE)

### Implementation

I tried to hack this in quickly but it proved to be more complex and so will benefit from some top down design. However here are some learning captured in my experimentation. 

#### Using an `option`

The idea is that flags are defined using an option:
```
testcase xxx {
   option testing.features = {
       myFlag: true
   }
}
```

Pros:

 * This can be processed statically allowing for the flag values to be set before we run semantic analysis 

Cons:
* Must be evaluated statically which has some limitations, the option must contain only literals
* The normal flow is that only Rust sees the AST. We have a few ways to work around this:
     * Add new logic in Rust to statically evaluate the option
     * Limit the scope of this feature to only within the test harness. The test harness necessarily has access to the AST in Go.
     * Always materialize the AST into Go values, this is likely prohibitively expensive

#### Using a Flux function

The idea is that flags are defined using a function:

```
testcase xxx {
   testing.setFeature(key: "myFlag", value: true)
}
```

Pros:
* Very easy to implement as a mutable flagger can be injected early enough into the evaluation process such that flags can be mutated

Cons: 
* Flags are set during interpretation, this is too late as you can't use it to enable feature flags in semantic analysis

#### How Flags interact with OSS and IDPE

OSS and IDPE have similar constraints on this problem. In both cases there are two contexts involved, one context created by the test harness, another created on the incoming HTTP request into the application. Neither project has a system for carrying over Flux feature flags from one context to the other. So something will need to exist to move the feature flags values if they are originally set by the test code on the test context.

OSS has a mechanism to add InfluxDB feature flag values, we could do something similar.

**Comment by onelson** [comment]
The latest case where flags not flowing through in fluxtest on the OSS side caused issues with the release: https://github.com/influxdata/flux/issues/5232

**Comment by onelson** [comment]
I'm a little worried about conflating the ideal situation with smaller practical changes that might reduce friction.

What follows are some of the smaller recommendations, then finally the ideal.

## OSS Practical

All this said, the pain point I'd like to relieve immediately is how new feature flags often have a cascading burden. Flags need to be enabled for each test harness (in cloud, OSS) and currently OSS does not even appear to allow us to do this via CLI at invocation time.

Manually managing flags in cloud isn't great, but the OSS situation warrants some immediate work. Today for OSS the SOP is to skip any tests that require a flag since there's no other good option. We're losing coverage in this env as a result.

I see OSS uses a "launcher" to configure the Query service, and I notice 2 things:

- this is where the flux dependencies are configured
- there's a branch for "testing" in there

https://github.com/influxdata/influxdb/blob/aa5c1c0bae0f02ff74d467ae7b82ab4fcea6680e/cmd/influxd/launcher/launcher.go#L400-L427

A quick-fix might be to leverage that branch for "testing" to inject the deps (and flagger) we define in vanilla. Right now it's not clear to me what all is being configured by default, but certainly we can go out of our way to inject the flagger we define for vanilla.


## OSS Post-practical 

If we decide we also need to be able to set flags via the CLI it seems like we could do something similar to what we do for the cloud test harness, adding a `--flux-features` flag which we would then feed through to the test launcher, which holds  a regular launcher as in the earlier "practical" pitch. If possible it'd be nice to merge keys supplied on the CLI with those in the default flagger so we can make select overrides as needed.

## Cloud Considerations

Today, we are able to pass flux feature flags explicitly to the cloud test harness. Missing bits:

- using the vanilla flagger by default
- using the CLI to specify features and have them merge/override the defaults

Today you manually have have to specify all the flags. Ideally the defaults set in vanilla would just flow through, but allow select overrides via CLI.

I don't know that there are challenges for this, but I understand the interaction between how we specify cloud-specific flags and the standard flux flagger was non-obvious the last time we looked at it and discussed. 


## The Ideal

Ideally we could specify features to enable on a testcase basis. A concrete benefit of this is it would allow us to show correctness between an existing implementation and a new (flagged) one. For example, with vectorization we could write a base testcase utilizing the row-based map, and extend it with the requisite vectorized flags enabled.

This would get us the same workflow we have today with pushdowns.

If this worked across all envs seamlessly I think this would resolve much of the extraneous changes we make today when flags are added/removed.

The challenges outlined in the issue description still stand, but I also have an additional question:

- when a flag is removed, should testcases that cite the flag error?

Based on the precedent we have with the CLI flagger overrides, I think the answer is "yes."

**Comment by onelson** [comment]
Did a quick POC for the OSS "set the flux flagger in the launcher" idea https://github.com/influxdata/influxdb/pull/23762

**Comment by onelson** [comment]
# Discussion notes

The team met for a working group on this today, and the TL;DR might be:

Instead of using the `option` or function pitches in the OP, we should instead look to leverage the new "attributes" being worked on as a part of the Editions work. 

- #5220  
- #5234


## Full notes

- feature flags impacting parsing (needing to reparse)
  - will editions solve this for us?
  - do things (like label polymorphism) require editions or can they be flagged?

Today we will not worry about this specific case (of needing to restart parsing).
At the moment we don't have this need, but we will probably need this in the future.

---

"Editions are a set of features" per the SPEC

Decouple a "feature of flux" from "feature flag"
FoF != FF

---

Attributes may be bound to the thing that follows them.
Testcase flagging therefore might be like
```
@features{this: true, that: false}
testcase foo {
 //
}
```

How would test extension work?

- testcase requires features (sets the features=on)
- testcase uses features ()

When extending a testcase - put a different set of attributes
on the extension to "override."


---

Happy with syntax?
Happy with being able to attached to certain stuff? (start with package/testcase)


Goal:
- no hardcoded features in test harness

**Yes to this.** :point_up: 


---

Migration path?

When will a feature graduate to an edition?

"pre" edition?

@edition "experimental"

---

SEC: users should not be able to mess with config cat flags et al.

---

Regarding the difference between "features" and "editions"...

User Contract:
Editions attr is "stable"
- release channel (beta, stable)
- doesn't allow for isolation, but maybe that's fine
- the point is we can break

Features (until we have a better name)  attr is "volatile"
- experimental/transient
- changes to impl details
- competing impls aiming to solve the same problem space
- per customer patches
- features might not be breaking, can be integrated _without an edition_.

Could still be useful to signal temporary stuff.

Convention:
- use editions for things expected permanent, explicitly a set of features
- use "features" for things expected to go away, non-user facing refactors

Later we might enforce breaking features can't be accessed directly via "features" attribute, only available as a part of an edition.

Diagnostically - helpful to see enabled features in query log?
Query Profile includes total flattened features map.

What about emergency situations? 
Config Cat can't override if we have
higher precedence on script attributes.
Might need a stronger way to set flags remotely via config cat.  

---

## Next Steps

- add syntax for attributes
- add attributes to base node of AST
- attach attrs to testcase "main package"
- _N.b no attributes to modify the parser should be needed today_
- test harness changes to wrangle feature enablement per test case
- `features` attr is highest precedence over env/config cat etc
- Merge flags with config cat where applicable
