### ISSUE TITLE
Integral function not returning expected results 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#4782]
https://community.influxdata.com/t/integral-function-not-returning-expected/25061
Thank you

**Comment by amykyta3** [comment]
@Anaisdg I have a more extreme example of integral() mis-calculating the result.
It seems to be an issue with the linear interpolation mode.

For example:
```flux
import "experimental/array"

array.from(rows: [
    {_value: 0, _start: 2022-12-04T00:00:00.000Z, _stop: 2022-12-04T13:00:00.000Z, _time: 2022-12-04T12:00:00.000Z},
    {_value: 1, _start: 2022-12-04T00:00:00.000Z, _stop: 2022-12-04T13:00:00.000Z, _time: 2022-12-04T12:01:00.000Z},
    {_value: 1, _start: 2022-12-04T00:00:00.000Z, _stop: 2022-12-04T13:00:00.000Z, _time: 2022-12-04T12:02:00.000Z},
    {_value: 0, _start: 2022-12-04T00:00:00.000Z, _stop: 2022-12-04T13:00:00.000Z, _time: 2022-12-04T12:03:00.000Z},
])
  |>  group(columns: ["_start", "_stop"])
  |> integral(unit: 1m, interpolate: "linear")
```
Using linear interpolation, I would expect the above integration of values `0,1,1,0` to return `2`. Instead, the flux query somehow comes up with `-260822.5`

Without interpolation, I get the expected result (which also happens to be `2` in this case)

**Comment by amykyta3** [comment]
After some experimentation, I think I understand what is going on.
Instead of simply interpolating *between* points, It appears to be also *extrapolating* the linear slope from the leading and trailing pair of points all the way to the beginning/end of the window.

This is extremely surprising and seems inappropriate. When dealing with sparse data, I would have expected it to clamp values to 0, or at least assume a zero-slope at the boundaries of the data.

**Comment by default-student** [comment]
This is still real bad and not fixed
