### ISSUE TITLE
Proposal: Strategy for dealing with runtime-provided variables

### ISSUE THREAD

**Issue by rockstar** [influxdata/flux#4834]
Problem
==

Across InfluxDB's ecosystem of web UI, tasks, and invocable scripts (Cloud only), there are three different dynamic parameter sets provided at runtime: `v`, `task`, and `params`. When writing a script in an editor that uses the lsp, these variables _appear_ as undefined variables, because they aren't declared in the script. On top of that, they are implied, so there is a "mystery meat" element to those references. Additionally, if a user happens to declare a variable that interferes with these runtime provided values, the script is now broken because we can't assign to an existing variable.

Solution 1 - add a file scope (the easier? one)
==

In order to solve the issue where the lsp server shows `v` as undefined (see influxdata/ui/#4566), the UI now "opens" a second file behind the scenes. That file is then evaluated as another file in the same package. This makes the error go away. However, if the user, for whatever reason, defines a `v` in the UI, an error about redefining `v` shows up. The user then asks "Why does it think `v` is defined? I'm defining it right here for the first time." An easy way to fix this would be to introduce a file scope. This way, a variable defined in one file of the package can be shadowed by a file-level reference. This means that we can implicitly provide values that would otherwise be specified at runtime, but if a user decides to define their own references, it seamlessly Just Works™ from the user perspective. However, the external api that injects these values at runtime would then have to check to make sure they wouldn't inject values that are already defined.

In the end, a lot of this solution seems to be a workaround for the fact that these values are created implicitly.

Solution 2 - extern keyword
==

A better (preferred?) way to solve this would be to create an `extern` keyword, and all scripts that would take one of `v`/`task`/`params` would then declare a `extern` to explicitly define what values would be provided at runtime. The `extern` keyword could optionally provide type information about the values provided as well. For instance, both of those would work:

```
extern v

extern v: {timeRangeStart: int, timeRangeStop: int}
```

I would _assume_ that just saying `extern v` means there is no typechecking on it, whereas the latter is like detailing the interface specifically. That's just a guess though, as I haven't really thought about the ramifications to type system here.

The downside to this solution is that all scripts currently in the wild that require the addition of `extern`. The migration path to making this work is a little hazy. The lsp can easily add a code action for detecting unknown `v`/`task`/`param` and suggesting we `extern (v|task|param)`, but I don't know what changes need to happen to the parser (execution engine?) to be able to support some migration story there.

Please comment now.

**Comment by nathanielc** [comment]
From solution 1:

>However, the external api that injects these values at runtime would then have to check to make sure they wouldn't inject values that are already defined.

I think we should change the way the API injects the values to use an explicit file so that there is no dynamic checking of what exists in the users code rather we just always put the extern in its own file and if the user shadows it thats fine.

Solution 1 has another problem as it creates an ambiguity when determining the values exported from a package. For example if `v` is defined in two files, which `v` would be exported from that package? Using file order is a poor choice which leaves us with an ambiguity that can't be easily resolved. A potential solution to this we could make this file scope thing a main package only feature, meaning it only works for queries but if you are developing a package you can't shadow package level variables. This feels like splitting hairs that would be hard to understand.
 
Solution 2 also has another problem, the ergonomics of needing to use `extern` in order to include values defined in the same package but in a different file is very combersome. I would expect `extern` to mean that the value must be defined in a separate package and loaded in from there.  But its not clear how that value gets specified.

Perhaps a new solution as a mix between these would work. We don't create a new file scope and we don't use explicit `extern` declarations. Instead we place any external values into their own package (not just file) called `extern` and then the `extern` package is implicitly part of the prelude. This has the behavior of the first solution in that you can shadow values in the `extern` package within the current package `main` or otherwise. We don't have to create a new scope layer that introduces ambiguity instead we simply leverage existing scope layers more precisely. However this creates a challenge in implementation because the execution path currently expects a single package to be executed not multiple packages. If however we develop a solution for user defined packages, then there will necessarily be a mechanism for defining new packages that can be consumed at runtime. We could leverage that mechanism to dynamically generate and insert the `extern` package and include it as part of the prelude. 


Thoughts?
