### ISSUE TITLE
SPIKE: REPL editing basics

### ISSUE THREAD

**Issue by onelson** [influxdata/flux#4861]
In an effort to better understand basic REPL features like handling multi-line input, build a standalone Go program that can accept multi-line input and print it back out.

The prompt should keep a history and allow you navigate the history with up/down cursor keys. With the pending input at the prompt, you should be able to modify the line(s) before sending it as new input.

Survey the available Go libraries for text-based UIs and/or prompts to try and identify the strongest candidates.

DOD:
- build an "echo prompt" program (print out input after it is entered)
- build history navigation and editing capabilities
- give attention to rendering defects which could impact the usability

**Comment by Marwes** [comment]
An alternative, if go does not have any fitting libraries, could be to allow Rust to drive the REPL only returning to Go when a script needs to be run. [rustyline](https://crates.io/crates/rustyline) is definitely good, providing history, hints, completion etc
https://github.com/gluon-lang/gluon/blob/aed148592e8b3c8db4825d9575156171c8a39df6/repl/src/repl.rs#L159-L259 .

The command in go would still exist, just be a thin shim before calling into rust.

**Comment by Westonside** [comment]
## Current State
Currently I have three CLI that meet the basic requirements. Both of the go CLI currently have issues with displaying the multi-line inputs (as shown in videos 1 and 2). I have been unable to discover why the issue for displaying multiline strings exists in go. The issue lies in the actual line reading packages that ishell and go prompt use (both of which are different but have the same issues).  Rustyline currently has no issues displaying multiline input. For the ishell and the Rustyline I have made a paste mode that stores multiple lines once ctrl-d is pressed allowing for the user to enter multiple lines or paste input. The key and implementation can be improved once I choose the best CLI option.

The issue of ishell and go prompt must be in the fact that the readline implementations only view up to the first '\n' so when there are multiple it ends up breaking.

### NOTE

The implementation is subject to change so rusty line and go prompt implementations are rough drafts and the paste mode and handling of multiline input can be improved.

Another thing to note is that the functionality of go prompt and ishell is very similar and it would probably be best to focus on go prompt since the current implementation lies there and would be an easier change (if keeping go in the CLI is chosen).

### ToDo for each implementation
Rustyline: I have a FFI working with a simple go function and to extend that functionality to call go subroutines and add better handling for multiline inputs
ishell and go prompt: research how the readline libraries handle viewing history and look for a fix

## Implications of each implication
- Ishell: Has terrible multiline handling and a proposed fix could be to investigate further into the readline libraries to see how they display the history and potentially make my own implementation. Possibly better handling of larger inputs? 
- goprompt: Terrible multiline handling as well. Similar fix proposal to ishell. Pro is that the current implementation is currently in the go prompt so it would be less work.
- Rustyline: This would involve the use of a lot of FFI involvement as this would involve a lot of Rust -> Go -> Go -> Rust. Pro  IOx SQL prompt is written with rustyline. Overall very strong handling of input, especially for larger input sizes.

## Example runs

Please ignore the terrible watermarks
Here is some examples how multiline input works on the CLI
For both go prompt and ishell lines are being printed even though the enter key is not being pressed but rather the history is being viewed.

ishell example:

https://user-images.githubusercontent.com/30425691/174875996-651bd2da-2160-4358-a651-63e847eceb37.mov


go prompt example:

https://user-images.githubusercontent.com/30425691/174876013-d13cb32e-e1d1-46e3-b1a9-fe229c0aaab9.mov


rusty line example:

https://user-images.githubusercontent.com/30425691/174876032-aebae53f-221a-4976-833d-6c290f93852d.mov

Notice how the rusty line does not print a ton of the same inputs when viewing the same history
