### ISSUE TITLE
csv.from() should have option to not interpolate

### ISSUE THREAD

**Issue by abalone23** [influxdata/flux#4897]
`csv.from()` in v0.171.0 attempts to interpolate a string that contains `${}`. For example:
```js
import "csv"

data =
"
#datatype,string,long,dateTime:RFC3339,string,double
#group,false,false,false,false,false
#default,,,,,
,result,table,_time,region,_value
,mean,0,2018-05-08T20:50:00Z,${n},1.4
"

csv.from(csv: data)
```

returns:
>error @9:32-9:33: undefined identifier n

According to @onelson there should be a way to indicate interpolation should not happen.

**Comment by onelson** [comment]
I was thinking about how shell variable expansion works for double quoted strings but not single quoted. If I remember correctly groovy uses this same scheme. Other langs use backticks instead of single or double quotes to opt-in for interpolation behavior.

Seems like it'd be nice if we offered some way to represent a string literal that won't attempt to interpolate.

**Comment by nathanielc** [comment]
As a workaround you can escape the interpolation characters to avoid it. From the SPEC https://github.com/influxdata/flux/blob/master/docs/SPEC.md#string-literals

This will work:
```
import "csv"

data =
"
#datatype,string,long,dateTime:RFC3339,string,double
#group,false,false,false,false,false
#default,,,,,
,result,table,_time,region,_value
,mean,0,2018-05-08T20:50:00Z,\${n},1.4
"

csv.from(csv: data)
```

**Comment by onelson** [comment]
Good to know this is mentioned in the spec.

I think when this issue was first raised in slack, part of the mystery was how the csv was being embedded inside a flux string from JS. The caller tried to escape interior quotes using `JSON.strigify` (which seems fair), but didn't realize they needed to also escape `${`. Ideally, I think it'd be nice to have a way to handle this more conveniently.
