### ISSUE TITLE
Window function will produce nonsensical window for times outside of range boundaries

### ISSUE THREAD

**Issue by jsternberg** [influxdata/flux#4979]
If you have a query like the following:

```
import "array"
import "planner"

// Disable planner rules for aggregate window optimization if present.
option planner.disablePhysicalRules = ["AggregateWindowRule", "AggregateWindowCreateEmptyRule"]

array.from(rows: [
  {_time: 2022-07-07T12:50:00Z, _value: 2.0},
])
  |> range(start: 2022-07-07T12:00:00Z, stop: 2022-07-07T13:00:00Z)
  |> aggregateWindow(every: 10m, fn: mean)
  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)
```

The `window()` call from the second aggregate window will create a non-sensical window boundary. When window is creating windows, it clips the boundaries of the windows to match the range boundary. This is intended behavior and meant to allow for partial windows to be clipped to match with the true start/stop of the query.

But, if you have an actual point in time that is outside of the range boundary (would have been filtered by the range), the window does not know how to clip it into a sensical time range. At the current moment, it chooses the start/stop time to match the range boundary instead of anything related to the actual window boundaries.

This arises because the first aggregate window sets the times to be the same as the stop time. The new time for the point is now outside of the boundary of the range. The second aggregate window then has a nonsensical behavior because the first aggregate window created a value with a time that was not part of the range.

To me, it is unclear what the behavior should be. It's not clear if the output from the first aggregate window is wrong or if the clipping behavior from the second is incorrect. Should we drop points that are outside of the range inside of aggregate window or should we create windows that are outside of the boundaries, but still clipped to them?

**Comment by gazpachoking** [comment]
I've just run in to similar issues and came looking for existing reports. I think the correct behavior would be to have aggregateWindow always place the resulting point inside the same window boundary the point was generated from.
There are 2 ways to achieve this:
- The way around it right now is to always run aggregateWindow with the `timeSrc` parameter set to "_start" (the default is "_stop".) Since the start of a range or window is inclusive, The newly created point is still within the original range and window bounds.
- Switch the inclusivity of start and stop. This isn't possible for users right now, but this would be my preferred answer. That way aggregateWindows can still create their points at the stop of the window bounds, but that point would be included in the window/range. (This would of course mean that overriding `timeSrc` to "_start" would bring up similar issues that we are having, but at least the default behavior would be more sane.)

The current behavior leads to some not so nice effects, like running the same aggregateWindow multiple times in a row will shift the data points into the future one `every` each time. As points scroll out of the range, you end up with an empty data point for each that left the range even when `createEmpty` is true.

**Comment by gazpachoking** [comment]
If you have multiple levels of rollup tasks, that each take their data from the previous rollup bucket, this means they will each shift the data as well. e.g. if you have an hourly daily and weekly rollup task all just using aggregateWindow on the previous level bucket:
- the daily one will include the last hour of the previous day, but not the last hour of the current day
- the weekly one will include the last 25 hours of the previous week, and not the last 25 hours of the current week
- Every level gets worse. If you had a monthly it could be shifted by up to (depending on how the end of the month lines up with the end of the week) 1week+1day+1hour in this scenario.

This seems like a serious usability issue to me.

**Comment by gazpachoking** [comment]
🙁
