### ISSUE TITLE
why task can't Trigger immediately

### ISSUE THREAD

**Issue by tuoeg** [influxdata/flux#5085]
import "http" import "json" option task = {name: "CPU Total 1 Hour New", cron: "* 0/10 * * *"}

http.post(url: "baidu.com",
headers:{Authorization:"12345", "Content-type": "application/json"},
data: json.encode(v:"123"))

**Comment by sanderson** [comment]
@tuoeg The task interval/schedule (`every`/`cron`) are passed off to the InfluxDB task engine which actually schedules and runs the task, so this is more of an InfluxDB issue than a Flux issue. To trigger a task outside of the specified schedule, you have to [manually run the task](https://docs.influxdata.com/influxdb/latest/process-data/manage-tasks/run-task/).

You may consider adding a feature request to the [InfluxDB repo](https://github.com/influxdata/influxdb/) for an option to immediately run a task after creating it. Because this is more of an InfluxDB issue, I'm going to close this issue.
