### ISSUE TITLE
Feature request: option to include/exclude start and stop times as a part of groups with windowing and aggregateWindow

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#5164]
**Proposal**: Allow users to include the last timestamp in the first window. For example: 
```
import "contrib/jsternberg/aggregate"
import "array"

rows = [{_time: 2022-01-01, baz: 21.2}, {_time: 2022-01-02, baz: 23.8}, {_time: 2022-01-03, baz: 25.8}, {_time: 2022-01-04, baz: 26.8}]

array.from(rows: rows)
|> range(start: 2022-01-01, stop: 2022-01-04)

|> window(every: 2d)
```
Would yield the following result:
```
#group,false,false,true,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double
#default,_result,,,,,
,result,table,_start,_stop,_time,baz
,,0,2022-01-01T00:00:00Z,2022-01-02T00:00:00Z,2022-01-01T00:00:00Z,21.2
,,1,2022-01-02T00:00:00Z,2022-01-04T00:00:00Z,2022-01-02T00:00:00Z,23.8
,,1,2022-01-02T00:00:00Z,2022-01-04T00:00:00Z,2022-01-03T00:00:00Z,25.8
```
Allow the user to perform the following queries: 
```
|> range(start: 2022-01-01, stop: 2022-01-04, option: inclusive)
|> window(every: 2d, option: inclusive)
```
To yield the following result: 
```
#group,false,false,true,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double
#default,_result,,,,,
,result,table,_start,_stop,_time,baz
,,0,2022-01-01T00:00:00Z,2022-01-02T00:00:00Z,2022-01-01T00:00:00Z,21.2
,,0,2022-01-02T00:00:00Z,2022-01-04T00:00:00Z,2022-01-02T00:00:00Z,23.8
,,1,2022-01-02T00:00:00Z,2022-01-04T00:00:00Z,2022-01-02T00:00:00Z,23.8
,,1,2022-01-02T00:00:00Z,2022-01-04T00:00:00Z,2022-01-03T00:00:00Z,25.8
,,1,2022-01-02T00:00:00Z,2022-01-04T00:00:00Z,2022-01-04T00:00:00Z,26.8
```

**Use case**
Often users want to define window periods or groupings with redundant start and stop times. 
https://community.influxdata.com/t/cumulative-data-management-converting-to-snapshots-data/26260

**Comment by Trovalo** [comment]
I've noticed the issue while working with cumulative counters and the result is pretty simple, without inclusive intervals you are losing/ignoring data.

How much data is "lost" depends on gathering frequency and grouping intervals.
The loss is fixed, as the final part of the time window will always be "missing", how big is the impact of it might vary considerably based on the time window and gathering interval

Let's say data are gathered every 15sec, meaning 5 times in a minute (inclusive).
- if I group by 1m, I'm losing 1/5 (20%) of the data...
- if I group by 5m I'm losing 1/25 (4%)
the wider the interval (compared to the gathering frequency) the lower the loss gets.

I'm surprised nobody raised this issue before, since I think it's pretty common to deal with this kind of data.

**Comment by nathanielc** [comment]
@Trovalo Can you share an example of the "lost" data? The `window` function should not loose any data because is has half-open intervals. Meaning given any stream of data on any interval every point should land in exactly one window interval. Points that land exactly on the boundary will be in the earlier interval since the stop boundary is exclusive (i.e. `[start,stop)` ).

**Comment by Trovalo** [comment]
> given any stream of data on any interval every point should land in exactly one window interval

This is exactly the problem I'm talking about. When you have a continuous incremental value the last value of an interval has to be considered as the first in the next, otherwise whatever happened between the two will be lost.

I'll attach some data (at the bottom), I'm not getting matching results from all the queries... specifically I'm unable to rebuild the "GroupedDiff" result with manual calculation which is odd
RawData - cumulative value as-is (over those I perform  the diff manually via excel or whatever)
Diff - difference point by point (current - previous, therefore the value gets "shifted" forward)
GroupedDiff - difference(last(__)) groped by 1m intervals

<details>
  <summary>Here are the queries I've used</summary>

A single series is considered with this filters
```
--Raw Data
SELECT time, wait_time_ms FROM "sqlserver_waitstats" 
WHERE 
    time >= '2022-09-13 15:30:00'
AND time <= '2022-09-13 15:35:00'
AND sql_instance = 'SQLCSRV04:SQL2017'
    AND wait_type = 'WRITELOG'

-- Plain difference
SELECT time, difference(wait_time_ms) AS wait_time_ms_diff FROM "sqlserver_waitstats" 
WHERE 
    time >= '2022-09-13 15:30:00'
AND time <= '2022-09-13 15:35:00'
AND sql_instance = 'SQLCSRV04:SQL2017'
    AND wait_type = 'WRITELOG'

--Grouped Diff
SELECT time, difference(last(wait_time_ms)) AS wait_time_ms_diff FROM "sqlserver_waitstats" 
WHERE 
    time >= '2022-09-13 15:30:00'
AND time <= '2022-09-13 15:35:00'
AND sql_instance = 'SQLCSRV04:SQL2017'
    AND wait_type = 'WRITELOG'
GROUP BY time(1m)
  ```
</details>

Here are some data raw data

time | wait_time_ms
-- | -- | --
13/09/2022 15:31:00 | 13032004
13/09/2022   15:31:15 | 13032198
13/09/2022 15:31:30 | 13032288
13/09/2022   15:31:45 | 13032353
13/09/2022 15:32:00 | 13032429
13/09/2022   15:32:15 | 13032488
13/09/2022 15:32:30 | 13032536
13/09/2022   15:32:46 | 13032616
13/09/2022 15:33:00 | 13032659


By manually applying the logic, since intervals are half open, what happens **using the difference with 1m intervals** is that:
- the aggregate of 15:31:00 will include the data  of points between 15:31:00 and 15:31:59:9999, which has a value of 349 (13032353 - 13032004)
- same goes for 15:32:00, which has a value of 187

Is it correct? I don't think so, as the half-open interval actually does not start over from the latest point it used, but goes to the next one, actually skipping a difference that has to be considered, what I expect is to see:
- the aggregate of 15:31:00 will go from 15:31:00 and 15:32:00, with a value of 425 (13032429 - 13032004)
- the inteval 15:32:00 of will have a value of 230 (13032659 - 13032429)

[WaitStatsSample_Raw.csv](https://github.com/influxdata/flux/files/9563873/WaitStatsSample_Raw.csv)
[WaitStatsSample_Diff.csv](https://github.com/influxdata/flux/files/9563871/WaitStatsSample_Diff.csv)
[WaitStatsSample_GroupedDiff.csv](https://github.com/influxdata/flux/files/9563872/WaitStatsSample_GroupedDiff.csv)
