### ISSUE TITLE
Parameterize the max width of the formatter 

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#5247]
The UI regularly generates Flux code for the user and leverages the formatter to ensure the code reads well. However because of the variable width of the editor its possible that lines get really long and you have to use the scroll bar in order to see all the code being generated.

We should consider making the formatter max width a runtime parameter to the formatter so that UI can choose an appropriate width based on the size of editor window.  Perhaps have a discrete set of widths and choose the largest that fits in the window. That way each resize of the window doesn't trigger a completely new formatting but there are steps.

**Comment by rockstar** [comment]
I think a configurable formatter is interesting, specifically if you could do `// pragma: formatter-max-width: 115` or whatever. Most formatters tend to have some dynamic configuration, and so that makes sense.

I'm not sure I agree with the reasoning for it though. The formatter and the web ui are two different layers of something, and I'm not sure they should communicate between each other, e.g. now the formatter has to become aware (likely via the lsp) that the window has been resized. It means that different folks get different results from the formatter for different sized monitors.

If the web UI editor is too narrow to be useful, I think that's an issue with the editor.
