### ISSUE TITLE
Order of operations or formatting problem 

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#5298]
A user was experiencing different results with the following two queries:
```
join(tables: {billed: billed, current: current}, on: ["type"])
    |> map(fn: (r) => ({r with balance: -r.peak_used_current - r.peak_used_billed + (r.peak_generated_current - r.peak_generated_billed)}))
    |> map(fn: (r) => ({r with join: 1}))

join(tables: {billed: billed, current: current}, on: ["type"])
  |> map(fn: (r) => ({ r with balance: -(r.peak_used_current-r.peak_used_billed)+(r.peak_generated_current-r.peak_generated_billed) }))
  |> map(fn: (r) => ({ r with join: 1 }))
```
From: 
https://community.influxdata.com/t/flux-query-reformatted-in-task/26840/2

Thank you!

**Comment by sanderson** [comment]
@Anaisdg This is _kind of_ an order of operations thing, but more of a signed-numeric-value thing. Let me explain:

Let's assign some arbitrary values to the variables used in the `map` call:

- `r.peak_used_current` = 10
- `r.peak_used_billed` = 8
- `r.peak_generated_current` = 12
- `r.peak_generated_billed` = 6

In the first query, the expression, `-r.peak_used_current - r.peak_used_billed`—`r.peak_used_current` is signed as a negative number (prepended with `-`). So the expression resolves to:

```js
-10 - 8 + (12 - 6)
// -18 + 6
// -12
```

In the second query, the expression, `-(r.peak_used_current - r.peak_used_billed)`—The result of `r.peak_used_current - r.peak_used_billed` is signed as negative (because the group `()` is prepended with `-`). So the expression resolves to:

```js
-(10 - 8) + (12 - 6)
// -2 + 6
// 4
```

**Comment by Marwes** [comment]
This is a bug in the formatter where the parenthesis on the left hand side gets removed. I thought it could be fixed easily by correcting the precedences for unary `+/-` but I couldn't get it right which I think partly is because the precedence table we have seems wrong, or at least odd? https://github.com/influxdata/flux/blob/master/docs/SPEC.md#operators-1

> Operators with a lower number have higher precedence.

This just seems backwards :S Just picking out https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence they have higher number means higher precedence which seems to make more sense (but for instance the C++ reference does this same reverse order as well https://en.cppreference.com/w/cpp/language/operator_precedence so :shrug: )

* Comparing with the javascript precedences we see that both flux and javascript have *high precedence* for call/index expressions etc. However for unary operators (`exists/not` in flux) we actually have a low precedence, but it is high on javascript which seems correct. So that just seems wrong on our end.

I'd be tempted to just remove the parenthesis rewriting that the formatter does and just leave any paretheses as is in the source, that seems to be the simplest fix (but requires some tedious updating of tests.

### Test

```rust
#[test]
fn dont_lose_parentheses() {
    assert_unchanged("-(r.peak_used_current - r.peak_used_billed) + (r.peak_generated_current - r.peak_generated_billed)");
}
```

**Comment by Anaisdg** [comment]
@sanderson oh that's embarrassing. My empathy aggravated dyslexia kicked in and I read a + instead of -. Thanks all.
