### ISSUE TITLE
timeWeightedAverage interpolation off?

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/flux#5349]
When I use the function I don't get an expected value. 
```
import "array"
array.from(rows: [{_time: 2022-01-02, _value: 1}, {_time: 2022-01-03, _value: 2}, {_time: 2022-01-04, _value: 3}])
|>range(start: 2022-01-01)
  |> timeWeightedAvg(unit: 1d)
```
gives 171.40402444422162

When I picture a straight line and take the integral for (1,1)(2,2)(3,3) I don't get a value remotely close to that. 
Thank you!

**Comment by sanderson** [comment]
I think the function is working as expected. `timeWeightedAvg()` use the `_start` and `_stop` times to interpolate values between. In this query, the stop time is `now()`, so `timeWeightedAvg()` is interpolating all the values between `2022-01-04T00:00:00Z` and `now()`. That's why the returned average is so high. If you explicitly set the stop time in `range()` to `2022-01-05`, it should give you the expected value.

```js
import "array"

array.from(
    rows: [
        {_time: 2022-01-02, _value: 1},
        {_time: 2022-01-03, _value: 2},
        {_time: 2022-01-04, _value: 3}
    ]
)
    |>range(start: 2022-01-01, stop: 2022-01-05)
    |> timeWeightedAvg(unit: 1d)
```

**Comment by Anaisdg** [comment]
Thanks @sanderson

**Comment by alberanid** [comment]
Thanks @Anaisdg and @sanderson for your analysis, but I in my experience the `timeWeightedAvg` function also produces unexpected values when you select a safe start and stop range **if there are gaps in the data**. That's not the case in your test data, so I agree that the result is sound in your case, but only because its data are stored at regular intervals.

There are various issues about this problem, like https://github.com/influxdata/influxdb/issues/7445 and the more recent https://github.com/influxdata/influxdb/issues/23929

A dataset that present this problem can be found here: https://community.influxdata.com/t/how-to-aggregate-non-regular-values-using-a-time-weighted-average/27619

As others are saying, in the IoT world is quite common to have sensors that send data only on changes, or when they wake up responding to certain events, and in that cases `timeWeightedAvg` can't be used. I agree that this probably opens various questions, like "what should be used as 'previous' value when you have a gap in the data", but then again the current implementation can't be used on series that are not regularly timed.

Thanks!

**Comment by sanderson** [comment]
> in my experience the timeWeightedAvg function also produces unexpected values when you select a safe start and stop range if there are gaps in the data.

@alberanid You're right and the root of the problem is the interpolation. Right now `timeWeightedAvg()` uses linear iterpolate to missing values. So instead of a flat line you'd expect with using the previous value to fill the data, you get a sloped line between two existing points. `timeWeightedAvg()` use the integral of the sloped line to time-weight the data.

I think `timeWeightedAvg()` needs a new interpolation option that would let you use different interpolation methods. I think the one that would work in the case of disparate data would be `step` interpolation.

**Comment by alberanid** [comment]
@sanderson that's correct, in our case (which is the case for most IoT devices that push their status at non-regular intervals) a stepped interpolation would produce a more meaingful result.

I may be wrong since I do not know all the maths behind it and I've given only a superficial look at the `timeWeightedAvg()` function in Go, but I think that there are two distinct problems.

The first is that right now `timeWeightedAvg` produces unexpected results even if you are okay with using the linear interpolation, as shown by https://github.com/influxdata/influxdb/issues/23929 . I guess - but take it just as a guess - that once you split the data in tables based on `unit` you interpolate the slope produced by joining the second-to-last value to the last value up to the end of the aggregation frame. This ends up with a (integral?) mean that doesn't match reality, since in fact the last slope of an aggregation frame should join its last point to the first point in the next aggregation frame. This should also be taken into consideration, otherwise you will have a mean that is higher/lower than the maximum/minimum values.

The second problem is exactly our use case, and as you said using a stepped interpolation would solve large part of the problem. Here, an important aspect to take into account is that once you split the data into aggregation frames you must take care to include the last value of the previous aggregation frame and assume that it was the value at Time0 of this aggregation frame. E.g.:
```
time    |   value
00:05 | 1
00:37 | 5
02:12 | 2
02:31 | 3
03: 00 | 7
```

In the above example, calculating the mean in the `02:00-03:00` time frame you must assume that at `02:00` value was `5` up until `02:12`, and that the value will be `3` from `02:31` to `03:00`.

I hope the idea is clear; as said I'm not an expert in statistics/maths, so I may have got some details wrong. If someone with a better understanding of this stuff can add mode details and fixes, it would help a lot.

In any case, we are developing some hackish solution in pure Flux; if we reach a working state we will share the result with the community.

**Comment by LarsStegman** [comment]
I think this issue is still present right?

**Comment by alberanid** [comment]
@LarsStegman I've not tested the latest releases since this issue is a showstopper for our use case, but I assume the problem is still present.

I remain of the opinion that this is an important feature for many use cases, especially in IoT.
