### ISSUE TITLE
Time literal arithmetic 

### ISSUE THREAD

**Issue by adamperlin** [influxdata/flux#761]
From ifql created by [nathanielc](https://github.com/nathanielc) : influxdata/ifql#216  

https://github.com/influxdata/influxdb/issues/6881
https://github.com/influxdata/influxdb/issues/8153

Should be able to convert between times, durations and ints.

**Comment by aanthony1243** [comment]
317 above is likely the wrong repo.

**Comment by roshie548** [comment]
Some questions about time literal arithmetic:
When dividing `Durations`, do we want to return an Int or a Float?
```
> 1m/1d
0.0006944444444444445 or 0
```
Should we be able to subtract times and receive a duration (in ns) as a result?
Should we be able to add/subtract durations?

**Comment by nathanielc** [comment]
Dividing durations should be a float and `1mo / 1d` should be `30` for now. When we implement duration vectors it will change.

>Should we be able to subtract times and receive a duration (in ns) as a result?

Yes the different of two times is a duration

> Should we be able to add/subtract durations?

Yes, add/subtracting durations will produce durations
Adding/subtracting durations with times will produce times.

**Comment by jlapacik** [comment]
Adding/subtracting durations with times will require the type system to support polymorphic literals. See #476 for a discussion. But duration or time arithmetic is already supported by the type system. All that's needed is to update the interpreter to support it. I.e adding new binary function signatures to `values/binary.go`.

**Comment by jlapacik** [comment]
Clarification. Adding and subtracting duration values is supported by the by the type signature of `+` and `-`. Every binary arithmetic operator has the following type signature:

    forall ['a] ('a, 'a) -> 'a

Given polymorphic literals, the above type signature supports adding or subtracting time and duration values together. However, it does not support adding two values of the same type together and producing a new different type as is the case with duration division producing a float.

We will need specific operators in order to support duration division returning a float, as well as time subtraction returning a duration. In other words we cannot overload the (/) and (-) operators to support these use cases.

**Comment by russorat** [comment]
was this solved by https://github.com/influxdata/flux/pull/1592 ?

or also https://v2.docs.influxdata.com/v2.0/reference/flux/stdlib/experimental/addduration/ ?
