### ISSUE TITLE
Tag Keys not populating in Flux Builder/Explorer

### ISSUE THREAD

**Issue by AlirieGray** [influxdata/flux#81]
When opening up the Tag Keys dropdown in the Flux Builder or Explorer, the results are empty as shown here:

<img width="304" alt="screen shot 2018-10-01 at 4 46 32 pm" src="https://user-images.githubusercontent.com/15273162/46321681-9ed18700-c599-11e8-8f58-75678e81fd42.png">

Looking into the network response, the server is sending back the error message: "panic: runtime error: index out of range".

**Comment by aanthony1243** [comment]
@AlirieGray   can you determine the query that's being sent?

**Comment by AlirieGray** [comment]
`query: "from(bucket:"telegraf")|>range(start:-1h)|>group(by:["_field"])|>distinct(column:"_field")|>group(by:["_stop","_start"])|>limit(n:10)"`

**Comment by aanthony1243** [comment]
@stuartcarnie  this looks like an issue on push-down of `group`  to influxdb.  It occurs if the range of data is empty.  A simpler test is:   `curl -XPOST -sS  -H 'content-type:application/vnd.flux' localhost:8086/v2/query -d 'from(bucket:"telegraf")|>range(start:-1h)|>group(by:["_field"])'`

**Comment by aanthony1243** [comment]
@stuartcarnie looks like the panic could occur here: 
https://github.com/influxdata/influxdb/blob/62b9791da8565364e9bb298497d5da33b3a5d94d/flux/functions/store/table.go#L107

we could put a check there but since this function doesn't return an error, i'm assuming that it should only be called when it's safe to do so.
