### ISSUE TITLE
Design testing package

### ISSUE THREAD

**Issue by nathanielc** [influxdata/flux#873]
Jotting down some notes here:

* Tests should be able to be run via the REPL and easily rerun etc
* Tests should be able to be run in isolation
* Tests need to handle testing both transformations and sources
* Tests need to be able to exercise the planner and sources
* Tests need control over how the planner and sources are executed

**Comment by jsternberg** [comment]
A related idea that I had and was demoing to @aanthony1243 was the ability to generate a test template with generated data according to a specific schema. The code to generate the data is already committed.

This tool would use that to generate the data and then run the query with the in data to automatically update the unit test with the appropriate output data by using `ast.Format`.

**Comment by aanthony1243** [comment]
should columns be order independent?

what kinds of error messages should we report in a teat failure?

**Comment by nathanielc** [comment]
During discussion we can up with a few ideas that started to work well together.

* Files can end in _test.flux and will be treated as test files.
* Test files must declare a package and the package must be `<pkg name>_test` for whatever package they are part of. (i.e. `package universe_test`)
* Test files are in their own package and are executed as such.
* Tests are defined by assigning a function with a specific signature: `() -> {input: stream, want: stream, fn: (tables: <-stream) -> stream}` to an identifier. The identifier becomes the test name.
* The testing.test function takes a test case and calls it:
```
test = (case) => {
    tc = case()
    got = tc.input |> tc.fn()
    diff = streamDiff(want: tc.want, got: got)
    pass = isEmpty(table: diff)
    return { tc with 
        got: got,
        diff: diff,
        pass: pass,
}
```

Example test file:
```
package universe_test

option now = () => //...

inData = //...
outData = //...

test mean = {
    input: testing.load(csv: inData),
    want:  csv.from(csv: outData),
    fn: (table=<-) =>  { return table
          |> range(start: 2018-12-01T00:00:00Z)
          |> mean()
    },
}

test meanEmpty = () => ({
    input: testing.load(csv: inDataEmpty),
    want:  csv.from(csv: outData),
    fn: (table=<-) => { return table
          |> range(start: 2018-12-01T00:00:00Z)
          |> mean()
    },
})
```

There are three variants to how to discover test cases defined in a test file:

1. Use the type of the value, if the type is correct assume it is a test case
2. Use a keyword `test` to indicate the value is a test case
3. Use a naming convention `testMean` to indicate the value is a test case

All of these are fine, we should just pick one. None of these should be difficult to implement.


There is either a code generation step or a reflection step that can take all test files in a package and run those tests. We do not have reflection in Flux ATM so I suggest we use code generation as we already have the tooling for it.

The code generation should find all test cases and create a test main function that calls all discovered tests. 

Example generated test main for the above test file:

```
import "testing"

testMain = () => {
    testing.test(case: mean)
    testing.test(case: meanEmpty)
}
```

The advantage of this design is that each test files can be executed manually and inspected on the fly as well as executed as a whole as part of a larger test suite.



Miscellaneous notes from our discussion:

* Use `option load` to define what the load function is instead of compile time changes

**Comment by affo** [comment]
> * Test files must declare a package and the package must be `<pkg name>_test` for whatever package they are part of. (i.e. `package universe_test`)
> * Test files are in their own package and are executed as such.

A note on this, I still think that specifying a package name that isn't actually used for scoping is counter-intuitive. Also because it is coherent with the SPEC:

> When a file does not declare a package clause, all identifiers in that file will belong to the special _main_ package.

Identifying a test by using the file name `_test.flux` should be enough. For interacting with the test in the repl one can do what @nathanielc was doing (e.g. @stdlid/universe/mean_test.flux). So I would stick with only:

> * Test files are in their own package and are executed as such.

For code generation/reflection, we will end up having a `*_test_gen.flux` (or a folder `test_gen` with a bunch of tests inside) for each e2e test, so that, later, we can iterate over files ending with `_test_gen.flux` (or every file in `test_gen`) and run tests in parallel (as now `stdlib/testing/end_to_end_test.go` does)? Am I on the right page?

**Comment by wolffcm** [comment]
How would code generation work with the `now` option, since different tests might want different value for `now`?  I guess that code generation could produce a different `testMain` for each `_test.flux` file?

I like the idea of a `test` keyword better than the other alternatives.  If we want to disable a test, we can just comment out this keyword.

**Comment by affo** [comment]
@wolffcm yeah, I had the same doubt. I think that the generation step is only required to avoid the burden of wrapping everything around `testing.test(...)` to the user. Eventually, it would always be a `t.Run()` thing, right?

A question, can the binary for `flux test` programmatically generate the code before running tests? If not users would be required to install Golang.

**Comment by jlapacik** [comment]
@affo the reason I like specifying a package name is that it makes clear it is a special test package and should be handled differently. For our internal test suite it doesn't really matter. But when users start writing test packages it will make it clear that it is a separate execution model. For instance, an interpreter can directly execute a __main__ package. It can't execute a testing package without the code generation step.

**Comment by affo** [comment]
Yeah, if we parse the files and get the AST, we can edit the AST and wrap the values of `test` option with `testing.test` using the `ast.Visitor`.

**Comment by jsternberg** [comment]
Some work on this was done in #926. We now have a `testing.diff` and `testing.assertEmpty` that are successfully used by the end to end tests and will output the diff. We will want to change the scaffolding behind it as described in this issue, but the scaffolding will likely generate something similar to the current `testing.test` function.

**Comment by jcmcken** [comment]
Sorry for the slightly off-topic comment, but I just want to express support for this issue (well, any of the Flux testing issues), and my hope that this test framework will be a first-class citizen for users of Flux. One of my main hangups/disappointments with TICKscript is how unwieldy it is to test. Yes, there's ``kapacitor-unit``, but this can only test alert state changes (AFAIK). Ideally, you would also be able to test the input and output of arbitrary nodes in the pipeline (e.g. alert ID, message, and details -- important so that you can verify that alert consumers are seeing the right info) and test templated tasks. 

Not sure how many of these concepts translate over to Flux (haven't had an opportunity to use it quite yet), but hopefully some of these things are on your minds.
