### ISSUE TITLE
Formatter formats options in units of nanoseconds.

### ISSUE THREAD

**Issue by docmerlin** [influxdata/flux#910]
This is due to the formatter.
![image 1](https://user-images.githubusercontent.com/1236827/51562773-411ac080-1e50-11e9-8628-4e72080f3d9b.png)

**Comment by jsternberg** [comment]
I discussed this with @docmerlin and this has more to do with how the option editor modifies the AST. The AST itself will output the duration correctly, but the option editor uses `time.ParseDuration` to  parse the duration and then puts it in a `values.Value` duration type. Since the duration parts information is lost by that point, it creates an `ast.Duration` with nanoseconds instead of what the user originally did.

We have exposed duration (and other literal) parsing in the `ast` package (specifically `ast.ParseDuration` for this). The option editor needs to be changed to take `ast.Expression` values instead of `values.Value`.

**Comment by nathanielc** [comment]
@docmerlin Does tasks's handling of the options require that you handle them as values? Or could you instead leave everything as its raw AST node? Granted when you go to schedule the task etc, you need to consume values but maybe during the edit process it can remain as AST nodes?

**Comment by docmerlin** [comment]
This was closed by https://github.com/influxdata/flux/pull/927
