### ISSUE TITLE
Implement Conditionals

### ISSUE THREAD

**Issue by nicgrobler** [influxdata/flux#923]
Hi,
Apologies if this has already been asked, and answered elsewhere - I have gone through the issues and source and found mentions that it was not yet implemented, but am wondering if this is on the list, and perhaps even a rough eta?
My current use case is simply using a basic IF statement to avoid ‘divide by zero’ when doing cross-series calculations. But there are many other scenarios where conditionals make life a LOT easier.

Thanks for your time ;-)

**Comment by dp1140a** [comment]
As part of this I would also like to add the implementation of looping as well as conditionals.  At a minimum to support the following:

Conditionals:
- if/else
- if/elseif/else
- switch

Looping:
- for
- for each
- while/ do while
- continue. break, and return

**Comment by nathanielc** [comment]
@nicgrobler Thanks for asking, we plan to support conditionals and loop iteration. As for an ETA I don't have any information other than we are not actively working on it. 

@dp1140a Flux is a functional language and its form of loop iteration will not likely have the imperative control flow like `continue`,`break` or `return`. We haven't SPEC out iteration much yet but my first assumptions are that it will use `map` and `reduce` as it primitives. 

So instead of a sum function looking like this:

```
s = 0
for each v in mydata {
   s += v
}
```

It will look more like this:

```
mydata |> reduce(init:0, fn: (s,v) => s + v)
```

All this said, nothing here is final. We still need to document in the SPEC what conditionals and loop iteration will look like.

**Comment by wolffcm** [comment]
Conditional expressions are now in Flux as of v0.27.0.  The syntax for conditional expressions are in the SPEC:
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#conditional-expressions

**Comment by dp1140a** [comment]
Although conditionals have been implemented, what is the status of looping in Flux.  Is Map/Reduce the chosen method of will there be soem sort of For loop syntax?

**Comment by wolffcm** [comment]
@dp1140a We provide a `reduce` function which you may have already found:
https://github.com/influxdata/flux/blob/master/docs/SPEC.md#reduce

A more general way to do looping is coming at some point, but the design has not been solidified yet.

**Comment by dp1140a** [comment]
Is there an update on the design of generalized looping beyond the reduce or map functions?

**Comment by nathanielc** [comment]
@dp1140a Can you open a new issue to discuss looping beyond `map` `reduce`?
